-- ----------------------------------------
-- Added to prevent timeout's while loading
-- ----------------------------------------
SET GLOBAL net_read_timeout=30;
SET GLOBAL net_write_timeout=60;
SET GLOBAL net_buffer_length=1000000; 
SET GLOBAL max_allowed_packet=1000000000;
SET GLOBAL connect_timeout=10000000;

-- --------------------------------------------------------------------------------
-- This is an attempt to create a full transactional MaNGOS update (v1.3)
-- --------------------------------------------------------------------------------
DROP PROCEDURE IF EXISTS `update_mangos`; 

DELIMITER $$

CREATE DEFINER=`root`@`localhost` PROCEDURE `update_mangos`()
BEGIN
    DECLARE bRollback BOOL  DEFAULT FALSE ;
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET `bRollback` = TRUE;

    -- Current Values (TODO - must be a better way to do this)
    SET @cCurVersion := (SELECT `version` FROM db_version ORDER BY `version` DESC, STRUCTURE DESC, CONTENT DESC LIMIT 0,1);
    SET @cCurStructure := (SELECT structure FROM db_version ORDER BY `version` DESC, STRUCTURE DESC, CONTENT DESC LIMIT 0,1);
    SET @cCurContent := (SELECT content FROM db_version ORDER BY `version` DESC, STRUCTURE DESC, CONTENT DESC LIMIT 0,1);

    -- Expected Values
    SET @cOldVersion = '21'; 
    SET @cOldStructure = '11'; 
    SET @cOldContent = '34';

    -- New Values
    SET @cNewVersion = '21';
    SET @cNewStructure = '11';
    SET @cNewContent = '35';
                            -- DESCRIPTION IS 30 Characters MAX    
    SET @cNewDescription = '[DBDOCS] Updated some fields';

                        -- COMMENT is 150 Characters MAX
    SET @cNewComment = '[DBDOCS] Updated some field descriptions';

    -- Evaluate all settings
    SET @cCurResult := (SELECT description FROM db_version ORDER BY `version` DESC, STRUCTURE DESC, CONTENT DESC LIMIT 0,1);
    SET @cOldResult := (SELECT description FROM db_version WHERE `version`=@cOldVersion AND `structure`=@cOldStructure AND `content`=@cOldContent);
    SET @cNewResult := (SELECT description FROM db_version WHERE `version`=@cNewVersion AND `structure`=@cNewStructure AND `content`=@cNewContent);

    IF (@cCurResult = @cOldResult) THEN    -- Does the current version match the expected version
        -- APPLY UPDATE
        START TRANSACTION;

        -- UPDATE THE DB VERSION
        -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
        INSERT INTO `db_version` VALUES (@cNewVersion, @cNewStructure, @cNewContent, @cNewDescription, @cNewComment);
        SET @cNewResult := (SELECT description FROM db_version WHERE `version`=@cNewVersion AND `structure`=@cNewStructure AND `content`=@cNewContent);

        -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
        -- -- PLACE UPDATE SQL BELOW -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
        -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -

DELETE FROM `dbdocstable` WHERE `languageId`=0 AND `tableName`='dbdocslanguage';
INSERT  INTO `dbdocstable`(`languageId`,`tableName`,`tableNotes`) VALUES (0, 'dbdocslanguage','This table is part of the implementation of the \'Mangos Database Documentation\' (MDD) Project.<br /><br />This table lists the supported dbdocs languages:<br /><br />¬subtable:101¬');

UPDATE `dbdocstable` SET `languageId`=0, `tableName`='gossip_texts', `tableNotes`='This table defines textes for gossip menu items, used by native ScriptDev3 C++ scripts.' WHERE tableId=67;
UPDATE `dbdocstable` SET `languageId`=0, `tableName`='npc_trainer', `tableNotes`='This table holds all the information on training NPCs. <br />All spells listed in the table are learning spells. <br /><br />This means that the main effect of the spells listed here is to teach spells to the target (which is the player in this case). <br /><br />Any other spell that is not a learning spell will be ignored and an error message will be shown in the console window. <br /><br />Learning spells usually have the same name as their actual spell counterparts and are listed as Uncategorized in Wowhead.' WHERE tableId=85;
UPDATE `dbdocstable` SET `languageId`=0, `tableName`='pool_creature_template', `tableNotes`='Contains all pool instances that participate, in particular, to any game event.' WHERE tableId=103;
UPDATE `dbdocstable` SET `languageId`=0, `tableName`='pool_gameobject', `tableNotes`='Contains all pool instances that participate, in particular, to any game event.' WHERE tableId=104;
UPDATE `dbdocstable` SET `languageId`=0, `tableName`='reputation_reward_rate', `tableNotes`='Holds reputation multipliers for specific factions.<br />Setting a rate to 0 disables reputation gain to the faction by the defined way completely.<br /><br />NOTE: For the low level kills/quests, the rate values are combined with the config file settings Rate.Reputation.LowLevel.Kill/Quest by multiplying.' WHERE tableId=110;
UPDATE `dbdocstable` SET `languageId`=0, `tableName`='script_texts', `tableNotes`='This table contains the texts (and localized ones) for ScriptDev3 C++ script engine, used in the function DoScriptText().' WHERE tableId=113;
UPDATE `dbdocstable` SET `languageId`=0, `tableName`='script_waypoint', `tableNotes`='The table contains creature waypoints used in the ScriptDev3 C++ script library. The data is used by npc_escortAI::FillPointMovementListForCreature().' WHERE tableId=114;
UPDATE `dbdocstable` SET `languageId`=0, `tableName`='spell_affect', `tableNotes`='This table holds information on what spells are affected by what spell mods. <br /><br />All spells in this table need to apply an aura that either adds a flat modifier to other spells or adds a percent modifier to other spells. <br /><br />Also, a single row in this table only holds information on a single spell effect that applies the aura. <br /><br />Therefore since a spell may have up to three effects, a maximum of 3 rows per spell is allowed. However, only the spell effects that apply the flat or percent auras will be used.' WHERE tableId=120;
UPDATE `dbdocstable` SET `languageId`=0, `tableName`='spell_chain', `tableNotes`='This table defines spell chains. A spell chain is a series of spells which all share the same name and all do the same thing; however, each has a different rank and as the rank increases, so does the spell damage/heal/etc values. <br /><br />This table also controls what spells are replaced by their more powerful later ranks; however, that is also decided by other factors as well (if mana costs for both spells are the same, etc). <br /><br />All fields in this table except rank are spell IDs from Spell.dbc.' WHERE tableId=123;
UPDATE `dbdocstable` SET `languageId`=0, `tableName`='dbdocslanguage', `tableNotes`='This table is part of the implementation of the \'Mangos Database Documentation\' (MDD) Project.<br /><br />This table lists the supported dbdocs languages:<br /><br />¬subtable:101¬' WHERE tableId=150;
UPDATE `dbdocstable` SET `languageId`=0, `tableName`='dbdocslanguage', `tableNotes`='This table is part of the implementation of the \'Mangos Database Documentation\' (MDD) Project.<br /><br />This table lists the supported dbdocs languages.' WHERE tableId=150;

UPDATE `dbdocsfields` SET `FieldComment` = 'The first actiontype.', `fieldNotes` = 'The first actiontype<br /><br /><br />Before we start to list and explain the different actions that can be taken, we must first look at how the eventAI targeting system works. Due to technical reasons in how targetting is handled, the eventAI script cannot target anything or anyone that is not in its threat list or is not the scripted creature itself. It also can\'t currently target anyone specific in its threat list except by their position in the threat list. However, even then it can only target specifically the current victim, the second unit in its threat list, and the last unit in its threat list. It can also target units in its threat list at random and has two options for that: anyone in its threat list at random, or anyone in its threat list excluding the unit with the most threat. Aside from all of those external targets, the script can always target itself. More information on the target types can be found in the reference tables at the end of this guide.<br /><br />One last note before we start looking at individual actions is about the texts. The eventAI script has support for localized text entries. Therefore, you can define what the mob will say in more than one language all in another table and the script will show the corresponding localized text to the corresponding client (english text to enUS/enGB clients, german text to deDE clients, etc). All of the localized text entries will have a unique text ID assigned to them and it is that text ID that will be used by any actions that require textual input.<br /><br />¬subtable:2¬' WHERE `fieldId`= '65' AND `languageId`= 0;
UPDATE `dbdocsfields` SET `FieldComment` = 'The Second actiontype (See creature_ai_scripts.action2_type)', `fieldNotes` = 'The Second actiontype (See creature_ai_scripts.action2_type)<br /><br />Possible target types<br />¬subtable:136¬' WHERE `fieldId`= '69' AND `languageId`= 0;
UPDATE `dbdocsfields` SET `FieldComment` = 'The ID of the language of the localised entry.', `fieldNotes` = 'The ID of the language of the localised entry.<br /><br />¬subtable:101¬' WHERE `fieldId`= '1580' AND `languageId`= 0;
UPDATE `dbdocsfields` SET `FieldComment` = 'Event Type ID', `fieldNotes` = 'Event Type ID, from one of the Events below:<br /><br />¬subtable:100¬<br /><br />Now that all of the supported events have been listed and described, we shall now move on to the actions that can be performed. Each event can take up to three actions. <br /><br />The actions will all be performed when the event is triggered and they will be performed in the order that they have been defined. <br /><br />This means that, for a certain event, <br /><br />action 1 will be performed first, followed by action 2, then lastly by action 3. Just like event definitions, <br /><br />Each action can use up to three different parameters but not all actions will use all three parameters. <br />If a parameter isn\'t mentioned for an action, then that action does not need that parameter.<br />' WHERE `fieldId`= '83' AND `languageId`= 0;

DELETE FROM `dbdocssubtables` WHERE `subtableId`= 2 AND languageId=0;
INSERT  INTO `dbdocssubtables`(`subtableId`,`languageId`,`subtableName`,`subtablecontent`,`subtableTemplate`) VALUES (2,0,'Creature AI Scripts Action_Type','<table border=\'1\' cellspacing=\'1\' cellpadding=\'3\' bgcolor=\'#f0f0f0\'>
<tr bgcolor=\'#f0f0ff\'>
<th><b>Action Type</b></th>
<th><b>Enum Name</b></th>
<th align=\'left\'><b>Description</b></th>
<th align=\'left\'><b>Parameters</b></th>
<tr bgcolor=\'#FFFFEE\'><td align=\'center\' valign=\'middle\'>0</td><td align=\'center\' valign=\'middle\'>ACTION_T_NONE</td><td align=\'left\' valign=\'middle\'>Does nothing!</td><td align=\'left\' valign=\'middle\'>&nbsp;</td></tr>
<tr bgcolor=\'#FEFEFF\'><td align=\'center\' valign=\'middle\'>1</td><td align=\'center\' valign=\'middle\'>ACTION_T_SAY</td><td align=\'left\' valign=\'middle\'>Displays the -TextId as defined. In case -TextId2 and optionally -TextId3, the output will be randomized. Type text are defined in the eventai_texts table (say, yell, whisper, etc) along with other options for the text. All values are required to be negative.</td><td align=\'left\' valign=\'middle\'>Parameter 1: The entry of the text that the NPC should use from eventai_texts table. Optionally a entry from other tables can be used (such as custom_texts are required to be negative and exist in a *_texts-table. The type text to be displayed are defined in the texts-table itself (Say, Yell, Whisper, Emote Text, Boss Whisper, Boss Emote)Other options are also to be defined in the texts-table, such as a sound to be heard with the text and the language used in output (common, dwarvish, etc).In case this entry has a localized version of the text, the localized text will be displayed in client that support this locale.<br/><br/>Parameter 2: Optional. TextId can be defined in addition. The same apply to this as explained above, however eventAI will randomize between the two.<br/><br/>Parameter 3: Optional, if Parameter 2 exist. In this case, eventAI will randomize between three.</td></tr>
<tr bgcolor=\'#FFFFEE\'><td align=\'center\' valign=\'middle\'>2</td><td align=\'center\' valign=\'middle\'>ACTION_T_YELL</td><td align=\'left\' valign=\'middle\'>UNUSED</td><td align=\'left\' valign=\'middle\'>&nbsp;</td></tr>
<tr bgcolor=\'#FEFEFF\'><td align=\'center\' valign=\'middle\'>3</td><td align=\'center\' valign=\'middle\'>ACTION_T_TEXTEMOTE</td><td align=\'left\' valign=\'middle\'>UNUSED</td><td align=\'left\' valign=\'middle\'>&nbsp;</td></tr>
<tr bgcolor=\'#FFFFEE\'><td align=\'center\' valign=\'middle\'>4</td><td align=\'center\' valign=\'middle\'>ACTION_T_SOUND</td><td align=\'left\' valign=\'middle\'>When activated, the creature will play the specified sound.</td><td align=\'left\' valign=\'middle\'>Parameter 1: The sound ID to be played. Sound IDs are contained in the DBC files.</td></tr>
<tr bgcolor=\'#FEFEFF\'><td align=\'center\' valign=\'middle\'>5</td><td align=\'center\' valign=\'middle\'>ACTION_T_EMOTE</td><td align=\'left\' valign=\'middle\'>When activated, the creature will perform a visual emote. Unlike a text emote, a visual emote is one where the creature will actually move or perform a gesture.</td><td align=\'left\' valign=\'middle\'>Parameter 1: The emote ID that the creature should perform. Emote IDs are also contained in the DBC but they can be found in the mangos source as well.</td></tr>
<tr bgcolor=\'#FFFFEE\'><td align=\'center\' valign=\'middle\'>6</td><td align=\'center\' valign=\'middle\'>ACTION_T_RANDOM_SAY</td><td align=\'left\' valign=\'middle\'>UNUSED</td><td align=\'left\' valign=\'middle\'>&nbsp;</td></tr>
<tr bgcolor=\'#FEFEFF\'><td align=\'center\' valign=\'middle\'>7</td><td align=\'center\' valign=\'middle\'>ACTION_T_RANDOM_YELL</td><td align=\'left\' valign=\'middle\'>UNUSED</td><td align=\'left\' valign=\'middle\'>&nbsp;</td></tr>
<tr bgcolor=\'#FFFFEE\'><td align=\'center\' valign=\'middle\'>8</td><td align=\'center\' valign=\'middle\'>ACTION_T_RANDOM_TEXTEMOTE</td><td align=\'left\' valign=\'middle\'>UNUSED</td><td align=\'left\' valign=\'middle\'>&nbsp;</td></tr>
<tr bgcolor=\'#FEFEFF\'><td align=\'center\' valign=\'middle\'>9</td><td align=\'center\' valign=\'middle\'>ACTION_T_RANDOM_SOUND</td><td align=\'left\' valign=\'middle\'>Similar to the ACTION_T_SOUND action, when this action is activated, it will choose at random a sound to play. This action needs all three parameters to be filled and it will pick a random entry from the three. Note: (1)</td><td align=\'left\' valign=\'middle\'>Parameter 1: The sound ID to be played as choice one.<br/><br/>Parameter 2: The sound ID to be played as choice two.<br/><br/>Parameter 3: The sound ID to be played as choice three.</td></tr>
<tr bgcolor=\'#FFFFEE\'><td align=\'center\' valign=\'middle\'>10</td><td align=\'center\' valign=\'middle\'>ACTION_T_RANDOM_EMOTE</td><td align=\'left\' valign=\'middle\'>Similar to the ACTION_T_EMOTE action, when this action is activated, it will choose at random an emote ID to emote visually. This action needs all three parameters to be filled and it will pick a random entry from the three. Note: (1)</td><td align=\'left\' valign=\'middle\'>Parameter 1: The emote ID that the creature should perform as choice one.<br/><br/>Parameter 2: The emote ID that the creature should perform as choice two.<br/><br/>Parameter 3: The emote ID that the creature should perform as choice three.</td></tr>
<tr bgcolor=\'#FEFEFF\'><td align=\'center\' valign=\'middle\'>11</td><td align=\'center\' valign=\'middle\'>ACTION_T_CAST</td><td align=\'left\' valign=\'middle\'>When activated, the creature will cast a spell specified by a spell ID on a target specified by the target type.</td><td align=\'left\' valign=\'middle\'>Parameter 1: The spell ID to use for the cast. The value used in this field needs to be a valid spell ID.<br/><br/>Parameter 2: The target type defining who the creature should cast on. The value in this field needs to be a valid target type as specified in the reference tables below.<br/><br/>Parameter 3: See spell flags. If it is 1, then the spell cast will interrupt any spells that are already in the progress of being casted; otherwise if the creature is already casting a spell and this field is 0, then this action will be skipped.</td></tr>
<tr bgcolor=\'#FFFFEE\'><td align=\'center\' valign=\'middle\'>12</td><td align=\'center\' valign=\'middle\'>ACTION_T_SUMMON</td><td align=\'left\' valign=\'middle\'>When activated, the creature will summon another creature at the same spot as itself that will attack the specified target.</td><td align=\'left\' valign=\'middle\'>Parameter 1: The creature template ID to be summoned. The value here needs to be a valid creature template ID.<br/><br/>Parameter 2: The target type defining who the summoned creature will attack. The value in this field needs to be a valid target type as specified in the reference tables below. Note: Using target type 0 will cause the summoned creature to not attack anyone.<br/><br/>Parameter 3: The duration until the summoned creature should be unsummoned. The value in this field is in milliseconds or 0. If zero, then the creature will not be unsummoned until it leaves combat, but only works with t_type !=0.</td></tr>
<tr bgcolor=\'#FEFEFF\'><td align=\'center\' valign=\'middle\'>13</td><td align=\'center\' valign=\'middle\'>ACTION_T_THREAT_SINGLE_PCT</td><td align=\'left\' valign=\'middle\'>When activated, this action will modify the threat of a target in the creature’s threat list by the specified percent.</td><td align=\'left\' valign=\'middle\'>Parameter 1: Threat percent that should be modified. The value in this field can range from -100 to +100. If it is negative, threat will be taken away and if positive, threat will be added.<br/><br/>Parameter 2: The target type defining on whom the threat change should occur. The value in this field needs to be a valid target type as specified in the reference tables below.</td></tr>
<tr bgcolor=\'#FFFFEE\'><td align=\'center\' valign=\'middle\'>14</td><td align=\'center\' valign=\'middle\'>ACTION_T_THREAT_ALL_PCT</td><td align=\'left\' valign=\'middle\'>When activated, this action will modify the threat for everyone in the creature’s threat list by the specified percent.</td><td align=\'left\' valign=\'middle\'>Parameter 1: The percent that should be used in modifying everyone’s threat in the creature’s threat list. The value here can range from -100 to +100. Note: Using -100 will cause the creature to reset everyone’s threat to 0 so that everyone has the same amount of threat. It does NOT make any changes as to who is in the threat list.</td></tr>
<tr bgcolor=\'#FEFEFF\'><td align=\'center\' valign=\'middle\'>15</td><td align=\'center\' valign=\'middle\'>ACTION_T_QUEST_EVENT</td><td align=\'left\' valign=\'middle\'>When activated, this action will satisfy the external completion requirement for the quest for the specified target defined by the target type. This action can only be used with player targets so it must be ensured that the target type will point to a player.</td><td align=\'left\' valign=\'middle\'>Parameter 1: The quest template ID. The value here must be a valid quest template ID. Furthermore, the quest should have SpecialFlags  &#124; 2 as it would need to be completed by an external event which is the activation of this action.<br/><br/>Parameter 2: The target type defining whom the quest should be completed for. The value in this field needs to be a valid target type as specified in the reference tables below.</td></tr>
<tr bgcolor=\'#FFFFEE\'><td align=\'center\' valign=\'middle\'>16</td><td align=\'center\' valign=\'middle\'>ACTION_T_CASTCREATUREGO</td><td align=\'left\' valign=\'middle\'>When activated, this action will call CastedCreatureOrGO() function for the player. It can be used to give quest credit for casting a spell on the creature.</td><td align=\'left\' valign=\'middle\'>Parameter 1: The quest template ID. The value here must be a valid quest template ID.<br/><br/>Parameter 2: The spell ID to use to simulate the cast. The value used in this field needs to be a valid spell ID.<br/><br/>Parameter 3: The target type defining whom the quest credit should be given to. The value in this field needs to be a valid target type as specified in the reference tables below.</td></tr>
<tr bgcolor=\'#FEFEFF\'><td align=\'center\' valign=\'middle\'>17</td><td align=\'center\' valign=\'middle\'>ACTION_T_SET_UNIT_FIELD</td><td align=\'left\' valign=\'middle\'>When activated, this action can change the target’s unit field values. More information on the field value indeces can be found at character data data.</td><td align=\'left\' valign=\'middle\'>Parameter 1: The index of the field number to be changed. Use character data data for a list of indeces and what they control. Note that a creature shares the same indeces with a player except for the PLAYER_* ones.<br/><br/>Parameter 2: The new value to be put in the field.<br/><br/>Parameter 3: The target type defining for whom the unit field should be changed. The value in this field needs to be a valid target type as specified in the reference tables below.</td></tr>
<tr bgcolor=\'#FFFFEE\'><td align=\'center\' valign=\'middle\'>18</td><td align=\'center\' valign=\'middle\'>ACTION_T_SET_UNIT_FLAG</td><td align=\'left\' valign=\'middle\'>When activated, this action changes the target’s flags by adding (turning on) more flags. For example, this action can make the creature unattackable/unselectable if the right flags are used.</td><td align=\'left\' valign=\'middle\'>Parameter 1: The flag(s) to be set. Multiple flags can be set by using bitwise-OR on them (adding them together).<br/><br/>Parameter 2: The target type defining for whom the flags should be changed. The value in this field needs to be a valid target type as specified in the reference tables below.</td></tr>
<tr bgcolor=\'#FEFEFF\'><td align=\'center\' valign=\'middle\'>19</td><td align=\'center\' valign=\'middle\'>ACTION_T_REMOVE_UNIT_FLAG</td><td align=\'left\' valign=\'middle\'>When activated, this action changes the target’s flags by removing (turning off) flags. For example, this action can make the creature normal after it was unattackable/unselectable if the right flags are used.</td><td align=\'left\' valign=\'middle\'>Parameter 1: The flag(s) to be removed. Multiple flags can be set by using bitwise-OR on them (adding them together).<br/><br/>Parameter 2: The target type defining for whom the flags should be changed. The value in this field needs to be a valid target type as specified in the reference tables below.</td></tr>
<tr bgcolor=\'#FFFFEE\'><td align=\'center\' valign=\'middle\'>20</td><td align=\'center\' valign=\'middle\'>ACTION_T_AUTO_ATTACK</td><td align=\'left\' valign=\'middle\'>This action controls whether or not the creature should stop or start the auto melee attack.</td><td align=\'left\' valign=\'middle\'>Parameter 1: If zero, then the creature will stop its melee attacks. If non-zero, then the creature will either continue its melee attacks (the action would then have no effect) or it will start its melee attacks on the target with the top threat if its melee attacks were previously stopped.</td></tr>
<tr bgcolor=\'#FEFEFF\'><td align=\'center\' valign=\'middle\'>21</td><td align=\'center\' valign=\'middle\'>ACTION_T_COMBAT_MOVEMENT</td><td align=\'left\' valign=\'middle\'>This action controls whether or not the creature will always move towards its target.</td><td align=\'left\' valign=\'middle\'>Parameter 1: If zero, then the creature will stop moving towards its victim (if its victim gets out of melee range) and will be stationary. If non-zero, then the creature will either continue to follow its victim (the action would have no effect) or it will start to follow the target with the top threat if its movement was disabled before.</td></tr>
<tr bgcolor=\'#FFFFEE\'><td align=\'center\' valign=\'middle\'>22</td><td align=\'center\' valign=\'middle\'>ACTION_T_SET_PHASE</td><td align=\'left\' valign=\'middle\'>When activated, this action sets the creature’s event to the specified value.</td><td align=\'left\' valign=\'middle\'>Parameter 1: The new phase to set the creature in. This number must be an integer between 0 and 31 inclusive.</td></tr>
<tr bgcolor=\'#FEFEFF\'><td align=\'center\' valign=\'middle\'>23</td><td align=\'center\' valign=\'middle\'>ACTION_T_INC_PHASE</td><td align=\'left\' valign=\'middle\'>When activated, this action will increase (or decrease) the current creature’s phase.</td><td align=\'left\' valign=\'middle\'>Parameter 1: The number of phases to increase or decrease. Use negative values to decrease the current phase. After increasing or decreasing the phase by this action, the current phase must not be lower than 0 or exceed 31.</td></tr>
<tr bgcolor=\'#FFFFEE\'><td align=\'center\' valign=\'middle\'>24</td><td align=\'center\' valign=\'middle\'>ACTION_T_EVADE</td><td align=\'left\' valign=\'middle\'>When activated, the creature will immediately exit out of combat, clear its threat list, and move back to its spawn point. Basically, this action will reset the whole encounter.</td></tr>
<tr bgcolor=\'#FEFEFF\'><td align=\'center\' valign=\'middle\'>25</td><td align=\'center\' valign=\'middle\'>ACTION_T_FLEE</td><td align=\'left\' valign=\'middle\'>When activated, the creature will try to flee from combat. Currently this is done by it casting a fear-like spell on itself called "Run Away".</td></tr>
<tr bgcolor=\'#FFFFEE\'><td align=\'center\' valign=\'middle\'>26</td><td align=\'center\' valign=\'middle\'>ACTION_T_QUEST_EVENT_ALL</td><td align=\'left\' valign=\'middle\'>This action does the same thing as the ACTION_T_QUEST_EVENT does but it does it for all players in the creature’s threat list. Note that if a player is not in its threat list for whatever reason, he/she won’t get the quest completed.</td><td align=\'left\' valign=\'middle\'>Parameter 1: The quest ID to finish for everyone.</td></tr>
<tr bgcolor=\'#FEFEFF\'><td align=\'center\' valign=\'middle\'>27</td><td align=\'center\' valign=\'middle\'>ACTION_T_CASTCREATUREGO_ALL</td><td align=\'left\' valign=\'middle\'>This action does the same thing as the ACTION_T_CASTCREATUREGO does but it does it for all players in the creature’s threat list. Note that if a player is not in its threat list for whatever reason, he/she won’t receive the cast emulation.</td><td align=\'left\' valign=\'middle\'>Parameter 1: The quest template ID.<br/><br/>Parameter 2: The spell ID used to simulate the cast.</td></tr>
<tr bgcolor=\'#FFFFEE\'><td align=\'center\' valign=\'middle\'>28</td><td align=\'center\' valign=\'middle\'>ACTION_T_REMOVEAURASFROMSPELL</td><td align=\'left\' valign=\'middle\'>This action will remove all auras from a specific spell from the target.</td><td align=\'left\' valign=\'middle\'>Parameter 1: The target type defining for whom the unit field should be changed. The value in this field needs to be a valid target type as specified in the reference tables below.<br/><br/>Parameter 2: The spell ID whose auras will be removed.</td></tr>
<tr bgcolor=\'#FEFEFF\'><td align=\'center\' valign=\'middle\'>29</td><td align=\'center\' valign=\'middle\'>ACTION_T_RANGED_MOVEMENT</td><td align=\'left\' valign=\'middle\'>This action changes the movement type generator to ranged type using the specified values for angle and distance. Note that specifying zero angle and distance will make it just melee instead.</td><td align=\'left\' valign=\'middle\'>Parameter 1: The distance the mob should keep between it and its target.<br/><br/>Parameter 2: The angle the mob should use.</td></tr>
<tr bgcolor=\'#FFFFEE\'><td align=\'center\' valign=\'middle\'>30</td><td align=\'center\' valign=\'middle\'>ACTION_T_RANDOM_PHASE</td><td align=\'left\' valign=\'middle\'>Randomly sets the phase to one from the three parameter choices. Note: (1)</td><td align=\'left\' valign=\'middle\'>Parameter 1: A possible random phase choice.<br/><br/>Parameter 2: A possible random phase choice.<br/><br/>Parameter 3: A possible random phase choice.</td></tr>
<tr bgcolor=\'#FEFEFF\'><td align=\'center\' valign=\'middle\'>31</td><td align=\'center\' valign=\'middle\'>ACTION_T_RANDOM_PHASE_RANGE</td><td align=\'left\' valign=\'middle\'>Randomly sets the phase between a range of phases controlled by the parameters.</td><td align=\'left\' valign=\'middle\'>Parameter 1: The minimum of the phase range.<br/><br/>Parameter 2: The maximum of the phase range. The number here must be greater than the one in parameter 1.</td></tr>
<tr bgcolor=\'#FFFFEE\'><td align=\'center\' valign=\'middle\'>32</td><td align=\'center\' valign=\'middle\'>ACTION_T_SUMMON</td><td align=\'left\' valign=\'middle\'>Summons a creature using the data specified in the separate summons table.</td><td align=\'left\' valign=\'middle\'>Parameter 1: The creature template ID to be summoned. The value here needs to be a valid creature template ID.<br/><br/>Parameter 2: The target type defining who the summoned creature will attack. The value in this field needs to be a valid target type as specified in the reference tables below. Note: Using target type 0 will cause the summoned creature to not attack anyone.<br/><br/>Parameter 3: The summon ID from the eventai_summons table controlling the position (and spawntime) where the summoned mob should be spawned at.</td></tr>
<tr bgcolor=\'#FEFEFF\'><td align=\'center\' valign=\'middle\'>33</td><td align=\'center\' valign=\'middle\'>ACTION_T_KILLED_MONSTER</td><td align=\'left\' valign=\'middle\'>When activated, this action will call KilledMonster() function for the player. It can be used to give creature credit for killing a creature (note that it can be ANY creature including certain quest specific triggers). In general if the quest is set to be accompished on different creatures (e.g. "Credit" templates).</td><td align=\'left\' valign=\'middle\'>Parameter 1: The creature template ID. The value here must be a valid creature template ID.<br/><br/>Parameter 2: The target type defining whom the quest kill count should be given to. The value in this field needs to be a valid target type as specified in the reference tables below.</td></tr>
<tr bgcolor=\'#FFFFEE\'><td align=\'center\' valign=\'middle\'>34</td><td align=\'center\' valign=\'middle\'>ACTION_T_SET_INST_DATA</td><td align=\'left\' valign=\'middle\'>Sets data for the instance. Note that this will only work when the creature is inside an instantiable zone that has a valid script (ScriptedInstance) assigned.</td><td align=\'left\' valign=\'middle\'>Parameter 1: The field to change in the instance script. Again, this field needs to be a valid field that has been already defined in the instance’s script.<br/><br/>Parameter 2: The value to put at that field index. The number here must be a valid 32 bit number.</td></tr>
<tr bgcolor=\'#FEFEFF\'><td align=\'center\' valign=\'middle\'>35</td><td align=\'center\' valign=\'middle\'>ACTION_T_SET_INST_DATA64</td><td align=\'left\' valign=\'middle\'>Sets GUID (64 bits) data for the instance based on the target. Note that this will only work when the creature is inside an instantiable zone that has a valid script (ScriptedInstance) assigned.</td><td align=\'left\' valign=\'middle\'>Parameter 1: The field to change in the instance script. Again, this field needs to be a valid field that has been already defined in the instance’s script.<br/><br/>Parameter 2: The target type to use to get the GUID that will be stored at the field index. The value in this field needs to be a valid target type as specified in the reference tables below.</td></tr>
<tr bgcolor=\'#FFFFEE\'><td align=\'center\' valign=\'middle\'>36</td><td align=\'center\' valign=\'middle\'>ACTION_T_UPDATE_TEMPLATE</td><td align=\'left\' valign=\'middle\'>This function temporarily changes creature entry to new entry, display is changed, loot is changed, but AI is not changed. At respawn creature will be reverted to original entry.</td><td align=\'left\' valign=\'middle\'>Parameter 1: The creature template ID. The value here must be a valid creature template ID.<br/><br/>Parameter 2: Use model_id from team: Alliance(0) or Horde (1).</td></tr>
<tr bgcolor=\'#FEFEFF\'><td align=\'center\' valign=\'middle\'>37</td><td align=\'center\' valign=\'middle\'>ACTION_T_DIE</td><td align=\'left\' valign=\'middle\'>Kills the creature</td></tr>
<tr bgcolor=\'#FFFFEE\'><td align=\'center\' valign=\'middle\'>38</td><td align=\'center\' valign=\'middle\'>ACTION_T_ZONE_COMBAT_PULSE</td><td align=\'left\' valign=\'middle\'>Places all players within the instance into combat with the creature. Only works in combat and only works inside of instances.</td></tr>
<tr bgcolor=\'#FEFEFF\'><td align=\'center\' valign=\'middle\'>39</td><td align=\'center\' valign=\'middle\'>ACTION_T_CALL_FOR_HELP</td><td align=\'left\' valign=\'middle\'>Call any friendly creatures (if its not in combat/etc) in radius attack creature target.</td><td align=\'left\' valign=\'middle\'>Parameter 1: Radius from creature.</td></tr>
<tr bgcolor=\'#FFFFEE\'><td align=\'center\' valign=\'middle\'>40</td><td align=\'center\' valign=\'middle\'>ACTION_T_SET_SHEATH</td><td align=\'left\' valign=\'middle\'>Let set sheath state for creature (0-no weapon show (not used mostly by creatures), 1-melee weapon show, 2-ranged weapon show)</td><td align=\'left\' valign=\'middle\'>Parameter 1: Sheath state of the creature.</td></tr>
<tr bgcolor=\'#FEFEFF\'><td align=\'center\' valign=\'middle\'>41</td><td align=\'center\' valign=\'middle\'>ACTION_T_FORCE_DESPAWN</td><td align=\'left\' valign=\'middle\'>Despawns the creature.</td><td align=\'left\' valign=\'middle\'>Parameter 1: Despawn delay.</td></tr>
</table>
','Action Type|Enum Name|<Description|<Parameters
0|ACTION_T_NONE|Does nothing!|&nbsp;
1|ACTION_T_SAY|Displays the -TextId as defined. In case -TextId2 and optionally -TextId3, the output will be randomized. Type text are defined in the eventai_texts table (say, yell, whisper, etc) along with other options for the text. All values are required to be negative.|Parameter 1: The entry of the text that the NPC should use from eventai_texts table. Optionally a entry from other tables can be used (such as custom_texts are required to be negative and exist in a *_texts-table. The type text to be displayed are defined in the texts-table itself (Say, Yell, Whisper, Emote Text, Boss Whisper, Boss Emote)Other options are also to be defined in the texts-table, such as a sound to be heard with the text and the language used in output (common, dwarvish, etc).In case this entry has a localized version of the text, the localized text will be displayed in client that support this locale.<br/><br/>Parameter 2: Optional. TextId can be defined in addition. The same apply to this as explained above, however eventAI will randomize between the two.<br/><br/>Parameter 3: Optional, if Parameter 2 exist. In this case, eventAI will randomize between three.
2|ACTION_T_YELL|UNUSED|&nbsp;
3|ACTION_T_TEXTEMOTE|UNUSED|&nbsp;
4|ACTION_T_SOUND|When activated, the creature will play the specified sound.|Parameter 1: The sound ID to be played. Sound IDs are contained in the DBC files.
5|ACTION_T_EMOTE|When activated, the creature will perform a visual emote. Unlike a text emote, a visual emote is one where the creature will actually move or perform a gesture.|Parameter 1: The emote ID that the creature should perform. Emote IDs are also contained in the DBC but they can be found in the mangos source as well.
6|ACTION_T_RANDOM_SAY|UNUSED|&nbsp;
7|ACTION_T_RANDOM_YELL|UNUSED|&nbsp;
8|ACTION_T_RANDOM_TEXTEMOTE|UNUSED|&nbsp;
9|ACTION_T_RANDOM_SOUND|Similar to the ACTION_T_SOUND action, when this action is activated, it will choose at random a sound to play. This action needs all three parameters to be filled and it will pick a random entry from the three. Note: (1)|Parameter 1: The sound ID to be played as choice one.<br/><br/>Parameter 2: The sound ID to be played as choice two.<br/><br/>Parameter 3: The sound ID to be played as choice three.
10|ACTION_T_RANDOM_EMOTE|Similar to the ACTION_T_EMOTE action, when this action is activated, it will choose at random an emote ID to emote visually. This action needs all three parameters to be filled and it will pick a random entry from the three. Note: (1)|Parameter 1: The emote ID that the creature should perform as choice one.<br/><br/>Parameter 2: The emote ID that the creature should perform as choice two.<br/><br/>Parameter 3: The emote ID that the creature should perform as choice three.
11|ACTION_T_CAST|When activated, the creature will cast a spell specified by a spell ID on a target specified by the target type.|Parameter 1: The spell ID to use for the cast. The value used in this field needs to be a valid spell ID.<br/><br/>Parameter 2: The target type defining who the creature should cast on. The value in this field needs to be a valid target type as specified in the reference tables below.<br/><br/>Parameter 3: See spell flags. If it is 1, then the spell cast will interrupt any spells that are already in the progress of being casted; otherwise if the creature is already casting a spell and this field is 0, then this action will be skipped.
12|ACTION_T_SUMMON|When activated, the creature will summon another creature at the same spot as itself that will attack the specified target.|Parameter 1: The creature template ID to be summoned. The value here needs to be a valid creature template ID.<br/><br/>Parameter 2: The target type defining who the summoned creature will attack. The value in this field needs to be a valid target type as specified in the reference tables below. Note: Using target type 0 will cause the summoned creature to not attack anyone.<br/><br/>Parameter 3: The duration until the summoned creature should be unsummoned. The value in this field is in milliseconds or 0. If zero, then the creature will not be unsummoned until it leaves combat, but only works with t_type !=0.
13|ACTION_T_THREAT_SINGLE_PCT|When activated, this action will modify the threat of a target in the creature’s threat list by the specified percent.|Parameter 1: Threat percent that should be modified. The value in this field can range from -100 to +100. If it is negative, threat will be taken away and if positive, threat will be added.<br/><br/>Parameter 2: The target type defining on whom the threat change should occur. The value in this field needs to be a valid target type as specified in the reference tables below.
14|ACTION_T_THREAT_ALL_PCT|When activated, this action will modify the threat for everyone in the creature’s threat list by the specified percent.|Parameter 1: The percent that should be used in modifying everyone’s threat in the creature’s threat list. The value here can range from -100 to +100. Note: Using -100 will cause the creature to reset everyone’s threat to 0 so that everyone has the same amount of threat. It does NOT make any changes as to who is in the threat list.
15|ACTION_T_QUEST_EVENT|When activated, this action will satisfy the external completion requirement for the quest for the specified target defined by the target type. This action can only be used with player targets so it must be ensured that the target type will point to a player.|Parameter 1: The quest template ID. The value here must be a valid quest template ID. Furthermore, the quest should have SpecialFlags  &#124; 2 as it would need to be completed by an external event which is the activation of this action.<br/><br/>Parameter 2: The target type defining whom the quest should be completed for. The value in this field needs to be a valid target type as specified in the reference tables below.
16|ACTION_T_CASTCREATUREGO|When activated, this action will call CastedCreatureOrGO() function for the player. It can be used to give quest credit for casting a spell on the creature.|Parameter 1: The quest template ID. The value here must be a valid quest template ID.<br/><br/>Parameter 2: The spell ID to use to simulate the cast. The value used in this field needs to be a valid spell ID.<br/><br/>Parameter 3: The target type defining whom the quest credit should be given to. The value in this field needs to be a valid target type as specified in the reference tables below.
17|ACTION_T_SET_UNIT_FIELD|When activated, this action can change the target’s unit field values. More information on the field value indeces can be found at character data data.|Parameter 1: The index of the field number to be changed. Use character data data for a list of indeces and what they control. Note that a creature shares the same indeces with a player except for the PLAYER_* ones.<br/><br/>Parameter 2: The new value to be put in the field.<br/><br/>Parameter 3: The target type defining for whom the unit field should be changed. The value in this field needs to be a valid target type as specified in the reference tables below.
18|ACTION_T_SET_UNIT_FLAG|When activated, this action changes the target’s flags by adding (turning on) more flags. For example, this action can make the creature unattackable/unselectable if the right flags are used.|Parameter 1: The flag(s) to be set. Multiple flags can be set by using bitwise-OR on them (adding them together).<br/><br/>Parameter 2: The target type defining for whom the flags should be changed. The value in this field needs to be a valid target type as specified in the reference tables below.
19|ACTION_T_REMOVE_UNIT_FLAG|When activated, this action changes the target’s flags by removing (turning off) flags. For example, this action can make the creature normal after it was unattackable/unselectable if the right flags are used.|Parameter 1: The flag(s) to be removed. Multiple flags can be set by using bitwise-OR on them (adding them together).<br/><br/>Parameter 2: The target type defining for whom the flags should be changed. The value in this field needs to be a valid target type as specified in the reference tables below.
20|ACTION_T_AUTO_ATTACK|This action controls whether or not the creature should stop or start the auto melee attack.|Parameter 1: If zero, then the creature will stop its melee attacks. If non-zero, then the creature will either continue its melee attacks (the action would then have no effect) or it will start its melee attacks on the target with the top threat if its melee attacks were previously stopped.
21|ACTION_T_COMBAT_MOVEMENT|This action controls whether or not the creature will always move towards its target.|Parameter 1: If zero, then the creature will stop moving towards its victim (if its victim gets out of melee range) and will be stationary. If non-zero, then the creature will either continue to follow its victim (the action would have no effect) or it will start to follow the target with the top threat if its movement was disabled before.
22|ACTION_T_SET_PHASE|When activated, this action sets the creature’s event to the specified value.|Parameter 1: The new phase to set the creature in. This number must be an integer between 0 and 31 inclusive.
23|ACTION_T_INC_PHASE|When activated, this action will increase (or decrease) the current creature’s phase.|Parameter 1: The number of phases to increase or decrease. Use negative values to decrease the current phase. After increasing or decreasing the phase by this action, the current phase must not be lower than 0 or exceed 31.
24|ACTION_T_EVADE|When activated, the creature will immediately exit out of combat, clear its threat list, and move back to its spawn point. Basically, this action will reset the whole encounter.
25|ACTION_T_FLEE|When activated, the creature will try to flee from combat. Currently this is done by it casting a fear-like spell on itself called "Run Away".
26|ACTION_T_QUEST_EVENT_ALL|This action does the same thing as the ACTION_T_QUEST_EVENT does but it does it for all players in the creature’s threat list. Note that if a player is not in its threat list for whatever reason, he/she won’t get the quest completed.|Parameter 1: The quest ID to finish for everyone.
27|ACTION_T_CASTCREATUREGO_ALL|This action does the same thing as the ACTION_T_CASTCREATUREGO does but it does it for all players in the creature’s threat list. Note that if a player is not in its threat list for whatever reason, he/she won’t receive the cast emulation.|Parameter 1: The quest template ID.<br/><br/>Parameter 2: The spell ID used to simulate the cast.
28|ACTION_T_REMOVEAURASFROMSPELL|This action will remove all auras from a specific spell from the target.|Parameter 1: The target type defining for whom the unit field should be changed. The value in this field needs to be a valid target type as specified in the reference tables below.<br/><br/>Parameter 2: The spell ID whose auras will be removed.
29|ACTION_T_RANGED_MOVEMENT|This action changes the movement type generator to ranged type using the specified values for angle and distance. Note that specifying zero angle and distance will make it just melee instead.|Parameter 1: The distance the mob should keep between it and its target.<br/><br/>Parameter 2: The angle the mob should use.
30|ACTION_T_RANDOM_PHASE|Randomly sets the phase to one from the three parameter choices. Note: (1)|Parameter 1: A possible random phase choice.<br/><br/>Parameter 2: A possible random phase choice.<br/><br/>Parameter 3: A possible random phase choice.
31|ACTION_T_RANDOM_PHASE_RANGE|Randomly sets the phase between a range of phases controlled by the parameters.|Parameter 1: The minimum of the phase range.<br/><br/>Parameter 2: The maximum of the phase range. The number here must be greater than the one in parameter 1.
32|ACTION_T_SUMMON|Summons a creature using the data specified in the separate summons table.|Parameter 1: The creature template ID to be summoned. The value here needs to be a valid creature template ID.<br/><br/>Parameter 2: The target type defining who the summoned creature will attack. The value in this field needs to be a valid target type as specified in the reference tables below. Note: Using target type 0 will cause the summoned creature to not attack anyone.<br/><br/>Parameter 3: The summon ID from the eventai_summons table controlling the position (and spawntime) where the summoned mob should be spawned at.
33|ACTION_T_KILLED_MONSTER|When activated, this action will call KilledMonster() function for the player. It can be used to give creature credit for killing a creature (note that it can be ANY creature including certain quest specific triggers). In general if the quest is set to be accompished on different creatures (e.g. "Credit" templates).|Parameter 1: The creature template ID. The value here must be a valid creature template ID.<br/><br/>Parameter 2: The target type defining whom the quest kill count should be given to. The value in this field needs to be a valid target type as specified in the reference tables below.
34|ACTION_T_SET_INST_DATA|Sets data for the instance. Note that this will only work when the creature is inside an instantiable zone that has a valid script (ScriptedInstance) assigned.|Parameter 1: The field to change in the instance script. Again, this field needs to be a valid field that has been already defined in the instance’s script.<br/><br/>Parameter 2: The value to put at that field index. The number here must be a valid 32 bit number.
35|ACTION_T_SET_INST_DATA64|Sets GUID (64 bits) data for the instance based on the target. Note that this will only work when the creature is inside an instantiable zone that has a valid script (ScriptedInstance) assigned.|Parameter 1: The field to change in the instance script. Again, this field needs to be a valid field that has been already defined in the instance’s script.<br/><br/>Parameter 2: The target type to use to get the GUID that will be stored at the field index. The value in this field needs to be a valid target type as specified in the reference tables below.
36|ACTION_T_UPDATE_TEMPLATE|This function temporarily changes creature entry to new entry, display is changed, loot is changed, but AI is not changed. At respawn creature will be reverted to original entry.|Parameter 1: The creature template ID. The value here must be a valid creature template ID.<br/><br/>Parameter 2: Use model_id from team: Alliance(0) or Horde (1).
37|ACTION_T_DIE|Kills the creature|
38|ACTION_T_ZONE_COMBAT_PULSE|Places all players within the instance into combat with the creature. Only works in combat and only works inside of instances.|
39|ACTION_T_CALL_FOR_HELP|Call any friendly creatures (if its not in combat/etc) in radius attack creature target.|Parameter 1: Radius from creature.
40|ACTION_T_SET_SHEATH|Let set sheath state for creature (0-no weapon show (not used mostly by creatures), 1-melee weapon show, 2-ranged weapon show)|Parameter 1: Sheath state of the creature.
41|ACTION_T_FORCE_DESPAWN|Despawns the creature.|Parameter 1: Despawn delay.');
    

        -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
        -- -- PLACE UPDATE SQL ABOVE -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
        -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -

        -- If we get here ok, commit the changes
        IF bRollback = TRUE THEN
            ROLLBACK;
            SHOW ERRORS;
            SELECT '* UPDATE FAILED *' AS `===== Status =====`,@cCurResult AS `===== DB is on Version: =====`;



        ELSE
            COMMIT;
            SELECT '* UPDATE COMPLETE *' AS `===== Status =====`,@cNewResult AS `===== DB is now on Version =====`;
        END IF;
    ELSE    -- Current version is not the expected version
        IF (@cCurResult = @cNewResult) THEN    -- Does the current version match the new version
            SELECT '* UPDATE SKIPPED *' AS `===== Status =====`,@cCurResult AS `===== DB is already on Version =====`;
        ELSE    -- Current version is not one related to this update
            IF(@cCurResult IS NULL) THEN    -- Something has gone wrong
                SELECT '* UPDATE FAILED *' AS `===== Status =====`,'Unable to locate DB Version Information' AS `============= Error Message =============`;
            ELSE
		IF(@cOldResult IS NULL) THEN    -- Something has gone wrong
		    SET @cCurVersion := (SELECT `version` FROM db_version ORDER BY `version` DESC, STRUCTURE DESC, CONTENT DESC LIMIT 0,1);
		    SET @cCurStructure := (SELECT `STRUCTURE` FROM db_version ORDER BY `version` DESC, STRUCTURE DESC, CONTENT DESC LIMIT 0,1);
		    SET @cCurContent := (SELECT `Content` FROM db_version ORDER BY `version` DESC, STRUCTURE DESC, CONTENT DESC LIMIT 0,1);
                    SET @cCurOutput = CONCAT(@cCurVersion, '_', @cCurStructure, '_', @cCurContent, ' - ',@cCurResult);
                    SET @cOldResult = CONCAT('Rel',@cOldVersion, '_', @cOldStructure, '_', @cOldContent, ' - ','IS NOT APPLIED');
                    SELECT '* UPDATE SKIPPED *' AS `===== Status =====`,@cOldResult AS `=== Expected ===`,@cCurOutput AS `===== Found Version =====`;
		ELSE
		    SET @cCurVersion := (SELECT `version` FROM db_version ORDER BY `version` DESC, STRUCTURE DESC, CONTENT DESC LIMIT 0,1);
		    SET @cCurStructure := (SELECT `STRUCTURE` FROM db_version ORDER BY `version` DESC, STRUCTURE DESC, CONTENT DESC LIMIT 0,1);
		    SET @cCurContent := (SELECT `Content` FROM db_version ORDER BY `version` DESC, STRUCTURE DESC, CONTENT DESC LIMIT 0,1);
                    SET @cCurOutput = CONCAT(@cCurVersion, '_', @cCurStructure, '_', @cCurContent, ' - ',@cCurResult);
                    SELECT '* UPDATE SKIPPED *' AS `===== Status =====`,@cOldResult AS `=== Expected ===`,@cCurOutput AS `===== Found Version =====`;
                END IF;
            END IF;
        END IF;
    END IF;
END $$

DELIMITER ;

-- Execute the procedure
CALL update_mangos();

-- Drop the procedure
DROP PROCEDURE IF EXISTS `update_mangos`;

