-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `gossip_texts` SET `content_loc8`='[PH] Неизвестный текст SD3' WHERE `entry`=-3000000;
UPDATE `gossip_texts` SET `content_loc8`='Иезекииль сказал, что у вас есть одна книга...' WHERE `entry`=-3000105;
UPDATE `gossip_texts` SET `content_loc8`='Пусть маршал Виндзор знает, что я готова.' WHERE `entry`=-3000106;
UPDATE `gossip_texts` SET `content_loc8`='Я готова, как и мои войска. Давайте закончим этот маскарад!' WHERE `entry`=-3000107;
UPDATE `gossip_texts` SET `content_loc8`='Уделите мне минутку вашего времени, сэр.' WHERE `entry`=-3000108;
UPDATE `gossip_texts` SET `content_loc8`='Я готова, Оронок. Давай уничтожим Цируха и освободим духов!' WHERE `entry`=-3000109;
UPDATE `gossip_texts` SET `content_loc8`='Да... конечно же, Страж Наковальни. Я должна показать вам кое-что в этом здании.' WHERE `entry`=-3000110;
UPDATE `gossip_texts` SET `content_loc8`='Поверните ключ, чтобы запустить механизм.' WHERE `entry`=-3000111;
UPDATE `gossip_texts` SET `content_loc8`='Открой дверь во внутренний двор.' WHERE `entry`=-3033000;
UPDATE `gossip_texts` SET `content_loc8`='Идем!' WHERE `entry`=-3043000;
UPDATE `gossip_texts` SET `content_loc8`='Я готова.' WHERE `entry`=-3090000;
UPDATE `gossip_texts` SET `content_loc8`='Ты свободен, Дугал! Выбирайся отсюда!' WHERE `entry`=-3230000;
UPDATE `gossip_texts` SET `content_loc8`='Выбирайся отсюда, Тобиас, ты свободен!' WHERE `entry`=-3230001;
UPDATE `gossip_texts` SET `content_loc8`='Ваше рабство заканчивается, Doom\'rel. Я бросаю вам вызов!' WHERE `entry`=-3230002;
UPDATE `gossip_texts` SET `content_loc8`='Почему бы вам с Камнеузлом не пойти и найти какое-нибудь укромное место...' WHERE `entry`=-3230003;
UPDATE `gossip_texts` SET `content_loc8`='Расскажите подробнее.' WHERE `entry`=-3409000;
UPDATE `gossip_texts` SET `content_loc8`='Что еще вы хотели сказать?' WHERE `entry`=-3409001;
UPDATE `gossip_texts` SET `content_loc8`='Ты бросил нам вызов, и мы пришли. Где тот господин, о котором ты говорил?' WHERE `entry`=-3409002;
UPDATE `gossip_texts` SET `content_loc8`='Я не сделала ни одной ошибки.' WHERE `entry`=-3469000;
UPDATE `gossip_texts` SET `content_loc8`='Ты совсем свихнулся, Нефарий. Ты разговариваешь загадками.' WHERE `entry`=-3469001;
UPDATE `gossip_texts` SET `content_loc8`='Давай.' WHERE `entry`=-3469002;
UPDATE `gossip_texts` SET `content_loc8`='Не могу, Валестраз! Ведь есть же какой-то способ тебя вылечить!' WHERE `entry`=-3469003;
UPDATE `gossip_texts` SET `content_loc8`='Валестраз, нет!!!' WHERE `entry`=-3469004;
UPDATE `gossip_texts` SET `content_loc8`='Давай разберемся.' WHERE `entry`=-3509000;
UPDATE `gossip_texts` SET `content_loc8`='Посмотрим, что у тебя есть.' WHERE `entry`=-3509001;

SET NAMES 'latin1';
