-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `gossip_texts` SET `content_loc3`='[PH] SD3 unbekannter Text' WHERE `entry`=-3000000;
UPDATE `gossip_texts` SET `content_loc3`='Ezekiel sagte, Ihr hättet da ein bestimmtes Buch...' WHERE `entry`=-3000105;
UPDATE `gossip_texts` SET `content_loc3`='Wohin würdet Ihr gerne fliegen?' WHERE `entry`=-3000106;
UPDATE `gossip_texts` SET `content_loc3`='Ich bin bereit, ebenso wie meine Streitkräfte. Lasst uns diese Maskerade beenden!' WHERE `entry`=-3000107;
UPDATE `gossip_texts` SET `content_loc3`='Habt Ihr einen Moment Zeit für mich, mein Herr?' WHERE `entry`=-3000108;
UPDATE `gossip_texts` SET `content_loc3`='Ich bin bereit, Oronok. Lasst uns Cyrukh zerstören und die Elemente befreien!' WHERE `entry`=-3000109;
UPDATE `gossip_texts` SET `content_loc3`='Warum... ja, natürlich. Ich möchte Euch etwas zeigen, hier, in diesem Gebäude dort, Meister Ambossel.' WHERE `entry`=-3000110;
UPDATE `gossip_texts` SET `content_loc3`='Dreht den Schlüssel, um die Maschine zu starten.' WHERE `entry`=-3000111;
UPDATE `gossip_texts` SET `content_loc3`='Öffnet bitte die Tür zum Hof.' WHERE `entry`=-3033000;
UPDATE `gossip_texts` SET `content_loc3`='Lasst das Ereignis beginnen!' WHERE `entry`=-3043000;
UPDATE `gossip_texts` SET `content_loc3`='Ich bin bereit anzufangen.' WHERE `entry`=-3090000;
UPDATE `gossip_texts` SET `content_loc3`='Ihr seid frei, Dughal! Verschwindet!' WHERE `entry`=-3230000;
UPDATE `gossip_texts` SET `content_loc3`='Raus hier, Tobias, Ihr seid frei!' WHERE `entry`=-3230001;
UPDATE `gossip_texts` SET `content_loc3`='Deine Bondage ist zu Ende, Doom\'rel. Ich fordere dich heraus!' WHERE `entry`=-3230002;
UPDATE `gossip_texts` SET `content_loc3`='Warum sucht Ihr und Rocknot Euch nicht ein ruhiges Plätzchen...' WHERE `entry`=-3230003;
UPDATE `gossip_texts` SET `content_loc3`='Erzählt mir mehr.' WHERE `entry`=-3409000;
UPDATE `gossip_texts` SET `content_loc3`='Habt Ihr sonst noch etwas zu sagen?' WHERE `entry`=-3409001;
UPDATE `gossip_texts` SET `content_loc3`='Ihr habt uns herausgefordert, und wir sind gekommen. Wo ist dieser Meister, von dem Ihr spracht?' WHERE `entry`=-3409002;
UPDATE `gossip_texts` SET `content_loc3`='Ich habe keine Fehler begangen.' WHERE `entry`=-3469000;
UPDATE `gossip_texts` SET `content_loc3`='Ihr habt den Verstand verloren, Nefarius. Ihr sprecht in Rätseln.' WHERE `entry`=-3469001;
UPDATE `gossip_texts` SET `content_loc3`='Bitte gern.' WHERE `entry`=-3469002;
UPDATE `gossip_texts` SET `content_loc3`='Ich kann nicht, Vaelastrasz! Mit Sicherheit kann etwas getan werden, um Euch zu heilen!' WHERE `entry`=-3469003;
UPDATE `gossip_texts` SET `content_loc3`='Nein, Vaelastrasz, nicht!!!' WHERE `entry`=-3469004;
UPDATE `gossip_texts` SET `content_loc3`='Finden wir\'s raus.' WHERE `entry`=-3509000;
UPDATE `gossip_texts` SET `content_loc3`='Schauen wir mal, was Ihr da habt.' WHERE `entry`=-3509001;

SET NAMES 'latin1';
