-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `gossip_texts` SET `content_loc7`='[PH] SD3 texto desconocido' WHERE `entry`=-3000000;
UPDATE `gossip_texts` SET `content_loc7`='Ezekiel dijo que tú podrías tener cierto libro...' WHERE `entry`=-3000105;
UPDATE `gossip_texts` SET `content_loc7`='Haz saber al mariscal Windsor que ya estoy lista.' WHERE `entry`=-3000106;
UPDATE `gossip_texts` SET `content_loc7`='Estoy lista; y también lo están mis tropas. ¡Acabemos con esta farsa!' WHERE `entry`=-3000107;
UPDATE `gossip_texts` SET `content_loc7`='Necesito un momento de su tiempo, señor.' WHERE `entry`=-3000108;
UPDATE `gossip_texts` SET `content_loc7`='Estoy preparada, Oronok. ¡Destruyamos a Cyrukh y liberemos los elementos!' WHERE `entry`=-3000109;
UPDATE `gossip_texts` SET `content_loc7`='Vaya... sí, por supuesto. Tengo algo que mostrarle dentro de ese edificio, Prospector Guardayunque.' WHERE `entry`=-3000110;
UPDATE `gossip_texts` SET `content_loc7`='Gira la llave para poner en marcha la máquina.' WHERE `entry`=-3000111;
UPDATE `gossip_texts` SET `content_loc7`='Por favor, abre la cerradura de la puerta del patio.' WHERE `entry`=-3033000;
UPDATE `gossip_texts` SET `content_loc7`='¡Que empiece la sesión!' WHERE `entry`=-3043000;
UPDATE `gossip_texts` SET `content_loc7`='Estoy lista para empezar.' WHERE `entry`=-3090000;
UPDATE `gossip_texts` SET `content_loc7`='¡Eres libre, Dughal! ¡Márchate!' WHERE `entry`=-3230000;
UPDATE `gossip_texts` SET `content_loc7`='¡Sal de aquí, Tobias! ¡Eres libre!' WHERE `entry`=-3230001;
UPDATE `gossip_texts` SET `content_loc7`='Tu esclavitud ha llegado a su fin, Doom\'rel. ¡Te desafío!' WHERE `entry`=-3230002;
UPDATE `gossip_texts` SET `content_loc7`='¿Por qué tú y Sinroca no buscáis un lugar más tranquilito...?' WHERE `entry`=-3230003;
UPDATE `gossip_texts` SET `content_loc7`='Cuéntame más.' WHERE `entry`=-3409000;
UPDATE `gossip_texts` SET `content_loc7`='¿Qué más tienes que decir?' WHERE `entry`=-3409001;
UPDATE `gossip_texts` SET `content_loc7`='Nos retaste y hemos venido. ¿Dónde está el maestro del que hablas?' WHERE `entry`=-3409002;
UPDATE `gossip_texts` SET `content_loc7`='No he cometido ningún error.' WHERE `entry`=-3469000;
UPDATE `gossip_texts` SET `content_loc7`='Has perdido la cabeza, Nefarius. Hablas con acertijos.' WHERE `entry`=-3469001;
UPDATE `gossip_texts` SET `content_loc7`='Hazlo, por favor.' WHERE `entry`=-3469002;
UPDATE `gossip_texts` SET `content_loc7`='¡No puedo, Vaelastrasz! ¡Tiene que haber algo que podamos hacer para curarte!' WHERE `entry`=-3469003;
UPDATE `gossip_texts` SET `content_loc7`='¡¡¡Vaelastrasz, no!!!' WHERE `entry`=-3469004;
UPDATE `gossip_texts` SET `content_loc7`='Comprobémoslo.' WHERE `entry`=-3509000;
UPDATE `gossip_texts` SET `content_loc7`='Veamos qué tienes.' WHERE `entry`=-3509001;

SET NAMES 'latin1';
