-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc4`='Ahn\'Qiraj Ossirian Crystal' WHERE `word_id` = 116901; -- locales_gameobject - name : entry=210312
UPDATE `trans_words` SET `content_loc4`='Ahn\'Qiraj Sand Trap' WHERE `word_id` = 116905; -- locales_gameobject - name : entry=210339
UPDATE `trans_words` SET `content_loc4`='Altar of Hyjal' WHERE `word_id` = 116916; -- locales_gameobject - name : entry=211019
UPDATE `trans_words` SET `content_loc4`='Arena Spoils' WHERE `word_id` = 116413; -- locales_gameobject - name : entry=181074
UPDATE `trans_words` SET `content_loc4`='Asheron\'s Tome of Summoning' WHERE `word_id` = 116915; -- locales_gameobject - name : entry=211018
UPDATE `trans_words` SET `content_loc4`='Black Portal' WHERE `word_id` = 116919; -- locales_gameobject - name : entry=211023
UPDATE `trans_words` SET `content_loc4`='Bowel with Boobles' WHERE `word_id` = 115556; -- locales_gameobject - name : entry=176157
UPDATE `trans_words` SET `content_loc4`='Cat Figurine Trap' WHERE `word_id` = 117014; -- locales_gameobject - name : entry=12653
UPDATE `trans_words` SET `content_loc4`='Commander\'s Tent' WHERE `word_id` = 116918; -- locales_gameobject - name : entry=211022
UPDATE `trans_words` SET `content_loc4`='Excavation Tent Pavillion' WHERE `word_id` = 116900; -- locales_gameobject - name : entry=210286
UPDATE `trans_words` SET `content_loc4`='Eye of Asheron' WHERE `word_id` = 116917; -- locales_gameobject - name : entry=211021
UPDATE `trans_words` SET `content_loc4`='Fire on ground' WHERE `word_id` = 114820; -- locales_gameobject - name : entry=56809
UPDATE `trans_words` SET `content_loc4`='Floating Purple Crystal Broken 01' WHERE `word_id` = 116912; -- locales_gameobject - name : entry=210348
UPDATE `trans_words` SET `content_loc4`='Floating Red Crystal Broken 01' WHERE `word_id` = 116910; -- locales_gameobject - name : entry=210346
UPDATE `trans_words` SET `content_loc4`='Floating Red Crystal Broken 03' WHERE `word_id` = 116909; -- locales_gameobject - name : entry=210345
UPDATE `trans_words` SET `content_loc4`='Gastric Exit' WHERE `word_id` = 116913; -- locales_gameobject - name : entry=210349
UPDATE `trans_words` SET `content_loc4`='Glyphed Crystal' WHERE `word_id` = 116904; -- locales_gameobject - name : entry=210337
UPDATE `trans_words` SET `content_loc4`='Hive Fireflies 01' WHERE `word_id` = 116906; -- locales_gameobject - name : entry=210341
UPDATE `trans_words` SET `content_loc4`='Kre\'tal\'s Wagon' WHERE `word_id` = 116914; -- locales_gameobject - name : entry=211017
UPDATE `trans_words` SET `content_loc4`='Lair Exit' WHERE `word_id` = 116921; -- locales_gameobject - name : entry=211035
UPDATE `trans_words` SET `content_loc4`='Locked Cage' WHERE `word_id` = 115510; -- locales_gameobject - name : entry=175786
UPDATE `trans_words` SET `content_loc4`='Logs on fire' WHERE `word_id` = 116717; -- locales_gameobject - name : entry=184507
UPDATE `trans_words` SET `content_loc4`='Mephistroph\'s HellFire' WHERE `word_id` = 116929; -- locales_gameobject - name : entry=211084
UPDATE `trans_words` SET `content_loc4`='Mysterious Monument' WHERE `word_id` = 116924; -- locales_gameobject - name : entry=211053
UPDATE `trans_words` SET `content_loc4`='Mysterious Wailing Caverns Chest' WHERE `word_id` = 116598; -- locales_gameobject - name : entry=180055
UPDATE `trans_words` SET `content_loc4`='New Year Alliance Standing Banner' WHERE `word_id` = 116898; -- locales_gameobject - name : entry=210214
UPDATE `trans_words` SET `content_loc4`='New Year Horde Hanging Banner 02' WHERE `word_id` = 116897; -- locales_gameobject - name : entry=210213
UPDATE `trans_words` SET `content_loc4`='OUT OF ORDER! Use Postman instead - your GM\'s' WHERE `word_id` = 116053; -- locales_gameobject - name : entry=179963
UPDATE `trans_words` SET `content_loc4`='Rockwall Fence' WHERE `word_id` = 116926; -- locales_gameobject - name : entry=211064
UPDATE `trans_words` SET `content_loc4`='Sand Worm Rock Base' WHERE `word_id` = 116907; -- locales_gameobject - name : entry=210343
UPDATE `trans_words` SET `content_loc4`='Sarcophag' WHERE `word_id` = 116928; -- locales_gameobject - name : entry=211067
UPDATE `trans_words` SET `content_loc4`='Silithus Crystal Formation 03' WHERE `word_id` = 116908; -- locales_gameobject - name : entry=210344
UPDATE `trans_words` SET `content_loc4`='Teleport-Stone to Hyjal' WHERE `word_id` = 116922; -- locales_gameobject - name : entry=211050
UPDATE `trans_words` SET `content_loc4`='Test' WHERE `word_id` = 49952; -- locales_gameobject - name : entry=2558
UPDATE `trans_words` SET `content_loc4`='Tree Stump' WHERE `word_id` = 116923; -- locales_gameobject - name : entry=211052
UPDATE `trans_words` SET `content_loc4`='Twilight Tablet' WHERE `word_id` = 116903; -- locales_gameobject - name : entry=210335
UPDATE `trans_words` SET `content_loc4`='Wickerman Guardian Ember' WHERE `word_id` = 117017; -- locales_gameobject - name : entry=180574
UPDATE `trans_words` SET `content_loc4`='Wooden Board' WHERE `word_id` = 116718; -- locales_gameobject - name : entry=184515

SET NAMES 'latin1';
