-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc4`='All I ever wanted to do was study.' WHERE `word_id` = 197115; -- locales_npc_text - Text1_0 : entry=11458
UPDATE `trans_words` SET `content_loc4`='Hey there, cutie! Mind rubbing some lotion on my exposed areas?' WHERE `word_id` = 196163; -- locales_npc_text - Text0_1 : entry=16644
UPDATE `trans_words` SET `content_loc4`='Hey there, friend. My name\'s Remy. I\'m from Redridge to the east, and came here looking for business, looking for business. You got any...got any??' WHERE `word_id` = 197874; -- locales_npc_text - Text0_1 : entry=6157
UPDATE `trans_words` SET `content_loc4`='Missing US text.' WHERE `word_id` = 196442; -- locales_npc_text - Text0_1 : entry=7775
UPDATE `trans_words` SET `content_loc4`='The Stormpike Guard is in need of your assistance in the fight against the Frostwolf Clan, $N. Speak to Brogun Stoneshield on the Warrior\'s Terrace and he will help you find your way to Alterac Valley.' WHERE `word_id` = 194630; -- locales_npc_text - Text1_0 : entry=7496
UPDATE `trans_words` SET `content_loc4`='Things can get a little stuffy here in Nethergarde. Sometimes a dwarf just needs a brew to take her mind off her duty for a bit.' WHERE `word_id` = 196190; -- locales_npc_text - Text0_1 : entry=16219
UPDATE `trans_words` SET `content_loc4`='UDB Missing US text' WHERE `word_id` = 197021; -- locales_npc_text - Text1_0 : entry=10734
UPDATE `trans_words` SET `content_loc4`='Weary of one of your demonic charges? Hoping for one with a more pleasing name?$B$BFor a price, I can assist you in the obliteration of a current minion so that you may summon an entirely new one...' WHERE `word_id` = 196121; -- locales_npc_text - Text0_1 : entry=17816
UPDATE `trans_words` SET `content_loc4`='Well, if it isn\'t a young, bristling $C, no doubt drawn here by talk of my exploits in fields of battle!$B$BNo time for stories now, for there are great, important deeds that need doing!  So if you\'re looking for glory, then luck shines on you today...' WHERE `word_id` = 197875; -- locales_npc_text - Text0_1 : entry=1244

SET NAMES 'latin1';
