-- File generated by Mangos Online Translation Editor (MOTE) v2.10
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc4`='Engraved with the words \'For years of service: -EVC.\'' WHERE `word_id`=9700; -- locales_item - description : entry=2239
UPDATE `trans_words` SET `content_loc4`='Only ONE May Rise... (and consequently, only ONE may loot this head)' WHERE `word_id`=22115; -- locales_item - description : entry=20383
UPDATE `trans_words` SET `content_loc4`='Teaches Inner Fire (Rank 2).' WHERE `word_id`=14419; -- locales_item - description : entry=8964
UPDATE `trans_words` SET `content_loc4`='Teaches Polymorph: Turtle.' WHERE `word_id` = 23741; -- locales_item - description : entry=22739
UPDATE `trans_words` SET `content_loc4`='Teaches you how to make Thorium Shells.' WHERE `word_id`=19461; -- locales_item - description : entry=16051
UPDATE `trans_words` SET `content_loc4`='Weapon of Mass Destruction (test)' WHERE `word_id` = 12211; -- locales_item - name : entry=5418
UPDATE `trans_words` SET `content_loc4`='Weapon of Massive Destruction (test)' WHERE `word_id` = 12210; -- locales_item - name : entry=5417
UPDATE `trans_words` SET `content_loc4`='可以作为空气图腾，大地图腾，火焰图腾和水之图腾使用。' WHERE `word_id`=23479; -- locales_item - description : entry=22345


SET NAMES 'latin1';
