-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `locales_command` SET `help_text_loc4`='语法: .荣誉展示\r\n\r\n显示被选中玩家的荣誉统计数据' WHERE `id`=252;

SET NAMES 'latin1';
