-- ----------------------------------------------------------------
-- This is an attempt to create a full transactional MaNGOS update
-- Now compatible with newer MySql Databases (v1.5)
-- ----------------------------------------------------------------
DROP PROCEDURE IF EXISTS `update_mangos`; 

DELIMITER $$

CREATE DEFINER=`root`@`localhost` PROCEDURE `update_mangos`()
BEGIN
    DECLARE bRollback BOOL  DEFAULT FALSE ;
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET `bRollback` = TRUE;

    -- Current Values (TODO - must be a better way to do this)
    SET @cCurVersion := (SELECT `version` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
    SET @cCurStructure := (SELECT `structure` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
    SET @cCurContent := (SELECT `content` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);

    -- Expected Values
    SET @cOldVersion = '22'; 
    SET @cOldStructure = '03'; 
    SET @cOldContent = '003';

    -- New Values
    SET @cNewVersion = '22';
    SET @cNewStructure = '03';
    SET @cNewContent = '004';
                            -- DESCRIPTION IS 30 Characters MAX    
    SET @cNewDescription = 'Update_conditions_comments';

                        -- COMMENT is 150 Characters MAX
    SET @cNewComment = 'Update_conditions_comments';

    -- Evaluate all settings
    SET @cCurResult := (SELECT `description` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
    SET @cOldResult := (SELECT `description` FROM `db_version` WHERE `version`=@cOldVersion AND `structure`=@cOldStructure AND `content`=@cOldContent);
    SET @cNewResult := (SELECT `description` FROM `db_version` WHERE `version`=@cNewVersion AND `structure`=@cNewStructure AND `content`=@cNewContent);

    IF (@cCurResult = @cOldResult) THEN    -- Does the current version match the expected version
        -- APPLY UPDATE
        START TRANSACTION;
        -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
        -- -- PLACE UPDATE SQL BELOW -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
        -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
		
		/*
			Update column `comments` in `conditions` table in order to understand better the condition purpose.
		*/
		
		UPDATE `conditions` SET `comments` =  'NOT (Quest ID 5944 Rewarded)' WHERE `condition_entry` = '294' AND `type` =  '-3';
		UPDATE `conditions` SET `comments` =  'NOT (Quest ID 4083 Rewarded)' WHERE `condition_entry` = '304' AND `type` =  '-3';
		UPDATE `conditions` SET `comments` =  'NOT (Quest ID 7785 Rewarded)' WHERE `condition_entry` = '310' AND `type` =  '-3';
		UPDATE `conditions` SET `comments` =  'NOT ((((Player Has Aura: 23768, EffectIndex: 0 OR Player Has Aura: 23769, EffectIndex: 0) OR (Player Has Aura: 23767, EffectIndex: 0 OR Player Has Aura: 23738, EffectIndex: 0)) OR ((Player Has Aura: 23766, EffectIndex: 0 OR Player Has Aura: 23737, EffectIndex: 0) OR (Player Has Aura: 23736, EffectIndex: 0 OR Player Has Aura: 23735, EffectIndex: 0))))' WHERE `condition_entry` = '870' AND `type` =  '-3';
		UPDATE `conditions` SET `comments` =  'NOT (Player Has Aura: 22799, EffectIndex: 0)' WHERE `condition_entry` = '977' AND `type` =  '-3';
		UPDATE `conditions` SET `comments` =  '(Quest ID 30 Taken OR Quest ID 272 Taken)' WHERE `condition_entry` = '357' AND `type` =  '-2';
		UPDATE `conditions` SET `comments` =  '(Player RaceMask: 4 OR (Has Minimum Rank Exalted With Faction ID: 47 AND Player RaceMask: 73))' WHERE `condition_entry` = '1100' AND `type` =  '-2';
		UPDATE `conditions` SET `comments` =  '(Quest ID 5929 Taken OR Quest ID 5930 Taken)' WHERE `condition_entry` = '298' AND `type` =  '-2';
		UPDATE `conditions` SET `comments` =  '(Quest ID 7734 Rewarded OR Quest ID 7734 Taken)' WHERE `condition_entry` = '102' AND `type` =  '-2';
		UPDATE `conditions` SET `comments` =  '(Quest ID 7733 Rewarded OR Quest ID 7733 Taken)' WHERE `condition_entry` = '103' AND `type` =  '-2';
		UPDATE `conditions` SET `comments` =  '(Quest ID 5401 Rewarded OR Quest ID 5405 Rewarded)' WHERE `condition_entry` = '141' AND `type` =  '-2';
		UPDATE `conditions` SET `comments` =  '(Quest ID 5503 Rewarded OR (Quest ID 5401 Rewarded OR Quest ID 5405 Rewarded))' WHERE `condition_entry` = '142' AND `type` =  '-2';
		UPDATE `conditions` SET `comments` =  '(Quest ID 5513 Rewarded OR Quest ID 5507 Rewarded)' WHERE `condition_entry` = '155' AND `type` =  '-2';
		UPDATE `conditions` SET `comments` =  '(Quest ID 5504 Rewarded OR (Quest ID 5513 Rewarded OR Quest ID 5507 Rewarded))' WHERE `condition_entry` = '156' AND `type` =  '-2';
		UPDATE `conditions` SET `comments` =  '(Quest ID 5524 Rewarded OR Quest ID 5521 Rewarded)' WHERE `condition_entry` = '160' AND `type` =  '-2';
		UPDATE `conditions` SET `comments` =  '(Quest ID 5517 Rewarded OR (Quest ID 5524 Rewarded OR Quest ID 5521 Rewarded))' WHERE `condition_entry` = '161' AND `type` =  '-2';
		UPDATE `conditions` SET `comments` =  '((Has Minimum Rank Exalted With Faction ID: 69 AND Player RaceMask: 69) OR Player RaceMask: 8)' WHERE `condition_entry` = '222' AND `type` =  '-2';
		UPDATE `conditions` SET `comments` =  '(Quest ID 5862 Taken OR (Quest ID 5862 Rewarded AND NOT (Quest ID 5944 Rewarded)))' WHERE `condition_entry` = '296' AND `type` =  '-2';
		UPDATE `conditions` SET `comments` =  '(Player Has 1 or more of Item ID 18563 in Inventory OR Player Has 1 or more of Item ID 18564 in Inventory)' WHERE `condition_entry` = '311' AND `type` =  '-2';
		UPDATE `conditions` SET `comments` =  '((Has Minimum Rank Exalted With Faction ID: 54 AND Player RaceMask: 13) OR Player RaceMask: 64)' WHERE `condition_entry` = '331' AND `type` =  '-2';
		UPDATE `conditions` SET `comments` =  '(Quest ID 5902 Taken OR Quest ID 5904 Taken)' WHERE `condition_entry` = '604' AND `type` =  '-2';
		UPDATE `conditions` SET `comments` =  '((Has Minimum Rank Exalted With Faction ID: 76 AND Player RaceMask: 176) OR Player RaceMask: 2)' WHERE `condition_entry` = '845' AND `type` =  '-2';
		UPDATE `conditions` SET `comments` =  '((Has Minimum Rank Exalted With Faction ID: 72 AND Player RaceMask: 76) OR Player RaceMask: 1)' WHERE `condition_entry` = '846' AND `type` =  '-2';
		UPDATE `conditions` SET `comments` =  '((Has Minimum Rank Exalted With Faction ID: 81 AND Player RaceMask: 146) OR Player RaceMask: 32)' WHERE `condition_entry` = '847' AND `type` =  '-2';
		UPDATE `conditions` SET `comments` =  '((Has Minimum Rank Exalted With Faction ID: 530 AND Player RaceMask: 50) OR Player RaceMask: 128)' WHERE `condition_entry` = '849' AND `type` =  '-2';
		UPDATE `conditions` SET `comments` =  '((Has Minimum Rank Exalted With Faction ID: 68 AND Player RaceMask: 162) OR Player RaceMask: 16)' WHERE `condition_entry` = '851' AND `type` =  '-2';
		UPDATE `conditions` SET `comments` =  '(Player Has Aura: 23768, EffectIndex: 0 OR Player Has Aura: 23769, EffectIndex: 0)' WHERE `condition_entry` = '863' AND `type` =  '-2';
		UPDATE `conditions` SET `comments` =  '(Player Has Aura: 23767, EffectIndex: 0 OR Player Has Aura: 23738, EffectIndex: 0)' WHERE `condition_entry` = '864' AND `type` =  '-2';
		UPDATE `conditions` SET `comments` =  '(Player Has Aura: 23766, EffectIndex: 0 OR Player Has Aura: 23737, EffectIndex: 0)' WHERE `condition_entry` = '865' AND `type` =  '-2';
		UPDATE `conditions` SET `comments` =  '(Player Has Aura: 23736, EffectIndex: 0 OR Player Has Aura: 23735, EffectIndex: 0)' WHERE `condition_entry` = '866' AND `type` =  '-2';
		UPDATE `conditions` SET `comments` =  '((Player Has Aura: 23768, EffectIndex: 0 OR Player Has Aura: 23769, EffectIndex: 0) OR (Player Has Aura: 23767, EffectIndex: 0 OR Player Has Aura: 23738, EffectIndex: 0))' WHERE `condition_entry` = '867' AND `type` =  '-2';
		UPDATE `conditions` SET `comments` =  '((Player Has Aura: 23766, EffectIndex: 0 OR Player Has Aura: 23737, EffectIndex: 0) OR (Player Has Aura: 23736, EffectIndex: 0 OR Player Has Aura: 23735, EffectIndex: 0))' WHERE `condition_entry` = '868' AND `type` =  '-2';
		UPDATE `conditions` SET `comments` =  '(((Player Has Aura: 23768, EffectIndex: 0 OR Player Has Aura: 23769, EffectIndex: 0) OR (Player Has Aura: 23767, EffectIndex: 0 OR Player Has Aura: 23738, EffectIndex: 0)) OR ((Player Has Aura: 23766, EffectIndex: 0 OR Player Has Aura: 23737, EffectIndex: 0) OR (Player Has Aura: 23736, EffectIndex: 0 OR Player Has Aura: 23735, EffectIndex: 0)))' WHERE `condition_entry` = '869' AND `type` =  '-2';
		UPDATE `conditions` SET `comments` =  '(Horde Player AND Player ClassMask: 1024)' WHERE `condition_entry` = '33' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Alliance Player AND Player ClassMask: 1024)' WHERE `condition_entry` = '34' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Quest ID 4101 Rewarded AND Player Has Less Than 1 of Item ID 11511 in Inventory/Bank)' WHERE `condition_entry` = '131' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Quest ID 4102 Rewarded AND Player Has Less Than 1 of Item ID 11511 in Inventory/Bank)' WHERE `condition_entry` = '132' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player ClassMask: 1 AND Player Level >= 10)' WHERE `condition_entry` = '133' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player ClassMask: 2 AND Player Level >= 10)' WHERE `condition_entry` = '134' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player ClassMask: 4 AND Player Level >= 10)' WHERE `condition_entry` = '135' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player ClassMask: 8 AND Player Level >= 10)' WHERE `condition_entry` = '136' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player ClassMask: 8 AND Player Level >= 24)' WHERE `condition_entry` = '181' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player ClassMask: 64 AND Player Level >= 10)' WHERE `condition_entry` = '137' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player ClassMask: 128 AND Player Level >= 10)' WHERE `condition_entry` = '138' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player ClassMask: 256 AND Player Level >= 10)' WHERE `condition_entry` = '139' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player ClassMask: 1024 AND Player Level >= 10)' WHERE `condition_entry` = '140' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player Has 1 or more of Item ID 9280 in Inventory AND Player Has Less Than 1 of Item ID 14639 in Inventory/Bank)' WHERE `condition_entry` = '1106' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Quest ID 8867 Rewarded AND Player Has Less Than 1 of Item ID 21711 in Inventory/Bank)' WHERE `condition_entry` = '47' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player Has Less Than 1 of Item ID 20949 in Inventory/Bank AND Quest ID 8555 Rewarded)' WHERE `condition_entry` = '62' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Quest ID 6824 Rewarded AND Has Maximum Rank Honored With Faction ID: 749)' WHERE `condition_entry` = '70' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Quest ID 6824 Rewarded AND Has Minimum Rank Revered With Faction ID: 749)' WHERE `condition_entry` = '74' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '((Quest ID 6824 Rewarded AND Has Maximum Rank Honored With Faction ID: 749) AND Player Has Less Than 1 of Item ID 17333 in Inventory/Bank)' WHERE `condition_entry` = '73' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '((Quest ID 6824 Rewarded AND Has Minimum Rank Revered With Faction ID: 749) AND Player Has Less Than 1 of Item ID 22754 in Inventory/Bank)' WHERE `condition_entry` = '76' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Has Skill ID 197, Minimum Skill Value 280 AND NOT Player Has Learned Spell: 26086)' WHERE `condition_entry` = '80' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Has Skill ID 197, Minimum Skill Value 280 AND Player Has Learned Spell: 26086)' WHERE `condition_entry` = '81' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player Has Less Than 1 of Item ID 12846 in Inventory AND (Quest ID 5503 Rewarded OR (Quest ID 5401 Rewarded OR Quest ID 5405 Rewarded)))' WHERE `condition_entry` = '143' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Quest ID 3454 Rewarded AND Player Has Less Than 1 of Item ID 10515 in Inventory/Bank)' WHERE `condition_entry` = '144' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Quest ID 5216 Rewarded AND Player Has Less Than 1 of Item ID 13370 in Inventory/Bank)' WHERE `condition_entry` = '145' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Quest ID 558 Taken AND Player Has Less Than 1 of Item ID 18642 in Inventory)' WHERE `condition_entry` = '147' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Quest ID 4261 Taken AND Player Has Less Than 1 of Item ID 11445 in Inventory/Bank)' WHERE `condition_entry` = '148' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Quest ID 8620 Taken AND Player Has Less Than 1 of Item ID 21106 in Inventory/Bank)' WHERE `condition_entry` = '149' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Quest ID 8620 Taken AND Player Has Less Than 1 of Item ID 21107 in Inventory/Bank)' WHERE `condition_entry` = '150' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Quest ID 8620 Taken AND Player Has Less Than 1 of Item ID 21109 in Inventory/Bank)' WHERE `condition_entry` = '151' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player Level >= 10 AND Player ClassMask: 1)' WHERE `condition_entry` = '1083' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player Level >= 10 AND Player ClassMask: 2)' WHERE `condition_entry` = '1082' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player Level >= 10 AND Player ClassMask: 4)' WHERE `condition_entry` = '1085' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player Level >= 10 AND Player ClassMask: 8)' WHERE `condition_entry` = '1081' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player Level >= 10 AND Player ClassMask: 64)' WHERE `condition_entry` = '1080' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player Level >= 10 AND Player ClassMask: 128)' WHERE `condition_entry` = '1079' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player Level >= 10 AND Player ClassMask: 256)' WHERE `condition_entry` = '1028' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player Level >= 10 AND Player ClassMask: 1024)' WHERE `condition_entry` = '1087' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player Level >= 10 AND Player ClassMask: 16)' WHERE `condition_entry` = '163' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Holiday 324 Active AND NOT Player Has Aura: 24755, EffectIndex: 0)' WHERE `condition_entry` = '164' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player Has Less Than 1 of Item ID 13370 in Inventory/Bank AND Quest ID 5237 Rewarded)' WHERE `condition_entry` = '279' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player Has Less Than 1 of Item ID 13370 in Inventory/Bank AND Quest ID 5238 Rewarded)' WHERE `condition_entry` = '280' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Has Skill ID 129, Minimum Skill Value 240 AND NOT Player Has Learned Spell: 10841)' WHERE `condition_entry` = '182' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Has Skill ID 129, Minimum Skill Value 260 AND NOT Player Has Learned Spell: 18629)' WHERE `condition_entry` = '183' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Has Skill ID 129, Minimum Skill Value 290 AND NOT Player Has Learned Spell: 18630)' WHERE `condition_entry` = '184' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player Has Learned Spell: 20219 AND NOT Player Has Learned Spell: 23489)' WHERE `condition_entry` = '185' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player Has Learned Spell: 20222 AND NOT Player Has Learned Spell: 23486)' WHERE `condition_entry` = '187' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Has Skill ID 202, Minimum Skill Value 260 AND (Player Has Learned Spell: 20219 AND NOT Player Has Learned Spell: 23489))' WHERE `condition_entry` = '191' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Has Skill ID 202, Minimum Skill Value 260 AND (Player Has Learned Spell: 20222 AND NOT Player Has Learned Spell: 23486))' WHERE `condition_entry` = '192' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player Level >= 40 AND (Has Skill ID 129, Minimum Skill Value 240 AND NOT Player Has Learned Spell: 10841))' WHERE `condition_entry` = '193' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player Level >= 40 AND (Has Skill ID 129, Minimum Skill Value 260 AND NOT Player Has Learned Spell: 18629))' WHERE `condition_entry` = '194' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player Level >= 40 AND (Has Skill ID 129, Minimum Skill Value 290 AND NOT Player Has Learned Spell: 18630))' WHERE `condition_entry` = '195' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Quest ID 6681 NOT Taken AND NOT Rewarded AND (Player ClassMask: 8 AND Player Level >= 24))' WHERE `condition_entry` = '196' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Has Minimum Rank Exalted With Faction ID: 69 AND Player RaceMask: 69)' WHERE `condition_entry` = '220' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Has Skill ID 202, Minimum Skill Value 300 AND NOT Player Has Learned Spell: 22704)' WHERE `condition_entry` = '248' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Quest ID 4296 Taken AND Player Has Less Than 1 of Item ID 11470 in Inventory/Bank)' WHERE `condition_entry` = '255' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Quest ID 975 Rewarded AND Player Has 1 or more of Item ID 12384 in Inventory/Bank)' WHERE `condition_entry` = '258' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Has Skill ID 171, Minimum Skill Value 300 AND NOT Player Has Learned Spell: 24266)' WHERE `condition_entry` = '262' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Quest ID 3628 Taken AND NOT Completed AND Player Has 1 or more of Item ID 10757 in Inventory)' WHERE `condition_entry` = '265' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Has Skill ID 171, Minimum Skill Value 180 AND NOT Player Has Learned Spell: 3451)' WHERE `condition_entry` = '272' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Has Skill ID 185, Minimum Skill Value 175 AND NOT Player Has Learned Spell: 13028)' WHERE `condition_entry` = '271' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Quest ID 6628 Taken AND NOT Player Has Aura: 6767, EffectIndex: 0)' WHERE `condition_entry` = '276' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Quest ID 925 Taken AND Player Has Less Than 1 of Item ID 18643 in Inventory/Bank)' WHERE `condition_entry` = '287' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Quest ID 5862 Rewarded AND NOT (Quest ID 5944 Rewarded))' WHERE `condition_entry` = '295' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(NOT Player Has Aura: 17961, EffectIndex: 0 AND (Quest ID 5862 Taken OR (Quest ID 5862 Rewarded AND NOT (Quest ID 5944 Rewarded))))' WHERE `condition_entry` = '297' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Has Skill ID 186, Minimum Skill Value 230 AND NOT Player Has Learned Spell: 14891)' WHERE `condition_entry` = '302' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Quest ID 4083 Rewarded AND (Has Skill ID 186, Minimum Skill Value 230 AND NOT Player Has Learned Spell: 14891))' WHERE `condition_entry` = '303' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '((Has Skill ID 186, Minimum Skill Value 230 AND NOT Player Has Learned Spell: 14891) AND NOT (Quest ID 4083 Rewarded))' WHERE `condition_entry` = '305' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player Has Less Than 1 of Item ID 19016 in Inventory/Bank AND NOT (Quest ID 7785 Rewarded))' WHERE `condition_entry` = '312' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '((Player Has 1 or more of Item ID 18563 in Inventory OR Player Has 1 or more of Item ID 18564 in Inventory) AND (Player Has Less Than 1 of Item ID 19016 in Inventory/Bank AND NOT (Quest ID 7785 Rewarded)))' WHERE `condition_entry` = '313' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Quest ID 1886 Taken AND Player Has Less Than 1 of Item ID 7231 in Inventory/Bank)' WHERE `condition_entry` = '321' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Has Minimum Rank Exalted With Faction ID: 54 AND Player RaceMask: 13)' WHERE `condition_entry` = '329' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Quest ID 8738 Taken AND Player Has Less Than 1 of Item ID 21160 in Inventory/Bank)' WHERE `condition_entry` = '360' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Has Skill ID 171, Minimum Skill Value 125 AND Horde Player)' WHERE `condition_entry` = '364' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Has Skill ID 171, Minimum Skill Value 125 AND Alliance Player)' WHERE `condition_entry` = '365' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Has Skill ID 197, Minimum Skill Value 125 AND Horde Player)' WHERE `condition_entry` = '375' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Has Skill ID 197, Minimum Skill Value 125 AND Alliance Player)' WHERE `condition_entry` = '376' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Source of Condition\'s Last Waypoint <= 2 AND Source of Condition\'s Last Waypoint >= 8)' WHERE `condition_entry` = '388' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Source of Condition\'s Last Waypoint <= 2 AND Source of Condition\'s Last Waypoint >= 10)' WHERE `condition_entry` = '387' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Has Skill ID 202, Minimum Skill Value 50 AND Horde Player)' WHERE `condition_entry` = '394' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Has Skill ID 202, Minimum Skill Value 50 AND Alliance Player)' WHERE `condition_entry` = '395' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Quest ID 2768 Taken AND Source of Condition\'s Last Waypoint == 8)' WHERE `condition_entry` = '409' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player Has Less Than 1 of Item ID 14639 in Inventory/Bank AND (Has Skill ID 202, Minimum Skill Value 140 AND Player Has 1 or more of Item ID 9280 in Inventory))' WHERE `condition_entry` = '672' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Has Skill ID 202, Minimum Skill Value 140 AND Player Has 1 or more of Item ID 9280 in Inventory)' WHERE `condition_entry` = '671' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player Has 1 or more of Item ID 15044 in Inventory AND (Quest ID 5902 Taken OR Quest ID 5904 Taken))' WHERE `condition_entry` = '605' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Quest ID 5535 Rewarded AND Quest ID 5536 Rewarded)' WHERE `condition_entry` = '676' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Has Minimum Rank Exalted With Faction ID: 76 AND Player RaceMask: 176)' WHERE `condition_entry` = '825' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Has Minimum Rank Exalted With Faction ID: 72 AND Player RaceMask: 76)' WHERE `condition_entry` = '826' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Has Minimum Rank Exalted With Faction ID: 81 AND Player RaceMask: 146)' WHERE `condition_entry` = '827' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Has Minimum Rank Exalted With Faction ID: 530 AND Player RaceMask: 50)' WHERE `condition_entry` = '829' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Has Minimum Rank Exalted With Faction ID: 68 AND Player RaceMask: 162)' WHERE `condition_entry` = '831' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player Has Aura: 24746, EffectIndex: 0 AND NOT Player Has Aura: 24748, EffectIndex: 0)' WHERE `condition_entry` = '890' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player Has Aura: 24746, EffectIndex: 0 AND Player Has Aura: 24748, EffectIndex: 0)' WHERE `condition_entry` = '892' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player Has Aura: 24746, EffectIndex: 0 AND Player Has 1 or more of Item ID 20416 in Inventory)' WHERE `condition_entry` = '899' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player Has Aura: 24746, EffectIndex: 0 AND Player Has 1 or more of Item ID 20419 in Inventory)' WHERE `condition_entry` = '900' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player Has Aura: 24746, EffectIndex: 0 AND Player Has 1 or more of Item ID 20418 in Inventory)' WHERE `condition_entry` = '901' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player Has Aura: 24746, EffectIndex: 0 AND Player Has 1 or more of Item ID 20420 in Inventory)' WHERE `condition_entry` = '902' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '((Player Has Aura: 24746, EffectIndex: 0 AND Player Has Aura: 24748, EffectIndex: 0) AND Player Has Aura: 24782, EffectIndex: 0)' WHERE `condition_entry` = '894' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '((Player Has Aura: 24746, EffectIndex: 0 AND Player Has Aura: 24748, EffectIndex: 0) AND Player Has 1 or more of Item ID 20432 in Inventory)' WHERE `condition_entry` = '907' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '((Player Has Aura: 24746, EffectIndex: 0 AND Player Has Aura: 24748, EffectIndex: 0) AND Player Has 1 or more of Item ID 20435 in Inventory)' WHERE `condition_entry` = '908' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '((Player Has Aura: 24746, EffectIndex: 0 AND Player Has Aura: 24748, EffectIndex: 0) AND Player Has 1 or more of Item ID 20433 in Inventory)' WHERE `condition_entry` = '909' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '((Player Has Aura: 24746, EffectIndex: 0 AND Player Has Aura: 24748, EffectIndex: 0) AND Player Has 1 or more of Item ID 20436 in Inventory)' WHERE `condition_entry` = '910' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(((Player Has Aura: 24746, EffectIndex: 0 AND Player Has Aura: 24748, EffectIndex: 0) AND Player Has Aura: 24782, EffectIndex: 0) AND Player Has 1 or more of Item ID 20447 in Inventory)' WHERE `condition_entry` = '915' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(((Player Has Aura: 24746, EffectIndex: 0 AND Player Has Aura: 24748, EffectIndex: 0) AND Player Has Aura: 24782, EffectIndex: 0) AND Player Has 1 or more of Item ID 20449 in Inventory)' WHERE `condition_entry` = '916' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(((Player Has Aura: 24746, EffectIndex: 0 AND Player Has Aura: 24748, EffectIndex: 0) AND Player Has Aura: 24782, EffectIndex: 0) AND Player Has 1 or more of Item ID 20448 in Inventory)' WHERE `condition_entry` = '917' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(((Player Has Aura: 24746, EffectIndex: 0 AND Player Has Aura: 24748, EffectIndex: 0) AND Player Has Aura: 24782, EffectIndex: 0) AND Player Has 1 or more of Item ID 20450 in Inventory)' WHERE `condition_entry` = '918' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Quest ID 4921 Rewarded AND Quest ID 899 Rewarded)' WHERE `condition_entry` = '943' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player Has Aura: 22799, EffectIndex: 0 AND Source of Condition\'s Last Waypoint == 7)' WHERE `condition_entry` = '979' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Has Maximum Rank Neutral With Faction ID: 349 AND Has Minimum Rank Neutral With Faction ID: 349)' WHERE `condition_entry` = '1004' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Has Maximum Rank Friendly With Faction ID: 349 AND Has Minimum Rank Friendly With Faction ID: 349)' WHERE `condition_entry` = '1007' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Quest ID 7721 Rewarded AND Quest ID 7003 Rewarded)' WHERE `condition_entry` = '1023' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Has Minimum Rank Exalted With Faction ID: 47 AND Player RaceMask: 73)' WHERE `condition_entry` = '1027' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Quest ID 2118 Taken AND Player Has Less Than 1 of Item ID 7586 in Inventory/Bank)' WHERE `condition_entry` = '1094' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Quest ID 4021 Taken AND Player Has Less Than 1 of Item ID 11227 in Inventory/Bank)' WHERE `condition_entry` = '1097' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Quest ID 8534 Taken AND Player Has Less Than 1 of Item ID 21158 in Inventory/Bank)' WHERE `condition_entry` = '1103' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '((Player Has 1 or more of Item ID 9280 in Inventory AND Player Has Less Than 1 of Item ID 14639 in Inventory/Bank) AND Player Has 1 or more of Item ID 9327 in Inventory)' WHERE `condition_entry` = '1107' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(((Player Has 1 or more of Item ID 9280 in Inventory AND Player Has Less Than 1 of Item ID 14639 in Inventory/Bank) AND Player Has 1 or more of Item ID 9327 in Inventory) AND Has Skill ID 202, Minimum Skill Value 160)' WHERE `condition_entry` = '1108' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Quest ID 8739 Taken AND Player Has Less Than 1 of Item ID 21161 in Inventory/Bank)' WHERE `condition_entry` = '1111' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Quest ID 8698 Rewarded AND Player Has Less Than 1 of Item ID 21399 in Inventory/Bank)' WHERE `condition_entry` = '1114' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Quest ID 8702 Rewarded AND Player Has Less Than 1 of Item ID 21417 in Inventory/Bank)' WHERE `condition_entry` = '1117' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Quest ID 8704 Rewarded AND Player Has Less Than 1 of Item ID 21402 in Inventory/Bank)' WHERE `condition_entry` = '1120' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Quest ID 8556 Rewarded AND Player Has Less Than 1 of Item ID 21393 in Inventory/Bank)' WHERE `condition_entry` = '1123' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player Level >= 55 AND Player Has Less Than 1 of Item ID 12563 in Inventory/Bank)' WHERE `condition_entry` = '1126' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(NOT Player Has Learned Spell: 3959 AND Player Has 1 or more of Item ID 9327 in Inventory)' WHERE `condition_entry` = '1143' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '((NOT Player Has Learned Spell: 3959 AND Player Has 1 or more of Item ID 9327 in Inventory) AND Has Skill ID 202, Minimum Skill Value 160)' WHERE `condition_entry` = '1144' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Has Minimum Rank Revered With Faction ID: 529 AND Has Skill ID 165, Minimum Skill Value 300)' WHERE `condition_entry` = '1353' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Has Minimum Rank Revered With Faction ID: 529 AND Has Skill ID 164, Minimum Skill Value 300)' WHERE `condition_entry` = '1355' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Has Minimum Rank Revered With Faction ID: 529 AND Has Skill ID 197, Minimum Skill Value 300)' WHERE `condition_entry` = '1357' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Has Minimum Rank Exalted With Faction ID: 529 AND NOT Player Has Learned Spell: 28222)' WHERE `condition_entry` = '1358' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Has Minimum Rank Exalted With Faction ID: 529 AND NOT Player Has Learned Spell: 28219)' WHERE `condition_entry` = '1359' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Has Minimum Rank Exalted With Faction ID: 529 AND NOT Player Has Learned Spell: 28242)' WHERE `condition_entry` = '1360' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Has Minimum Rank Exalted With Faction ID: 529 AND NOT Player Has Learned Spell: 28208)' WHERE `condition_entry` = '1361' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Has Minimum Rank Exalted With Faction ID: 529 AND NOT Player Has Learned Spell: 28207)' WHERE `condition_entry` = '1362' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '(Player Has Less Than 1 of Item ID 22719 in Inventory/Bank AND Quest ID 9233 NOT Taken AND NOT Rewarded)' WHERE `condition_entry` = '1365' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  '((Player Has Less Than 1 of Item ID 22719 in Inventory/Bank AND Quest ID 9233 NOT Taken AND NOT Rewarded) AND Has Minimum Rank Revered With Faction ID: 529)' WHERE `condition_entry` = '1366' AND `type` =  '-1';
		UPDATE `conditions` SET `comments` =  'Player Has Aura: 22799, EffectIndex: 0' WHERE `condition_entry` = '976' AND `type` =  '1';
		UPDATE `conditions` SET `comments` =  'Player Has Aura: 23735, EffectIndex: 0' WHERE `condition_entry` = '862' AND `type` =  '1';
		UPDATE `conditions` SET `comments` =  'Player Has Aura: 23736, EffectIndex: 0' WHERE `condition_entry` = '861' AND `type` =  '1';
		UPDATE `conditions` SET `comments` =  'Player Has Aura: 23737, EffectIndex: 0' WHERE `condition_entry` = '860' AND `type` =  '1';
		UPDATE `conditions` SET `comments` =  'Player Has Aura: 23738, EffectIndex: 0' WHERE `condition_entry` = '858' AND `type` =  '1';
		UPDATE `conditions` SET `comments` =  'Player Has Aura: 23766, EffectIndex: 0' WHERE `condition_entry` = '859' AND `type` =  '1';
		UPDATE `conditions` SET `comments` =  'Player Has Aura: 23767, EffectIndex: 0' WHERE `condition_entry` = '857' AND `type` =  '1';
		UPDATE `conditions` SET `comments` =  'Player Has Aura: 23768, EffectIndex: 0' WHERE `condition_entry` = '855' AND `type` =  '1';
		UPDATE `conditions` SET `comments` =  'Player Has Aura: 23769, EffectIndex: 0' WHERE `condition_entry` = '856' AND `type` =  '1';
		UPDATE `conditions` SET `comments` =  'Player Has Aura: 24705, EffectIndex: 0' WHERE `condition_entry` = '1371' AND `type` =  '1';
		UPDATE `conditions` SET `comments` =  'Player Has Aura: 24746, EffectIndex: 0' WHERE `condition_entry` = '888' AND `type` =  '1';
		UPDATE `conditions` SET `comments` =  'Player Has Aura: 24748, EffectIndex: 0' WHERE `condition_entry` = '891' AND `type` =  '1';
		UPDATE `conditions` SET `comments` =  'Player Has Aura: 24782, EffectIndex: 0' WHERE `condition_entry` = '893' AND `type` =  '1';
		UPDATE `conditions` SET `comments` =  'Player Has 1 or more of Item ID 9173 in Inventory' WHERE `condition_entry` = '2034' AND `type` =  '2';
		UPDATE `conditions` SET `comments` =  'Player Has 1 or more of Item ID 9279 in Inventory' WHERE `condition_entry` = '1' AND `type` =  '2';
		UPDATE `conditions` SET `comments` =  'Player Has 1 or more of Item ID 9280 in Inventory' WHERE `condition_entry` = '35' AND `type` =  '2';
		UPDATE `conditions` SET `comments` =  'Player Has 1 or more of Item ID 9281 in Inventory' WHERE `condition_entry` = '2' AND `type` =  '2';
		UPDATE `conditions` SET `comments` =  'Player Has 1 or more of Item ID 9282 in Inventory' WHERE `condition_entry` = '36' AND `type` =  '2';
		UPDATE `conditions` SET `comments` =  'Player Has 1 or more of Item ID 9327 in Inventory' WHERE `condition_entry` = '1104' AND `type` =  '2';
		UPDATE `conditions` SET `comments` =  'Player Has 1 or more of Item ID 10455 in Inventory' WHERE `condition_entry` = '8' AND `type` =  '2';
		UPDATE `conditions` SET `comments` =  'Player Has 1 or more of Item ID 10757 in Inventory' WHERE `condition_entry` = '264' AND `type` =  '2';
		UPDATE `conditions` SET `comments` =  'Player Has 1 or more of Item ID 11511 in Inventory' WHERE `condition_entry` = '197' AND `type` =  '2';
		UPDATE `conditions` SET `comments` =  'Player Has 1 or more of Item ID 12219 in Inventory' WHERE `condition_entry` = '63' AND `type` =  '2';
		UPDATE `conditions` SET `comments` =  'Player Has 1 or more of Item ID 12384 in Inventory' WHERE `condition_entry` = '207' AND `type` =  '2';
		UPDATE `conditions` SET `comments` =  'Player Has 1 or more of Item ID 12765 in Inventory' WHERE `condition_entry` = '239' AND `type` =  '2';
		UPDATE `conditions` SET `comments` =  'Player Has 1 or more of Item ID 12766 in Inventory' WHERE `condition_entry` = '240' AND `type` =  '2';
		UPDATE `conditions` SET `comments` =  'Player Has 1 or more of Item ID 13370 in Inventory' WHERE `condition_entry` = '208' AND `type` =  '2';
		UPDATE `conditions` SET `comments` =  'Player Has 1 or more of Item ID 15044 in Inventory' WHERE `condition_entry` = '601' AND `type` =  '2';
		UPDATE `conditions` SET `comments` =  'Player Has 1 or more of Item ID 17203 in Inventory' WHERE `condition_entry` = '356' AND `type` =  '2';
		UPDATE `conditions` SET `comments` =  'Player Has 1 or more of Item ID 18250 in Inventory' WHERE `condition_entry` = '114' AND `type` =  '2';
		UPDATE `conditions` SET `comments` =  'Player Has 1 or more of Item ID 18563 in Inventory' WHERE `condition_entry` = '306' AND `type` =  '2';
		UPDATE `conditions` SET `comments` =  'Player Has 1 or more of Item ID 18564 in Inventory' WHERE `condition_entry` = '307' AND `type` =  '2';
		UPDATE `conditions` SET `comments` =  'Player Has 1 or more of Item ID 19727 in Inventory' WHERE `condition_entry` = '241' AND `type` =  '2';
		UPDATE `conditions` SET `comments` =  'Player Has 1 or more of Item ID 20416 in Inventory' WHERE `condition_entry` = '895' AND `type` =  '2';
		UPDATE `conditions` SET `comments` =  'Player Has 1 or more of Item ID 20418 in Inventory' WHERE `condition_entry` = '897' AND `type` =  '2';
		UPDATE `conditions` SET `comments` =  'Player Has 1 or more of Item ID 20419 in Inventory' WHERE `condition_entry` = '896' AND `type` =  '2';
		UPDATE `conditions` SET `comments` =  'Player Has 1 or more of Item ID 20420 in Inventory' WHERE `condition_entry` = '898' AND `type` =  '2';
		UPDATE `conditions` SET `comments` =  'Player Has 1 or more of Item ID 20432 in Inventory' WHERE `condition_entry` = '903' AND `type` =  '2';
		UPDATE `conditions` SET `comments` =  'Player Has 1 or more of Item ID 20433 in Inventory' WHERE `condition_entry` = '905' AND `type` =  '2';
		UPDATE `conditions` SET `comments` =  'Player Has 1 or more of Item ID 20435 in Inventory' WHERE `condition_entry` = '904' AND `type` =  '2';
		UPDATE `conditions` SET `comments` =  'Player Has 1 or more of Item ID 20436 in Inventory' WHERE `condition_entry` = '906' AND `type` =  '2';
		UPDATE `conditions` SET `comments` =  'Player Has 1 or more of Item ID 20447 in Inventory' WHERE `condition_entry` = '911' AND `type` =  '2';
		UPDATE `conditions` SET `comments` =  'Player Has 1 or more of Item ID 20448 in Inventory' WHERE `condition_entry` = '913' AND `type` =  '2';
		UPDATE `conditions` SET `comments` =  'Player Has 1 or more of Item ID 20449 in Inventory' WHERE `condition_entry` = '912' AND `type` =  '2';
		UPDATE `conditions` SET `comments` =  'Player Has 1 or more of Item ID 20450 in Inventory' WHERE `condition_entry` = '914' AND `type` =  '2';
		UPDATE `conditions` SET `comments` =  'Player Has 1 or more of Item ID 20453 in Inventory' WHERE `condition_entry` = '1367' AND `type` =  '2';
		UPDATE `conditions` SET `comments` =  'Player Has 1 or more of Item ID 20949 in Inventory' WHERE `condition_entry` = '60' AND `type` =  '2';
		UPDATE `conditions` SET `comments` =  'Player Has 1 or more of Item ID 21211 in Inventory' WHERE `condition_entry` = '37' AND `type` =  '2';
		UPDATE `conditions` SET `comments` =  'Is In Area ID: 17' WHERE `condition_entry` = '673' AND `type` =  '4';
		UPDATE `conditions` SET `comments` =  'Is In Area ID: 490' WHERE `condition_entry` = '242' AND `type` =  '4';
		UPDATE `conditions` SET `comments` =  'Has Minimum Rank Exalted With Faction ID: 47' WHERE `condition_entry` = '1025' AND `type` =  '5';
		UPDATE `conditions` SET `comments` =  'Has Minimum Rank Exalted With Faction ID: 54' WHERE `condition_entry` = '327' AND `type` =  '5';
		UPDATE `conditions` SET `comments` =  'Has Minimum Rank Friendly With Faction ID: 59' WHERE `condition_entry` = '289' AND `type` =  '5';
		UPDATE `conditions` SET `comments` =  'Has Minimum Rank Exalted With Faction ID: 68' WHERE `condition_entry` = '812' AND `type` =  '5';
		UPDATE `conditions` SET `comments` =  'Has Minimum Rank Exalted With Faction ID: 69' WHERE `condition_entry` = '218' AND `type` =  '5';
		UPDATE `conditions` SET `comments` =  'Has Minimum Rank Exalted With Faction ID: 72' WHERE `condition_entry` = '807' AND `type` =  '5';
		UPDATE `conditions` SET `comments` =  'Has Minimum Rank Exalted With Faction ID: 76' WHERE `condition_entry` = '806' AND `type` =  '5';
		UPDATE `conditions` SET `comments` =  'Has Minimum Rank Exalted With Faction ID: 81' WHERE `condition_entry` = '808' AND `type` =  '5';
		UPDATE `conditions` SET `comments` =  'Has Minimum Rank Neutral With Faction ID: 349' WHERE `condition_entry` = '1003' AND `type` =  '5';
		UPDATE `conditions` SET `comments` =  'Has Minimum Rank Friendly With Faction ID: 349' WHERE `condition_entry` = '1006' AND `type` =  '5';
		UPDATE `conditions` SET `comments` =  'Has Minimum Rank Honored With Faction ID: 349' WHERE `condition_entry` = '1008' AND `type` =  '5';
		UPDATE `conditions` SET `comments` =  'Has Minimum Rank Revered With Faction ID: 529' WHERE `condition_entry` = '1349' AND `type` =  '5';
		UPDATE `conditions` SET `comments` =  'Has Minimum Rank Exalted With Faction ID: 529' WHERE `condition_entry` = '1351' AND `type` =  '5';
		UPDATE `conditions` SET `comments` =  'Has Minimum Rank Exalted With Faction ID: 530' WHERE `condition_entry` = '810' AND `type` =  '5';
		UPDATE `conditions` SET `comments` =  'Has Minimum Rank Exalted With Faction ID: 589' WHERE `condition_entry` = '273' AND `type` =  '5';
		UPDATE `conditions` SET `comments` =  'Has Minimum Rank Revered With Faction ID: 749' WHERE `condition_entry` = '71' AND `type` =  '5';
		UPDATE `conditions` SET `comments` =  'Horde Player' WHERE `condition_entry` = '3' AND `type` =  '6';
		UPDATE `conditions` SET `comments` =  'Alliance Player' WHERE `condition_entry` = '4' AND `type` =  '6';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 129, Minimum Skill Value 1' WHERE `condition_entry` = '396' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 129, Minimum Skill Value 50' WHERE `condition_entry` = '397' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 129, Minimum Skill Value 125' WHERE `condition_entry` = '398' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 129, Minimum Skill Value 200' WHERE `condition_entry` = '399' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 129, Minimum Skill Value 240' WHERE `condition_entry` = '165' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 129, Minimum Skill Value 260' WHERE `condition_entry` = '166' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 129, Minimum Skill Value 290' WHERE `condition_entry` = '167' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 164, Minimum Skill Value 1' WHERE `condition_entry` = '198' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 164, Minimum Skill Value 50' WHERE `condition_entry` = '366' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 164, Minimum Skill Value 125' WHERE `condition_entry` = '367' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 164, Minimum Skill Value 200' WHERE `condition_entry` = '368' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 164, Minimum Skill Value 300' WHERE `condition_entry` = '1354' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 165, Minimum Skill Value 1' WHERE `condition_entry` = '199' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 165, Minimum Skill Value 50' WHERE `condition_entry` = '377' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 165, Minimum Skill Value 125' WHERE `condition_entry` = '378' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 165, Minimum Skill Value 200' WHERE `condition_entry` = '379' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 165, Minimum Skill Value 300' WHERE `condition_entry` = '1352' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 171, Minimum Skill Value 1' WHERE `condition_entry` = '209' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 171, Minimum Skill Value 50' WHERE `condition_entry` = '361' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 171, Minimum Skill Value 125' WHERE `condition_entry` = '362' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 171, Minimum Skill Value 180' WHERE `condition_entry` = '267' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 171, Minimum Skill Value 200' WHERE `condition_entry` = '363' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 171, Minimum Skill Value 300' WHERE `condition_entry` = '260' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 182, Minimum Skill Value 1' WHERE `condition_entry` = '38' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 185, Minimum Skill Value 1' WHERE `condition_entry` = '400' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 185, Minimum Skill Value 50' WHERE `condition_entry` = '401' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 185, Minimum Skill Value 125' WHERE `condition_entry` = '402' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 185, Minimum Skill Value 175' WHERE `condition_entry` = '268' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 185, Minimum Skill Value 200' WHERE `condition_entry` = '403' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 186, Minimum Skill Value 1' WHERE `condition_entry` = '200' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 186, Minimum Skill Value 230' WHERE `condition_entry` = '299' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 197, Minimum Skill Value 1' WHERE `condition_entry` = '201' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 197, Minimum Skill Value 50' WHERE `condition_entry` = '372' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 197, Minimum Skill Value 125' WHERE `condition_entry` = '373' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 197, Minimum Skill Value 200' WHERE `condition_entry` = '374' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 197, Minimum Skill Value 280' WHERE `condition_entry` = '77' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 197, Minimum Skill Value 300' WHERE `condition_entry` = '1356' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 202, Minimum Skill Value 1' WHERE `condition_entry` = '202' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 202, Minimum Skill Value 50' WHERE `condition_entry` = '391' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 202, Minimum Skill Value 125' WHERE `condition_entry` = '392' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 202, Minimum Skill Value 140' WHERE `condition_entry` = '462' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 202, Minimum Skill Value 160' WHERE `condition_entry` = '1105' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 202, Minimum Skill Value 200' WHERE `condition_entry` = '393' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 202, Minimum Skill Value 260' WHERE `condition_entry` = '178' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 202, Minimum Skill Value 300' WHERE `condition_entry` = '243' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 333, Minimum Skill Value 1' WHERE `condition_entry` = '203' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 333, Minimum Skill Value 50' WHERE `condition_entry` = '380' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 333, Minimum Skill Value 125' WHERE `condition_entry` = '381' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 333, Minimum Skill Value 200' WHERE `condition_entry` = '382' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 356, Minimum Skill Value 1' WHERE `condition_entry` = '404' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 356, Minimum Skill Value 50' WHERE `condition_entry` = '405' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 356, Minimum Skill Value 125' WHERE `condition_entry` = '406' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Has Skill ID 356, Minimum Skill Value 200' WHERE `condition_entry` = '407' AND `type` =  '7';
		UPDATE `conditions` SET `comments` =  'Quest ID 862 Rewarded' WHERE `condition_entry` = '1086' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 899 Rewarded' WHERE `condition_entry` = '941' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 975 Rewarded' WHERE `condition_entry` = '256' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 1029 Rewarded' WHERE `condition_entry` = '1009' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 1094 Rewarded' WHERE `condition_entry` = '315' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 1269 Rewarded' WHERE `condition_entry` = '1089' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 1324 Rewarded' WHERE `condition_entry` = '41' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 2458 Rewarded' WHERE `condition_entry` = '1024' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 2662 Rewarded' WHERE `condition_entry` = '43' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 3129 Rewarded' WHERE `condition_entry` = '1088' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 3454 Rewarded' WHERE `condition_entry` = '92' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 3785 Rewarded' WHERE `condition_entry` = '965' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 3786 Rewarded' WHERE `condition_entry` = '974' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 4083 Rewarded' WHERE `condition_entry` = '300' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 4101 Rewarded' WHERE `condition_entry` = '5' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 4102 Rewarded' WHERE `condition_entry` = '6' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 4242 Rewarded' WHERE `condition_entry` = '210' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 4289 Rewarded' WHERE `condition_entry` = '1145' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 4290 Rewarded' WHERE `condition_entry` = '1146' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 4321 Rewarded' WHERE `condition_entry` = '7' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 4921 Rewarded' WHERE `condition_entry` = '942' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 4985 Rewarded' WHERE `condition_entry` = '803' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 5052 Rewarded' WHERE `condition_entry` = '324' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 5058 Rewarded' WHERE `condition_entry` = '1336' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 5216 Rewarded' WHERE `condition_entry` = '93' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 5237 Rewarded' WHERE `condition_entry` = '277' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 5238 Rewarded' WHERE `condition_entry` = '278' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 5245 Rewarded' WHERE `condition_entry` = '805' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 5251 Rewarded' WHERE `condition_entry` = '212' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 5384 Rewarded' WHERE `condition_entry` = '213' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 5401 Rewarded' WHERE `condition_entry` = '106' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 5405 Rewarded' WHERE `condition_entry` = '109' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 5503 Rewarded' WHERE `condition_entry` = '110' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 5504 Rewarded' WHERE `condition_entry` = '154' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 5507 Rewarded' WHERE `condition_entry` = '153' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 5513 Rewarded' WHERE `condition_entry` = '152' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 5517 Rewarded' WHERE `condition_entry` = '159' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 5521 Rewarded' WHERE `condition_entry` = '158' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 5524 Rewarded' WHERE `condition_entry` = '157' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 5529 Rewarded' WHERE `condition_entry` = '325' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 5535 Rewarded' WHERE `condition_entry` = '674' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 5536 Rewarded' WHERE `condition_entry` = '675' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 5862 Rewarded' WHERE `condition_entry` = '290' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 5944 Rewarded' WHERE `condition_entry` = '291' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 6164 Rewarded' WHERE `condition_entry` = '266' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 6383 Rewarded' WHERE `condition_entry` = '214' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 6805 Rewarded' WHERE `condition_entry` = '67' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 6824 Rewarded' WHERE `condition_entry` = '68' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 7003 Rewarded' WHERE `condition_entry` = '1022' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 7721 Rewarded' WHERE `condition_entry` = '1021' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 7733 Rewarded' WHERE `condition_entry` = '99' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 7734 Rewarded' WHERE `condition_entry` = '98' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 7761 Rewarded' WHERE `condition_entry` = '249' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 7785 Rewarded' WHERE `condition_entry` = '308' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 7786 Rewarded' WHERE `condition_entry` = '215' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 7848 Rewarded' WHERE `condition_entry` = '44' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 8227 Rewarded' WHERE `condition_entry` = '259' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 8311 Rewarded' WHERE `condition_entry` = '1368' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 8312 Rewarded' WHERE `condition_entry` = '1369' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 8460 Rewarded' WHERE `condition_entry` = '216' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 8464 Rewarded' WHERE `condition_entry` = '217' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 8555 Rewarded' WHERE `condition_entry` = '59' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 8556 Rewarded' WHERE `condition_entry` = '1121' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 8698 Rewarded' WHERE `condition_entry` = '1112' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 8702 Rewarded' WHERE `condition_entry` = '1115' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 8704 Rewarded' WHERE `condition_entry` = '1118' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 8867 Rewarded' WHERE `condition_entry` = '45' AND `type` =  '8';
		UPDATE `conditions` SET `comments` =  'Quest ID 30 Taken' WHERE `condition_entry` = '10' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 272 Taken' WHERE `condition_entry` = '11' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 558 Taken' WHERE `condition_entry` = '95' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 925 Taken' WHERE `condition_entry` = '285' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 1846 Taken' WHERE `condition_entry` = '223' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 1886 Taken' WHERE `condition_entry` = '320' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 1999 Taken' WHERE `condition_entry` = '1090' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 2118 Taken' WHERE `condition_entry` = '1092' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 2278 Taken' WHERE `condition_entry` = '50' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 2381 Taken' WHERE `condition_entry` = '1091' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 2768 Taken' WHERE `condition_entry` = '408' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 2936 Taken' WHERE `condition_entry` = '832' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 3377 Taken AND NOT Completed' WHERE `condition_entry` = '252' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 3382 Taken' WHERE `condition_entry` = '966' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 3441 Taken AND NOT Completed' WHERE `condition_entry` = '51' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 3566 Taken' WHERE `condition_entry` = '52' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 3628 Taken AND NOT Completed' WHERE `condition_entry` = '263' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 3702 Taken' WHERE `condition_entry` = '282' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 3801 Taken' WHERE `condition_entry` = '205' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 3909 Taken' WHERE `condition_entry` = '283' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 4001 Taken' WHERE `condition_entry` = '1098' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 4021 Taken' WHERE `condition_entry` = '1095' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 4136 Taken' WHERE `condition_entry` = '844' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 4224 Taken' WHERE `condition_entry` = '871' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 4261 Taken' WHERE `condition_entry` = '96' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 4285 Taken' WHERE `condition_entry` = '53' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 4287 Taken' WHERE `condition_entry` = '54' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 4288 Taken' WHERE `condition_entry` = '55' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 4296 Taken' WHERE `condition_entry` = '253' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 4342 Taken' WHERE `condition_entry` = '1099' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 4941 Taken' WHERE `condition_entry` = '9' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 5056 Taken' WHERE `condition_entry` = '224' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 5121 Taken' WHERE `condition_entry` = '211' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 5126 Taken' WHERE `condition_entry` = '288' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 5247 Taken' WHERE `condition_entry` = '804' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 5721 Taken' WHERE `condition_entry` = '39' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 5727 Taken AND NOT Completed' WHERE `condition_entry` = '56' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 5742 Taken' WHERE `condition_entry` = '281' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 5862 Taken' WHERE `condition_entry` = '292' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 5902 Taken' WHERE `condition_entry` = '602' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 5904 Taken' WHERE `condition_entry` = '603' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 5929 Taken' WHERE `condition_entry` = '57' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 5930 Taken' WHERE `condition_entry` = '58' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 6001 Taken AND NOT Completed' WHERE `condition_entry` = '250' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 6002 Taken AND NOT Completed' WHERE `condition_entry` = '251' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 6627 Taken' WHERE `condition_entry` = '12' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 6628 Taken' WHERE `condition_entry` = '274' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 6981 Taken' WHERE `condition_entry` = '316' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 7481 Taken' WHERE `condition_entry` = '49' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 7482 Taken' WHERE `condition_entry` = '48' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 7733 Taken' WHERE `condition_entry` = '101' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 7734 Taken' WHERE `condition_entry` = '100' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 8283 Taken' WHERE `condition_entry` = '1020' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 8304 Taken' WHERE `condition_entry` = '314' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 8534 Taken' WHERE `condition_entry` = '1101' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 8620 Taken' WHERE `condition_entry` = '97' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 8738 Taken' WHERE `condition_entry` = '358' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Quest ID 8739 Taken' WHERE `condition_entry` = '1109' AND `type` =  '9';
		UPDATE `conditions` SET `comments` =  'Player has any Argent Dawn Commission Aura Active (17670,23930,24198,29112,29113)' WHERE `condition_entry` = '237' AND `type` =  '10';
		UPDATE `conditions` SET `comments` =  'NOT Player Has Aura: 6767, EffectIndex: 0' WHERE `condition_entry` = '275' AND `type` =  '11';
		UPDATE `conditions` SET `comments` =  'NOT Player Has Aura: 17961, EffectIndex: 0' WHERE `condition_entry` = '293' AND `type` =  '11';
		UPDATE `conditions` SET `comments` =  'NOT Player Has Aura: 24705, EffectIndex: 0' WHERE `condition_entry` = '1370' AND `type` =  '11';
		UPDATE `conditions` SET `comments` =  'NOT Player Has Aura: 24746, EffectIndex: 0' WHERE `condition_entry` = '887' AND `type` =  '11';
		UPDATE `conditions` SET `comments` =  'NOT Player Has Aura: 24748, EffectIndex: 0' WHERE `condition_entry` = '889' AND `type` =  '11';
		UPDATE `conditions` SET `comments` =  'NOT Player Has Aura: 24755, EffectIndex: 0' WHERE `condition_entry` = '111' AND `type` =  '11';
		UPDATE `conditions` SET `comments` =  'Event ID 2 Active' WHERE `condition_entry` = '238' AND `type` =  '12';
		UPDATE `conditions` SET `comments` =  'Event ID 12 Active' WHERE `condition_entry` = '162' AND `type` =  '12';
		UPDATE `conditions` SET `comments` =  'Event ID 35 Active' WHERE `condition_entry` = '322' AND `type` =  '12';
		UPDATE `conditions` SET `comments` =  'Event ID 36 Active' WHERE `condition_entry` = '323' AND `type` =  '12';
		UPDATE `conditions` SET `comments` =  'Area Flag 1048576 Present in Current Area' WHERE `condition_entry` = '88' AND `type` =  '13';
		UPDATE `conditions` SET `comments` =  'Player ClassMask: 1' WHERE `condition_entry` = '13' AND `type` =  '14';
		UPDATE `conditions` SET `comments` =  'Player ClassMask: 2' WHERE `condition_entry` = '14' AND `type` =  '14';
		UPDATE `conditions` SET `comments` =  'Player ClassMask: 4' WHERE `condition_entry` = '15' AND `type` =  '14';
		UPDATE `conditions` SET `comments` =  'Player ClassMask: 8' WHERE `condition_entry` = '16' AND `type` =  '14';
		UPDATE `conditions` SET `comments` =  'Player ClassMask: 16' WHERE `condition_entry` = '112' AND `type` =  '14';
		UPDATE `conditions` SET `comments` =  'Player ClassMask: 64' WHERE `condition_entry` = '17' AND `type` =  '14';
		UPDATE `conditions` SET `comments` =  'Player ClassMask: 128' WHERE `condition_entry` = '18' AND `type` =  '14';
		UPDATE `conditions` SET `comments` =  'Player ClassMask: 256' WHERE `condition_entry` = '19' AND `type` =  '14';
		UPDATE `conditions` SET `comments` =  'Player ClassMask: 511' WHERE `condition_entry` = '20' AND `type` =  '14';
		UPDATE `conditions` SET `comments` =  'Player ClassMask: 1024' WHERE `condition_entry` = '21' AND `type` =  '14';
		UPDATE `conditions` SET `comments` =  'Player ClassMask: 1279' WHERE `condition_entry` = '22' AND `type` =  '14';
		UPDATE `conditions` SET `comments` =  'Player ClassMask: 1407' WHERE `condition_entry` = '23' AND `type` =  '14';
		UPDATE `conditions` SET `comments` =  'Player ClassMask: 1471' WHERE `condition_entry` = '24' AND `type` =  '14';
		UPDATE `conditions` SET `comments` =  'Player ClassMask: 1519' WHERE `condition_entry` = '1001' AND `type` =  '14';
		UPDATE `conditions` SET `comments` =  'Player ClassMask: 1527' WHERE `condition_entry` = '25' AND `type` =  '14';
		UPDATE `conditions` SET `comments` =  'Player ClassMask: 1531' WHERE `condition_entry` = '26' AND `type` =  '14';
		UPDATE `conditions` SET `comments` =  'Player ClassMask: 1533' WHERE `condition_entry` = '27' AND `type` =  '14';
		UPDATE `conditions` SET `comments` =  'Player ClassMask: 1534' WHERE `condition_entry` = '28' AND `type` =  '14';
		UPDATE `conditions` SET `comments` =  'Player RaceMask: 1' WHERE `condition_entry` = '835' AND `type` =  '14';
		UPDATE `conditions` SET `comments` =  'Player RaceMask: 2' WHERE `condition_entry` = '836' AND `type` =  '14';
		UPDATE `conditions` SET `comments` =  'Player RaceMask: 4' WHERE `condition_entry` = '40' AND `type` =  '14';
		UPDATE `conditions` SET `comments` =  'Player RaceMask: 8' WHERE `condition_entry` = '221' AND `type` =  '14';
		UPDATE `conditions` SET `comments` =  'Player RaceMask: 13' WHERE `condition_entry` = '328' AND `type` =  '14';
		UPDATE `conditions` SET `comments` =  'Player RaceMask: 16' WHERE `condition_entry` = '839' AND `type` =  '14';
		UPDATE `conditions` SET `comments` =  'Player RaceMask: 32' WHERE `condition_entry` = '840' AND `type` =  '14';
		UPDATE `conditions` SET `comments` =  'Player RaceMask: 64' WHERE `condition_entry` = '330' AND `type` =  '14';
		UPDATE `conditions` SET `comments` =  'Player RaceMask: 69' WHERE `condition_entry` = '219' AND `type` =  '14';
		UPDATE `conditions` SET `comments` =  'Player RaceMask: 128' WHERE `condition_entry` = '842' AND `type` =  '14';
		UPDATE `conditions` SET `comments` =  'Player Level >= 10' WHERE `condition_entry` = '107' AND `type` =  '15';
		UPDATE `conditions` SET `comments` =  'Player Level <= 19' WHERE `condition_entry` = '326' AND `type` =  '15';
		UPDATE `conditions` SET `comments` =  'Player Level >= 20' WHERE `condition_entry` = '1011' AND `type` =  '15';
		UPDATE `conditions` SET `comments` =  'Player Level >= 24' WHERE `condition_entry` = '168' AND `type` =  '15';
		UPDATE `conditions` SET `comments` =  'Player Level >= 40' WHERE `condition_entry` = '179' AND `type` =  '15';
		UPDATE `conditions` SET `comments` =  'Player Level >= 51' WHERE `condition_entry` = '1010' AND `type` =  '15';
		UPDATE `conditions` SET `comments` =  'Player Level >= 55' WHERE `condition_entry` = '1125' AND `type` =  '15';
		UPDATE `conditions` SET `comments` =  'Player Has Less Than 1 of Item ID 9279 in Inventory' WHERE `condition_entry` = '29' AND `type` =  '16';
		UPDATE `conditions` SET `comments` =  'Player Has Less Than 1 of Item ID 9281 in Inventory' WHERE `condition_entry` = '30' AND `type` =  '16';
		UPDATE `conditions` SET `comments` =  'Player Has Less Than 1 of Item ID 18642 in Inventory' WHERE `condition_entry` = '113' AND `type` =  '16';
		UPDATE `conditions` SET `comments` =  'NOT Player Has Learned Spell: 3451' WHERE `condition_entry` = '269' AND `type` =  '17';
		UPDATE `conditions` SET `comments` =  'NOT Player Has Learned Spell: 3959' WHERE `condition_entry` = '1142' AND `type` =  '17';
		UPDATE `conditions` SET `comments` =  'NOT Player Has Learned Spell: 10841' WHERE `condition_entry` = '171' AND `type` =  '17';
		UPDATE `conditions` SET `comments` =  'NOT Player Has Learned Spell: 13028' WHERE `condition_entry` = '270' AND `type` =  '17';
		UPDATE `conditions` SET `comments` =  'NOT Player Has Learned Spell: 14891' WHERE `condition_entry` = '301' AND `type` =  '17';
		UPDATE `conditions` SET `comments` =  'NOT Player Has Learned Spell: 18629' WHERE `condition_entry` = '172' AND `type` =  '17';
		UPDATE `conditions` SET `comments` =  'NOT Player Has Learned Spell: 18630' WHERE `condition_entry` = '173' AND `type` =  '17';
		UPDATE `conditions` SET `comments` =  'Player Has Learned Spell: 20219' WHERE `condition_entry` = '169' AND `type` =  '17';
		UPDATE `conditions` SET `comments` =  'Player Has Learned Spell: 20222' WHERE `condition_entry` = '170' AND `type` =  '17';
		UPDATE `conditions` SET `comments` =  'Player Has Learned Spell: 22704' WHERE `condition_entry` = '244' AND `type` =  '17';
		UPDATE `conditions` SET `comments` =  'NOT Player Has Learned Spell: 22704' WHERE `condition_entry` = '245' AND `type` =  '17';
		UPDATE `conditions` SET `comments` =  'NOT Player Has Learned Spell: 23486' WHERE `condition_entry` = '174' AND `type` =  '17';
		UPDATE `conditions` SET `comments` =  'NOT Player Has Learned Spell: 23489' WHERE `condition_entry` = '175' AND `type` =  '17';
		UPDATE `conditions` SET `comments` =  'NOT Player Has Learned Spell: 24266' WHERE `condition_entry` = '261' AND `type` =  '17';
		UPDATE `conditions` SET `comments` =  'Player Has Learned Spell: 26086' WHERE `condition_entry` = '79' AND `type` =  '17';
		UPDATE `conditions` SET `comments` =  'NOT Player Has Learned Spell: 26086' WHERE `condition_entry` = '78' AND `type` =  '17';
		UPDATE `conditions` SET `comments` =  'NOT Player Has Learned Spell: 28205' WHERE `condition_entry` = '1347' AND `type` =  '17';
		UPDATE `conditions` SET `comments` =  'NOT Player Has Learned Spell: 28207' WHERE `condition_entry` = '1350' AND `type` =  '17';
		UPDATE `conditions` SET `comments` =  'NOT Player Has Learned Spell: 28208' WHERE `condition_entry` = '1348' AND `type` =  '17';
		UPDATE `conditions` SET `comments` =  'NOT Player Has Learned Spell: 28209' WHERE `condition_entry` = '1346' AND `type` =  '17';
		UPDATE `conditions` SET `comments` =  'NOT Player Has Learned Spell: 28219' WHERE `condition_entry` = '1340' AND `type` =  '17';
		UPDATE `conditions` SET `comments` =  'NOT Player Has Learned Spell: 28220' WHERE `condition_entry` = '1341' AND `type` =  '17';
		UPDATE `conditions` SET `comments` =  'NOT Player Has Learned Spell: 28221' WHERE `condition_entry` = '1342' AND `type` =  '17';
		UPDATE `conditions` SET `comments` =  'NOT Player Has Learned Spell: 28222' WHERE `condition_entry` = '1337' AND `type` =  '17';
		UPDATE `conditions` SET `comments` =  'NOT Player Has Learned Spell: 28223' WHERE `condition_entry` = '1338' AND `type` =  '17';
		UPDATE `conditions` SET `comments` =  'NOT Player Has Learned Spell: 28224' WHERE `condition_entry` = '1339' AND `type` =  '17';
		UPDATE `conditions` SET `comments` =  'NOT Player Has Learned Spell: 28242' WHERE `condition_entry` = '1343' AND `type` =  '17';
		UPDATE `conditions` SET `comments` =  'NOT Player Has Learned Spell: 28243' WHERE `condition_entry` = '1344' AND `type` =  '17';
		UPDATE `conditions` SET `comments` =  'NOT Player Has Learned Spell: 28244' WHERE `condition_entry` = '1345' AND `type` =  '17';
		UPDATE `conditions` SET `comments` =  'Quest ID 770 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '284' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 4321 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '31' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 6681 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '180' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8619 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1057' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8635 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1052' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8636 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1045' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8642 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1058' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8643 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1061' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8644 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1059' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8645 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1049' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8646 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1070' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8647 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1076' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8648 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1043' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8649 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1054' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8650 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1046' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8651 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1041' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8652 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1040' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8653 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1056' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8654 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1031' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8670 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1044' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8671 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1073' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8672 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1038' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8673 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1055' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8674 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1071' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8675 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1078' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8676 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1068' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8677 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1039' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8678 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1035' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8679 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1060' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8680 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1036' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8681 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1032' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8682 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1062' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8683 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1069' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8684 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1067' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8685 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1050' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8686 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1033' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8688 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1047' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8713 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1075' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8714 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1042' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8715 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1072' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8716 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1077' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8717 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1034' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8718 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1029' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8719 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1066' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8720 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1030' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8721 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1065' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8722 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1048' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8723 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1037' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8724 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1051' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8725 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1064' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8726 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1063' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8727 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1074' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 8866 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1053' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Quest ID 9233 NOT Taken AND NOT Rewarded' WHERE `condition_entry` = '1364' AND `type` =  '22';
		UPDATE `conditions` SET `comments` =  'Player Has Less Than 1 of Item ID 7231 in Inventory/Bank' WHERE `condition_entry` = '319' AND `type` =  '24';
		UPDATE `conditions` SET `comments` =  'Player Has Less Than 1 of Item ID 7586 in Inventory/Bank' WHERE `condition_entry` = '1093' AND `type` =  '24';
		UPDATE `conditions` SET `comments` =  'Player Has Less Than 1 of Item ID 10515 in Inventory/Bank' WHERE `condition_entry` = '118' AND `type` =  '24';
		UPDATE `conditions` SET `comments` =  'Player Has Less Than 1 of Item ID 11227 in Inventory/Bank' WHERE `condition_entry` = '1096' AND `type` =  '24';
		UPDATE `conditions` SET `comments` =  'Player Has Less Than 1 of Item ID 11445 in Inventory/Bank' WHERE `condition_entry` = '119' AND `type` =  '24';
		UPDATE `conditions` SET `comments` =  'Player Has Less Than 1 of Item ID 11470 in Inventory/Bank' WHERE `condition_entry` = '254' AND `type` =  '24';
		UPDATE `conditions` SET `comments` =  'Player Has Less Than 1 of Item ID 11511 in Inventory/Bank' WHERE `condition_entry` = '120' AND `type` =  '24';
		UPDATE `conditions` SET `comments` =  'Player Has Less Than 1 of Item ID 12563 in Inventory/Bank' WHERE `condition_entry` = '1124' AND `type` =  '24';
		UPDATE `conditions` SET `comments` =  'Player Has Less Than 1 of Item ID 13370 in Inventory/Bank' WHERE `condition_entry` = '121' AND `type` =  '24';
		UPDATE `conditions` SET `comments` =  'Player Has Less Than 1 of Item ID 14639 in Inventory/Bank' WHERE `condition_entry` = '461' AND `type` =  '24';
		UPDATE `conditions` SET `comments` =  'Player Has Less Than 1 of Item ID 17333 in Inventory/Bank' WHERE `condition_entry` = '72' AND `type` =  '24';
		UPDATE `conditions` SET `comments` =  'Player Has Less Than 1 of Item ID 18643 in Inventory/Bank' WHERE `condition_entry` = '286' AND `type` =  '24';
		UPDATE `conditions` SET `comments` =  'Player Has Less Than 1 of Item ID 19016 in Inventory/Bank' WHERE `condition_entry` = '309' AND `type` =  '24';
		UPDATE `conditions` SET `comments` =  'Player Has Less Than 1 of Item ID 20949 in Inventory/Bank' WHERE `condition_entry` = '61' AND `type` =  '24';
		UPDATE `conditions` SET `comments` =  'Player Has Less Than 1 of Item ID 21106 in Inventory/Bank' WHERE `condition_entry` = '122' AND `type` =  '24';
		UPDATE `conditions` SET `comments` =  'Player Has Less Than 1 of Item ID 21107 in Inventory/Bank' WHERE `condition_entry` = '123' AND `type` =  '24';
		UPDATE `conditions` SET `comments` =  'Player Has Less Than 1 of Item ID 21109 in Inventory/Bank' WHERE `condition_entry` = '124' AND `type` =  '24';
		UPDATE `conditions` SET `comments` =  'Player Has Less Than 1 of Item ID 21158 in Inventory/Bank' WHERE `condition_entry` = '1102' AND `type` =  '24';
		UPDATE `conditions` SET `comments` =  'Player Has Less Than 1 of Item ID 21160 in Inventory/Bank' WHERE `condition_entry` = '359' AND `type` =  '24';
		UPDATE `conditions` SET `comments` =  'Player Has Less Than 1 of Item ID 21161 in Inventory/Bank' WHERE `condition_entry` = '1110' AND `type` =  '24';
		UPDATE `conditions` SET `comments` =  'Player Has Less Than 1 of Item ID 21393 in Inventory/Bank' WHERE `condition_entry` = '1122' AND `type` =  '24';
		UPDATE `conditions` SET `comments` =  'Player Has Less Than 1 of Item ID 21399 in Inventory/Bank' WHERE `condition_entry` = '1113' AND `type` =  '24';
		UPDATE `conditions` SET `comments` =  'Player Has Less Than 1 of Item ID 21402 in Inventory/Bank' WHERE `condition_entry` = '1119' AND `type` =  '24';
		UPDATE `conditions` SET `comments` =  'Player Has Less Than 1 of Item ID 21417 in Inventory/Bank' WHERE `condition_entry` = '1116' AND `type` =  '24';
		UPDATE `conditions` SET `comments` =  'Player Has Less Than 1 of Item ID 21711 in Inventory/Bank' WHERE `condition_entry` = '46' AND `type` =  '24';
		UPDATE `conditions` SET `comments` =  'Player Has Less Than 1 of Item ID 22719 in Inventory/Bank' WHERE `condition_entry` = '1363' AND `type` =  '24';
		UPDATE `conditions` SET `comments` =  'Player Has Less Than 1 of Item ID 22754 in Inventory/Bank' WHERE `condition_entry` = '75' AND `type` =  '24';
		UPDATE `conditions` SET `comments` =  'Holiday 141 Active' WHERE `condition_entry` = '32' AND `type` =  '26';
		UPDATE `conditions` SET `comments` =  'Holiday 324 Active' WHERE `condition_entry` = '108' AND `type` =  '26';
		UPDATE `conditions` SET `comments` =  'Skill level of Skill ID 202 Below level 1' WHERE `condition_entry` = '246' AND `type` =  '29';
		UPDATE `conditions` SET `comments` =  'Skill level of Skill ID 202 Below level 300' WHERE `condition_entry` = '247' AND `type` =  '29';
		UPDATE `conditions` SET `comments` =  'Has Maximum Rank Neutral With Faction ID: 349' WHERE `condition_entry` = '1002' AND `type` =  '30';
		UPDATE `conditions` SET `comments` =  'Has Maximum Rank Friendly With Faction ID: 349' WHERE `condition_entry` = '1005' AND `type` =  '30';
		UPDATE `conditions` SET `comments` =  'Has Maximum Rank Honored With Faction ID: 749' WHERE `condition_entry` = '69' AND `type` =  '30';
		UPDATE `conditions` SET `comments` =  'Source of Condition\'s Last Waypoint == 1' WHERE `condition_entry` = '389' AND `type` =  '33';
		UPDATE `conditions` SET `comments` =  'Source of Condition\'s Last Waypoint <= 2' WHERE `condition_entry` = '383' AND `type` =  '33';
		UPDATE `conditions` SET `comments` =  'Source of Condition\'s Last Waypoint == 7' WHERE `condition_entry` = '978' AND `type` =  '33';
		UPDATE `conditions` SET `comments` =  'Source of Condition\'s Last Waypoint == 8' WHERE `condition_entry` = '384' AND `type` =  '33';
		UPDATE `conditions` SET `comments` =  'Source of Condition\'s Last Waypoint >= 8' WHERE `condition_entry` = '385' AND `type` =  '33';
		UPDATE `conditions` SET `comments` =  'Source of Condition\'s Last Waypoint == 9' WHERE `condition_entry` = '720' AND `type` =  '33';
		UPDATE `conditions` SET `comments` =  'Source of Condition\'s Last Waypoint >= 10' WHERE `condition_entry` = '386' AND `type` =  '33';
		UPDATE `conditions` SET `comments` =  'Source of Condition\'s Last Waypoint == 19' WHERE `condition_entry` = '390' AND `type` =  '33';
		UPDATE `conditions` SET `comments` =  'Source of Condition\'s Last Waypoint == 32' WHERE `condition_entry` = '722' AND `type` =  '33';
		UPDATE `conditions` SET `comments` =  'Source of Condition\'s Last Waypoint == 38' WHERE `condition_entry` = '723' AND `type` =  '33';
		UPDATE `conditions` SET `comments` =  'Player is Dead OR NOT Within 60y of Source' WHERE `condition_entry` = '317' AND `type` =  '36';
		UPDATE `conditions` SET `comments` =  'Creature Source is Dead' WHERE `condition_entry` = '318' AND `type` =  '36';
		UPDATE `conditions` SET `comments` =  'Creature of Entry 7172 Found Alive Within 80y of Source' WHERE `condition_entry` = '89' AND `type` =  '37';

        -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
        -- -- PLACE UPDATE SQL ABOVE -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
        -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -

        -- If we get here ok, commit the changes
        IF bRollback = TRUE THEN
            ROLLBACK;
            SHOW ERRORS;
            SELECT '* UPDATE FAILED *' AS `===== Status =====`,@cCurResult AS `===== DB is on Version: =====`;
        ELSE
            COMMIT;
            -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
            -- UPDATE THE DB VERSION
            -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
            INSERT INTO `db_version` VALUES (@cNewVersion, @cNewStructure, @cNewContent, @cNewDescription, @cNewComment);
            SET @cNewResult := (SELECT `description` FROM `db_version` WHERE `version`=@cNewVersion AND `structure`=@cNewStructure AND `content`=@cNewContent);

            SELECT '* UPDATE COMPLETE *' AS `===== Status =====`,@cNewResult AS `===== DB is now on Version =====`;
        END IF;
    ELSE    -- Current version is not the expected version
        IF (@cCurResult = @cNewResult) THEN    -- Does the current version match the new version
            SELECT '* UPDATE SKIPPED *' AS `===== Status =====`,@cCurResult AS `===== DB is already on Version =====`;
        ELSE    -- Current version is not one related to this update
            IF(@cCurResult IS NULL) THEN    -- Something has gone wrong
                SELECT '* UPDATE FAILED *' AS `===== Status =====`,'Unable to locate DB Version Information' AS `============= Error Message =============`;
            ELSE
                IF(@cOldResult IS NULL) THEN    -- Something has gone wrong
                    SET @cCurVersion := (SELECT `version` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
                    SET @cCurStructure := (SELECT `STRUCTURE` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
                    SET @cCurContent := (SELECT `Content` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
                    SET @cCurOutput = CONCAT(@cCurVersion, '_', @cCurStructure, '_', @cCurContent, ' - ',@cCurResult);
                    SET @cOldResult = CONCAT('Rel',@cOldVersion, '_', @cOldStructure, '_', @cOldContent, ' - ','IS NOT APPLIED');
                    SELECT '* UPDATE SKIPPED *' AS `===== Status =====`,@cOldResult AS `=== Expected ===`,@cCurOutput AS `===== Found Version =====`;
                ELSE
                    SET @cCurVersion := (SELECT `version` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
                    SET @cCurStructure := (SELECT `STRUCTURE` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
                    SET @cCurContent := (SELECT `Content` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
                    SET @cCurOutput = CONCAT(@cCurVersion, '_', @cCurStructure, '_', @cCurContent, ' - ',@cCurResult);
                    SELECT '* UPDATE SKIPPED *' AS `===== Status =====`,@cOldResult AS `=== Expected ===`,@cCurOutput AS `===== Found Version =====`;
                END IF;
            END IF;
        END IF;
    END IF;
END $$

DELIMITER ;

-- Execute the procedure
CALL update_mangos();

-- Drop the procedure
DROP PROCEDURE IF EXISTS `update_mangos`;


