-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `locales_page_text` SET `text_loc5`='我想尖叫可是只有一聲低喘迸出我嘴邊。我很快就被這次的反叛行動給打敗。當我躺在地上，我可以看見馬帝斯在薩魯安的屍體前跺步。他看起來很擔心。他聲稱如果薩魯安被打死的話，賽羅娜斯、賽羅娜或類似這樣的實體會把他的肉體從骨頭上剝下。' WHERE `entry`=2939;

SET NAMES 'latin1';
