-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc5`='[PH] Alliance A1 Tower Banner BIG' WHERE `word_id` = 115930; -- locales_gameobject - name : entry=178927
UPDATE `trans_words` SET `content_loc5`='[PH] Alliance A2 Tower Banner BIG' WHERE `word_id` = 115931; -- locales_gameobject - name : entry=178932
UPDATE `trans_words` SET `content_loc5`='[PH] Alliance A3 Tower Banner BIG' WHERE `word_id` = 115934; -- locales_gameobject - name : entry=178947
UPDATE `trans_words` SET `content_loc5`='[PH] Alliance A4 Tower Banner BIG' WHERE `word_id` = 115935; -- locales_gameobject - name : entry=178948
UPDATE `trans_words` SET `content_loc5`='[PH] Alliance Graveyard Mid Banner BIG' WHERE `word_id` = 115945; -- locales_gameobject - name : entry=179044
UPDATE `trans_words` SET `content_loc5`='[PH] Alliance Graveyard Mid Pre-Banner BIG' WHERE `word_id` = 115955; -- locales_gameobject - name : entry=179424
UPDATE `trans_words` SET `content_loc5`='[PH] Alliance H1 Tower Pre-Banner BIG' WHERE `word_id` = 115963; -- locales_gameobject - name : entry=179446
UPDATE `trans_words` SET `content_loc5`='[PH] Alliance H2 Tower Pre-Banner BIG' WHERE `word_id` = 115964; -- locales_gameobject - name : entry=179450
UPDATE `trans_words` SET `content_loc5`='[PH] Alliance H3 Tower Pre-Banner BIG' WHERE `word_id` = 115965; -- locales_gameobject - name : entry=179454
UPDATE `trans_words` SET `content_loc5`='[PH] Alliance H4 Tower Pre-Banner BIG' WHERE `word_id` = 115966; -- locales_gameobject - name : entry=179458
UPDATE `trans_words` SET `content_loc5`='[PH] Horde A1 Tower Pre-Banner BIG' WHERE `word_id` = 115957; -- locales_gameobject - name : entry=179436
UPDATE `trans_words` SET `content_loc5`='[PH] Horde A2 Tower Pre-Banner BIG' WHERE `word_id` = 115960; -- locales_gameobject - name : entry=179440
UPDATE `trans_words` SET `content_loc5`='[PH] Horde A3 Tower Pre-Banner BIG' WHERE `word_id` = 115961; -- locales_gameobject - name : entry=179442
UPDATE `trans_words` SET `content_loc5`='[PH] Horde A4 Tower Pre-Banner BIG' WHERE `word_id` = 115962; -- locales_gameobject - name : entry=179444
UPDATE `trans_words` SET `content_loc5`='[PH] Horde H1 Tower Banner BIG' WHERE `word_id` = 115936; -- locales_gameobject - name : entry=178955
UPDATE `trans_words` SET `content_loc5`='[PH] Horde H2 Tower Banner BIG' WHERE `word_id` = 115937; -- locales_gameobject - name : entry=178956
UPDATE `trans_words` SET `content_loc5`='[PH] Horde H3 Tower Banner BIG' WHERE `word_id` = 115938; -- locales_gameobject - name : entry=178957
UPDATE `trans_words` SET `content_loc5`='[PH] Horde H4 Tower Banner BIG' WHERE `word_id` = 115939; -- locales_gameobject - name : entry=178958
UPDATE `trans_words` SET `content_loc5`='Ahn\'Qiraj Door 01' WHERE `word_id` = 116911; -- locales_gameobject - name : entry=210347
UPDATE `trans_words` SET `content_loc5`='Ahn\'Qiraj Gong' WHERE `word_id` = 115700; -- locales_gameobject - name : entry=177223
UPDATE `trans_words` SET `content_loc5`='Ahn\'Qiraj Ossirian Crystal' WHERE `word_id` = 116901; -- locales_gameobject - name : entry=210312
UPDATE `trans_words` SET `content_loc5`='Ahn\'Qiraj Sand Trap' WHERE `word_id` = 116905; -- locales_gameobject - name : entry=210339
UPDATE `trans_words` SET `content_loc5`='Altar of Hyjal' WHERE `word_id` = 116916; -- locales_gameobject - name : entry=211019
UPDATE `trans_words` SET `content_loc5`='Ani' WHERE `word_id` = 115088; -- locales_gameobject - name : entry=149420
UPDATE `trans_words` SET `content_loc5`='Arena Spoils' WHERE `word_id` = 116413; -- locales_gameobject - name : entry=181074
UPDATE `trans_words` SET `content_loc5`='Asheron\'s Tome of Summoning' WHERE `word_id` = 116915; -- locales_gameobject - name : entry=211018
UPDATE `trans_words` SET `content_loc5`='Bed' WHERE `word_id` = 115307; -- locales_gameobject - name : entry=174849
UPDATE `trans_words` SET `content_loc5`='Benedict\'s Chest' WHERE `word_id` = 114459; -- locales_gameobject - name : entry=3239
UPDATE `trans_words` SET `content_loc5`='BerryFizz Potions and Mixed Drinks' WHERE `word_id` = 114764; -- locales_gameobject - name : entry=34357
UPDATE `trans_words` SET `content_loc5`='BigDoorDummyCollision02' WHERE `word_id` = 115142; -- locales_gameobject - name : entry=161516
UPDATE `trans_words` SET `content_loc5`='Black Portal' WHERE `word_id` = 116919; -- locales_gameobject - name : entry=211023
UPDATE `trans_words` SET `content_loc5`='Blackwood Fruit Stores' WHERE `word_id` = 115360; -- locales_gameobject - name : entry=175330
UPDATE `trans_words` SET `content_loc5`='Blackwood Grain Stores' WHERE `word_id` = 115361; -- locales_gameobject - name : entry=175331
UPDATE `trans_words` SET `content_loc5`='Blackwood Nut Stores' WHERE `word_id` = 115359; -- locales_gameobject - name : entry=175329
UPDATE `trans_words` SET `content_loc5`='Blue Raptor Nest' WHERE `word_id` = 114517; -- locales_gameobject - name : entry=6907
UPDATE `trans_words` SET `content_loc5`='Boat to Menethil' WHERE `word_id` = 115591; -- locales_gameobject - name : entry=176364
UPDATE `trans_words` SET `content_loc5`='Boat to Teldrassil' WHERE `word_id` = 115592; -- locales_gameobject - name : entry=176365
UPDATE `trans_words` SET `content_loc5`='Boat to Theramore' WHERE `word_id` = 115593; -- locales_gameobject - name : entry=176369
UPDATE `trans_words` SET `content_loc5`='Booty Bay Alarm Bell' WHERE `word_id` = 115533; -- locales_gameobject - name : entry=175948
UPDATE `trans_words` SET `content_loc5`='Bowel with Boobles' WHERE `word_id` = 115556; -- locales_gameobject - name : entry=176157
UPDATE `trans_words` SET `content_loc5`='Brazier of Everfount' WHERE `word_id` = 114939; -- locales_gameobject - name : entry=113791
UPDATE `trans_words` SET `content_loc5`='Buzzbox 323' WHERE `word_id` = 114556; -- locales_gameobject - name : entry=17184
UPDATE `trans_words` SET `content_loc5`='Captain Sanders Chest' WHERE `word_id` = 114196; -- locales_gameobject - name : entry=38
UPDATE `trans_words` SET `content_loc5`='Captain\'s Chest' WHERE `word_id` = 268307; -- locales_gameobject - name : entry=142184
UPDATE `trans_words` SET `content_loc5`='Cat Figurine Trap' WHERE `word_id` = 117014; -- locales_gameobject - name : entry=12653
UPDATE `trans_words` SET `content_loc5`='CavernDoor01' WHERE `word_id` = 115664; -- locales_gameobject - name : entry=176996
UPDATE `trans_words` SET `content_loc5`='Circle of Imprisonment' WHERE `word_id` = 114630; -- locales_gameobject - name : entry=19901
UPDATE `trans_words` SET `content_loc5`='Command Tent' WHERE `word_id` = 115571; -- locales_gameobject - name : entry=176210
UPDATE `trans_words` SET `content_loc5`='Commander\'s Tent' WHERE `word_id` = 116918; -- locales_gameobject - name : entry=211022
UPDATE `trans_words` SET `content_loc5`='Communication Crystal' WHERE `word_id` = 116902; -- locales_gameobject - name : entry=210327
UPDATE `trans_words` SET `content_loc5`='Corpse Laden Boat' WHERE `word_id` = 114268; -- locales_gameobject - name : entry=1593
UPDATE `trans_words` SET `content_loc5`='Dangerous!' WHERE `word_id` = 114329; -- locales_gameobject - name : entry=2008
UPDATE `trans_words` SET `content_loc5`='Desk Chair' WHERE `word_id` = 114697; -- locales_gameobject - name : entry=22256
UPDATE `trans_words` SET `content_loc5`='Dining Bench' WHERE `word_id` = 114774; -- locales_gameobject - name : entry=36990
UPDATE `trans_words` SET `content_loc5`='Doodad_Ahn_Qiraj_DoorRoots01' WHERE `word_id` = 115552; -- locales_gameobject - name : entry=176147
UPDATE `trans_words` SET `content_loc5`='Doodad_Ahn_Qiraj_DoorRunes01' WHERE `word_id` = 115553; -- locales_gameobject - name : entry=176148
UPDATE `trans_words` SET `content_loc5`='Drizzlik\'s Emporium' WHERE `word_id` = 114487; -- locales_gameobject - name : entry=3767
UPDATE `trans_words` SET `content_loc5`='Egg-O-Matic' WHERE `word_id` = 114997; -- locales_gameobject - name : entry=142071
UPDATE `trans_words` SET `content_loc5`='Eliza\'s Tombstone' WHERE `word_id` = 114195; -- locales_gameobject - name : entry=37
UPDATE `trans_words` SET `content_loc5`='Elwynn Fence' WHERE `word_id` = 116925; -- locales_gameobject - name : entry=211062
UPDATE `trans_words` SET `content_loc5`='Excavation Tent Pavillion' WHERE `word_id` = 116900; -- locales_gameobject - name : entry=210286
UPDATE `trans_words` SET `content_loc5`='Eye of Asheron' WHERE `word_id` = 116917; -- locales_gameobject - name : entry=211021
UPDATE `trans_words` SET `content_loc5`='Farmountain Maps' WHERE `word_id` = 114725; -- locales_gameobject - name : entry=26492
UPDATE `trans_words` SET `content_loc5`='Fel Orc Encampment Custom Area' WHERE `word_id` = 116892; -- locales_gameobject - name : entry=200000
UPDATE `trans_words` SET `content_loc5`='Fire on ground' WHERE `word_id` = 114820; -- locales_gameobject - name : entry=56809
UPDATE `trans_words` SET `content_loc5`='Fire With Boiling Water' WHERE `word_id` = 114910; -- locales_gameobject - name : entry=103773
UPDATE `trans_words` SET `content_loc5`='Flickering Campfire' WHERE `word_id` = 114657; -- locales_gameobject - name : entry=20881
UPDATE `trans_words` SET `content_loc5`='Flinthammer\'s Armorer and Clothier' WHERE `word_id` = 114741; -- locales_gameobject - name : entry=143332
UPDATE `trans_words` SET `content_loc5`='Floating Purple Crystal Broken 01' WHERE `word_id` = 116912; -- locales_gameobject - name : entry=210348
UPDATE `trans_words` SET `content_loc5`='Floating Red Crystal Broken 01' WHERE `word_id` = 116910; -- locales_gameobject - name : entry=210346
UPDATE `trans_words` SET `content_loc5`='Floating Red Crystal Broken 03' WHERE `word_id` = 116909; -- locales_gameobject - name : entry=210345
UPDATE `trans_words` SET `content_loc5`='Fragile - Do Not Drop' WHERE `word_id` = 114488; -- locales_gameobject - name : entry=3768
UPDATE `trans_words` SET `content_loc5`='Gadgetzan Auction' WHERE `word_id` = 115524; -- locales_gameobject - name : entry=175904
UPDATE `trans_words` SET `content_loc5`='Gastric Exit' WHERE `word_id` = 116913; -- locales_gameobject - name : entry=210349
UPDATE `trans_words` SET `content_loc5`='Gates of Zul\'Gurub' WHERE `word_id` = 116128; -- locales_gameobject - name : entry=180323
UPDATE `trans_words` SET `content_loc5`='Giant Sea Turtle' WHERE `word_id` = 114653; -- locales_gameobject - name : entry=20820
UPDATE `trans_words` SET `content_loc5`='Giant Turtle' WHERE `word_id` = 114654; -- locales_gameobject - name : entry=20821
UPDATE `trans_words` SET `content_loc5`='Glyphed Crystal' WHERE `word_id` = 116904; -- locales_gameobject - name : entry=210337
UPDATE `trans_words` SET `content_loc5`='Gnomes' WHERE `word_id` = 114760; -- locales_gameobject - name : entry=32419
UPDATE `trans_words` SET `content_loc5`='Goblin Shredder Suit' WHERE `word_id` = 114603; -- locales_gameobject - name : entry=19582
UPDATE `trans_words` SET `content_loc5`='Gong of Bethekk' WHERE `word_id` = 116216; -- locales_gameobject - name : entry=180526
UPDATE `trans_words` SET `content_loc5`='Gordunni Cobalt Visual (DND)' WHERE `word_id` = 115758; -- locales_gameobject - name : entry=177683
UPDATE `trans_words` SET `content_loc5`='Grand Widow Faerlina Door' WHERE `word_id` = 116442; -- locales_gameobject - name : entry=181167
UPDATE `trans_words` SET `content_loc5`='Grave' WHERE `word_id` = 116927; -- locales_gameobject - name : entry=211065
UPDATE `trans_words` SET `content_loc5`='Graveyard Banner' WHERE `word_id` = 114539; -- locales_gameobject - name : entry=13756
UPDATE `trans_words` SET `content_loc5`='Guard Tower' WHERE `word_id` = 114649; -- locales_gameobject - name : entry=20816
UPDATE `trans_words` SET `content_loc5`='HDressing, Christmas Standing Medium Exterior' WHERE `word_id` = 116871; -- locales_gameobject - name : entry=187235
UPDATE `trans_words` SET `content_loc5`='Hive Fireflies 01' WHERE `word_id` = 116906; -- locales_gameobject - name : entry=210341
UPDATE `trans_words` SET `content_loc5`='Hoofprints' WHERE `word_id` = 114667; -- locales_gameobject - name : entry=21015
UPDATE `trans_words` SET `content_loc5`='Industrial District' WHERE `word_id` = 114713; -- locales_gameobject - name : entry=25334
UPDATE `trans_words` SET `content_loc5`='IronForge Elevator' WHERE `word_id` = 114740; -- locales_gameobject - name : entry=32056
UPDATE `trans_words` SET `content_loc5`='Kaldorei Tome of Summoning' WHERE `word_id` = 115100; -- locales_gameobject - name : entry=151286
UPDATE `trans_words` SET `content_loc5`='Kre\'tal\'s Wagon' WHERE `word_id` = 116914; -- locales_gameobject - name : entry=211017
UPDATE `trans_words` SET `content_loc5`='L70ETC Music Doodad' WHERE `word_id` = 116846; -- locales_gameobject - name : entry=186312
UPDATE `trans_words` SET `content_loc5`='Lair Exit' WHERE `word_id` = 116921; -- locales_gameobject - name : entry=211035
UPDATE `trans_words` SET `content_loc5`='Large x2 Fire' WHERE `word_id` = 116720; -- locales_gameobject - name : entry=184563
UPDATE `trans_words` SET `content_loc5`='Loatheb Fight Door 01 (not used)' WHERE `word_id` = 116477; -- locales_gameobject - name : entry=181240
UPDATE `trans_words` SET `content_loc5`='Loatheb Fight Door 02 (not used)' WHERE `word_id` = 116479; -- locales_gameobject - name : entry=181242
UPDATE `trans_words` SET `content_loc5`='Loatheb Fight Door 03 (not used)' WHERE `word_id` = 116480; -- locales_gameobject - name : entry=181243
UPDATE `trans_words` SET `content_loc5`='Locked Cage' WHERE `word_id` = 115510; -- locales_gameobject - name : entry=175786
UPDATE `trans_words` SET `content_loc5`='Logs on fire' WHERE `word_id` = 116717; -- locales_gameobject - name : entry=184507
UPDATE `trans_words` SET `content_loc5`='Longtoo - Teapee' WHERE `word_id` = 114461; -- locales_gameobject - name : entry=3265
UPDATE `trans_words` SET `content_loc5`='lowerLdoor' WHERE `word_id` = 114638; -- locales_gameobject - name : entry=20651
UPDATE `trans_words` SET `content_loc5`='Mage Quarters' WHERE `word_id` = 114373; -- locales_gameobject - name : entry=2188
UPDATE `trans_words` SET `content_loc5`='Magus Rimtori\'s Journal' WHERE `word_id` = 115110; -- locales_gameobject - name : entry=152098
UPDATE `trans_words` SET `content_loc5`='Market Walk' WHERE `word_id` = 114753; -- locales_gameobject - name : entry=32364
UPDATE `trans_words` SET `content_loc5`='Meetingstone01' WHERE `word_id` = 115997; -- locales_gameobject - name : entry=179597
UPDATE `trans_words` SET `content_loc5`='Mephistroph\'s HellFire' WHERE `word_id` = 116929; -- locales_gameobject - name : entry=211084
UPDATE `trans_words` SET `content_loc5`='Moon Well 2' WHERE `word_id` = 114652; -- locales_gameobject - name : entry=20819
UPDATE `trans_words` SET `content_loc5`='Mound of loose dirt' WHERE `word_id` = 114200; -- locales_gameobject - name : entry=59
UPDATE `trans_words` SET `content_loc5`='Mysterious Monument' WHERE `word_id` = 116924; -- locales_gameobject - name : entry=211053
UPDATE `trans_words` SET `content_loc5`='Mysterious Wailing Caverns Chest' WHERE `word_id` = 116598; -- locales_gameobject - name : entry=180055
UPDATE `trans_words` SET `content_loc5`='New Year Alliance Hanging Banner 02' WHERE `word_id` = 116895; -- locales_gameobject - name : entry=210211
UPDATE `trans_words` SET `content_loc5`='New Year Alliance Hanging Banner' WHERE `word_id` = 116894; -- locales_gameobject - name : entry=210210
UPDATE `trans_words` SET `content_loc5`='New Year Alliance Standing Banner' WHERE `word_id` = 116898; -- locales_gameobject - name : entry=210214
UPDATE `trans_words` SET `content_loc5`='New Year Horde Hanging Banner 02' WHERE `word_id` = 116897; -- locales_gameobject - name : entry=210213
UPDATE `trans_words` SET `content_loc5`='New Year Horde Hanging Banner' WHERE `word_id` = 116896; -- locales_gameobject - name : entry=210212
UPDATE `trans_words` SET `content_loc5`='New Year Horde Standing Banner' WHERE `word_id` = 116899; -- locales_gameobject - name : entry=210215
UPDATE `trans_words` SET `content_loc5`='Night Elf Moon Well' WHERE `word_id` = 114651; -- locales_gameobject - name : entry=20818
UPDATE `trans_words` SET `content_loc5`='Orc Tower' WHERE `word_id` = 114648; -- locales_gameobject - name : entry=20812
UPDATE `trans_words` SET `content_loc5`='OUT OF ORDER! Use Postman instead - your GM\'s' WHERE `word_id` = 116053; -- locales_gameobject - name : entry=179963
UPDATE `trans_words` SET `content_loc5`='Pillar of Amethyst' WHERE `word_id` = 114427; -- locales_gameobject - name : entry=2858
UPDATE `trans_words` SET `content_loc5`='Pillar of Diamond' WHERE `word_id` = 114423; -- locales_gameobject - name : entry=2842
UPDATE `trans_words` SET `content_loc5`='Pillar of Opal' WHERE `word_id` = 114425; -- locales_gameobject - name : entry=2848
UPDATE `trans_words` SET `content_loc5`='Pithwick\'s Bags and Supplies' WHERE `word_id` = 114724; -- locales_gameobject - name : entry=26491
UPDATE `trans_words` SET `content_loc5`='Player Housing' WHERE `word_id` = 114656; -- locales_gameobject - name : entry=20823
UPDATE `trans_words` SET `content_loc5`='Postbox' WHERE `word_id` = 115449; -- locales_gameobject - name : entry=175668
UPDATE `trans_words` SET `content_loc5`='Pull rope Bell' WHERE `word_id` = 115726; -- locales_gameobject - name : entry=177271
UPDATE `trans_words` SET `content_loc5`='Rail' WHERE `word_id` = 114872; -- locales_gameobject - name : entry=80024
UPDATE `trans_words` SET `content_loc5`='Red Raptor Nest' WHERE `word_id` = 114516; -- locales_gameobject - name : entry=6906
UPDATE `trans_words` SET `content_loc5`='Rin\'ji\'s Cage' WHERE `word_id` = 114996; -- locales_gameobject - name : entry=142036
UPDATE `trans_words` SET `content_loc5`='Rockwall Fence' WHERE `word_id` = 116926; -- locales_gameobject - name : entry=211064
UPDATE `trans_words` SET `content_loc5`='Rune of Beth\'Amara' WHERE `word_id` = 115093; -- locales_gameobject - name : entry=149481
UPDATE `trans_words` SET `content_loc5`='Rune of Jin\'yael' WHERE `word_id` = 115092; -- locales_gameobject - name : entry=149480
UPDATE `trans_words` SET `content_loc5`='Rune of Markri' WHERE `word_id` = 115094; -- locales_gameobject - name : entry=149482
UPDATE `trans_words` SET `content_loc5`='Rune of Sael\'hai' WHERE `word_id` = 115095; -- locales_gameobject - name : entry=149483
UPDATE `trans_words` SET `content_loc5`='Sand Worm Rock Base' WHERE `word_id` = 116907; -- locales_gameobject - name : entry=210343
UPDATE `trans_words` SET `content_loc5`='Sarcophag' WHERE `word_id` = 116928; -- locales_gameobject - name : entry=211067
UPDATE `trans_words` SET `content_loc5`='Seal of the Earth' WHERE `word_id` = 114443; -- locales_gameobject - name : entry=2933
UPDATE `trans_words` SET `content_loc5`='Shopping Centre' WHERE `word_id` = 116893; -- locales_gameobject - name : entry=200001
UPDATE `trans_words` SET `content_loc5`='Silithus Crystal Formation 03' WHERE `word_id` = 116908; -- locales_gameobject - name : entry=210344
UPDATE `trans_words` SET `content_loc5`='SmallBrazier01' WHERE `word_id` = 116034; -- locales_gameobject - name : entry=179878
UPDATE `trans_words` SET `content_loc5`='SmallBrazier03' WHERE `word_id` = 116032; -- locales_gameobject - name : entry=179876
UPDATE `trans_words` SET `content_loc5`='SmallBrazier04' WHERE `word_id` = 116033; -- locales_gameobject - name : entry=179877
UPDATE `trans_words` SET `content_loc5`='SmallBrazier19' WHERE `word_id` = 116031; -- locales_gameobject - name : entry=179875
UPDATE `trans_words` SET `content_loc5`='SmallBrazier31' WHERE `word_id` = 116030; -- locales_gameobject - name : entry=179874
UPDATE `trans_words` SET `content_loc5`='Smoldering Coals' WHERE `word_id` = 114984; -- locales_gameobject - name : entry=140358
UPDATE `trans_words` SET `content_loc5`='Smoldering Fire' WHERE `word_id` = 114328; -- locales_gameobject - name : entry=2004
UPDATE `trans_words` SET `content_loc5`='Stand up Torch' WHERE `word_id` = 114559; -- locales_gameobject - name : entry=18047
UPDATE `trans_words` SET `content_loc5`='Stanley\'s Dish' WHERE `word_id` = 114297; -- locales_gameobject - name : entry=1720
UPDATE `trans_words` SET `content_loc5`='Stolen Books' WHERE `word_id` = 114873; -- locales_gameobject - name : entry=83763
UPDATE `trans_words` SET `content_loc5`='Stone Chair' WHERE `word_id` = 115033; -- locales_gameobject - name : entry=142947
UPDATE `trans_words` SET `content_loc5`='Stonebranch Herbalist' WHERE `word_id` = 114726; -- locales_gameobject - name : entry=26493
UPDATE `trans_words` SET `content_loc5`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176004
UPDATE `trans_words` SET `content_loc5`='Target' WHERE `word_id` = 114541; -- locales_gameobject - name : entry=13952
UPDATE `trans_words` SET `content_loc5`='Teleport-Stone to Hyjal' WHERE `word_id` = 116922; -- locales_gameobject - name : entry=211050
UPDATE `trans_words` SET `content_loc5`='TEST Circle of Flame' WHERE `word_id` = 114470; -- locales_gameobject - name : entry=3523
UPDATE `trans_words` SET `content_loc5`='Test Rift' WHERE `word_id` = 116815; -- locales_gameobject - name : entry=185595
UPDATE `trans_words` SET `content_loc5`='Test' WHERE `word_id` = 49952; -- locales_gameobject - name : entry=2558
UPDATE `trans_words` SET `content_loc5`='Thane\'s Boots and Shoulderpads' WHERE `word_id` = 114355; -- locales_gameobject - name : entry=2151
UPDATE `trans_words` SET `content_loc5`='The Cheese Cutters' WHERE `word_id` = 114352; -- locales_gameobject - name : entry=2148
UPDATE `trans_words` SET `content_loc5`='The Commerce Ward' WHERE `word_id` = 114750; -- locales_gameobject - name : entry=32357
UPDATE `trans_words` SET `content_loc5`='The Fall of Ameth\'Aran' WHERE `word_id` = 24269; -- locales_gameobject - name : entry=17189
UPDATE `trans_words` SET `content_loc5`='The Forlorn Caverns' WHERE `word_id` = 114756; -- locales_gameobject - name : entry=32381
UPDATE `trans_words` SET `content_loc5`='The Lay of Ameth\'Aran' WHERE `word_id` = 24268; -- locales_gameobject - name : entry=17188
UPDATE `trans_words` SET `content_loc5`='The Punisher (DND)' WHERE `word_id` = 114952; -- locales_gameobject - name : entry=123334
UPDATE `trans_words` SET `content_loc5`='The Seven Deadly Venoms' WHERE `word_id` = 114353; -- locales_gameobject - name : entry=2149
UPDATE `trans_words` SET `content_loc5`='The Wine Cask' WHERE `word_id` = 114347; -- locales_gameobject - name : entry=2130
UPDATE `trans_words` SET `content_loc5`='Thundershot Guns \'n Ammo' WHERE `word_id` = 114718; -- locales_gameobject - name : entry=26485
UPDATE `trans_words` SET `content_loc5`='Tree Stump' WHERE `word_id` = 116923; -- locales_gameobject - name : entry=211052
UPDATE `trans_words` SET `content_loc5`='Twilight Tablet' WHERE `word_id` = 116903; -- locales_gameobject - name : entry=210335
UPDATE `trans_words` SET `content_loc5`='unk' WHERE `word_id` = 114688; -- locales_gameobject - name : entry=21653
UPDATE `trans_words` SET `content_loc5`='upperLdoor' WHERE `word_id` = 114637; -- locales_gameobject - name : entry=20650
UPDATE `trans_words` SET `content_loc5`='Vator2' WHERE `word_id` = 114874; -- locales_gameobject - name : entry=85556
UPDATE `trans_words` SET `content_loc5`='Vault Door' WHERE `word_id` = 115704; -- locales_gameobject - name : entry=177237
UPDATE `trans_words` SET `content_loc5`='WANTED: Chok\'sul' WHERE `word_id` = 114225; -- locales_gameobject - name : entry=254
UPDATE `trans_words` SET `content_loc5`='WANTED: Murkdeep!' WHERE `word_id` = 115358; -- locales_gameobject - name : entry=175320
UPDATE `trans_words` SET `content_loc5`='Wickerman Guardian Ember' WHERE `word_id` = 117017; -- locales_gameobject - name : entry=180574
UPDATE `trans_words` SET `content_loc5`='Wooden Board' WHERE `word_id` = 116718; -- locales_gameobject - name : entry=184515
UPDATE `trans_words` SET `content_loc5`='Yellow Raptor Nest' WHERE `word_id` = 114518; -- locales_gameobject - name : entry=6908
UPDATE `trans_words` SET `content_loc5`='Zeppelin Landing Tower' WHERE `word_id` = 115195; -- locales_gameobject - name : entry=165557

SET NAMES 'latin1';
