-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc5`='A reagent for mage spells.' WHERE `word_id` = 12315; -- locales_item - description : entry=5517
UPDATE `trans_words` SET `content_loc5`='Alex\'s Ring of Audacity' WHERE `word_id` = 16991; -- locales_item - name : entry=12947
UPDATE `trans_words` SET `content_loc5`='Alex\'s Test Beatdown Staff' WHERE `word_id` = 21820; -- locales_item - name : entry=19879
UPDATE `trans_words` SET `content_loc5`='Codex of Flash Heal' WHERE `word_id` = 14418; -- locales_item - name : entry=8964
UPDATE `trans_words` SET `content_loc5`='Counts as an Air, Earth, Fire, and Water totem.' WHERE `word_id` = 23479; -- locales_item - description : entry=22345
UPDATE `trans_words` SET `content_loc5`='Diet McWeaksauce' WHERE `word_id` = 24081; -- locales_item - name : entry=23578
UPDATE `trans_words` SET `content_loc5`='Engraved with the words \'For years of service: -EVC.\'' WHERE `word_id` = 9700; -- locales_item - description : entry=2239
UPDATE `trans_words` SET `content_loc5`='Explosive Shell' WHERE `word_id` = 11998; -- locales_item - name : entry=5105
UPDATE `trans_words` SET `content_loc5`='Food for the Mind' WHERE `word_id` = 24082; -- locales_item - description : entry=23578
UPDATE `trans_words` SET `content_loc5`='Glaive of the Defender' WHERE `word_id` = 23918; -- locales_item - name : entry=23051
UPDATE `trans_words` SET `content_loc5`='Glyphic Rune' WHERE `word_id` = 14757; -- locales_item - name : entry=9572
UPDATE `trans_words` SET `content_loc5`='Gor\'tesh\'s severed head, propped up on a pike.' WHERE `word_id` = 15848; -- locales_item - description : entry=11079
UPDATE `trans_words` SET `content_loc5`='Gordok Inner Door Key' WHERE `word_id` = 20591; -- locales_item - name : entry=18268
UPDATE `trans_words` SET `content_loc5`='James\' Key' WHERE `word_id` = 20248; -- locales_item - name : entry=17262
UPDATE `trans_words` SET `content_loc5`='Key to Salem\'s Chest' WHERE `word_id` = 20246; -- locales_item - name : entry=17242
UPDATE `trans_words` SET `content_loc5`='Lok\'delar, Stave of the Ancient Keepers DEP' WHERE `word_id` = 22194; -- locales_item - name : entry=20487
UPDATE `trans_words` SET `content_loc5`='Looks great. Less filling.' WHERE `word_id` = 16992; -- locales_item - description : entry=12947
UPDATE `trans_words` SET `content_loc5`='Master Key to the Depths, Courtesy of F.F.F.' WHERE `word_id` = 15831; -- locales_item - description : entry=11000
UPDATE `trans_words` SET `content_loc5`='Only ONE May Rise... (and consequently, only ONE may loot this head)' WHERE `word_id` = 22115; -- locales_item - description : entry=20383
UPDATE `trans_words` SET `content_loc5`='Opens Dark Cleric Salem\'s Chest' WHERE `word_id` = 20247; -- locales_item - description : entry=17242
UPDATE `trans_words` SET `content_loc5`='Opens the stolen chest from the Cathedral of Light' WHERE `word_id` = 20249; -- locales_item - description : entry=17262
UPDATE `trans_words` SET `content_loc5`='Reins of the Spotted Nightsaber' WHERE `word_id` = 14355; -- locales_item - name : entry=8628
UPDATE `trans_words` SET `content_loc5`='Rhok\'delar, Longbow of the Ancient Keepers DEP' WHERE `word_id` = 22195; -- locales_item - name : entry=20488
UPDATE `trans_words` SET `content_loc5`='Ring of Critical Testing 2' WHERE `word_id` = 21161; -- locales_item - name : entry=18970
UPDATE `trans_words` SET `content_loc5`='Shadowforge Key' WHERE `word_id` = 15830; -- locales_item - name : entry=11000
UPDATE `trans_words` SET `content_loc5`='Skeleton Key' WHERE `word_id` = 17505; -- locales_item - name : entry=13704
UPDATE `trans_words` SET `content_loc5`='Talisman of Binding Shard' WHERE `word_id` = 20467; -- locales_item - name : entry=17782
UPDATE `trans_words` SET `content_loc5`='Teaches Inner Fire (Rank 2).' WHERE `word_id` = 14419; -- locales_item - description : entry=8964
UPDATE `trans_words` SET `content_loc5`='Teaches you how to make Thorium Shells.' WHERE `word_id` = 19461; -- locales_item - description : entry=16051
UPDATE `trans_words` SET `content_loc5`='Test Arcane Res Legs Mail' WHERE `word_id` = 19488; -- locales_item - name : entry=16165
UPDATE `trans_words` SET `content_loc5`='Test Stationery' WHERE `word_id` = 14090; -- locales_item - name : entry=8164
UPDATE `trans_words` SET `content_loc5`='The completed amulet of Rakh\'likh.' WHERE `word_id` = 15727; -- locales_item - description : entry=10757
UPDATE `trans_words` SET `content_loc5`='The McWeaksauce Classic' WHERE `word_id` = 24083; -- locales_item - name : entry=23579
UPDATE `trans_words` SET `content_loc5`='The Original.' WHERE `word_id` = 24084; -- locales_item - description : entry=23579
UPDATE `trans_words` SET `content_loc5`='This blade is dimensional. It appears to be fading from this plane of existence.' WHERE `word_id` = 23739; -- locales_item - description : entry=22736
UPDATE `trans_words` SET `content_loc5`='Viewing Room Key' WHERE `word_id` = 17548; -- locales_item - name : entry=13873
UPDATE `trans_words` SET `content_loc5`='Warsong Mark of Honor' WHERE `word_id` = 21461; -- locales_item - name : entry=19322
UPDATE `trans_words` SET `content_loc5`='Weapon of Mass Destruction (test)' WHERE `word_id` = 12211; -- locales_item - name : entry=5418
UPDATE `trans_words` SET `content_loc5`='Weapon of Massive Destruction (test)' WHERE `word_id` = 12210; -- locales_item - name : entry=5417
UPDATE `trans_words` SET `content_loc5`='Work Shirt' WHERE `word_id` = 10340; -- locales_item - name : entry=3148

SET NAMES 'latin1';
