-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc2`='Acolyte Dellis' WHERE `word_id` = 76609; -- locales_creature - name : entry=5386
UPDATE `trans_words` SET `content_loc2`='Acolyte Fenrick' WHERE `word_id` = 77246; -- locales_creature - name : entry=6253
UPDATE `trans_words` SET `content_loc2`='Acolyte Magaz' WHERE `word_id` = 77245; -- locales_creature - name : entry=6252
UPDATE `trans_words` SET `content_loc2`='Acolyte Porena' WHERE `word_id` = 77249; -- locales_creature - name : entry=6267
UPDATE `trans_words` SET `content_loc2`='Acolyte Wytula' WHERE `word_id` = 77247; -- locales_creature - name : entry=6254
UPDATE `trans_words` SET `content_loc2`='Agent Kearnen' WHERE `word_id` = 77491; -- locales_creature - name : entry=7024
UPDATE `trans_words` SET `content_loc2`='Baron Aquanis' WHERE `word_id` = 80052; -- locales_creature - name : entry=12876
UPDATE `trans_words` SET `content_loc2`='Baron Charr' WHERE `word_id` = 80547; -- locales_creature - name : entry=14461
UPDATE `trans_words` SET `content_loc2`='Baron Geddon' WHERE `word_id` = 79773; -- locales_creature - name : entry=12056
UPDATE `trans_words` SET `content_loc2`='Baron Kazum' WHERE `word_id` = 80967; -- locales_creature - name : entry=15205
UPDATE `trans_words` SET `content_loc2`='Baron Revilgaz' WHERE `word_id` = 74238; -- locales_creature - name : entry=2496
UPDATE `trans_words` SET `content_loc2`='Baron Vardus' WHERE `word_id` = 74060; -- locales_creature - name : entry=2306
UPDATE `trans_words` SET `content_loc2`='Cavalier Durgen' WHERE `word_id` = 79489; -- locales_creature - name : entry=11611
UPDATE `trans_words` SET `content_loc2`='Crocilisk Trainer' WHERE `word_id` = 74578; -- locales_creature - subname : entry=2876
UPDATE `trans_words` SET `content_loc2`='Enraged Form' WHERE `word_id` = 74198; -- locales_creature - subname : entry=2454
UPDATE `trans_words` SET `content_loc2`='Gazelle' WHERE `word_id` = 75742; -- locales_creature - name : entry=4166
UPDATE `trans_words` SET `content_loc2`='General Colbatann' WHERE `word_id` = 78787; -- locales_creature - name : entry=10196
UPDATE `trans_words` SET `content_loc2`='General Drakkisath' WHERE `word_id` = 78846; -- locales_creature - name : entry=10363
UPDATE `trans_words` SET `content_loc2`='General Kirika' WHERE `word_id` = 81841; -- locales_creature - name : entry=17079
UPDATE `trans_words` SET `content_loc2`='General Marcus Jonathan' WHERE `word_id` = 72551; -- locales_creature - name : entry=466
UPDATE `trans_words` SET `content_loc2`='General Rajaxx' WHERE `word_id` = 81046; -- locales_creature - name : entry=15341
UPDATE `trans_words` SET `content_loc2`='General Zog' WHERE `word_id` = 81199; -- locales_creature - name : entry=15539
UPDATE `trans_words` SET `content_loc2`='Gest' WHERE `word_id` = 75008; -- locales_creature - name : entry=3327
UPDATE `trans_words` SET `content_loc2`='Ghost Visual' WHERE `word_id` = 80045; -- locales_creature - subname : entry=12861
UPDATE `trans_words` SET `content_loc2`='Ghost/Ghoul spawner' WHERE `word_id` = 81712; -- locales_creature - subname : entry=16306
UPDATE `trans_words` SET `content_loc2`='Ghost/Skeleton spawner' WHERE `word_id` = 81713; -- locales_creature - subname : entry=16336
UPDATE `trans_words` SET `content_loc2`='Ghoul/Skeleton spawner' WHERE `word_id` = 81714; -- locales_creature - subname : entry=16338
UPDATE `trans_words` SET `content_loc2`='Glacier' WHERE `word_id` = 78996; -- locales_creature - name : entry=10619
UPDATE `trans_words` SET `content_loc2`='Grunt Bek\'rah' WHERE `word_id` = 80027; -- locales_creature - name : entry=12798
UPDATE `trans_words` SET `content_loc2`='Grunt Dogran' WHERE `word_id` = 77009; -- locales_creature - name : entry=5908
UPDATE `trans_words` SET `content_loc2`='Grunt Gargal' WHERE `word_id` = 78459; -- locales_creature - name : entry=9086
UPDATE `trans_words` SET `content_loc2`='Grunt Komak' WHERE `word_id` = 76734; -- locales_creature - name : entry=5597
UPDATE `trans_words` SET `content_loc2`='Grunt Kor\'ja' WHERE `word_id` = 79933; -- locales_creature - name : entry=12430
UPDATE `trans_words` SET `content_loc2`='Grunt Korf' WHERE `word_id` = 80026; -- locales_creature - name : entry=12797
UPDATE `trans_words` SET `content_loc2`='Grunt Logmar' WHERE `word_id` = 77012; -- locales_creature - name : entry=5911
UPDATE `trans_words` SET `content_loc2`='Grunt Maug' WHERE `word_id` = 81139; -- locales_creature - name : entry=15460
UPDATE `trans_words` SET `content_loc2`='Grunt Mojka' WHERE `word_id` = 76740; -- locales_creature - name : entry=5603
UPDATE `trans_words` SET `content_loc2`='Grunt Tharlak' WHERE `word_id` = 76721; -- locales_creature - name : entry=5547
UPDATE `trans_words` SET `content_loc2`='Grunt Zuul' WHERE `word_id` = 76720; -- locales_creature - name : entry=5546
UPDATE `trans_words` SET `content_loc2`='Infernal' WHERE `word_id` = 72332; -- locales_creature - name : entry=89
UPDATE `trans_words` SET `content_loc2`='Lieutenant Beitha' WHERE `word_id` = 81785; -- locales_creature - name : entry=16495
UPDATE `trans_words` SET `content_loc2`='Lieutenant Benedict' WHERE `word_id` = 74882; -- locales_creature - name : entry=3192
UPDATE `trans_words` SET `content_loc2`='Lieutenant Caldwell' WHERE `word_id` = 76385; -- locales_creature - name : entry=5046
UPDATE `trans_words` SET `content_loc2`='Lieutenant Dagel' WHERE `word_id` = 81783; -- locales_creature - name : entry=16493
UPDATE `trans_words` SET `content_loc2`='Lieutenant Doren' WHERE `word_id` = 72555; -- locales_creature - name : entry=469
UPDATE `trans_words` SET `content_loc2`='Lieutenant Farren Orinelle' WHERE `word_id` = 74001; -- locales_creature - name : entry=2228
UPDATE `trans_words` SET `content_loc2`='Lieutenant Grummus' WHERE `word_id` = 80135; -- locales_creature - name : entry=13145
UPDATE `trans_words` SET `content_loc2`='Lieutenant Haggerdin' WHERE `word_id` = 80339; -- locales_creature - name : entry=13841
UPDATE `trans_words` SET `content_loc2`='Lieutenant Jocryn Heldric' WHERE `word_id` = 81548; -- locales_creature - name : entry=16005
UPDATE `trans_words` SET `content_loc2`='Lieutenant Karter' WHERE `word_id` = 80010; -- locales_creature - name : entry=12783
UPDATE `trans_words` SET `content_loc2`='Lieutenant Largent' WHERE `word_id` = 80179; -- locales_creature - name : entry=13296
UPDATE `trans_words` SET `content_loc2`='Lieutenant Lewis' WHERE `word_id` = 80137; -- locales_creature - name : entry=13147
UPDATE `trans_words` SET `content_loc2`='Lieutenant Lisande' WHERE `word_id` = 81782; -- locales_creature - name : entry=16490
UPDATE `trans_words` SET `content_loc2`='Lieutenant Lonadin' WHERE `word_id` = 80182; -- locales_creature - name : entry=13299
UPDATE `trans_words` SET `content_loc2`='Lieutenant Mancuso' WHERE `word_id` = 80183; -- locales_creature - name : entry=13300
UPDATE `trans_words` SET `content_loc2`='Lieutenant Murp' WHERE `word_id` = 80136; -- locales_creature - name : entry=13146
UPDATE `trans_words` SET `content_loc2`='Lieutenant Nevell' WHERE `word_id` = 81780; -- locales_creature - name : entry=16484
UPDATE `trans_words` SET `content_loc2`='Lieutenant Orrin' WHERE `word_id` = 81778; -- locales_creature - name : entry=16478
UPDATE `trans_words` SET `content_loc2`='Lieutenant Rachel Vaccar' WHERE `word_id` = 80002; -- locales_creature - name : entry=12778
UPDATE `trans_words` SET `content_loc2`='Lieutenant Rotimer' WHERE `word_id` = 80341; -- locales_creature - name : entry=13843
UPDATE `trans_words` SET `content_loc2`='Lieutenant Rugba' WHERE `word_id` = 80127; -- locales_creature - name : entry=13137
UPDATE `trans_words` SET `content_loc2`='Lieutenant Rukag' WHERE `word_id` = 81784; -- locales_creature - name : entry=16494
UPDATE `trans_words` SET `content_loc2`='Lieutenant Sanders' WHERE `word_id` = 80147; -- locales_creature - name : entry=13158
UPDATE `trans_words` SET `content_loc2`='Lieutenant Spencer' WHERE `word_id` = 80128; -- locales_creature - name : entry=13138
UPDATE `trans_words` SET `content_loc2`='Lieutenant Vol\'talar' WHERE `word_id` = 80134; -- locales_creature - name : entry=13144
UPDATE `trans_words` SET `content_loc2`='Mini Diablo' WHERE `word_id` = 79350; -- locales_creature - name : entry=11326
UPDATE `trans_words` SET `content_loc2`='Murloc' WHERE `word_id` = 72439; -- locales_creature - name : entry=285
UPDATE `trans_words` SET `content_loc2`='Mythidan' WHERE `word_id` = 75806; -- locales_creature - name : entry=4233
UPDATE `trans_words` SET `content_loc2`='Novice Elreth' WHERE `word_id` = 73555; -- locales_creature - name : entry=1661
UPDATE `trans_words` SET `content_loc2`='Novice Thaivand' WHERE `word_id` = 74178; -- locales_creature - name : entry=2429
UPDATE `trans_words` SET `content_loc2`='Prince Kellen' WHERE `word_id` = 80384; -- locales_creature - name : entry=14225
UPDATE `trans_words` SET `content_loc2`='Prince Nazjak' WHERE `word_id` = 74498; -- locales_creature - name : entry=2779
UPDATE `trans_words` SET `content_loc2`='Prince Raze' WHERE `word_id` = 79010; -- locales_creature - name : entry=10647
UPDATE `trans_words` SET `content_loc2`='Prince Skaldrenox' WHERE `word_id` = 80964; -- locales_creature - name : entry=15203
UPDATE `trans_words` SET `content_loc2`='Prince Tortheldrin' WHERE `word_id` = 79435; -- locales_creature - name : entry=11486
UPDATE `trans_words` SET `content_loc2`='Prince Xavalis' WHERE `word_id` = 78694; -- locales_creature - name : entry=9877
UPDATE `trans_words` SET `content_loc2`='Rat' WHERE `word_id` = 75669; -- locales_creature - name : entry=4075
UPDATE `trans_words` SET `content_loc2`='Sage Korolusk' WHERE `word_id` = 80477; -- locales_creature - name : entry=14373
UPDATE `trans_words` SET `content_loc2`='The Head of The Black Flight' WHERE `word_id` = 79478; -- locales_creature - subname : entry=11583
UPDATE `trans_words` SET `content_loc2`='Treant' WHERE `word_id` = 73797; -- locales_creature - name : entry=1964

SET NAMES 'latin1';
