-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc6`='"Threshwackonator First Mate unit prepared to follow"' WHERE `word_id` = 219; -- script_texts - content : entry=-1000325
UPDATE `trans_words` SET `content_loc6`='$C, no hurt A-Me. A-Me good.' WHERE `word_id` = 343; -- script_texts - content : entry=-1000449
UPDATE `trans_words` SET `content_loc6`='$C, Where am I? Who are you? Oh no! What happened to the ship?' WHERE `word_id` = 74; -- script_texts - content : entry=-1000177
UPDATE `trans_words` SET `content_loc6`='%s begins to unleash an insect swarm!' WHERE `word_id` = 1272; -- script_texts - content : entry=-1533154
UPDATE `trans_words` SET `content_loc6`='%s casts Condemation on everyone!' WHERE `word_id` = 1275; -- script_texts - content : entry=-1533157
UPDATE `trans_words` SET `content_loc6`='%s collapses onto the ground.' WHERE `word_id` = 323; -- script_texts - content : entry=-1000429
UPDATE `trans_words` SET `content_loc6`='%s fades away after a long pause.' WHERE `word_id` = 327; -- script_texts - content : entry=-1000433
UPDATE `trans_words` SET `content_loc6`='%s hands one glowing goggles over to Doctor Draxlegauge.' WHERE `word_id` = 166; -- script_texts - content : entry=-1000272
UPDATE `trans_words` SET `content_loc6`='%s hands the Scepter of the Shifting Sands to $N.' WHERE `word_id` = 600; -- script_texts - content : entry=-1000762
UPDATE `trans_words` SET `content_loc6`='%s has entered our world' WHERE `word_id` = 512; -- script_texts - content : entry=-1000674
UPDATE `trans_words` SET `content_loc6`='%s hisses' WHERE `word_id` = 706; -- script_texts - content : entry=-1000872
UPDATE `trans_words` SET `content_loc6`='%s is wholly consumed by the Light of Elune. Tranquility sets in over the Moonglade' WHERE `word_id` = 535; -- script_texts - content : entry=-1000697
UPDATE `trans_words` SET `content_loc6`='%s jumps into the moonwell and goes underwater...' WHERE `word_id` = 433; -- script_texts - content : entry=-1000541
UPDATE `trans_words` SET `content_loc6`='%s kneels down and pick up the amulet.' WHERE `word_id` = 93; -- script_texts - content : entry=-1000197
UPDATE `trans_words` SET `content_loc6`='%s kneels down to pickup the fragments of the shattered scepter.' WHERE `word_id` = 607; -- script_texts - content : entry=-1000769
UPDATE `trans_words` SET `content_loc6`='%s lifts off into the air!' WHERE `word_id` = 1141; -- script_texts - content : entry=-1533022
UPDATE `trans_words` SET `content_loc6`='%s looks at you unexpectadly.' WHERE `word_id` = 101; -- script_texts - content : entry=-1000205
UPDATE `trans_words` SET `content_loc6`='%s performs one last service for Ragnaros.' WHERE `word_id` = 983; -- script_texts - content : entry=-1409000
UPDATE `trans_words` SET `content_loc6`='%s puts the shell to his ear.' WHERE `word_id` = 82; -- script_texts - content : entry=-1000185
UPDATE `trans_words` SET `content_loc6`='%s reaches into his pack and pulls out the encoded tablets...' WHERE `word_id` = 692; -- script_texts - content : entry=-1000858
UPDATE `trans_words` SET `content_loc6`='%s reads from the tablets. Unknown, unheard sounds flow through your consciousness' WHERE `word_id` = 695; -- script_texts - content : entry=-1000861
UPDATE `trans_words` SET `content_loc6`='%s refuses to die while its master is in trouble.' WHERE `word_id` = 984; -- script_texts - content : entry=-1409002
UPDATE `trans_words` SET `content_loc6`='%s resumes his attacks!' WHERE `word_id` = 1201; -- script_texts - content : entry=-1533083
UPDATE `trans_words` SET `content_loc6`='%s spots a nearby Zombie to devour!' WHERE `word_id` = 1237; -- script_texts - content : entry=-1533119
UPDATE `trans_words` SET `content_loc6`='%s stands up after a short pause.' WHERE `word_id` = 324; -- script_texts - content : entry=-1000430
UPDATE `trans_words` SET `content_loc6`='%s starts pecking at the feed.' WHERE `word_id` = 102; -- script_texts - content : entry=-1000206
UPDATE `trans_words` SET `content_loc6`='%s strikes!' WHERE `word_id` = 1253; -- script_texts - content : entry=-1533135
UPDATE `trans_words` SET `content_loc6`='%s suddenly falls asleep' WHERE `word_id` = 330; -- script_texts - content : entry=-1000436
UPDATE `trans_words` SET `content_loc6`='...and stay dead! He got served' WHERE `word_id` = 837; -- script_texts - content : entry=-1090027
UPDATE `trans_words` SET `content_loc6`='<Kel\'Thuzad cackles maniacally!>' WHERE `word_id` = 1216; -- script_texts - content : entry=-1533098
UPDATE `trans_words` SET `content_loc6`='<ScriptDev3 Text Entry Missing!>' WHERE `word_id` = 1; -- script_texts - content : entry=-1000000
UPDATE `trans_words` SET `content_loc6`='AAAAGHHH!... Do not rejoice... your victory is a hollow one... for I shall return with powers beyond your imagining!' WHERE `word_id` = 1217; -- script_texts - content : entry=-1533099
UPDATE `trans_words` SET `content_loc6`='Ah! Fresh air at last! I never thought I\'d see the day.' WHERE `word_id` = 1287; -- script_texts - content : entry=-1001154
UPDATE `trans_words` SET `content_loc6`='Ah, $GPriest:Priestess; you came along just in time. I appreciate it.' WHERE `word_id` = 126; -- script_texts - content : entry=-1000231
UPDATE `trans_words` SET `content_loc6`='Ah, fresh air, at last! I need a moment to rest.' WHERE `word_id` = 446; -- script_texts - content : entry=-1000562
UPDATE `trans_words` SET `content_loc6`='Ah, I have been waiting for a real challenge!' WHERE `word_id` = 858; -- script_texts - content : entry=-1189000
UPDATE `trans_words` SET `content_loc6`='Ah, lambs to the slaughter!' WHERE `word_id` = 1104; -- script_texts - content : entry=-1531026
UPDATE `trans_words` SET `content_loc6`='Ah. I remember now! I gave the mysterious fossil to Hollee! Check with her.' WHERE `word_id` = 231; -- script_texts - content : entry=-1000337
UPDATE `trans_words` SET `content_loc6`='Ah...the wondrous sound of kodos. I love the way they make the ground shake... inspect the beast for me.' WHERE `word_id` = 242; -- script_texts - content : entry=-1000348
UPDATE `trans_words` SET `content_loc6`='Alexstrasza, give me the resolve to drive your enemies back.' WHERE `word_id` = 589; -- script_texts - content : entry=-1000751
UPDATE `trans_words` SET `content_loc6`='All life must be eradicated!' WHERE `word_id` = 56; -- script_texts - content : entry=-1000150
UPDATE `trans_words` SET `content_loc6`='All of Draenor shall quick beneath my feet! I will destroy this world and reshape it in my image!' WHERE `word_id` = 67; -- script_texts - content : entry=-1000170
UPDATE `trans_words` SET `content_loc6`='All right, stay close. These fiends will jump right out of the shadows at you if you let your guard down.' WHERE `word_id` = 850; -- script_texts - content : entry=-1129005
UPDATE `trans_words` SET `content_loc6`='Alright, alright I think I can figure out how to operate this thing...' WHERE `word_id` = 192; -- script_texts - content : entry=-1000298
UPDATE `trans_words` SET `content_loc6`='A-Me home! A-Me good! Good A-Me. Home. Home. Home.' WHERE `word_id` = 342; -- script_texts - content : entry=-1000448
UPDATE `trans_words` SET `content_loc6`='An honorable... death...' WHERE `word_id` = 1247; -- script_texts - content : entry=-1533129
UPDATE `trans_words` SET `content_loc6`='Anachronos, the diversion will give you an the young druid time enough to seal the gate. Do not falter. Now, let us see how they deal with chaotic magic.' WHERE `word_id` = 586; -- script_texts - content : entry=-1000748
UPDATE `trans_words` SET `content_loc6`='And now you know all that there is to know, mortal' WHERE `word_id` = 608; -- script_texts - content : entry=-1000770
UPDATE `trans_words` SET `content_loc6`='And try not to get lost this time...' WHERE `word_id` = 292; -- script_texts - content : entry=-1000398
UPDATE `trans_words` SET `content_loc6`='Are you so eager to die? I would be happy to accomodate you.' WHERE `word_id` = 1078; -- script_texts - content : entry=-1531000
UPDATE `trans_words` SET `content_loc6`='At last! Free from Northwatch Hold! I need a moment to catch my breath...' WHERE `word_id` = 265; -- script_texts - content : entry=-1000371
UPDATE `trans_words` SET `content_loc6`='Attack and make them pay dearly!' WHERE `word_id` = 1058; -- script_texts - content : entry=-1509011
UPDATE `trans_words` SET `content_loc6`='Attack my sisters! The troll must not escape!' WHERE `word_id` = 298; -- script_texts - content : entry=-1000404
UPDATE `trans_words` SET `content_loc6`='Awake ye servants, defend the discs!' WHERE `word_id` = 808; -- script_texts - content : entry=-1070002
UPDATE `trans_words` SET `content_loc6`='Aye, Fandral, remember these words: Let not your grief guide your faith. These thoughts you hold... dark places you go, night elf.Absolution cannot be had through misguided vengeance.' WHERE `word_id` = 582; -- script_texts - content : entry=-1000744
UPDATE `trans_words` SET `content_loc6`='Be careful, $N. Those wolves like to hide among the trees.' WHERE `word_id` = 201; -- script_texts - content : entry=-1000307
UPDATE `trans_words` SET `content_loc6`='Before I leave this place, I make one final offering for you, Lord Staghelm. Should a time arise in which you must gain entry to this accursed fortress, use the scepter of the shifting sands on the sacred gong. The magic holding the barrier together will dissipate an the horrors of the Ahn\'Qiraj will be unleashed upon the world once more.' WHERE `word_id` = 599; -- script_texts - content : entry=-1000761
UPDATE `trans_words` SET `content_loc6`='Behold Ragnaros, the Firelord! He who was ancient when this world was young! Bow before him, mortals! Bow before your ending!' WHERE `word_id` = 990; -- script_texts - content : entry=-1409008
UPDATE `trans_words` SET `content_loc6`='Beware $N! Look to the west!' WHERE `word_id` = 724; -- script_texts - content : entry=-1000891
UPDATE `trans_words` SET `content_loc6`='Bless you mortal for this release. Hakkar controls me no longer...' WHERE `word_id` = 944; -- script_texts - content : entry=-1309008
UPDATE `trans_words` SET `content_loc6`='Brashly you have come to rest the secrets of the living flame. You will soon regret the recklessness of your quest.' WHERE `word_id` = 1002; -- script_texts - content : entry=-1409020
UPDATE `trans_words` SET `content_loc6`='BREAK YOU!' WHERE `word_id` = 1151; -- script_texts - content : entry=-1533032
UPDATE `trans_words` SET `content_loc6`='Breath your last!' WHERE `word_id` = 1063; -- script_texts - content : entry=-1509016
UPDATE `trans_words` SET `content_loc6`='Burn mortals! Burn for this transgression!' WHERE `word_id` = 988; -- script_texts - content : entry=-1409006
UPDATE `trans_words` SET `content_loc6`='Calm down lad, it\'s just a birdshot!' WHERE `word_id` = 497; -- script_texts - content : entry=-1000650
UPDATE `trans_words` SET `content_loc6`='Clever Mortals but I am not so easily lured away from my sanctum!' WHERE `word_id` = 1011; -- script_texts - content : entry=-1469001
UPDATE `trans_words` SET `content_loc6`='Cloaking systems online! CLUCK! Engaging cloak for transport to Booty Bay!' WHERE `word_id` = 186; -- script_texts - content : entry=-1000292
UPDATE `trans_words` SET `content_loc6`='Close your eyes... sleep!' WHERE `word_id` = 1230; -- script_texts - content : entry=-1533112
UPDATE `trans_words` SET `content_loc6`='Closer now... tasty morsels. I\'ve been too long without food. Without blood to drink.' WHERE `word_id` = 1126; -- script_texts - content : entry=-1533007
UPDATE `trans_words` SET `content_loc6`='CLUCK! Sensors detect spatial anomaly - danger imminent! CLUCK!' WHERE `word_id` = 184; -- script_texts - content : entry=-1000290
UPDATE `trans_words` SET `content_loc6`='Come out and fight, ye wee ninny!' WHERE `word_id` = 1170; -- script_texts - content : entry=-1533051
UPDATE `trans_words` SET `content_loc6`='Come to aid the Throne!' WHERE `word_id` = 897; -- script_texts - content : entry=-1230001
UPDATE `trans_words` SET `content_loc6`='Come, Zeliek, do not drive them out. Not before we\'ve had our fun.' WHERE `word_id` = 1164; -- script_texts - content : entry=-1533045
UPDATE `trans_words` SET `content_loc6`='Conserve your anger! Harness your rage! You will all have outlets for your frustration soon enough.' WHERE `word_id` = 1191; -- script_texts - content : entry=-1533072
UPDATE `trans_words` SET `content_loc6`='Cower mortals! The age of darkness is at hand.' WHERE `word_id` = 1079; -- script_texts - content : entry=-1531001
UPDATE `trans_words` SET `content_loc6`='Crush them! Drive them out!' WHERE `word_id` = 1059; -- script_texts - content : entry=-1509012
UPDATE `trans_words` SET `content_loc6`='D\'oh !' WHERE `word_id` = 337437; -- script_texts - content : entry=-1429004
UPDATE `trans_words` SET `content_loc6`='Death is close...' WHERE `word_id` = 1111; -- script_texts - content : entry=-1531033
UPDATE `trans_words` SET `content_loc6`='Death is the only escape.' WHERE `word_id` = 1160; -- script_texts - content : entry=-1533041
UPDATE `trans_words` SET `content_loc6`='Death Knights, get over here!' WHERE `word_id` = 1041; -- script_texts - content : entry=-1469031
UPDATE `trans_words` SET `content_loc6`='Defend Nightaven, hero...' WHERE `word_id` = 511; -- script_texts - content : entry=-1000673
UPDATE `trans_words` SET `content_loc6`='Defend youself!' WHERE `word_id` = 1163; -- script_texts - content : entry=-1533044
UPDATE `trans_words` SET `content_loc6`='Deployment sucessful. Trespassers will be neutralized.' WHERE `word_id` = 85; -- script_texts - content : entry=-1000188
UPDATE `trans_words` SET `content_loc6`='Destroy them, Torloth. Let lose their blood like a river upon this hallowed ground.' WHERE `word_id` = 427; -- script_texts - content : entry=-1000535
UPDATE `trans_words` SET `content_loc6`='DIE DEMON DOGS!' WHERE `word_id` = 1286; -- script_texts - content : entry=-1001153
UPDATE `trans_words` SET `content_loc6`='DIE INSECT!' WHERE `word_id` = 999; -- script_texts - content : entry=-1409017
UPDATE `trans_words` SET `content_loc6`='Do not forget sacrifices made on this day, night elf. We have all suffered immensely at the hands of these beasts.' WHERE `word_id` = 588; -- script_texts - content : entry=-1000750
UPDATE `trans_words` SET `content_loc6`='Do not hesitate! Destroy them!' WHERE `word_id` = 1060; -- script_texts - content : entry=-1509013
UPDATE `trans_words` SET `content_loc6`='Don\'t cross those beams!' WHERE `word_id` = 967; -- script_texts - content : entry=-1329003
UPDATE `trans_words` SET `content_loc6`='Don\'t just stand there! Help him out!' WHERE `word_id` = 421; -- script_texts - content : entry=-1000529
UPDATE `trans_words` SET `content_loc6`='Don\'t leave me in here! Cause if you do I will find you!' WHERE `word_id` = 487; -- script_texts - content : entry=-1000631
UPDATE `trans_words` SET `content_loc6`='Don\'t make me angry. You won\'t like it when I\'m angry.' WHERE `word_id` = 955; -- script_texts - content : entry=-1309019
UPDATE `trans_words` SET `content_loc6`='Draw me to your web mistress Shadra. Unleash your venom!' WHERE `word_id` = 941; -- script_texts - content : entry=-1309005
UPDATE `trans_words` SET `content_loc6`='Druids and your silly shapeshifting. Let\'s see it in action!' WHERE `word_id` = 1025; -- script_texts - content : entry=-1469015
UPDATE `trans_words` SET `content_loc6`='Duro will be reinforced! Ultris was a complete disaster. I will NOT have that mistake repeated!' WHERE `word_id` = 39; -- script_texts - content : entry=-1000133
UPDATE `trans_words` SET `content_loc6`='EAT YOUR BONES!' WHERE `word_id` = 1150; -- script_texts - content : entry=-1533031
UPDATE `trans_words` SET `content_loc6`='Emergency power activated! Initializing ambulanory motor! CLUCK!' WHERE `word_id` = 181; -- script_texts - content : entry=-1000287
UPDATE `trans_words` SET `content_loc6`='Emergency shutdown aborted.' WHERE `word_id` = 111; -- script_texts - content : entry=-1000216
UPDATE `trans_words` SET `content_loc6`='Enough prattling. Let them come! We shall grind their bones to dust.' WHERE `word_id` = 1190; -- script_texts - content : entry=-1533071
UPDATE `trans_words` SET `content_loc6`='Enough! I grow tired of these distractions!' WHERE `word_id` = 1225; -- script_texts - content : entry=-1533107
UPDATE `trans_words` SET `content_loc6`='Enough! Now you vermin shall feel the force of my birthright, the fury of the earth itself.' WHERE `word_id` = 1018; -- script_texts - content : entry=-1469008
UPDATE `trans_words` SET `content_loc6`='Everything hurts, Please make it stop...' WHERE `word_id` = 78; -- script_texts - content : entry=-1000181
UPDATE `trans_words` SET `content_loc6`='Explosions! MORE explosions! I\'ve got to have more explosions!' WHERE `word_id` = 836; -- script_texts - content : entry=-1090026
UPDATE `trans_words` SET `content_loc6`='Feugen make master happy!' WHERE `word_id` = 1146; -- script_texts - content : entry=-1533027
UPDATE `trans_words` SET `content_loc6`='Finally ...death. Curse you Hakkar! Curse you!' WHERE `word_id` = 940; -- script_texts - content : entry=-1309004
UPDATE `trans_words` SET `content_loc6`='FOOL! YOU ALLOWED THESE INSECTS TO RUN RAMPANT THROUGH THE HALLOWED CORE, AND NOW YOU LEAD THEM TO MY VERY LAIR? YOU HAVE FAILED ME, EXECUTUS! JUSTICE SHALL BE MET, INDEED!' WHERE `word_id` = 993; -- script_texts - content : entry=-1409011
UPDATE `trans_words` SET `content_loc6`='Fools, you have spread your powers too thin. Be free, my minions!' WHERE `word_id` = 1226; -- script_texts - content : entry=-1533108
UPDATE `trans_words` SET `content_loc6`='Fools, you think yourselves triumphant? You have only taken one step closer to the abyss!' WHERE `word_id` = 1209; -- script_texts - content : entry=-1533091
UPDATE `trans_words` SET `content_loc6`='Foolsss...Kill the one in the dress!' WHERE `word_id` = 881; -- script_texts - content : entry=-1229006
UPDATE `trans_words` SET `content_loc6`='For so long, I was lost... The Nightmare\'s corruption had consumed me... And now, you... all of you.. you have saved me. Released me from its grasp.' WHERE `word_id` = 538; -- script_texts - content : entry=-1000700
UPDATE `trans_words` SET `content_loc6`='FROST SHOCK!!!' WHERE `word_id` = 379; -- script_texts - content : entry=-1000487
UPDATE `trans_words` SET `content_loc6`='Go report that the outpost is taken. We will remain here.' WHERE `word_id` = 16; -- script_texts - content : entry=-1000110
UPDATE `trans_words` SET `content_loc6`='Grant me protection $N, i must break trough their foul magic!' WHERE `word_id` = 278; -- script_texts - content : entry=-1000384
UPDATE `trans_words` SET `content_loc6`='Grark Lorkrub, you have been charged and found guilty of treason against Horde. How you plead is unimportant. High Executioner Nuzrak, step forward.' WHERE `word_id` = 717; -- script_texts - content : entry=-1000884
UPDATE `trans_words` SET `content_loc6`='Hah hah, I\'m just getting warmed up!' WHERE `word_id` = 1238; -- script_texts - content : entry=-1533120
UPDATE `trans_words` SET `content_loc6`='Hah, is that all?' WHERE `word_id` = 861; -- script_texts - content : entry=-1189003
UPDATE `trans_words` SET `content_loc6`='Hakkar binds me no more! Peace at last!' WHERE `word_id` = 946; -- script_texts - content : entry=-1309010
UPDATE `trans_words` SET `content_loc6`='HALT! There were...reports...of a...disturbance.' WHERE `word_id` = 1305; -- script_texts - content : entry=-1230048
UPDATE `trans_words` SET `content_loc6`='He will stop at nothing to get to Malfurion\'s physical manifistation. That must not happen... We must keep the beast occupied long enough for Tyrande to arrive.' WHERE `word_id` = 510; -- script_texts - content : entry=-1000672
UPDATE `trans_words` SET `content_loc6`='Help! Please, You must help me!' WHERE `word_id` = 459; -- script_texts - content : entry=-1000582
UPDATE `trans_words` SET `content_loc6`='Here they come! Defend yourself!' WHERE `word_id` = 304; -- script_texts - content : entry=-1000410
UPDATE `trans_words` SET `content_loc6`='Hey! Get away from that!' WHERE `word_id` = 1312; -- script_texts - content : entry=-1230055
UPDATE `trans_words` SET `content_loc6`='Hmm... I don\'t think this blinking red light is a good thing...' WHERE `word_id` = 199; -- script_texts - content : entry=-1000305
UPDATE `trans_words` SET `content_loc6`='How fortuitous. Usually, I must leave my lair to feed.' WHERE `word_id` = 930; -- script_texts - content : entry=-1249000
UPDATE `trans_words` SET `content_loc6`='Hungry worms will feast on your rotten flesh!' WHERE `word_id` = 1235; -- script_texts - content : entry=-1533117
UPDATE `trans_words` SET `content_loc6`='I am gathering a bogbean. It takes some time.' WHERE `word_id` = 744; -- script_texts - content : entry=-1000961
UPDATE `trans_words` SET `content_loc6`='I am ready, $N. Let\'s find my equipment and get out of here. I think I know where it is.' WHERE `word_id` = 1281; -- script_texts - content : entry=-1001148
UPDATE `trans_words` SET `content_loc6`='I am rejuvinated!' WHERE `word_id` = 1065; -- script_texts - content : entry=-1509018
UPDATE `trans_words` SET `content_loc6`='I am returning to Tempest Keep. See to it that I do not have reason to return!' WHERE `word_id` = 41; -- script_texts - content : entry=-1000135
UPDATE `trans_words` SET `content_loc6`='I bet Quae\'ll think this is important. She\'s pretty knowledgeable about these things--no expert, but knowledgable.' WHERE `word_id` = 739; -- script_texts - content : entry=-1000954
UPDATE `trans_words` SET `content_loc6`='I bet you\'re sorry now, aren\'t you?' WHERE `word_id` = 908; -- script_texts - content : entry=-1230012
UPDATE `trans_words` SET `content_loc6`='I can find my way from here. My friend Mekeda will reward you for your kind actions.' WHERE `word_id` = 373; -- script_texts - content : entry=-1000481
UPDATE `trans_words` SET `content_loc6`='I can make it the rest of the way. $N. THANKS!' WHERE `word_id` = 732; -- script_texts - content : entry=-1000906
UPDATE `trans_words` SET `content_loc6`='I discovered this cave on our first day here. I believe the energy in the stone can be used to our advantage.' WHERE `word_id` = 159; -- script_texts - content : entry=-1000265
UPDATE `trans_words` SET `content_loc6`='I don\'t know if I can make it, please help me...' WHERE `word_id` = 80; -- script_texts - content : entry=-1000183
UPDATE `trans_words` SET `content_loc6`='I don\'t think it can top the one time where he told us that he\'d heard that Artha\'s "cousin\'s" skeleton was frozen beneath a glacier in Winterspring. I\'ll never forgive you for that one, Letoll. I mean honestly... Artha\'s cousin?' WHERE `word_id` = 416; -- script_texts - content : entry=-1000524
UPDATE `trans_words` SET `content_loc6`='I DRAW CLOSER TO YOUR WORLD!' WHERE `word_id` = 847; -- script_texts - content : entry=-1109008
UPDATE `trans_words` SET `content_loc6`='I foresee no complications at this... wait! What is this!?' WHERE `word_id` = 1204; -- script_texts - content : entry=-1533086
UPDATE `trans_words` SET `content_loc6`='I go now to summon the lord whos house this is. Should you seek an audiance with him your paltry lives will surly be forfit. Nevertheless seek out his lair if you dare!' WHERE `word_id` = 1003; -- script_texts - content : entry=-1409021
UPDATE `trans_words` SET `content_loc6`='I have waited long enough! Now, you face the harvester of souls!' WHERE `word_id` = 1162; -- script_texts - content : entry=-1533043
UPDATE `trans_words` SET `content_loc6`='I hear little hearts beating. Yesss... beating faster now. Soon the beating will stop.' WHERE `word_id` = 1123; -- script_texts - content : entry=-1533004
UPDATE `trans_words` SET `content_loc6`='I heard about enough of yer sniveling. Shut yer fly trap \'afore I shut it for ye!' WHERE `word_id` = 1172; -- script_texts - content : entry=-1533053
UPDATE `trans_words` SET `content_loc6`='I- I have no choice but to obey!' WHERE `word_id` = 1181; -- script_texts - content : entry=-1533062
UPDATE `trans_words` SET `content_loc6`='I remember well the sting of defeat at the conclusion of the Third War. I have waited far too long for my revenge. Now the shadow of the Legion falls over this world. It is only a matter of time until all of your failed creation... is undone.' WHERE `word_id` = 53; -- script_texts - content : entry=-1000147
UPDATE `trans_words` SET `content_loc6`='I see endless suffering, I see torment, I see rage. I see... everything!' WHERE `word_id` = 1232; -- script_texts - content : entry=-1533114
UPDATE `trans_words` SET `content_loc6`='I sense the tortured spirits, $N. They are this way, come quickly!' WHERE `word_id` = 275; -- script_texts - content : entry=-1000381
UPDATE `trans_words` SET `content_loc6`='I swear. I didn\'t steal anything from you! Here, take some of my supplies, just go away!' WHERE `word_id` = 349; -- script_texts - content : entry=-1000455
UPDATE `trans_words` SET `content_loc6`='I think those weird bird guys were going to eat us. Gross!' WHERE `word_id` = 468; -- script_texts - content : entry=-1000591
UPDATE `trans_words` SET `content_loc6`='I want more ale! Give me more ale!' WHERE `word_id` = 1294; -- script_texts - content : entry=-1230036
UPDATE `trans_words` SET `content_loc6`='I want nothing to do with Silithus, the Qiraji and least of all, any damed dragons!' WHERE `word_id` = 602; -- script_texts - content : entry=-1000764
UPDATE `trans_words` SET `content_loc6`='I will serve the master... in... death!' WHERE `word_id` = 1200; -- script_texts - content : entry=-1533081
UPDATE `trans_words` SET `content_loc6`='I... am... undone!' WHERE `word_id` = 1161; -- script_texts - content : entry=-1533042
UPDATE `trans_words` SET `content_loc6`='I...am...released! Perhaps it\'s not too late to' WHERE `word_id` = 1193; -- script_texts - content : entry=-1533074
UPDATE `trans_words` SET `content_loc6`='If I fall into the abyss I\'ll take all of you mortals with me...' WHERE `word_id` = 1035; -- script_texts - content : entry=-1469025
UPDATE `trans_words` SET `content_loc6`='Impossible! Rise my minions! Serve your master once more!' WHERE `word_id` = 1020; -- script_texts - content : entry=-1469010
UPDATE `trans_words` SET `content_loc6`='Impossible! Stay your attack mortals! I submitt! I submitt!' WHERE `word_id` = 989; -- script_texts - content : entry=-1409007
UPDATE `trans_words` SET `content_loc6`='Intruders are destroying our eggs! Stop!!' WHERE `word_id` = 895; -- script_texts - content : entry=-1229020
UPDATE `trans_words` SET `content_loc6`='Intruders! More pawns of the Argent Dawn, no doubt. I already count one of their number among my prisoners. Withdraw from my domain before she is executed!' WHERE `word_id` = 973; -- script_texts - content : entry=-1329009
UPDATE `trans_words` SET `content_loc6`='Is that the best you can do? Do you really expect that you could defeat someone as awe inspiring as me?' WHERE `word_id` = 1318; -- script_texts - content : entry=-1230061
UPDATE `trans_words` SET `content_loc6`='IT BURNS! THE PAIN.. SEARING...' WHERE `word_id` = 532; -- script_texts - content : entry=-1000694
UPDATE `trans_words` SET `content_loc6`='It is best that we split up now, in case they send more after us. Hopefully one of us will make it back to Garrosh. Farewell stranger.' WHERE `word_id` = 380; -- script_texts - content : entry=-1000488
UPDATE `trans_words` SET `content_loc6`='It is done, dragon. Lead the way!' WHERE `word_id` = 591; -- script_texts - content : entry=-1000753
UPDATE `trans_words` SET `content_loc6`='It is good that you serve me so faithfully. Soon... all will serve the Lich King and in the end, you shall be rewarded. So long as you do not falter.' WHERE `word_id` = 1203; -- script_texts - content : entry=-1533085
UPDATE `trans_words` SET `content_loc6`='It was ... terrible... the demon...' WHERE `word_id` = 436; -- script_texts - content : entry=-1000544
UPDATE `trans_words` SET `content_loc6`='It\'s too late to turn away.' WHERE `word_id` = 1097; -- script_texts - content : entry=-1531019
UPDATE `trans_words` SET `content_loc6`='Join me brother, there is blood to be shed!' WHERE `word_id` = 1106; -- script_texts - content : entry=-1531028
UPDATE `trans_words` SET `content_loc6`='Khadgar himself is showing you around? You must have made a good impression, $N.' WHERE `word_id` = 387; -- script_texts - content : entry=-1000495
UPDATE `trans_words` SET `content_loc6`='Kill two monsters, who stay near Bogbean plant and then I gather a bogbean.' WHERE `word_id` = 743; -- script_texts - content : entry=-1000960
UPDATE `trans_words` SET `content_loc6`='Kneel, Grark' WHERE `word_id` = 716; -- script_texts - content : entry=-1000883
UPDATE `trans_words` SET `content_loc6`='Kolkar are the strongest!' WHERE `word_id` = 727; -- script_texts - content : entry=-1000894
UPDATE `trans_words` SET `content_loc6`='Kolkar invaders are retreating!' WHERE `word_id` = 726; -- script_texts - content : entry=-1000893
UPDATE `trans_words` SET `content_loc6`='Learn your place mortal!' WHERE `word_id` = 931; -- script_texts - content : entry=-1249001
UPDATE `trans_words` SET `content_loc6`='Let none survive!' WHERE `word_id` = 1105; -- script_texts - content : entry=-1531027
UPDATE `trans_words` SET `content_loc6`='Let the trial begin, Bloodwrath, attack!' WHERE `word_id` = 213; -- script_texts - content : entry=-1000319
UPDATE `trans_words` SET `content_loc6`='Let them feelt the wrath of the blue flight! May Malygos protect me!' WHERE `word_id` = 587; -- script_texts - content : entry=-1000749
UPDATE `trans_words` SET `content_loc6`='Let us go into the Lower City. I will warn you that as one of the only safe havens in Outland, Shattrath has attracted droves of refugees from all wars, current and past.' WHERE `word_id` = 133; -- script_texts - content : entry=-1000238
UPDATE `trans_words` SET `content_loc6`='Let us leave Nighthave, hero. Seek me out at the grove.' WHERE `word_id` = 543; -- script_texts - content : entry=-1000705
UPDATE `trans_words` SET `content_loc6`='Let\'s get to the others, and keep an eye open for those wolves cutside...' WHERE `word_id` = 200; -- script_texts - content : entry=-1000306
UPDATE `trans_words` SET `content_loc6`='Let\'s go $N!' WHERE `word_id` = 609; -- script_texts - content : entry=-1000771
UPDATE `trans_words` SET `content_loc6`='Let\'s go $N. I am ready to reach Whitereach Post.' WHERE `word_id` = 256; -- script_texts - content : entry=-1000362
UPDATE `trans_words` SET `content_loc6`='Liatha, get someone to look at those injuries. Thank you for bringing her back safely.' WHERE `word_id` = 52; -- script_texts - content : entry=-1000146
UPDATE `trans_words` SET `content_loc6`='Light be with you, $N. And welcome to Shattrath.' WHERE `word_id` = 385; -- script_texts - content : entry=-1000493
UPDATE `trans_words` SET `content_loc6`='Like a fly in a web.' WHERE `word_id` = 1099; -- script_texts - content : entry=-1531021
UPDATE `trans_words` SET `content_loc6`='Look brother, fresh blood!' WHERE `word_id` = 1107; -- script_texts - content : entry=-1531029
UPDATE `trans_words` SET `content_loc6`='Look out! The $C attacks!' WHERE `word_id` = 461; -- script_texts - content : entry=-1000584
UPDATE `trans_words` SET `content_loc6`='Look out, $N! Enemies ahead!' WHERE `word_id` = 240; -- script_texts - content : entry=-1000346
UPDATE `trans_words` SET `content_loc6`='Looks like we won\'t get away so easy. Get ready!' WHERE `word_id` = 238; -- script_texts - content : entry=-1000344
UPDATE `trans_words` SET `content_loc6`='Looks like we\'re out of woods, eh? Wonder what this does...' WHERE `word_id` = 196; -- script_texts - content : entry=-1000302
UPDATE `trans_words` SET `content_loc6`='Lord Hir\'eek, grant me wings of vengance!' WHERE `word_id` = 938; -- script_texts - content : entry=-1309002
UPDATE `trans_words` SET `content_loc6`='Many of the priesthood had been slain by the same magisters who now vowed to serve the naaru. They were not happy to share the city with their former enemies.' WHERE `word_id` = 144; -- script_texts - content : entry=-1000249
UPDATE `trans_words` SET `content_loc6`='Marshal Marris, sir. Corporal Keeshan of the 12th Sabre Regiment returned from battle and reporting for duty!' WHERE `word_id` = 448; -- script_texts - content : entry=-1000564
UPDATE `trans_words` SET `content_loc6`='Master save me...' WHERE `word_id` = 1144; -- script_texts - content : entry=-1533025
UPDATE `trans_words` SET `content_loc6`='Master! I require aid!' WHERE `word_id` = 1221; -- script_texts - content : entry=-1533103
UPDATE `trans_words` SET `content_loc6`='Minions, servants, soldiers of the cold dark, obey the call of Kel\'Thuzad!' WHERE `word_id` = 1223; -- script_texts - content : entry=-1533105
UPDATE `trans_words` SET `content_loc6`='My brother...NO!' WHERE `word_id` = 1102; -- script_texts - content : entry=-1531024
UPDATE `trans_words` SET `content_loc6`='My dearest Torta. I have been gone for so long. Finally we are reunited. At long last our love can blossom again.' WHERE `word_id` = 289; -- script_texts - content : entry=-1000395
UPDATE `trans_words` SET `content_loc6`='My flame! Please don\'t take away my flame...' WHERE `word_id` = 1004; -- script_texts - content : entry=-1409022
UPDATE `trans_words` SET `content_loc6`='My forces cannot overcome the Qiraji defenses. We will not be able to get close enough to place our precious barrier, dragon.' WHERE `word_id` = 579; -- script_texts - content : entry=-1000741
UPDATE `trans_words` SET `content_loc6`='My lady, I am unworthy of your prayer. Truly, you are an angel of light. Please, assist me in returning to the barrow den so that I may return to the Dream. I like Malfurion, also have a love awaiting me... I must return to her... to protect her...' WHERE `word_id` = 540; -- script_texts - content : entry=-1000702
UPDATE `trans_words` SET `content_loc6`='MY PATIENCE IS DWINDILING! COME NATS TO YOUR DEATH!' WHERE `word_id` = 1000; -- script_texts - content : entry=-1409018
UPDATE `trans_words` SET `content_loc6`='My powers are renewed!' WHERE `word_id` = 1066; -- script_texts - content : entry=-1509019
UPDATE `trans_words` SET `content_loc6`='My powers return!' WHERE `word_id` = 1067; -- script_texts - content : entry=-1509020
UPDATE `trans_words` SET `content_loc6`='My son\'s soul will find no comfort in this hollow victory, dragon! I will have him back. Though it takes a millenia. I WILL have my son back!' WHERE `word_id` = 605; -- script_texts - content : entry=-1000767
UPDATE `trans_words` SET `content_loc6`='No doubt the fools that banished me are long dead. I shall take wing survey my demense. Pray to whatever gods you hold dear that we do not meet again.' WHERE `word_id` = 69; -- script_texts - content : entry=-1000172
UPDATE `trans_words` SET `content_loc6`='No mysterious fossil here... Ah, but my copy of Green Hills of Stranglethorn. What a good book!' WHERE `word_id` = 224; -- script_texts - content : entry=-1000330
UPDATE `trans_words` SET `content_loc6`='No one challanges the Wastewander nomads - not even robotic chickens! ATTACK!' WHERE `word_id` = 185; -- script_texts - content : entry=-1000291
UPDATE `trans_words` SET `content_loc6`='No... more... Feugen...' WHERE `word_id` = 1147; -- script_texts - content : entry=-1533028
UPDATE `trans_words` SET `content_loc6`='Noo... o...' WHERE `word_id` = 1236; -- script_texts - content : entry=-1533118
UPDATE `trans_words` SET `content_loc6`='NOOOOooooooo!' WHERE `word_id` = 70; -- script_texts - content : entry=-1000173
UPDATE `trans_words` SET `content_loc6`='Nope. didn\'t leave the fossil back here!' WHERE `word_id` = 230; -- script_texts - content : entry=-1000336
UPDATE `trans_words` SET `content_loc6`='NOW FOR YOU, INSECTS. BOLDLY YOU SAUGHT THE POWER OF RAGNAROS NOW YOU SHALL SEE IT FIRST HAND.' WHERE `word_id` = 994; -- script_texts - content : entry=-1409012
UPDATE `trans_words` SET `content_loc6`='Now I cut you!' WHERE `word_id` = 83; -- script_texts - content : entry=-1000186
UPDATE `trans_words` SET `content_loc6`='Now there is only one way out - to walk the lonely path of the damned.' WHERE `word_id` = 1260; -- script_texts - content : entry=-1533142
UPDATE `trans_words` SET `content_loc6`='Now this looks familiar. If we keep heading east, I think we can... Ahh, Wyvern on the attack!' WHERE `word_id` = 257; -- script_texts - content : entry=-1000363
UPDATE `trans_words` SET `content_loc6`='Now YOU feel pain!' WHERE `word_id` = 1153; -- script_texts - content : entry=-1533034
UPDATE `trans_words` SET `content_loc6`='NOW,STAGHELM! WE GO NOW! Prepare your magic!' WHERE `word_id` = 590; -- script_texts - content : entry=-1000752
UPDATE `trans_words` SET `content_loc6`='Objective acquired. Initiating security routines.' WHERE `word_id` = 86; -- script_texts - content : entry=-1000189
UPDATE `trans_words` SET `content_loc6`='Oh my! Look at this... all these candles. I\'m sure they\'re used for some terrible ritual or dark summoning. We best make haste.' WHERE `word_id` = 1282; -- script_texts - content : entry=-1001149
UPDATE `trans_words` SET `content_loc6`='Oh no! A $C is upon us!' WHERE `word_id` = 204; -- script_texts - content : entry=-1000310
UPDATE `trans_words` SET `content_loc6`='Oh! Now I\'m pissed!' WHERE `word_id` = 1297; -- script_texts - content : entry=-1230039
UPDATE `trans_words` SET `content_loc6`='Oh, it\'s on now! But you thought I\'d be alone too, huh?!' WHERE `word_id` = 745; -- script_texts - content : entry=-1000977
UPDATE `trans_words` SET `content_loc6`='OK boss, I get back to tree hitting.' WHERE `word_id` = 629; -- script_texts - content : entry=-1000795
UPDATE `trans_words` SET `content_loc6`='Ok, let\'s go!!' WHERE `word_id` = 731; -- script_texts - content : entry=-1000905
UPDATE `trans_words` SET `content_loc6`='Okay, okay... gimme a minute to rest now. You gone and beat me up good.' WHERE `word_id` = 250; -- script_texts - content : entry=-1000356
UPDATE `trans_words` SET `content_loc6`='One more minute! Hold on now, the ritual is about to take hold!' WHERE `word_id` = 856; -- script_texts - content : entry=-1129011
UPDATE `trans_words` SET `content_loc6`='Orb of Domination loses power and shuts off!' WHERE `word_id` = 1045; -- script_texts - content : entry=-1469035
UPDATE `trans_words` SET `content_loc6`='Our preparations continue as planned master.' WHERE `word_id` = 1202; -- script_texts - content : entry=-1533084
UPDATE `trans_words` SET `content_loc6`='Our time is at an end $N. I would wish you luck, if such a thing existed.' WHERE `word_id` = 125; -- script_texts - content : entry=-1000230
UPDATE `trans_words` SET `content_loc6`='Overlord Wyrmthalak calls for help!' WHERE `word_id` = 1327; -- script_texts - content : entry=-1999926
UPDATE `trans_words` SET `content_loc6`='Paladins, I\'ve heard you have many lives. Show me.' WHERE `word_id` = 1027; -- script_texts - content : entry=-1469017
UPDATE `trans_words` SET `content_loc6`='Perhaps they will come to their senses, and run away as fast as they can!' WHERE `word_id` = 1179; -- script_texts - content : entry=-1533060
UPDATE `trans_words` SET `content_loc6`='Physical threat detected! Evasive action! CLUCK!' WHERE `word_id` = 182; -- script_texts - content : entry=-1000288
UPDATE `trans_words` SET `content_loc6`='Pitful predictable mortals... You know not what you have done! The master\'s will fulfilled. The Moonglade shall be destroyed and Malfurion along with it!' WHERE `word_id` = 513; -- script_texts - content : entry=-1000675
UPDATE `trans_words` SET `content_loc6`='Please, light this while I am channeling' WHERE `word_id` = 547; -- script_texts - content : entry=-1000709
UPDATE `trans_words` SET `content_loc6`='Please, nooo!' WHERE `word_id` = 1158; -- script_texts - content : entry=-1533039
UPDATE `trans_words` SET `content_loc6`='Pleeease!' WHERE `word_id` = 1155; -- script_texts - content : entry=-1533036
UPDATE `trans_words` SET `content_loc6`='Prepare for the return of the ancient ones!' WHERE `word_id` = 1084; -- script_texts - content : entry=-1531006
UPDATE `trans_words` SET `content_loc6`='Prepare to embrace oblivion!' WHERE `word_id` = 1098; -- script_texts - content : entry=-1531020
UPDATE `trans_words` SET `content_loc6`='Prepare to meet your doom at the hands of Ragnaros\' most powerful servant!' WHERE `word_id` = 1322; -- script_texts - content : entry=-1230065
UPDATE `trans_words` SET `content_loc6`='Prepare yourselves. Silverwing is just around the bend.' WHERE `word_id` = 14; -- script_texts - content : entry=-1000108
UPDATE `trans_words` SET `content_loc6`='PRIDE HERALDS THE END OF YOUR WORLD. COME, MORTALS! FACE THE WRATH OF THE SOULFLAYER!' WHERE `word_id` = 956; -- script_texts - content : entry=-1309020
UPDATE `trans_words` SET `content_loc6`='Protect the city at all costs!' WHERE `word_id` = 1068; -- script_texts - content : entry=-1509021
UPDATE `trans_words` SET `content_loc6`='Puny $R wanna fight %s? Me beat you! Me boss here!' WHERE `word_id` = 391; -- script_texts - content : entry=-1000499
UPDATE `trans_words` SET `content_loc6`='Reckless mortal.' WHERE `word_id` = 810; -- script_texts - content : entry=-1070004
UPDATE `trans_words` SET `content_loc6`='Reckless mortals, none may challenge the sons of the living flame!' WHERE `word_id` = 985; -- script_texts - content : entry=-1409003
UPDATE `trans_words` SET `content_loc6`='Remember, I need your help to properly channel. I will ask you to aid me several times in our path, so please be ready.' WHERE `word_id` = 577; -- script_texts - content : entry=-1000739
UPDATE `trans_words` SET `content_loc6`='Rin\'ji can see road now, $N. Rin\'ji knows the way home.' WHERE `word_id` = 301; -- script_texts - content : entry=-1000407
UPDATE `trans_words` SET `content_loc6`='Rivendare must die' WHERE `word_id` = 965; -- script_texts - content : entry=-1329001
UPDATE `trans_words` SET `content_loc6`='Run! They are coming.' WHERE `word_id` = 1044; -- script_texts - content : entry=-1469034
UPDATE `trans_words` SET `content_loc6`='Seek sanctuary in Hearthglen! It is our only hope!' WHERE `word_id` = 655; -- script_texts - content : entry=-1000821
UPDATE `trans_words` SET `content_loc6`='Shall be your undoing!' WHERE `word_id` = 1110; -- script_texts - content : entry=-1531032
UPDATE `trans_words` SET `content_loc6`='Shh... it will all be over soon.' WHERE `word_id` = 1127; -- script_texts - content : entry=-1533008
UPDATE `trans_words` SET `content_loc6`='Show our guest around Shattrath, will you? Keep an eye out for pickpockets in the lower city.' WHERE `word_id` = 381; -- script_texts - content : entry=-1000489
UPDATE `trans_words` SET `content_loc6`='Soon you will know the price of your meddling, mortals... The master is nearly whole... And when he rises, your world will be cease!' WHERE `word_id` = 1064; -- script_texts - content : entry=-1509017
UPDATE `trans_words` SET `content_loc6`='Soon... the world will tremble!' WHERE `word_id` = 1233; -- script_texts - content : entry=-1533115
UPDATE `trans_words` SET `content_loc6`='Spineless wretches! You will drown in rivers of blood!' WHERE `word_id` = 1082; -- script_texts - content : entry=-1531004
UPDATE `trans_words` SET `content_loc6`='Ssserenity..at lassst!' WHERE `word_id` = 937; -- script_texts - content : entry=-1309001
UPDATE `trans_words` SET `content_loc6`='Stop, make it stop!' WHERE `word_id` = 1156; -- script_texts - content : entry=-1533037
UPDATE `trans_words` SET `content_loc6`='Succumb to the endless dream, little ones. Let it comsume you!' WHERE `word_id` = 585; -- script_texts - content : entry=-1000747
UPDATE `trans_words` SET `content_loc6`='Sweep the leg! Do you have a problem with that?' WHERE `word_id` = 1241; -- script_texts - content : entry=-1533123
UPDATE `trans_words` SET `content_loc6`='Thank you $N. I will remember you always. You can find my strongbox in my camp, north of Stonard.' WHERE `word_id` = 463; -- script_texts - content : entry=-1000586
UPDATE `trans_words` SET `content_loc6`='Thank you for agreeing to help. Now, let\'s get out of here $N.' WHERE `word_id` = 23; -- script_texts - content : entry=-1000117
UPDATE `trans_words` SET `content_loc6`='Thank you for saving my life and bringing me back to safety, $N' WHERE `word_id` = 50; -- script_texts - content : entry=-1000144
UPDATE `trans_words` SET `content_loc6`='Thank you for you help, $N. I wish you well in your adventures.' WHERE `word_id` = 574; -- script_texts - content : entry=-1000736
UPDATE `trans_words` SET `content_loc6`='Thank you! I will run for safety immediately!' WHERE `word_id` = 928; -- script_texts - content : entry=-1230032
UPDATE `trans_words` SET `content_loc6`='Thank you, dear $C, you just saved my life.' WHERE `word_id` = 84; -- script_texts - content : entry=-1000187
UPDATE `trans_words` SET `content_loc6`='Thanks to Egan' WHERE `word_id` = 964; -- script_texts - content : entry=-1329000
UPDATE `trans_words` SET `content_loc6`='Thanks you for help.' WHERE `word_id` = 1280; -- script_texts - content : entry=-1000962
UPDATE `trans_words` SET `content_loc6`='That kodo sure is a beauty. Wait a minute, where are my bifocals? Perhaps you should inspect the beast for me.' WHERE `word_id` = 244; -- script_texts - content : entry=-1000350
UPDATE `trans_words` SET `content_loc6`='That was a close one! Well, let\'s get going, it\'s still a ways to Ratchet!' WHERE `word_id` = 198; -- script_texts - content : entry=-1000304
UPDATE `trans_words` SET `content_loc6`='The Affray has begun. $N, get ready to fight!' WHERE `word_id` = 30; -- script_texts - content : entry=-1000124
UPDATE `trans_words` SET `content_loc6`='The Affray is over.' WHERE `word_id` = 33; -- script_texts - content : entry=-1000127
UPDATE `trans_words` SET `content_loc6`='The demon is loose! Quickly we must restrain him!' WHERE `word_id` = 1007; -- script_texts - content : entry=-1429000
UPDATE `trans_words` SET `content_loc6`='The entrance is hidden here in Moonbrook. Keep your eyes peeled for thieves. They want me dead.' WHERE `word_id` = 8; -- script_texts - content : entry=-1000102
UPDATE `trans_words` SET `content_loc6`='The feast of souls begin now...' WHERE `word_id` = 1096; -- script_texts - content : entry=-1531018
UPDATE `trans_words` SET `content_loc6`='The grasp of the Old Gods is unmoving. He is consumed by their dark thoughts... I... I... I cannot... cannot channel much longer... Elune aide me.' WHERE `word_id` = 531; -- script_texts - content : entry=-1000693
UPDATE `trans_words` SET `content_loc6`='The king is dead - OH NOES! Summon Mizzle da Crafty! He knows what to do next!' WHERE `word_id` = 337438; -- script_texts - content : entry=-1429003
UPDATE `trans_words` SET `content_loc6`='The master has fallen! Avenge him my brethren!' WHERE `word_id` = 871; -- script_texts - content : entry=-1189035
UPDATE `trans_words` SET `content_loc6`='The master... will avenge me!' WHERE `word_id` = 1135; -- script_texts - content : entry=-1533016
UPDATE `trans_words` SET `content_loc6`='The monster got what he deserved.' WHERE `word_id` = 868; -- script_texts - content : entry=-1189015
UPDATE `trans_words` SET `content_loc6`='The naaru accepted the defectors, who would become known as the Scryers; their dwelling lies in the platform above. Only those initiated with the Scryers are allowed there.' WHERE `word_id` = 142; -- script_texts - content : entry=-1000247
UPDATE `trans_words` SET `content_loc6`='The only thing hurt is your pride, lad! Buck up!' WHERE `word_id` = 498; -- script_texts - content : entry=-1000651
UPDATE `trans_words` SET `content_loc6`='The power of Necrotic Aura begins to wane!' WHERE `word_id` = 1262; -- script_texts - content : entry=-1533144
UPDATE `trans_words` SET `content_loc6`='The priesthood, known as the Aldor, quickly regained its strength as word spread that the naaru had returned and reconstruction soon began. The ruined temple is now used as an infirmary for injured refugees.' WHERE `word_id` = 136; -- script_texts - content : entry=-1000241
UPDATE `trans_words` SET `content_loc6`='The rift will be opened there, above the Lake Elun\'ara. Prepare yourself, $N. Eranikus entry into our world will be wrought with chaos and strife.' WHERE `word_id` = 509; -- script_texts - content : entry=-1000671
UPDATE `trans_words` SET `content_loc6`='The runes of warding have been destroyed! Hunt down the infedels my bretheren.' WHERE `word_id` = 986; -- script_texts - content : entry=-1409004
UPDATE `trans_words` SET `content_loc6`='The screams of the dying will fill the air. A symphony of terror is about to begin!' WHERE `word_id` = 1083; -- script_texts - content : entry=-1531005
UPDATE `trans_words` SET `content_loc6`='The time for practice is over! Show me what you\'ve learned!' WHERE `word_id` = 1246; -- script_texts - content : entry=-1533128
UPDATE `trans_words` SET `content_loc6`='There he continues to wage war on Illidan with the assistance of the Aldor and the Scryers. The two factions have not given up on their old feuds, though.' WHERE `word_id` = 147; -- script_texts - content : entry=-1000252
UPDATE `trans_words` SET `content_loc6`='There is but one duty that remains' WHERE `word_id` = 598; -- script_texts - content : entry=-1000760
UPDATE `trans_words` SET `content_loc6`='This part of forest are very danger for us. We must be a careful!' WHERE `word_id` = 742; -- script_texts - content : entry=-1000959
UPDATE `trans_words` SET `content_loc6`='This timeway is currently collapsing. What that may hold for the past, present and future is currently unknown...' WHERE `word_id` = 122; -- script_texts - content : entry=-1000227
UPDATE `trans_words` SET `content_loc6`='This timeway is in great disarray! We have agents inside right now attempting to restore order. What information I have indicates that Thrall\'s freedom is in jeopardy. A malevolent organization known as the Infinite Dragonflight is trying to prevent his escape. I fear without outside assistance, all will be lost.' WHERE `word_id` = 120; -- script_texts - content : entry=-1000225
UPDATE `trans_words` SET `content_loc6`='This will be a though fight, $N. Follow me closely.' WHERE `word_id` = 394; -- script_texts - content : entry=-1000502
UPDATE `trans_words` SET `content_loc6`='Thread analyzed! Activating combat plan beta! CLUCK!' WHERE `word_id` = 183; -- script_texts - content : entry=-1000289
UPDATE `trans_words` SET `content_loc6`='Three minutes left -- I can feel the energy starting to build! Keep up the solid defense!' WHERE `word_id` = 854; -- script_texts - content : entry=-1129009
UPDATE `trans_words` SET `content_loc6`='Time to teach you a lesson in manners, little $Gboy:girl;!' WHERE `word_id` = 168; -- script_texts - content : entry=-1000274
UPDATE `trans_words` SET `content_loc6`='To decorate our halls!' WHERE `word_id` = 1103; -- script_texts - content : entry=-1531025
UPDATE `trans_words` SET `content_loc6`='To my side, brothers. For the makers!' WHERE `word_id` = 809; -- script_texts - content : entry=-1070003
UPDATE `trans_words` SET `content_loc6`='To your posts. Defend the city.' WHERE `word_id` = 1070; -- script_texts - content : entry=-1509023
UPDATE `trans_words` SET `content_loc6`='TOO SOON! YOU HAVE AWAKENED ME TOO SOON, EXECUTUS! WHAT IS THE MEANING OF THIS INTRUSION?' WHERE `word_id` = 991; -- script_texts - content : entry=-1409009
UPDATE `trans_words` SET `content_loc6`='Torloth your master calls!' WHERE `word_id` = 431; -- script_texts - content : entry=-1000539
UPDATE `trans_words` SET `content_loc6`='Tou... che!' WHERE `word_id` = 1169; -- script_texts - content : entry=-1533050
UPDATE `trans_words` SET `content_loc6`='Tremble! The end is upon you.' WHERE `word_id` = 1080; -- script_texts - content : entry=-1531002
UPDATE `trans_words` SET `content_loc6`='Tresspassers will be terminated.' WHERE `word_id` = 1071; -- script_texts - content : entry=-1509024
UPDATE `trans_words` SET `content_loc6`='Try to take better care of yourself, Quinn. You were lucky this time.' WHERE `word_id` = 212; -- script_texts - content : entry=-1000318
UPDATE `trans_words` SET `content_loc6`='Ughhh... I hurt. Can you help me?' WHERE `word_id` = 79; -- script_texts - content : entry=-1000182
UPDATE `trans_words` SET `content_loc6`='Use my shinies...make weather good again...make undead things go away.' WHERE `word_id` = 473; -- script_texts - content : entry=-1000615
UPDATE `trans_words` SET `content_loc6`='Very well... warriors of the frozen wastes, rise up! I command you to fight, kill, and die for your master. Let none survive...' WHERE `word_id` = 1222; -- script_texts - content : entry=-1533104
UPDATE `trans_words` SET `content_loc6`='Violence! Property damage! None shall pass!!' WHERE `word_id` = 1298; -- script_texts - content : entry=-1230040
UPDATE `trans_words` SET `content_loc6`='Warning! %s emergency shutdown process initiated by $N. Shutdown will complete in two minutes.' WHERE `word_id` = 106; -- script_texts - content : entry=-1000211
UPDATE `trans_words` SET `content_loc6`='Warriors! Captains! Continue the fight!' WHERE `word_id` = 1061; -- script_texts - content : entry=-1509014
UPDATE `trans_words` SET `content_loc6`='Was this fabled, Windsor? If it was death that you came for then the prophecy has been fulfilled. May your consciousness rot in the Twisting Nether. Finish the rest of these meddlesome insects, children. Bolvar, you have been a pleasureable puppet.' WHERE `word_id` = 701; -- script_texts - content : entry=-1000867
UPDATE `trans_words` SET `content_loc6`='We can overcome these foul creatures.' WHERE `word_id` = 626; -- script_texts - content : entry=-1000792
UPDATE `trans_words` SET `content_loc6`='We do not know if the Caverns of Time have always been accessible to mortals. Truly, it is impossible to tell as the Timeless One is in perpetual motion, changing our timeways as he sees fit. What you see now may very well not exist tomorrow. You may wake up and have no memory of this place.' WHERE `word_id` = 113; -- script_texts - content : entry=-1000218
UPDATE `trans_words` SET `content_loc6`='We leave, Torlok. I have only one request...' WHERE `word_id` = 646; -- script_texts - content : entry=-1000812
UPDATE `trans_words` SET `content_loc6`='We made it! Thanks, $N. I couldn\'t have gotten without you.' WHERE `word_id` = 206; -- script_texts - content : entry=-1000312
UPDATE `trans_words` SET `content_loc6`='We must act quickly or shall be lost!' WHERE `word_id` = 578; -- script_texts - content : entry=-1000740
UPDATE `trans_words` SET `content_loc6`='We must go and gather with the other Disciplies. There is much work to be done before I can make another attempt to restore the Barrens. Farewell, brave souls!' WHERE `word_id` = 791; -- script_texts - content : entry=-1043016
UPDATE `trans_words` SET `content_loc6`='We will battle these fiends, together! Nighthaven\'s Defenders are also among us. They will fight to the death if asked. Now, quickly, we must drive these aberations back to the Nightmare. Destroy them all!' WHERE `word_id` = 523; -- script_texts - content : entry=-1000685
UPDATE `trans_words` SET `content_loc6`='We will locate the origin of the Nightmare through the fragments you collected, $N. From there, we will pull Eranikus through a rift in the Dream. Steel yourself, $C. We are inviting the embodiment of the Nightmare into our world.' WHERE `word_id` = 507; -- script_texts - content : entry=-1000669
UPDATE `trans_words` SET `content_loc6`='We will push him back, Anachronos. This is wow. Uphold your end of this task. Let not your hands falter as you seal our fates behind the barrier.' WHERE `word_id` = 584; -- script_texts - content : entry=-1000746
UPDATE `trans_words` SET `content_loc6`='Welcome to da great show friends! Step right up to die!' WHERE `word_id` = 950; -- script_texts - content : entry=-1309014
UPDATE `trans_words` SET `content_loc6`='Welcome, kind spirit. What has brought you to us?' WHERE `word_id` = 390; -- script_texts - content : entry=-1000498
UPDATE `trans_words` SET `content_loc6`='Well done, my minions. The mortals\' courage begins to wane! Now, let\'s see how they contend with the true Lord of Blackrock Spire!' WHERE `word_id` = 1017; -- script_texts - content : entry=-1469007
UPDATE `trans_words` SET `content_loc6`='Well then, let\'s get this started. The longer we\'re here, the more damage the undead could be doing back in Hilsbrad.' WHERE `word_id` = 733; -- script_texts - content : entry=-1000948
UPDATE `trans_words` SET `content_loc6`='Well, now or never I suppose. Remember, once we get to the road safety, return to Terenthis to let him know we escaped.' WHERE `word_id` = 624; -- script_texts - content : entry=-1000789
UPDATE `trans_words` SET `content_loc6`='What happened to... Patch...' WHERE `word_id` = 1139; -- script_texts - content : entry=-1533020
UPDATE `trans_words` SET `content_loc6`='What manner of trick is this, $R? If you seek to ambush me, I warn you I will not go down quietly!' WHERE `word_id` = 105; -- script_texts - content : entry=-1000210
UPDATE `trans_words` SET `content_loc6`='What say the elements, Torlok? I only hear silence.' WHERE `word_id` = 640; -- script_texts - content : entry=-1000806
UPDATE `trans_words` SET `content_loc6`='What was that?! Trey? TREY?' WHERE `word_id` = 1289; -- script_texts - content : entry=-1001156
UPDATE `trans_words` SET `content_loc6`='What, Mograine has fallen? You shall pay for this treachery!' WHERE `word_id` = 865; -- script_texts - content : entry=-1189008
UPDATE `trans_words` SET `content_loc6`='Where shall I begin? I cannot bother myself with a worm such as yourself. There is a world to be conquered!' WHERE `word_id` = 68; -- script_texts - content : entry=-1000171
UPDATE `trans_words` SET `content_loc6`='Which one shall I eat first? So difficult to choose... the all smell so delicious.' WHERE `word_id` = 1125; -- script_texts - content : entry=-1533006
UPDATE `trans_words` SET `content_loc6`='Who dares awaken Archaedas? Who dares the wrath of the makers!' WHERE `word_id` = 807; -- script_texts - content : entry=-1070001
UPDATE `trans_words` SET `content_loc6`='Who dares violate the sanctity of my domain? Be warned, all who trespass here are doomed.' WHERE `word_id` = 1208; -- script_texts - content : entry=-1533090
UPDATE `trans_words` SET `content_loc6`='Who you gonna call?' WHERE `word_id` = 966; -- script_texts - content : entry=-1329002
UPDATE `trans_words` SET `content_loc6`='Why don\'t we deal with you now, Hendel? Lady Proudmoore will speak for you back in the tower.' WHERE `word_id` = 305; -- script_texts - content : entry=-1000411
UPDATE `trans_words` SET `content_loc6`='WHY? Why did this happen to... to me? Where were you Tyrande? Where were you when I fell from the grace of Elune?' WHERE `word_id` = 533; -- script_texts - content : entry=-1000695
UPDATE `trans_words` SET `content_loc6`='Worthless $N! Your friends will join you soon enough!' WHERE `word_id` = 1021; -- script_texts - content : entry=-1469011
UPDATE `trans_words` SET `content_loc6`='YARRR! Swabie, what have ye done?! He\'s gone mad! Baton him down the hatches! Hoist the mast! ARRRR! Every man for hi\'self!' WHERE `word_id` = 220; -- script_texts - content : entry=-1000326
UPDATE `trans_words` SET `content_loc6`='Yes Torta. Whatever your heart desires...' WHERE `word_id` = 291; -- script_texts - content : entry=-1000397
UPDATE `trans_words` SET `content_loc6`='Yes, Lord Illidan, I would sacrifice to you this magnificent physique. On this day you will fall - another victim of Torloth...' WHERE `word_id` = 426; -- script_texts - content : entry=-1000534
UPDATE `trans_words` SET `content_loc6`='You are already dead.' WHERE `word_id` = 1112; -- script_texts - content : entry=-1531034
UPDATE `trans_words` SET `content_loc6`='You are certanly not your father, insect. Should it interest me, I would crush you with but a swipe of my claws. Turn Shan\'do Stormrage over to me and your pitiful life will be spared along with the lives of your people.' WHERE `word_id` = 516; -- script_texts - content : entry=-1000678
UPDATE `trans_words` SET `content_loc6`='You are mine now!' WHERE `word_id` = 1227; -- script_texts - content : entry=-1533109
UPDATE `trans_words` SET `content_loc6`='You are no challenge for the Crimson Sigil. Mind breakers, end this nonsense.' WHERE `word_id` = 429; -- script_texts - content : entry=-1000537
UPDATE `trans_words` SET `content_loc6`='You are not worth my time $N!' WHERE `word_id` = 268196; -- script_texts - content : entry=-1509015
UPDATE `trans_words` SET `content_loc6`='You are too late... I... must... OBEY!' WHERE `word_id` = 1148; -- script_texts - content : entry=-1533029
UPDATE `trans_words` SET `content_loc6`='You are weak.' WHERE `word_id` = 1117; -- script_texts - content : entry=-1531039
UPDATE `trans_words` SET `content_loc6`='You cannot be serious! We are severely understaffed and can barely keep this manaforge functional!' WHERE `word_id` = 35; -- script_texts - content : entry=-1000129
UPDATE `trans_words` SET `content_loc6`='YOU CANNOT DEFEAT THE LIVING FLAME! COME YOU MINIONS OF FIRE! COME FORTH YOU CREATURES OF HATE! YOUR MASTER CALLS!' WHERE `word_id` = 996; -- script_texts - content : entry=-1409014
UPDATE `trans_words` SET `content_loc6`='You die now!' WHERE `word_id` = 1152; -- script_texts - content : entry=-1533033
UPDATE `trans_words` SET `content_loc6`='You do not fight alone, %n! Together, we will banish this spawn of hellfire!' WHERE `word_id` = 637; -- script_texts - content : entry=-1000803
UPDATE `trans_words` SET `content_loc6`='You have my word that I shall find a use for your body after I\'ve killed you, Kinelory.' WHERE `word_id` = 736; -- script_texts - content : entry=-1000951
UPDATE `trans_words` SET `content_loc6`='You kept me in the cell for too long, monster!' WHERE `word_id` = 1290; -- script_texts - content : entry=-1001157
UPDATE `trans_words` SET `content_loc6`='You must protect me from monsters, who are living in this forest!' WHERE `word_id` = 741; -- script_texts - content : entry=-1000958
UPDATE `trans_words` SET `content_loc6`='You only delay... the inevetable.' WHERE `word_id` = 1085; -- script_texts - content : entry=-1531007
UPDATE `trans_words` SET `content_loc6`='You should have stayed home!' WHERE `word_id` = 1242; -- script_texts - content : entry=-1533124
UPDATE `trans_words` SET `content_loc6`='You will betray your friends.' WHERE `word_id` = 1115; -- script_texts - content : entry=-1531037
UPDATE `trans_words` SET `content_loc6`='You will die.' WHERE `word_id` = 1116; -- script_texts - content : entry=-1531038
UPDATE `trans_words` SET `content_loc6`='You will do as ordered. Manaforge Duro has come under heavy attack by mana creatures and the situation is out of control. Failure to comply will not be tolerated!' WHERE `word_id` = 36; -- script_texts - content : entry=-1000130
UPDATE `trans_words` SET `content_loc6`='You! Enter the fray!' WHERE `word_id` = 31; -- script_texts - content : entry=-1000125
UPDATE `trans_words` SET `content_loc6`='You...are next!' WHERE `word_id` = 1229; -- script_texts - content : entry=-1533111
UPDATE `trans_words` SET `content_loc6`='You\'ll pay for forcing me to do this.' WHERE `word_id` = 1032; -- script_texts - content : entry=-1469022
UPDATE `trans_words` SET `content_loc6`='Your brash arrogance!' WHERE `word_id` = 1100; -- script_texts - content : entry=-1531022
UPDATE `trans_words` SET `content_loc6`='Your courage will fail.' WHERE `word_id` = 1113; -- script_texts - content : entry=-1531035
UPDATE `trans_words` SET `content_loc6`='Your efforts are utterly pointless, fools! You will never be able to defeat me!' WHERE `word_id` = 1320; -- script_texts - content : entry=-1230063
UPDATE `trans_words` SET `content_loc6`='Your friends will abandon you.' WHERE `word_id` = 1114; -- script_texts - content : entry=-1531036
UPDATE `trans_words` SET `content_loc6`='Your heart will explode.' WHERE `word_id` = 1118; -- script_texts - content : entry=-1531040
UPDATE `trans_words` SET `content_loc6`='Your old lives, your mortal desires, mean nothing. You are acolytes of the master now, and you will serve the cause without question! The greatest glory is to die in the master\'s service!' WHERE `word_id` = 1128; -- script_texts - content : entry=-1533009
UPDATE `trans_words` SET `content_loc6`='Your security measures have failed! See to this interruption immediately!' WHERE `word_id` = 1205; -- script_texts - content : entry=-1533087
UPDATE `trans_words` SET `content_loc6`='Your soul, is bound to me now!' WHERE `word_id` = 1218; -- script_texts - content : entry=-1533100
UPDATE `trans_words` SET `content_loc6`='Your victory shall be short lived. The days of both the Alliance and Horde are coming to an end. The next time we meet shall be the last.' WHERE `word_id` = 893; -- script_texts - content : entry=-1229018

SET NAMES 'latin1';
