-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc6`='A reagent for mage spells.' WHERE `word_id` = 12315; -- locales_item - description : entry=5517
UPDATE `trans_words` SET `content_loc6`='Alex\'s Ring of Audacity' WHERE `word_id` = 16991; -- locales_item - name : entry=12947
UPDATE `trans_words` SET `content_loc6`='Alex\'s Test Beatdown Staff' WHERE `word_id` = 21820; -- locales_item - name : entry=19879
UPDATE `trans_words` SET `content_loc6`='Ankh' WHERE `word_id` = 20154; -- locales_item - name : entry=17030
UPDATE `trans_words` SET `content_loc6`='Archeus' WHERE `word_id` = 9530; -- locales_item - name : entry=2000
UPDATE `trans_words` SET `content_loc6`='Bullova' WHERE `word_id` = 9897; -- locales_item - name : entry=2523
UPDATE `trans_words` SET `content_loc6`='Codex of Flash Heal' WHERE `word_id` = 14418; -- locales_item - name : entry=8964
UPDATE `trans_words` SET `content_loc6`='Counts as an Air, Earth, Fire, and Water totem.' WHERE `word_id` = 23479; -- locales_item - description : entry=22345
UPDATE `trans_words` SET `content_loc6`='Diet McWeaksauce' WHERE `word_id` = 24081; -- locales_item - name : entry=23578
UPDATE `trans_words` SET `content_loc6`='Draco-Incarcinatrix 900' WHERE `word_id` = 16552; -- locales_item - name : entry=12284
UPDATE `trans_words` SET `content_loc6`='Engraved with the words \'For years of service: -EVC.\'' WHERE `word_id` = 9700; -- locales_item - description : entry=2239
UPDATE `trans_words` SET `content_loc6`='Espadon' WHERE `word_id` = 9549; -- locales_item - name : entry=2024
UPDATE `trans_words` SET `content_loc6`='Explosive Shell' WHERE `word_id` = 11998; -- locales_item - name : entry=5105
UPDATE `trans_words` SET `content_loc6`='-Feralas' WHERE `word_id` = 22588; -- locales_item - description : entry=21148
UPDATE `trans_words` SET `content_loc6`='Flamberge' WHERE `word_id` = 9895; -- locales_item - name : entry=2521
UPDATE `trans_words` SET `content_loc6`='Food for the Mind' WHERE `word_id` = 24082; -- locales_item - description : entry=23578
UPDATE `trans_words` SET `content_loc6`='Francisca' WHERE `word_id` = 9904; -- locales_item - name : entry=2530
UPDATE `trans_words` SET `content_loc6`='Gladius' WHERE `word_id` = 9873; -- locales_item - name : entry=2488
UPDATE `trans_words` SET `content_loc6`='Glaive of the Defender' WHERE `word_id` = 23918; -- locales_item - name : entry=23051
UPDATE `trans_words` SET `content_loc6`='Glyphic Rune' WHERE `word_id` = 14757; -- locales_item - name : entry=9572
UPDATE `trans_words` SET `content_loc6`='Gor\'tesh\'s severed head, propped up on a pike.' WHERE `word_id` = 15848; -- locales_item - description : entry=11079
UPDATE `trans_words` SET `content_loc6`='Gordok Inner Door Key' WHERE `word_id` = 20591; -- locales_item - name : entry=18268
UPDATE `trans_words` SET `content_loc6`='Jambiya' WHERE `word_id` = 9669; -- locales_item - name : entry=2207
UPDATE `trans_words` SET `content_loc6`='James\' Key' WHERE `word_id` = 20248; -- locales_item - name : entry=17262
UPDATE `trans_words` SET `content_loc6`='Jom Gabbar' WHERE `word_id` = 24079; -- locales_item - name : entry=23570
UPDATE `trans_words` SET `content_loc6`='Key to Salem\'s Chest' WHERE `word_id` = 20246; -- locales_item - name : entry=17242
UPDATE `trans_words` SET `content_loc6`='Kris' WHERE `word_id` = 9671; -- locales_item - name : entry=2209
UPDATE `trans_words` SET `content_loc6`='Lok\'amir il Romathis' WHERE `word_id` = 21506; -- locales_item - name : entry=19360
UPDATE `trans_words` SET `content_loc6`='Looks great. Less filling.' WHERE `word_id` = 16992; -- locales_item - description : entry=12947
UPDATE `trans_words` SET `content_loc6`='Master Key to the Depths, Courtesy of F.F.F.' WHERE `word_id` = 15831; -- locales_item - description : entry=11000
UPDATE `trans_words` SET `content_loc6`='Olmann Sewar' WHERE `word_id` = 11192; -- locales_item - name : entry=4116
UPDATE `trans_words` SET `content_loc6`='Only ONE May Rise... (and consequently, only ONE may loot this head)' WHERE `word_id` = 22115; -- locales_item - description : entry=20383
UPDATE `trans_words` SET `content_loc6`='Opens Dark Cleric Salem\'s Chest' WHERE `word_id` = 20247; -- locales_item - description : entry=17242
UPDATE `trans_words` SET `content_loc6`='Opens the stolen chest from the Cathedral of Light' WHERE `word_id` = 20249; -- locales_item - description : entry=17262
UPDATE `trans_words` SET `content_loc6`='Quel\'Serrar' WHERE `word_id` = 20658; -- locales_item - name : entry=18348
UPDATE `trans_words` SET `content_loc6`='Reins of the Spotted Nightsaber' WHERE `word_id` = 14355; -- locales_item - name : entry=8628
UPDATE `trans_words` SET `content_loc6`='Ring of Critical Testing 2' WHERE `word_id` = 21161; -- locales_item - name : entry=18970
UPDATE `trans_words` SET `content_loc6`='Rondel' WHERE `word_id` = 9908; -- locales_item - name : entry=2534
UPDATE `trans_words` SET `content_loc6`='Serathil' WHERE `word_id` = 17045; -- locales_item - name : entry=13015
UPDATE `trans_words` SET `content_loc6`='Shadowforge Key' WHERE `word_id` = 15830; -- locales_item - name : entry=11000
UPDATE `trans_words` SET `content_loc6`='Shinsollo' WHERE `word_id` = 19494; -- locales_item - name : entry=16171
UPDATE `trans_words` SET `content_loc6`='Skeleton Key' WHERE `word_id` = 17505; -- locales_item - name : entry=13704
UPDATE `trans_words` SET `content_loc6`='Tabar' WHERE `word_id` = 9089; -- locales_item - name : entry=1196
UPDATE `trans_words` SET `content_loc6`='Talisman of Binding Shard' WHERE `word_id` = 20467; -- locales_item - name : entry=17782
UPDATE `trans_words` SET `content_loc6`='Teaches Inner Fire (Rank 2).' WHERE `word_id` = 14419; -- locales_item - description : entry=8964
UPDATE `trans_words` SET `content_loc6`='Test Arcane Res Legs Mail' WHERE `word_id` = 19488; -- locales_item - name : entry=16165
UPDATE `trans_words` SET `content_loc6`='Test Stationery' WHERE `word_id` = 14090; -- locales_item - name : entry=8164
UPDATE `trans_words` SET `content_loc6`='The completed amulet of Rakh\'likh.' WHERE `word_id` = 15727; -- locales_item - description : entry=10757
UPDATE `trans_words` SET `content_loc6`='The McWeaksauce Classic' WHERE `word_id` = 24083; -- locales_item - name : entry=23579
UPDATE `trans_words` SET `content_loc6`='The Original.' WHERE `word_id` = 24084; -- locales_item - description : entry=23579
UPDATE `trans_words` SET `content_loc6`='This blade is dimensional. It appears to be fading from this plane of existence.' WHERE `word_id` = 23739; -- locales_item - description : entry=22736
UPDATE `trans_words` SET `content_loc6`='Tomahawk' WHERE `word_id` = 9875; -- locales_item - name : entry=2490
UPDATE `trans_words` SET `content_loc6`='Vendetta' WHERE `word_id` = 8903; -- locales_item - name : entry=776
UPDATE `trans_words` SET `content_loc6`='Viewing Room Key' WHERE `word_id` = 17548; -- locales_item - name : entry=13873
UPDATE `trans_words` SET `content_loc6`='Warsong Mark of Honor' WHERE `word_id` = 21461; -- locales_item - name : entry=19322
UPDATE `trans_words` SET `content_loc6`='Work Shirt' WHERE `word_id` = 10340; -- locales_item - name : entry=3148

SET NAMES 'latin1';
