-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc8`='Alex\'s Test Beatdown Staff' WHERE `word_id` = 21820; -- locales_item - name : entry=19879
UPDATE `trans_words` SET `content_loc8`='Codex of Flash Heal' WHERE `word_id` = 14418; -- locales_item - name : entry=8964
UPDATE `trans_words` SET `content_loc8`='Glaive of the Defender' WHERE `word_id` = 23918; -- locales_item - name : entry=23051
UPDATE `trans_words` SET `content_loc8`='Glyphic Rune' WHERE `word_id` = 14757; -- locales_item - name : entry=9572
UPDATE `trans_words` SET `content_loc8`='Looks great. Less filling.' WHERE `word_id` = 16992; -- locales_item - description : entry=12947
UPDATE `trans_words` SET `content_loc8`='Ring of Critical Testing 2' WHERE `word_id` = 21161; -- locales_item - name : entry=18970
UPDATE `trans_words` SET `content_loc8`='Teaches Inner Fire (Rank 2).' WHERE `word_id` = 14419; -- locales_item - description : entry=8964
UPDATE `trans_words` SET `content_loc8`='Teaches Ritual of Doom.' WHERE `word_id` = 11219; -- locales_item - description : entry=4213
UPDATE `trans_words` SET `content_loc8`='Teaches you how to make a Major Troll\'s Blood Potion.' WHERE `word_id` = 21955; -- locales_item - description : entry=20014

SET NAMES 'latin1';
