-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc8`='[DND]Cage Base' WHERE `word_id` = 116798; -- locales_gameobject - name : entry=185301
UPDATE `trans_words` SET `content_loc8`='[DND]Dragon Totem' WHERE `word_id` = 116801; -- locales_gameobject - name : entry=185314
UPDATE `trans_words` SET `content_loc8`='Ahn\'Qiraj Door 01' WHERE `word_id` = 116911; -- locales_gameobject - name : entry=210347
UPDATE `trans_words` SET `content_loc8`='Ahn\'Qiraj Gong' WHERE `word_id` = 115700; -- locales_gameobject - name : entry=177223
UPDATE `trans_words` SET `content_loc8`='Ahn\'Qiraj Ossirian Crystal' WHERE `word_id` = 116901; -- locales_gameobject - name : entry=210312
UPDATE `trans_words` SET `content_loc8`='Ahn\'Qiraj Sand Trap' WHERE `word_id` = 116905; -- locales_gameobject - name : entry=210339
UPDATE `trans_words` SET `content_loc8`='Altar of Hyjal' WHERE `word_id` = 116916; -- locales_gameobject - name : entry=211019
UPDATE `trans_words` SET `content_loc8`='Asheron\'s Tome of Summoning' WHERE `word_id` = 116915; -- locales_gameobject - name : entry=211018
UPDATE `trans_words` SET `content_loc8`='Black Portal' WHERE `word_id` = 116919; -- locales_gameobject - name : entry=211023
UPDATE `trans_words` SET `content_loc8`='Bowel with Boobles' WHERE `word_id` = 115556; -- locales_gameobject - name : entry=176157
UPDATE `trans_words` SET `content_loc8`='Captain Sanders Chest' WHERE `word_id` = 114196; -- locales_gameobject - name : entry=38
UPDATE `trans_words` SET `content_loc8`='Cat Figurine Trap' WHERE `word_id` = 117014; -- locales_gameobject - name : entry=12653
UPDATE `trans_words` SET `content_loc8`='CavernDoor01' WHERE `word_id` = 115664; -- locales_gameobject - name : entry=176996
UPDATE `trans_words` SET `content_loc8`='Commander\'s Tent' WHERE `word_id` = 116918; -- locales_gameobject - name : entry=211022
UPDATE `trans_words` SET `content_loc8`='Communication Crystal' WHERE `word_id` = 116902; -- locales_gameobject - name : entry=210327
UPDATE `trans_words` SET `content_loc8`='Dining Bench' WHERE `word_id` = 114774; -- locales_gameobject - name : entry=36990
UPDATE `trans_words` SET `content_loc8`='Doodad_Ahn_Qiraj_DoorRoots01' WHERE `word_id` = 115552; -- locales_gameobject - name : entry=176147
UPDATE `trans_words` SET `content_loc8`='Doodad_Ahn_Qiraj_DoorRunes01' WHERE `word_id` = 115553; -- locales_gameobject - name : entry=176148
UPDATE `trans_words` SET `content_loc8`='Excavation Tent Pavillion' WHERE `word_id` = 116900; -- locales_gameobject - name : entry=210286
UPDATE `trans_words` SET `content_loc8`='Eye of Asheron' WHERE `word_id` = 116917; -- locales_gameobject - name : entry=211021
UPDATE `trans_words` SET `content_loc8`='Farmountain Maps' WHERE `word_id` = 114725; -- locales_gameobject - name : entry=26492
UPDATE `trans_words` SET `content_loc8`='Fel Orc Encampment Custom Area' WHERE `word_id` = 116892; -- locales_gameobject - name : entry=200000
UPDATE `trans_words` SET `content_loc8`='Fire on ground' WHERE `word_id` = 114820; -- locales_gameobject - name : entry=56809
UPDATE `trans_words` SET `content_loc8`='Fire With Boiling Water' WHERE `word_id` = 114910; -- locales_gameobject - name : entry=103773
UPDATE `trans_words` SET `content_loc8`='Flinthammer\'s Armorer and Clothier' WHERE `word_id` = 114741; -- locales_gameobject - name : entry=143332
UPDATE `trans_words` SET `content_loc8`='Floating Purple Crystal Broken 01' WHERE `word_id` = 116912; -- locales_gameobject - name : entry=210348
UPDATE `trans_words` SET `content_loc8`='Floating Red Crystal Broken 01' WHERE `word_id` = 116910; -- locales_gameobject - name : entry=210346
UPDATE `trans_words` SET `content_loc8`='Floating Red Crystal Broken 03' WHERE `word_id` = 116909; -- locales_gameobject - name : entry=210345
UPDATE `trans_words` SET `content_loc8`='Gadgetzan Auction' WHERE `word_id` = 115524; -- locales_gameobject - name : entry=175904
UPDATE `trans_words` SET `content_loc8`='Gastric Exit' WHERE `word_id` = 116913; -- locales_gameobject - name : entry=210349
UPDATE `trans_words` SET `content_loc8`='Giant Sea Turtle' WHERE `word_id` = 114653; -- locales_gameobject - name : entry=20820
UPDATE `trans_words` SET `content_loc8`='Giant Turtle' WHERE `word_id` = 114654; -- locales_gameobject - name : entry=20821
UPDATE `trans_words` SET `content_loc8`='Glyphed Crystal' WHERE `word_id` = 116904; -- locales_gameobject - name : entry=210337
UPDATE `trans_words` SET `content_loc8`='Gnomes' WHERE `word_id` = 114760; -- locales_gameobject - name : entry=32419
UPDATE `trans_words` SET `content_loc8`='Goblin Shredder Suit' WHERE `word_id` = 114603; -- locales_gameobject - name : entry=19582
UPDATE `trans_words` SET `content_loc8`='Grand Widow Faerlina Door' WHERE `word_id` = 116442; -- locales_gameobject - name : entry=181167
UPDATE `trans_words` SET `content_loc8`='Grave' WHERE `word_id` = 116927; -- locales_gameobject - name : entry=211065
UPDATE `trans_words` SET `content_loc8`='Graveyard Banner' WHERE `word_id` = 114539; -- locales_gameobject - name : entry=13756
UPDATE `trans_words` SET `content_loc8`='Guard Tower' WHERE `word_id` = 114649; -- locales_gameobject - name : entry=20816
UPDATE `trans_words` SET `content_loc8`='Hive Fireflies 01' WHERE `word_id` = 116906; -- locales_gameobject - name : entry=210341
UPDATE `trans_words` SET `content_loc8`='Hoofprints' WHERE `word_id` = 114667; -- locales_gameobject - name : entry=21015
UPDATE `trans_words` SET `content_loc8`='Industrial District' WHERE `word_id` = 114713; -- locales_gameobject - name : entry=25334
UPDATE `trans_words` SET `content_loc8`='IronForge Elevator' WHERE `word_id` = 114740; -- locales_gameobject - name : entry=32056
UPDATE `trans_words` SET `content_loc8`='Kre\'tal\'s Wagon' WHERE `word_id` = 116914; -- locales_gameobject - name : entry=211017
UPDATE `trans_words` SET `content_loc8`='Lair Exit' WHERE `word_id` = 116921; -- locales_gameobject - name : entry=211035
UPDATE `trans_words` SET `content_loc8`='Large x2 Fire' WHERE `word_id` = 116720; -- locales_gameobject - name : entry=184563
UPDATE `trans_words` SET `content_loc8`='Locked Cage' WHERE `word_id` = 115510; -- locales_gameobject - name : entry=175786
UPDATE `trans_words` SET `content_loc8`='Logs on fire' WHERE `word_id` = 116717; -- locales_gameobject - name : entry=184507
UPDATE `trans_words` SET `content_loc8`='Longtoo - Teapee' WHERE `word_id` = 114461; -- locales_gameobject - name : entry=3265
UPDATE `trans_words` SET `content_loc8`='Mage Quarters' WHERE `word_id` = 114373; -- locales_gameobject - name : entry=2188
UPDATE `trans_words` SET `content_loc8`='Market Walk' WHERE `word_id` = 114753; -- locales_gameobject - name : entry=32364
UPDATE `trans_words` SET `content_loc8`='Mephistroph\'s HellFire' WHERE `word_id` = 116929; -- locales_gameobject - name : entry=211084
UPDATE `trans_words` SET `content_loc8`='Midsummer Music Doodad' WHERE `word_id` = 116888; -- locales_gameobject - name : entry=188174
UPDATE `trans_words` SET `content_loc8`='Mysterious Monument' WHERE `word_id` = 116924; -- locales_gameobject - name : entry=211053
UPDATE `trans_words` SET `content_loc8`='New Year Alliance Hanging Banner 02' WHERE `word_id` = 116895; -- locales_gameobject - name : entry=210211
UPDATE `trans_words` SET `content_loc8`='New Year Alliance Hanging Banner' WHERE `word_id` = 116894; -- locales_gameobject - name : entry=210210
UPDATE `trans_words` SET `content_loc8`='New Year Alliance Standing Banner' WHERE `word_id` = 116898; -- locales_gameobject - name : entry=210214
UPDATE `trans_words` SET `content_loc8`='New Year Horde Hanging Banner 02' WHERE `word_id` = 116897; -- locales_gameobject - name : entry=210213
UPDATE `trans_words` SET `content_loc8`='New Year Horde Hanging Banner' WHERE `word_id` = 116896; -- locales_gameobject - name : entry=210212
UPDATE `trans_words` SET `content_loc8`='New Year Horde Standing Banner' WHERE `word_id` = 116899; -- locales_gameobject - name : entry=210215
UPDATE `trans_words` SET `content_loc8`='Night Elf Moon Well' WHERE `word_id` = 114651; -- locales_gameobject - name : entry=20818
UPDATE `trans_words` SET `content_loc8`='Orc Tower' WHERE `word_id` = 114648; -- locales_gameobject - name : entry=20812
UPDATE `trans_words` SET `content_loc8`='OUT OF ORDER! Use Postman instead - your GM\'s' WHERE `word_id` = 116053; -- locales_gameobject - name : entry=179963
UPDATE `trans_words` SET `content_loc8`='Pithwick\'s Bags and Supplies' WHERE `word_id` = 114724; -- locales_gameobject - name : entry=26491
UPDATE `trans_words` SET `content_loc8`='Player Housing' WHERE `word_id` = 114656; -- locales_gameobject - name : entry=20823
UPDATE `trans_words` SET `content_loc8`='Pull rope Bell' WHERE `word_id` = 115726; -- locales_gameobject - name : entry=177271
UPDATE `trans_words` SET `content_loc8`='PVP HOLIDAY GENERIC SIGNPOST' WHERE `word_id` = 116168; -- locales_gameobject - name : entry=180397
UPDATE `trans_words` SET `content_loc8`='Rail' WHERE `word_id` = 114872; -- locales_gameobject - name : entry=80024
UPDATE `trans_words` SET `content_loc8`='Rockwall Fence' WHERE `word_id` = 116926; -- locales_gameobject - name : entry=211064
UPDATE `trans_words` SET `content_loc8`='Sand Worm Rock Base' WHERE `word_id` = 116907; -- locales_gameobject - name : entry=210343
UPDATE `trans_words` SET `content_loc8`='Sarcophag' WHERE `word_id` = 116928; -- locales_gameobject - name : entry=211067
UPDATE `trans_words` SET `content_loc8`='Shopping Centre' WHERE `word_id` = 116893; -- locales_gameobject - name : entry=200001
UPDATE `trans_words` SET `content_loc8`='Silithus Crystal Formation 03' WHERE `word_id` = 116908; -- locales_gameobject - name : entry=210344
UPDATE `trans_words` SET `content_loc8`='SmallBrazier01' WHERE `word_id` = 116034; -- locales_gameobject - name : entry=179878
UPDATE `trans_words` SET `content_loc8`='SmallBrazier03' WHERE `word_id` = 116032; -- locales_gameobject - name : entry=179876
UPDATE `trans_words` SET `content_loc8`='SmallBrazier04' WHERE `word_id` = 116033; -- locales_gameobject - name : entry=179877
UPDATE `trans_words` SET `content_loc8`='SmallBrazier19' WHERE `word_id` = 116031; -- locales_gameobject - name : entry=179875
UPDATE `trans_words` SET `content_loc8`='SmallBrazier31' WHERE `word_id` = 116030; -- locales_gameobject - name : entry=179874
UPDATE `trans_words` SET `content_loc8`='Stand up Torch' WHERE `word_id` = 114559; -- locales_gameobject - name : entry=18047
UPDATE `trans_words` SET `content_loc8`='Stonebranch Herbalist' WHERE `word_id` = 114726; -- locales_gameobject - name : entry=26493
UPDATE `trans_words` SET `content_loc8`='Target' WHERE `word_id` = 114541; -- locales_gameobject - name : entry=13952
UPDATE `trans_words` SET `content_loc8`='Teleport-Stone to Hyjal' WHERE `word_id` = 116922; -- locales_gameobject - name : entry=211050
UPDATE `trans_words` SET `content_loc8`='Thane\'s Boots and Shoulderpads' WHERE `word_id` = 114355; -- locales_gameobject - name : entry=2151
UPDATE `trans_words` SET `content_loc8`='The Cheese Cutters' WHERE `word_id` = 114352; -- locales_gameobject - name : entry=2148
UPDATE `trans_words` SET `content_loc8`='The Commerce Ward' WHERE `word_id` = 114750; -- locales_gameobject - name : entry=32357
UPDATE `trans_words` SET `content_loc8`='The Seven Deadly Venoms' WHERE `word_id` = 114353; -- locales_gameobject - name : entry=2149
UPDATE `trans_words` SET `content_loc8`='The Wine Cask' WHERE `word_id` = 114347; -- locales_gameobject - name : entry=2130
UPDATE `trans_words` SET `content_loc8`='Thundershot Guns \'n Ammo' WHERE `word_id` = 114718; -- locales_gameobject - name : entry=26485
UPDATE `trans_words` SET `content_loc8`='Tree Stump' WHERE `word_id` = 116923; -- locales_gameobject - name : entry=211052
UPDATE `trans_words` SET `content_loc8`='Twilight Tablet' WHERE `word_id` = 116903; -- locales_gameobject - name : entry=210335
UPDATE `trans_words` SET `content_loc8`='unk' WHERE `word_id` = 114688; -- locales_gameobject - name : entry=21653
UPDATE `trans_words` SET `content_loc8`='Vault Door' WHERE `word_id` = 115704; -- locales_gameobject - name : entry=177237
UPDATE `trans_words` SET `content_loc8`='Wooden Board' WHERE `word_id` = 116718; -- locales_gameobject - name : entry=184515

SET NAMES 'latin1';
