-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc8`='$C, no hurt A-Me. A-Me good.' WHERE `word_id` = 343; -- script_texts - content : entry=-1000449
UPDATE `trans_words` SET `content_loc8`='%s casts Condemation on everyone!' WHERE `word_id` = 1275; -- script_texts - content : entry=-1533157
UPDATE `trans_words` SET `content_loc8`='%s collapses onto the ground.' WHERE `word_id` = 323; -- script_texts - content : entry=-1000429
UPDATE `trans_words` SET `content_loc8`='%s fades away after a long pause.' WHERE `word_id` = 327; -- script_texts - content : entry=-1000433
UPDATE `trans_words` SET `content_loc8`='%s has entered our world' WHERE `word_id` = 512; -- script_texts - content : entry=-1000674
UPDATE `trans_words` SET `content_loc8`='%s hisses' WHERE `word_id` = 706; -- script_texts - content : entry=-1000872
UPDATE `trans_words` SET `content_loc8`='%s is wholly consumed by the Light of Elune. Tranquility sets in over the Moonglade' WHERE `word_id` = 535; -- script_texts - content : entry=-1000697
UPDATE `trans_words` SET `content_loc8`='%s jumps into the moonwell and goes underwater...' WHERE `word_id` = 433; -- script_texts - content : entry=-1000541
UPDATE `trans_words` SET `content_loc8`='%s kneels down and pick up the amulet.' WHERE `word_id` = 93; -- script_texts - content : entry=-1000197
UPDATE `trans_words` SET `content_loc8`='%s looks at you unexpectadly.' WHERE `word_id` = 101; -- script_texts - content : entry=-1000205
UPDATE `trans_words` SET `content_loc8`='%s reaches into his pack and pulls out the encoded tablets...' WHERE `word_id` = 692; -- script_texts - content : entry=-1000858
UPDATE `trans_words` SET `content_loc8`='%s reads from the tablets. Unknown, unheard sounds flow through your consciousness' WHERE `word_id` = 695; -- script_texts - content : entry=-1000861
UPDATE `trans_words` SET `content_loc8`='%s refuses to die while its master is in trouble.' WHERE `word_id` = 984; -- script_texts - content : entry=-1409002
UPDATE `trans_words` SET `content_loc8`='%s spots a nearby Zombie to devour!' WHERE `word_id` = 1237; -- script_texts - content : entry=-1533119
UPDATE `trans_words` SET `content_loc8`='%s stands up after a short pause.' WHERE `word_id` = 324; -- script_texts - content : entry=-1000430
UPDATE `trans_words` SET `content_loc8`='%s starts pecking at the feed.' WHERE `word_id` = 102; -- script_texts - content : entry=-1000206
UPDATE `trans_words` SET `content_loc8`='%s strikes!' WHERE `word_id` = 1253; -- script_texts - content : entry=-1533135
UPDATE `trans_words` SET `content_loc8`='<Kel\'Thuzad cackles maniacally!>' WHERE `word_id` = 1216; -- script_texts - content : entry=-1533098
UPDATE `trans_words` SET `content_loc8`='<ScriptDev3 Text Entry Missing!>' WHERE `word_id` = 1; -- script_texts - content : entry=-1000000
UPDATE `trans_words` SET `content_loc8`='A $C! Slaying him would please the master. Attack!' WHERE `word_id` = 613; -- script_texts - content : entry=-1000775
UPDATE `trans_words` SET `content_loc8`='A %s joins the fight!' WHERE `word_id` = 1271; -- script_texts - content : entry=-1533153
UPDATE `trans_words` SET `content_loc8`='Ah! Fresh air at last! I never thought I\'d see the day.' WHERE `word_id` = 1287; -- script_texts - content : entry=-1001154
UPDATE `trans_words` SET `content_loc8`='Ah, $GPriest:Priestess; you came along just in time. I appreciate it.' WHERE `word_id` = 126; -- script_texts - content : entry=-1000231
UPDATE `trans_words` SET `content_loc8`='Ah, lambs to the slaughter!' WHERE `word_id` = 1104; -- script_texts - content : entry=-1531026
UPDATE `trans_words` SET `content_loc8`='All of Draenor shall quick beneath my feet! I will destroy this world and reshape it in my image!' WHERE `word_id` = 67; -- script_texts - content : entry=-1000170
UPDATE `trans_words` SET `content_loc8`='And try not to get lost this time...' WHERE `word_id` = 292; -- script_texts - content : entry=-1000398
UPDATE `trans_words` SET `content_loc8`='Attack and make them pay dearly!' WHERE `word_id` = 1058; -- script_texts - content : entry=-1509011
UPDATE `trans_words` SET `content_loc8`='Attack my sisters! The troll must not escape!' WHERE `word_id` = 298; -- script_texts - content : entry=-1000404
UPDATE `trans_words` SET `content_loc8`='Beware $N! Look to the west!' WHERE `word_id` = 724; -- script_texts - content : entry=-1000891
UPDATE `trans_words` SET `content_loc8`='BREAK YOU!' WHERE `word_id` = 1151; -- script_texts - content : entry=-1533032
UPDATE `trans_words` SET `content_loc8`='Breath your last!' WHERE `word_id` = 1063; -- script_texts - content : entry=-1509016
UPDATE `trans_words` SET `content_loc8`='Burn mortals! Burn for this transgression!' WHERE `word_id` = 988; -- script_texts - content : entry=-1409006
UPDATE `trans_words` SET `content_loc8`='Calm down lad, it\'s just a birdshot!' WHERE `word_id` = 497; -- script_texts - content : entry=-1000650
UPDATE `trans_words` SET `content_loc8`='Come, Zeliek, do not drive them out. Not before we\'ve had our fun.' WHERE `word_id` = 1164; -- script_texts - content : entry=-1533045
UPDATE `trans_words` SET `content_loc8`='Conserve your anger! Harness your rage! You will all have outlets for your frustration soon enough.' WHERE `word_id` = 1191; -- script_texts - content : entry=-1533072
UPDATE `trans_words` SET `content_loc8`='Cower mortals! The age of darkness is at hand.' WHERE `word_id` = 1079; -- script_texts - content : entry=-1531001
UPDATE `trans_words` SET `content_loc8`='Crush them! Drive them out!' WHERE `word_id` = 1059; -- script_texts - content : entry=-1509012
UPDATE `trans_words` SET `content_loc8`='D\'oh !' WHERE `word_id` = 337437; -- script_texts - content : entry=-1429004
UPDATE `trans_words` SET `content_loc8`='Death is close...' WHERE `word_id` = 1111; -- script_texts - content : entry=-1531033
UPDATE `trans_words` SET `content_loc8`='Destroy them, Torloth. Let lose their blood like a river upon this hallowed ground.' WHERE `word_id` = 427; -- script_texts - content : entry=-1000535
UPDATE `trans_words` SET `content_loc8`='DIE DEMON DOGS!' WHERE `word_id` = 1286; -- script_texts - content : entry=-1001153
UPDATE `trans_words` SET `content_loc8`='Do not hesitate! Destroy them!' WHERE `word_id` = 1060; -- script_texts - content : entry=-1509013
UPDATE `trans_words` SET `content_loc8`='Don\'t cross those beams!' WHERE `word_id` = 967; -- script_texts - content : entry=-1329003
UPDATE `trans_words` SET `content_loc8`='Don\'t leave me in here! Cause if you do I will find you!' WHERE `word_id` = 487; -- script_texts - content : entry=-1000631
UPDATE `trans_words` SET `content_loc8`='Don\'t make me angry. You won\'t like it when I\'m angry.' WHERE `word_id` = 955; -- script_texts - content : entry=-1309019
UPDATE `trans_words` SET `content_loc8`='Draw me to your web mistress Shadra. Unleash your venom!' WHERE `word_id` = 941; -- script_texts - content : entry=-1309005
UPDATE `trans_words` SET `content_loc8`='Emergency shutdown aborted.' WHERE `word_id` = 111; -- script_texts - content : entry=-1000216
UPDATE `trans_words` SET `content_loc8`='Enough prattling. Let them come! We shall grind their bones to dust.' WHERE `word_id` = 1190; -- script_texts - content : entry=-1533071
UPDATE `trans_words` SET `content_loc8`='Enough! I grow tired of these distractions!' WHERE `word_id` = 1225; -- script_texts - content : entry=-1533107
UPDATE `trans_words` SET `content_loc8`='Enough! Now you vermin shall feel the force of my birthright, the fury of the earth itself.' WHERE `word_id` = 1018; -- script_texts - content : entry=-1469008
UPDATE `trans_words` SET `content_loc8`='Fools, you think yourselves triumphant? You have only taken one step closer to the abyss!' WHERE `word_id` = 1209; -- script_texts - content : entry=-1533091
UPDATE `trans_words` SET `content_loc8`='For so long, I was lost... The Nightmare\'s corruption had consumed me... And now, you... all of you.. you have saved me. Released me from its grasp.' WHERE `word_id` = 538; -- script_texts - content : entry=-1000700
UPDATE `trans_words` SET `content_loc8`='Grark Lorkrub, you have been charged and found guilty of treason against Horde. How you plead is unimportant. High Executioner Nuzrak, step forward.' WHERE `word_id` = 717; -- script_texts - content : entry=-1000884
UPDATE `trans_words` SET `content_loc8`='HALT! There were...reports...of a...disturbance.' WHERE `word_id` = 1305; -- script_texts - content : entry=-1230048
UPDATE `trans_words` SET `content_loc8`='He will stop at nothing to get to Malfurion\'s physical manifistation. That must not happen... We must keep the beast occupied long enough for Tyrande to arrive.' WHERE `word_id` = 510; -- script_texts - content : entry=-1000672
UPDATE `trans_words` SET `content_loc8`='I am gathering a bogbean. It takes some time.' WHERE `word_id` = 744; -- script_texts - content : entry=-1000961
UPDATE `trans_words` SET `content_loc8`='I am ready, $N. Let\'s find my equipment and get out of here. I think I know where it is.' WHERE `word_id` = 1281; -- script_texts - content : entry=-1001148
UPDATE `trans_words` SET `content_loc8`='I am rejuvinated!' WHERE `word_id` = 1065; -- script_texts - content : entry=-1509018
UPDATE `trans_words` SET `content_loc8`='I bet Quae\'ll think this is important. She\'s pretty knowledgeable about these things--no expert, but knowledgable.' WHERE `word_id` = 739; -- script_texts - content : entry=-1000954
UPDATE `trans_words` SET `content_loc8`='I bet you\'re sorry now, aren\'t you?' WHERE `word_id` = 908; -- script_texts - content : entry=-1230012
UPDATE `trans_words` SET `content_loc8`='I don\'t think it can top the one time where he told us that he\'d heard that Artha\'s "cousin\'s" skeleton was frozen beneath a glacier in Winterspring. I\'ll never forgive you for that one, Letoll. I mean honestly... Artha\'s cousin?' WHERE `word_id` = 416; -- script_texts - content : entry=-1000524
UPDATE `trans_words` SET `content_loc8`='I DRAW CLOSER TO YOUR WORLD!' WHERE `word_id` = 847; -- script_texts - content : entry=-1109008
UPDATE `trans_words` SET `content_loc8`='I foresee no complications at this... wait! What is this!?' WHERE `word_id` = 1204; -- script_texts - content : entry=-1533086
UPDATE `trans_words` SET `content_loc8`='I heard about enough of yer sniveling. Shut yer fly trap \'afore I shut it for ye!' WHERE `word_id` = 1172; -- script_texts - content : entry=-1533053
UPDATE `trans_words` SET `content_loc8`='I swear. I didn\'t steal anything from you! Here, take some of my supplies, just go away!' WHERE `word_id` = 349; -- script_texts - content : entry=-1000455
UPDATE `trans_words` SET `content_loc8`='I think those weird bird guys were going to eat us. Gross!' WHERE `word_id` = 468; -- script_texts - content : entry=-1000591
UPDATE `trans_words` SET `content_loc8`='I want more ale! Give me more ale!' WHERE `word_id` = 1294; -- script_texts - content : entry=-1230036
UPDATE `trans_words` SET `content_loc8`='I will serve the master... in... death!' WHERE `word_id` = 1200; -- script_texts - content : entry=-1533081
UPDATE `trans_words` SET `content_loc8`='I...am...released! Perhaps it\'s not too late to' WHERE `word_id` = 1193; -- script_texts - content : entry=-1533074
UPDATE `trans_words` SET `content_loc8`='Intruders are destroying our eggs! Stop!!' WHERE `word_id` = 895; -- script_texts - content : entry=-1229020
UPDATE `trans_words` SET `content_loc8`='Intruders! More pawns of the Argent Dawn, no doubt. I already count one of their number among my prisoners. Withdraw from my domain before she is executed!' WHERE `word_id` = 973; -- script_texts - content : entry=-1329009
UPDATE `trans_words` SET `content_loc8`='Is that the best you can do? Do you really expect that you could defeat someone as awe inspiring as me?' WHERE `word_id` = 1318; -- script_texts - content : entry=-1230061
UPDATE `trans_words` SET `content_loc8`='IT BURNS! THE PAIN.. SEARING...' WHERE `word_id` = 532; -- script_texts - content : entry=-1000694
UPDATE `trans_words` SET `content_loc8`='It is good that you serve me so faithfully. Soon... all will serve the Lich King and in the end, you shall be rewarded. So long as you do not falter.' WHERE `word_id` = 1203; -- script_texts - content : entry=-1533085
UPDATE `trans_words` SET `content_loc8`='It\'s too late to turn away.' WHERE `word_id` = 1097; -- script_texts - content : entry=-1531019
UPDATE `trans_words` SET `content_loc8`='Join me brother, there is blood to be shed!' WHERE `word_id` = 1106; -- script_texts - content : entry=-1531028
UPDATE `trans_words` SET `content_loc8`='Khadgar himself is showing you around? You must have made a good impression, $N.' WHERE `word_id` = 387; -- script_texts - content : entry=-1000495
UPDATE `trans_words` SET `content_loc8`='Kill two monsters, who stay near Bogbean plant and then I gather a bogbean.' WHERE `word_id` = 743; -- script_texts - content : entry=-1000960
UPDATE `trans_words` SET `content_loc8`='Kneel, Grark' WHERE `word_id` = 716; -- script_texts - content : entry=-1000883
UPDATE `trans_words` SET `content_loc8`='Kolkar are the strongest!' WHERE `word_id` = 727; -- script_texts - content : entry=-1000894
UPDATE `trans_words` SET `content_loc8`='Kolkar invaders are retreating!' WHERE `word_id` = 726; -- script_texts - content : entry=-1000893
UPDATE `trans_words` SET `content_loc8`='Let none survive!' WHERE `word_id` = 1105; -- script_texts - content : entry=-1531027
UPDATE `trans_words` SET `content_loc8`='Let us leave Nighthave, hero. Seek me out at the grove.' WHERE `word_id` = 543; -- script_texts - content : entry=-1000705
UPDATE `trans_words` SET `content_loc8`='Let\'s go $N!' WHERE `word_id` = 609; -- script_texts - content : entry=-1000771
UPDATE `trans_words` SET `content_loc8`='Like a fly in a web.' WHERE `word_id` = 1099; -- script_texts - content : entry=-1531021
UPDATE `trans_words` SET `content_loc8`='Look brother, fresh blood!' WHERE `word_id` = 1107; -- script_texts - content : entry=-1531029
UPDATE `trans_words` SET `content_loc8`='My brother...NO!' WHERE `word_id` = 1102; -- script_texts - content : entry=-1531024
UPDATE `trans_words` SET `content_loc8`='My flame! Please don\'t take away my flame...' WHERE `word_id` = 1004; -- script_texts - content : entry=-1409022
UPDATE `trans_words` SET `content_loc8`='My lady, I am unworthy of your prayer. Truly, you are an angel of light. Please, assist me in returning to the barrow den so that I may return to the Dream. I like Malfurion, also have a love awaiting me... I must return to her... to protect her...' WHERE `word_id` = 540; -- script_texts - content : entry=-1000702
UPDATE `trans_words` SET `content_loc8`='My powers are renewed!' WHERE `word_id` = 1066; -- script_texts - content : entry=-1509019
UPDATE `trans_words` SET `content_loc8`='My powers return!' WHERE `word_id` = 1067; -- script_texts - content : entry=-1509020
UPDATE `trans_words` SET `content_loc8`='No doubt the fools that banished me are long dead. I shall take wing survey my demense. Pray to whatever gods you hold dear that we do not meet again.' WHERE `word_id` = 69; -- script_texts - content : entry=-1000172
UPDATE `trans_words` SET `content_loc8`='Noo... o...' WHERE `word_id` = 1236; -- script_texts - content : entry=-1533118
UPDATE `trans_words` SET `content_loc8`='NOOOOooooooo!' WHERE `word_id` = 70; -- script_texts - content : entry=-1000173
UPDATE `trans_words` SET `content_loc8`='NOW,STAGHELM! WE GO NOW! Prepare your magic!' WHERE `word_id` = 590; -- script_texts - content : entry=-1000752
UPDATE `trans_words` SET `content_loc8`='Oh my! Look at this... all these candles. I\'m sure they\'re used for some terrible ritual or dark summoning. We best make haste.' WHERE `word_id` = 1282; -- script_texts - content : entry=-1001149
UPDATE `trans_words` SET `content_loc8`='Oh no! A $C is upon us!' WHERE `word_id` = 204; -- script_texts - content : entry=-1000310
UPDATE `trans_words` SET `content_loc8`='Oh! Now I\'m pissed!' WHERE `word_id` = 1297; -- script_texts - content : entry=-1230039
UPDATE `trans_words` SET `content_loc8`='OK boss, I get back to tree hitting.' WHERE `word_id` = 629; -- script_texts - content : entry=-1000795
UPDATE `trans_words` SET `content_loc8`='Orb of Domination loses power and shuts off!' WHERE `word_id` = 1045; -- script_texts - content : entry=-1469035
UPDATE `trans_words` SET `content_loc8`='Our preparations continue as planned master.' WHERE `word_id` = 1202; -- script_texts - content : entry=-1533084
UPDATE `trans_words` SET `content_loc8`='Overlord Wyrmthalak calls for help!' WHERE `word_id` = 1327; -- script_texts - content : entry=-1999926
UPDATE `trans_words` SET `content_loc8`='Perhaps they will come to their senses, and run away as fast as they can!' WHERE `word_id` = 1179; -- script_texts - content : entry=-1533060
UPDATE `trans_words` SET `content_loc8`='Pitful predictable mortals... You know not what you have done! The master\'s will fulfilled. The Moonglade shall be destroyed and Malfurion along with it!' WHERE `word_id` = 513; -- script_texts - content : entry=-1000675
UPDATE `trans_words` SET `content_loc8`='Please, nooo!' WHERE `word_id` = 1158; -- script_texts - content : entry=-1533039
UPDATE `trans_words` SET `content_loc8`='Pleeease!' WHERE `word_id` = 1155; -- script_texts - content : entry=-1533036
UPDATE `trans_words` SET `content_loc8`='Prepare for the return of the ancient ones!' WHERE `word_id` = 1084; -- script_texts - content : entry=-1531006
UPDATE `trans_words` SET `content_loc8`='Prepare to embrace oblivion!' WHERE `word_id` = 1098; -- script_texts - content : entry=-1531020
UPDATE `trans_words` SET `content_loc8`='Prepare to meet your doom at the hands of Ragnaros\' most powerful servant!' WHERE `word_id` = 1322; -- script_texts - content : entry=-1230065
UPDATE `trans_words` SET `content_loc8`='Protect the city at all costs!' WHERE `word_id` = 1068; -- script_texts - content : entry=-1509021
UPDATE `trans_words` SET `content_loc8`='Run! They are coming.' WHERE `word_id` = 1044; -- script_texts - content : entry=-1469034
UPDATE `trans_words` SET `content_loc8`='Seek sanctuary in Hearthglen! It is our only hope!' WHERE `word_id` = 655; -- script_texts - content : entry=-1000821
UPDATE `trans_words` SET `content_loc8`='Shall be your undoing!' WHERE `word_id` = 1110; -- script_texts - content : entry=-1531032
UPDATE `trans_words` SET `content_loc8`='Soon you will know the price of your meddling, mortals... The master is nearly whole... And when he rises, your world will be cease!' WHERE `word_id` = 1064; -- script_texts - content : entry=-1509017
UPDATE `trans_words` SET `content_loc8`='Spineless wretches! You will drown in rivers of blood!' WHERE `word_id` = 1082; -- script_texts - content : entry=-1531004
UPDATE `trans_words` SET `content_loc8`='Thank you for agreeing to help. Now, let\'s get out of here $N.' WHERE `word_id` = 23; -- script_texts - content : entry=-1000117
UPDATE `trans_words` SET `content_loc8`='Thank you! I will run for safety immediately!' WHERE `word_id` = 928; -- script_texts - content : entry=-1230032
UPDATE `trans_words` SET `content_loc8`='Thank you, dear $C, you just saved my life.' WHERE `word_id` = 84; -- script_texts - content : entry=-1000187
UPDATE `trans_words` SET `content_loc8`='Thanks you for help.' WHERE `word_id` = 1280; -- script_texts - content : entry=-1000962
UPDATE `trans_words` SET `content_loc8`='That was a close one! Well, let\'s get going, it\'s still a ways to Ratchet!' WHERE `word_id` = 198; -- script_texts - content : entry=-1000304
UPDATE `trans_words` SET `content_loc8`='The demon is loose! Quickly we must restrain him!' WHERE `word_id` = 1007; -- script_texts - content : entry=-1429000
UPDATE `trans_words` SET `content_loc8`='The feast of souls begin now...' WHERE `word_id` = 1096; -- script_texts - content : entry=-1531018
UPDATE `trans_words` SET `content_loc8`='The grasp of the Old Gods is unmoving. He is consumed by their dark thoughts... I... I... I cannot... cannot channel much longer... Elune aide me.' WHERE `word_id` = 531; -- script_texts - content : entry=-1000693
UPDATE `trans_words` SET `content_loc8`='The king is dead - OH NOES! Summon Mizzle da Crafty! He knows what to do next!' WHERE `word_id` = 337438; -- script_texts - content : entry=-1429003
UPDATE `trans_words` SET `content_loc8`='The master has fallen! Avenge him my brethren!' WHERE `word_id` = 871; -- script_texts - content : entry=-1189035
UPDATE `trans_words` SET `content_loc8`='The monster got what he deserved.' WHERE `word_id` = 868; -- script_texts - content : entry=-1189015
UPDATE `trans_words` SET `content_loc8`='The only thing hurt is your pride, lad! Buck up!' WHERE `word_id` = 498; -- script_texts - content : entry=-1000651
UPDATE `trans_words` SET `content_loc8`='The power of Necrotic Aura begins to wane!' WHERE `word_id` = 1262; -- script_texts - content : entry=-1533144
UPDATE `trans_words` SET `content_loc8`='The rift will be opened there, above the Lake Elun\'ara. Prepare yourself, $N. Eranikus entry into our world will be wrought with chaos and strife.' WHERE `word_id` = 509; -- script_texts - content : entry=-1000671
UPDATE `trans_words` SET `content_loc8`='The runes of warding have been destroyed! Hunt down the infedels my bretheren.' WHERE `word_id` = 986; -- script_texts - content : entry=-1409004
UPDATE `trans_words` SET `content_loc8`='The screams of the dying will fill the air. A symphony of terror is about to begin!' WHERE `word_id` = 1083; -- script_texts - content : entry=-1531005
UPDATE `trans_words` SET `content_loc8`='This part of forest are very danger for us. We must be a careful!' WHERE `word_id` = 742; -- script_texts - content : entry=-1000959
UPDATE `trans_words` SET `content_loc8`='This timeway is currently collapsing. What that may hold for the past, present and future is currently unknown...' WHERE `word_id` = 122; -- script_texts - content : entry=-1000227
UPDATE `trans_words` SET `content_loc8`='This timeway is in great disarray! We have agents inside right now attempting to restore order. What information I have indicates that Thrall\'s freedom is in jeopardy. A malevolent organization known as the Infinite Dragonflight is trying to prevent his escape. I fear without outside assistance, all will be lost.' WHERE `word_id` = 120; -- script_texts - content : entry=-1000225
UPDATE `trans_words` SET `content_loc8`='To decorate our halls!' WHERE `word_id` = 1103; -- script_texts - content : entry=-1531025
UPDATE `trans_words` SET `content_loc8`='To your posts. Defend the city.' WHERE `word_id` = 1070; -- script_texts - content : entry=-1509023
UPDATE `trans_words` SET `content_loc8`='Torloth your master calls!' WHERE `word_id` = 431; -- script_texts - content : entry=-1000539
UPDATE `trans_words` SET `content_loc8`='Tremble! The end is upon you.' WHERE `word_id` = 1080; -- script_texts - content : entry=-1531002
UPDATE `trans_words` SET `content_loc8`='Tresspassers will be terminated.' WHERE `word_id` = 1071; -- script_texts - content : entry=-1509024
UPDATE `trans_words` SET `content_loc8`='Very well... warriors of the frozen wastes, rise up! I command you to fight, kill, and die for your master. Let none survive...' WHERE `word_id` = 1222; -- script_texts - content : entry=-1533104
UPDATE `trans_words` SET `content_loc8`='Warning! %s emergency shutdown process initiated by $N. Shutdown will complete in two minutes.' WHERE `word_id` = 106; -- script_texts - content : entry=-1000211
UPDATE `trans_words` SET `content_loc8`='Was this fabled, Windsor? If it was death that you came for then the prophecy has been fulfilled. May your consciousness rot in the Twisting Nether. Finish the rest of these meddlesome insects, children. Bolvar, you have been a pleasureable puppet.' WHERE `word_id` = 701; -- script_texts - content : entry=-1000867
UPDATE `trans_words` SET `content_loc8`='We do not know if the Caverns of Time have always been accessible to mortals. Truly, it is impossible to tell as the Timeless One is in perpetual motion, changing our timeways as he sees fit. What you see now may very well not exist tomorrow. You may wake up and have no memory of this place.' WHERE `word_id` = 113; -- script_texts - content : entry=-1000218
UPDATE `trans_words` SET `content_loc8`='We must act quickly or shall be lost!' WHERE `word_id` = 578; -- script_texts - content : entry=-1000740
UPDATE `trans_words` SET `content_loc8`='We will battle these fiends, together! Nighthaven\'s Defenders are also among us. They will fight to the death if asked. Now, quickly, we must drive these aberations back to the Nightmare. Destroy them all!' WHERE `word_id` = 523; -- script_texts - content : entry=-1000685
UPDATE `trans_words` SET `content_loc8`='We will locate the origin of the Nightmare through the fragments you collected, $N. From there, we will pull Eranikus through a rift in the Dream. Steel yourself, $C. We are inviting the embodiment of the Nightmare into our world.' WHERE `word_id` = 507; -- script_texts - content : entry=-1000669
UPDATE `trans_words` SET `content_loc8`='Welcome, kind spirit. What has brought you to us?' WHERE `word_id` = 390; -- script_texts - content : entry=-1000498
UPDATE `trans_words` SET `content_loc8`='Well done, my minions. The mortals\' courage begins to wane! Now, let\'s see how they contend with the true Lord of Blackrock Spire!' WHERE `word_id` = 1017; -- script_texts - content : entry=-1469007
UPDATE `trans_words` SET `content_loc8`='What was that?! Trey? TREY?' WHERE `word_id` = 1289; -- script_texts - content : entry=-1001156
UPDATE `trans_words` SET `content_loc8`='Where shall I begin? I cannot bother myself with a worm such as yourself. There is a world to be conquered!' WHERE `word_id` = 68; -- script_texts - content : entry=-1000171
UPDATE `trans_words` SET `content_loc8`='Who dares violate the sanctity of my domain? Be warned, all who trespass here are doomed.' WHERE `word_id` = 1208; -- script_texts - content : entry=-1533090
UPDATE `trans_words` SET `content_loc8`='Who you gonna call?' WHERE `word_id` = 966; -- script_texts - content : entry=-1329002
UPDATE `trans_words` SET `content_loc8`='Why don\'t we deal with you now, Hendel? Lady Proudmoore will speak for you back in the tower.' WHERE `word_id` = 305; -- script_texts - content : entry=-1000411
UPDATE `trans_words` SET `content_loc8`='WHY? Why did this happen to... to me? Where were you Tyrande? Where were you when I fell from the grace of Elune?' WHERE `word_id` = 533; -- script_texts - content : entry=-1000695
UPDATE `trans_words` SET `content_loc8`='YARRR! Swabie, what have ye done?! He\'s gone mad! Baton him down the hatches! Hoist the mast! ARRRR! Every man for hi\'self!' WHERE `word_id` = 220; -- script_texts - content : entry=-1000326
UPDATE `trans_words` SET `content_loc8`='Yes, Lord Illidan, I would sacrifice to you this magnificent physique. On this day you will fall - another victim of Torloth...' WHERE `word_id` = 426; -- script_texts - content : entry=-1000534
UPDATE `trans_words` SET `content_loc8`='You are already dead.' WHERE `word_id` = 1112; -- script_texts - content : entry=-1531034
UPDATE `trans_words` SET `content_loc8`='You are certanly not your father, insect. Should it interest me, I would crush you with but a swipe of my claws. Turn Shan\'do Stormrage over to me and your pitiful life will be spared along with the lives of your people.' WHERE `word_id` = 516; -- script_texts - content : entry=-1000678
UPDATE `trans_words` SET `content_loc8`='You are no challenge for the Crimson Sigil. Mind breakers, end this nonsense.' WHERE `word_id` = 429; -- script_texts - content : entry=-1000537
UPDATE `trans_words` SET `content_loc8`='You are too late... I... must... OBEY!' WHERE `word_id` = 1148; -- script_texts - content : entry=-1533029
UPDATE `trans_words` SET `content_loc8`='You are weak.' WHERE `word_id` = 1117; -- script_texts - content : entry=-1531039
UPDATE `trans_words` SET `content_loc8`='You die now!' WHERE `word_id` = 1152; -- script_texts - content : entry=-1533033
UPDATE `trans_words` SET `content_loc8`='You have my word that I shall find a use for your body after I\'ve killed you, Kinelory.' WHERE `word_id` = 736; -- script_texts - content : entry=-1000951
UPDATE `trans_words` SET `content_loc8`='You kept me in the cell for too long, monster!' WHERE `word_id` = 1290; -- script_texts - content : entry=-1001157
UPDATE `trans_words` SET `content_loc8`='You must protect me from monsters, who are living in this forest!' WHERE `word_id` = 741; -- script_texts - content : entry=-1000958
UPDATE `trans_words` SET `content_loc8`='You should have stayed home!' WHERE `word_id` = 1242; -- script_texts - content : entry=-1533124
UPDATE `trans_words` SET `content_loc8`='You will betray your friends.' WHERE `word_id` = 1115; -- script_texts - content : entry=-1531037
UPDATE `trans_words` SET `content_loc8`='You will die.' WHERE `word_id` = 1116; -- script_texts - content : entry=-1531038
UPDATE `trans_words` SET `content_loc8`='Your brash arrogance!' WHERE `word_id` = 1100; -- script_texts - content : entry=-1531022
UPDATE `trans_words` SET `content_loc8`='Your courage will fail.' WHERE `word_id` = 1113; -- script_texts - content : entry=-1531035
UPDATE `trans_words` SET `content_loc8`='Your efforts are utterly pointless, fools! You will never be able to defeat me!' WHERE `word_id` = 1320; -- script_texts - content : entry=-1230063
UPDATE `trans_words` SET `content_loc8`='Your friends will abandon you.' WHERE `word_id` = 1114; -- script_texts - content : entry=-1531036
UPDATE `trans_words` SET `content_loc8`='Your heart will explode.' WHERE `word_id` = 1118; -- script_texts - content : entry=-1531040
UPDATE `trans_words` SET `content_loc8`='Your security measures have failed! See to this interruption immediately!' WHERE `word_id` = 1205; -- script_texts - content : entry=-1533087

SET NAMES 'latin1';
