-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc9`=' Orientation: %f' WHERE `word_id` = 4931; -- mangos_string - content : entry=248
UPDATE `trans_words` SET `content_loc9`=' Waittime: %d' WHERE `word_id` = 4930; -- mangos_string - content : entry=247
UPDATE `trans_words` SET `content_loc9`='$N captured the Alliance flag!' WHERE `word_id` = 4659; -- mangos_string - content : entry=606
UPDATE `trans_words` SET `content_loc9`='$N captured the Horde flag!' WHERE `word_id` = 4658; -- mangos_string - content : entry=605
UPDATE `trans_words` SET `content_loc9`='$N claims the %s! If left unchallenged, the %s will control it in 1 minute!' WHERE `word_id` = 4677; -- mangos_string - content : entry=660
UPDATE `trans_words` SET `content_loc9`='$N has assaulted the %s' WHERE `word_id` = 4676; -- mangos_string - content : entry=659
UPDATE `trans_words` SET `content_loc9`='$N has defended the %s' WHERE `word_id` = 4675; -- mangos_string - content : entry=658
UPDATE `trans_words` SET `content_loc9`='%d - %s %s (Map:%u X:%f Y:%f Z:%f)' WHERE `word_id` = 4800; -- mangos_string - content : entry=1129
UPDATE `trans_words` SET `content_loc9`='%d - |cffffffff|Hcreature_entry:%d|h[%s]|h|r' WHERE `word_id` = 4573; -- mangos_string - content : entry=514
UPDATE `trans_words` SET `content_loc9`='%d - |cffffffff|Hfaction:%d|h[%s]|h|r' WHERE `word_id` = 4394; -- mangos_string - content : entry=311
UPDATE `trans_words` SET `content_loc9`='%d - |cffffffff|Hgameevent:%d|h[%s]|h|r%s' WHERE `word_id` = 4636; -- mangos_string - content : entry=583
UPDATE `trans_words` SET `content_loc9`='%d - |cffffffff|Hgameobject_entry:%d|h[%s]|h|r' WHERE `word_id` = 4575; -- mangos_string - content : entry=516
UPDATE `trans_words` SET `content_loc9`='%d - |cffffffff|Hitem:%d:0:0:0:0:0:0:0|h[%s]|h|r %s' WHERE `word_id` = 4571; -- mangos_string - content : entry=512
UPDATE `trans_words` SET `content_loc9`='%d - |cffffffff|Hitemset:%d|h[%s %s]|h|r' WHERE `word_id` = 4577; -- mangos_string - content : entry=518
UPDATE `trans_words` SET `content_loc9`='%d - |cffffffff|Hquest:%d:%d|h[%s]|h|r %s' WHERE `word_id` = 4572; -- mangos_string - content : entry=513
UPDATE `trans_words` SET `content_loc9`='%d - |cffffffff|Hskill:%d|h[%s %s]|h|r %s %s' WHERE `word_id` = 4580; -- mangos_string - content : entry=521
UPDATE `trans_words` SET `content_loc9`='%d - |cffffffff|Hspell:%d|h[%s]|h|r' WHERE `word_id` = 4579; -- mangos_string - content : entry=520
UPDATE `trans_words` SET `content_loc9`='%d - |cffffffff|Htaxinode:%u|h[%s %s]|h|r (Map:%u X:%f Y:%f Z:%f)' WHERE `word_id` = 4799; -- mangos_string - content : entry=1128
UPDATE `trans_words` SET `content_loc9`='%d - guild: %s (guid: %u) %s' WHERE `word_id` = 4794; -- mangos_string - content : entry=1118
UPDATE `trans_words` SET `content_loc9`='%d - owner: %s (guid: %u account: %u ) %s' WHERE `word_id` = 4568; -- mangos_string - content : entry=1103
UPDATE `trans_words` SET `content_loc9`='%d - sender: %s (guid: %u account: %u ) receiver: %s (guid: %u account: %u ) %s' WHERE `word_id` = 4569; -- mangos_string - content : entry=509
UPDATE `trans_words` SET `content_loc9`='%d%s - %s X:%f Y:%f Z:%f MapId:%d' WHERE `word_id` = 4787; -- mangos_string - content : entry=1110
UPDATE `trans_words` SET `content_loc9`='%d%s - [%s] X:%f Y:%f Z:%f MapId:%d Chance:%f %s' WHERE `word_id` = 4449; -- mangos_string - content : entry=381
UPDATE `trans_words` SET `content_loc9`='%d%s - |cffffffff|Hcreature:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r Chance:%f %s' WHERE `word_id` = 4448; -- mangos_string - content : entry=380
UPDATE `trans_words` SET `content_loc9`='%d%s - |cffffffff|Hcreature:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r' WHERE `word_id` = 4574; -- mangos_string - content : entry=515
UPDATE `trans_words` SET `content_loc9`='%d%s - |cffffffff|Hgameobject:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r Chance:%f %s' WHERE `word_id` = 4450; -- mangos_string - content : entry=384
UPDATE `trans_words` SET `content_loc9`='%d%s - |cffffffff|Hgameobject:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r' WHERE `word_id` = 4808; -- mangos_string - content : entry=1137
UPDATE `trans_words` SET `content_loc9`='%d%s, Entry %d - |cffffffff|Hgameobject:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r' WHERE `word_id` = 4576; -- mangos_string - content : entry=517
UPDATE `trans_words` SET `content_loc9`='%s %s not found' WHERE `word_id` = 4473; -- mangos_string - content : entry=410
UPDATE `trans_words` SET `content_loc9`='%s (lowguid: %u) movement generators stack:' WHERE `word_id` = 4585; -- mangos_string - content : entry=526
UPDATE `trans_words` SET `content_loc9`='%s changed your ENERGY to %i/%i.' WHERE `word_id` = 4252; -- mangos_string - content : entry=123
UPDATE `trans_words` SET `content_loc9`='%s changed your HP to %i/%i.' WHERE `word_id` = 4248; -- mangos_string - content : entry=119
UPDATE `trans_words` SET `content_loc9`='%s changed your MANA to %i/%i.' WHERE `word_id` = 4250; -- mangos_string - content : entry=121
UPDATE `trans_words` SET `content_loc9`='%s changed your rage to %i/%i.' WHERE `word_id` = 4255; -- mangos_string - content : entry=126
UPDATE `trans_words` SET `content_loc9`='%s changed your security level to %i.' WHERE `word_id` = 4465; -- mangos_string - content : entry=402
UPDATE `trans_words` SET `content_loc9`='%s changed your spellmod %u to value %i for spell with family bit %u.' WHERE `word_id` = 4261; -- mangos_string - content : entry=132
UPDATE `trans_words` SET `content_loc9`='%s does not wish to be disturbed: %s' WHERE `word_id` = 4686; -- mangos_string - content : entry=707
UPDATE `trans_words` SET `content_loc9`='%s doesn\'t know that spell.' WHERE `word_id` = 4550; -- mangos_string - content : entry=490
UPDATE `trans_words` SET `content_loc9`='%s gave you %i copper.' WHERE `word_id` = 4285; -- mangos_string - content : entry=158
UPDATE `trans_words` SET `content_loc9`='%s gave you a mount.' WHERE `word_id` = 4278; -- mangos_string - content : entry=151
UPDATE `trans_words` SET `content_loc9`='%s has access to all taxi nodes now (until logout).' WHERE `word_id` = 4262; -- mangos_string - content : entry=133
UPDATE `trans_words` SET `content_loc9`='%s has bitstr value:[FIELD]:%u [VALUE]:%s' WHERE `word_id` = 4825; -- mangos_string - content : entry=1154
UPDATE `trans_words` SET `content_loc9`='%s has explored all zones for you.' WHERE `word_id` = 4612; -- mangos_string - content : entry=553
UPDATE `trans_words` SET `content_loc9`='%s has explored all zones now.' WHERE `word_id` = 4610; -- mangos_string - content : entry=551
UPDATE `trans_words` SET `content_loc9`='%s has float value:[FIELD]:%u [VALUE]:%f' WHERE `word_id` = 4627; -- mangos_string - content : entry=572
UPDATE `trans_words` SET `content_loc9`='%s has given you access to all taxi nodes (until logout).' WHERE `word_id` = 4264; -- mangos_string - content : entry=135
UPDATE `trans_words` SET `content_loc9`='%s has hex value:[FIELD]:%u [VALUE]:%x' WHERE `word_id` = 4827; -- mangos_string - content : entry=1156
UPDATE `trans_words` SET `content_loc9`='%s has hidden all zones from you.' WHERE `word_id` = 4613; -- mangos_string - content : entry=554
UPDATE `trans_words` SET `content_loc9`='%s has no more access to all taxi nodes now (only visited accessible).' WHERE `word_id` = 4263; -- mangos_string - content : entry=134
UPDATE `trans_words` SET `content_loc9`='%s has no more explored zones.' WHERE `word_id` = 4611; -- mangos_string - content : entry=552
UPDATE `trans_words` SET `content_loc9`='%s has no path or path empty, path-id %i (loaded from %s)' WHERE `word_id` = 4338; -- mangos_string - content : entry=222
UPDATE `trans_words` SET `content_loc9`='%s has removed access to all taxi nodes (only visited still accessible).' WHERE `word_id` = 4265; -- mangos_string - content : entry=136
UPDATE `trans_words` SET `content_loc9`='%s has uint32 value:[FIELD]:%u [VALUE]:%u' WHERE `word_id` = 4625; -- mangos_string - content : entry=570
UPDATE `trans_words` SET `content_loc9`='%s is already being teleported.' WHERE `word_id` = 4231; -- mangos_string - content : entry=102
UPDATE `trans_words` SET `content_loc9`='%s is appearing to your location.' WHERE `word_id` = 4243; -- mangos_string - content : entry=114
UPDATE `trans_words` SET `content_loc9`='%s is Away from Keyboard: %s' WHERE `word_id` = 4687; -- mangos_string - content : entry=708
UPDATE `trans_words` SET `content_loc9`='%s is banned for %s. Reason: %s.' WHERE `word_id` = 4471; -- mangos_string - content : entry=408
UPDATE `trans_words` SET `content_loc9`='%s is banned permanently for %s.' WHERE `word_id` = 4472; -- mangos_string - content : entry=409
UPDATE `trans_words` SET `content_loc9`='%s is flying command failed.' WHERE `word_id` = 4184; -- mangos_string - content : entry=21
UPDATE `trans_words` SET `content_loc9`='%s is not following you.' WHERE `word_id` = 4424; -- mangos_string - content : entry=341
UPDATE `trans_words` SET `content_loc9`='%s is not in a group.' WHERE `word_id` = 4246; -- mangos_string - content : entry=117
UPDATE `trans_words` SET `content_loc9`='%s is now following you.' WHERE `word_id` = 4423; -- mangos_string - content : entry=340
UPDATE `trans_words` SET `content_loc9`='%s is now not following you.' WHERE `word_id` = 4425; -- mangos_string - content : entry=342
UPDATE `trans_words` SET `content_loc9`='%s level down you to (%i)' WHERE `word_id` = 4615; -- mangos_string - content : entry=558
UPDATE `trans_words` SET `content_loc9`='%s level up you to (%i)' WHERE `word_id` = 4614; -- mangos_string - content : entry=557
UPDATE `trans_words` SET `content_loc9`='%s reset your level progress.' WHERE `word_id` = 4616; -- mangos_string - content : entry=559
UPDATE `trans_words` SET `content_loc9`='%s set all your speeds to %2.2f from normal.' WHERE `word_id` = 4267; -- mangos_string - content : entry=138
UPDATE `trans_words` SET `content_loc9`='%s set your backwards run speed to %2.2f from normal.' WHERE `word_id` = 4273; -- mangos_string - content : entry=144
UPDATE `trans_words` SET `content_loc9`='%s set your size to %2.2f.' WHERE `word_id` = 4275; -- mangos_string - content : entry=148
UPDATE `trans_words` SET `content_loc9`='%s set your speed to %2.2f from normal.' WHERE `word_id` = 4269; -- mangos_string - content : entry=140
UPDATE `trans_words` SET `content_loc9`='%s set your swim speed to %2.2f from normal.' WHERE `word_id` = 4271; -- mangos_string - content : entry=142
UPDATE `trans_words` SET `content_loc9`='%s took %i copper from you.' WHERE `word_id` = 4283; -- mangos_string - content : entry=156
UPDATE `trans_words` SET `content_loc9`='%s took you all of your copper.' WHERE `word_id` = 4281; -- mangos_string - content : entry=154
UPDATE `trans_words` SET `content_loc9`='%s unbanned.' WHERE `word_id` = 4474; -- mangos_string - content : entry=411
UPDATE `trans_words` SET `content_loc9`='%s was destroyed by the %s!' WHERE `word_id` = 4711; -- mangos_string - content : entry=759
UPDATE `trans_words` SET `content_loc9`='%s[Trigger target %u] Map %u X:%f Y:%f Z:%f' WHERE `word_id` = 4433; -- mangos_string - content : entry=360
UPDATE `trans_words` SET `content_loc9`='%s\'s Fly Mode %s' WHERE `word_id` = 4537; -- mangos_string - content : entry=477
UPDATE `trans_words` SET `content_loc9`='%s|cffffffff|Hareatrigger_target:%u|h[Trigger target %u]|h|r Map %u X:%f Y:%f Z:%f%s' WHERE `word_id` = 4432; -- mangos_string - content : entry=359
UPDATE `trans_words` SET `content_loc9`='%u - %s (Online:%s IP:%s GM:%u Expansion:%u)' WHERE `word_id` = 4813; -- mangos_string - content : entry=1142
UPDATE `trans_words` SET `content_loc9`='%u - [%s] AutoSpawn: %u MaxLimit: %u Creatures: %u GameObjecs: %u Pools %u Chance: %f %s' WHERE `word_id` = 4906; -- mangos_string - content : entry=1500
UPDATE `trans_words` SET `content_loc9`='%u - [%s] AutoSpawn: %u MaxLimit: %u Creatures: %u GameObjecs: %u Pools %u' WHERE `word_id` = 4459; -- mangos_string - content : entry=396
UPDATE `trans_words` SET `content_loc9`='%u - |cffffffff|Hpool:%u|h[%s]|h|r AutoSpawn: %u MaxLimit: %u Creatures: %u GameObjecs: %u Pools %u Chance: %f %s' WHERE `word_id` = 4462; -- mangos_string - content : entry=1501
UPDATE `trans_words` SET `content_loc9`='%u - |cffffffff|Hpool:%u|h[%s]|h|r AutoSpawn: %u MaxLimit: %u Creatures: %u GameObjecs: %u Pools %u' WHERE `word_id` = 4444; -- mangos_string - content : entry=376
UPDATE `trans_words` SET `content_loc9`='(%u/%u +perm %u +temp %u)' WHERE `word_id` = 4798; -- mangos_string - content : entry=1122
UPDATE `trans_words` SET `content_loc9`=', rank' WHERE `word_id` = 4193; -- mangos_string - content : entry=30
UPDATE `trans_words` SET `content_loc9`='[Trigger %u] Map %u X:%f Y:%f Z:%f%s%s' WHERE `word_id` = 4435; -- mangos_string - content : entry=362
UPDATE `trans_words` SET `content_loc9`='|           |Alliance|  Horde |Neutral | Amount  |' WHERE `word_id` = 4847; -- mangos_string - content : entry=1181
UPDATE `trans_words` SET `content_loc9`='|           |Alliance| Horde  |Neutral | Total   |' WHERE `word_id` = 4841; -- mangos_string - content : entry=1175
UPDATE `trans_words` SET `content_loc9`='|      IP      |  BanDate   |  UnbanDate | Banned By   |  Ban Reason  |' WHERE `word_id` = 4649; -- mangos_string - content : entry=596
UPDATE `trans_words` SET `content_loc9`='|    Account   |  BanDate   |  UnbanDate | Banned By   |  Ban Reason  |' WHERE `word_id` = 4647; -- mangos_string - content : entry=594
UPDATE `trans_words` SET `content_loc9`='|    Account   | GM  |' WHERE `word_id` = 4651; -- mangos_string - content : entry=598
UPDATE `trans_words` SET `content_loc9`='| GUID      |Name                |Account                     |Delete Date         |' WHERE `word_id` = 4769; -- mangos_string - content : entry=1016
UPDATE `trans_words` SET `content_loc9`='|cffff0000[BG Queue Announcer]:|r %s -- [%u-%u] A: %u/%u, H: %u/%u|r' WHERE `word_id` = 4691; -- mangos_string - content : entry=712
UPDATE `trans_words` SET `content_loc9`='|cffff0000[BG Queue Announcer]:|r %s -- [%u-%u] Started!|r' WHERE `word_id` = 4693; -- mangos_string - content : entry=717
UPDATE `trans_words` SET `content_loc9`='|cffff0000[Event Message]: %s|r' WHERE `word_id` = 4167; -- mangos_string - content : entry=4
UPDATE `trans_words` SET `content_loc9`='|cffff0000[Server Announce]:|r%s' WHERE `word_id` = 4949; -- mangos_string - content : entry=1700
UPDATE `trans_words` SET `content_loc9`='|cffff0000[System Message]: %s|r' WHERE `word_id` = 4166; -- mangos_string - content : entry=3
UPDATE `trans_words` SET `content_loc9`='|cffffffff|Hareatrigger:%u|h[Trigger %u]|h|r Map %u X:%f Y:%f Z:%f%s%s%s' WHERE `word_id` = 4434; -- mangos_string - content : entry=361
UPDATE `trans_words` SET `content_loc9`='|cffffffff|Htele:%s|h[%s]|h|r' WHERE `word_id` = 4578; -- mangos_string - content : entry=519
UPDATE `trans_words` SET `content_loc9`='<non-existing character>' WHERE `word_id` = 4210; -- mangos_string - content : entry=47
UPDATE `trans_words` SET `content_loc9`='= Shown %u tickets of total %u.' WHERE `word_id` = 4947; -- mangos_string - content : entry=1517
UPDATE `trans_words` SET `content_loc9`='= Shown %u tickets out of total %u from online players.' WHERE `word_id` = 4945; -- mangos_string - content : entry=1515
UPDATE `trans_words` SET `content_loc9`='>> Add Game Object \'%i\' (%s) (GUID: %i) added at \'%f %f %f\'.' WHERE `word_id` = 4584; -- mangos_string - content : entry=525
UPDATE `trans_words` SET `content_loc9`='>> Game Object %s (GUID: %u) at %f %f %f. Orientation %f.' WHERE `word_id` = 4582; -- mangos_string - content : entry=523
UPDATE `trans_words` SET `content_loc9`='1 minute until the battle for Alterac Valley begins.' WHERE `word_id` = 4733; -- mangos_string - content : entry=784
UPDATE `trans_words` SET `content_loc9`='30 seconds until the battle for Alterac Valley begins. Prepare yourselves!' WHERE `word_id` = 4734; -- mangos_string - content : entry=785
UPDATE `trans_words` SET `content_loc9`='Accepting Whisper: %s' WHERE `word_id` = 4370; -- mangos_string - content : entry=284
UPDATE `trans_words` SET `content_loc9`='Accepting Whisper: OFF' WHERE `word_id` = 4372; -- mangos_string - content : entry=286
UPDATE `trans_words` SET `content_loc9`='Accepting Whisper: ON' WHERE `word_id` = 4371; -- mangos_string - content : entry=285
UPDATE `trans_words` SET `content_loc9`='Accepts whispers' WHERE `word_id` = 4225; -- mangos_string - content : entry=63
UPDATE `trans_words` SET `content_loc9`='Account %s (%u) have max amount allowed characters (client limit)' WHERE `word_id` = 4789; -- mangos_string - content : entry=1113
UPDATE `trans_words` SET `content_loc9`='Account %s (Id: %u) has been granted %u expansion rights.' WHERE `word_id` = 4783; -- mangos_string - content : entry=1100
UPDATE `trans_words` SET `content_loc9`='Account %s has never been banned' WHERE `word_id` = 4479; -- mangos_string - content : entry=416
UPDATE `trans_words` SET `content_loc9`='Account %s NOT created (probably sql file format was updated)' WHERE `word_id` = 4761; -- mangos_string - content : entry=1007
UPDATE `trans_words` SET `content_loc9`='Account %s NOT created (unknown error)' WHERE `word_id` = 4762; -- mangos_string - content : entry=1008
UPDATE `trans_words` SET `content_loc9`='Account %s NOT deleted (probably sql file format was updated)' WHERE `word_id` = 4756; -- mangos_string - content : entry=1002
UPDATE `trans_words` SET `content_loc9`='Account %s NOT deleted (unknown error)' WHERE `word_id` = 4757; -- mangos_string - content : entry=1003
UPDATE `trans_words` SET `content_loc9`='Account created: %s' WHERE `word_id` = 4758; -- mangos_string - content : entry=1004
UPDATE `trans_words` SET `content_loc9`='Account deleted: %s' WHERE `word_id` = 4755; -- mangos_string - content : entry=1001
UPDATE `trans_words` SET `content_loc9`='Account for character %s not found' WHERE `word_id` = 4748; -- mangos_string - content : entry=809
UPDATE `trans_words` SET `content_loc9`='Account name cannot be longer than 16 characters (client limit), account not created!' WHERE `word_id` = 4759; -- mangos_string - content : entry=1005
UPDATE `trans_words` SET `content_loc9`='Account not exist: %s' WHERE `word_id` = 4476; -- mangos_string - content : entry=413
UPDATE `trans_words` SET `content_loc9`='Account with this name already exist!' WHERE `word_id` = 4760; -- mangos_string - content : entry=1006
UPDATE `trans_words` SET `content_loc9`='Added Waypoint %u to %s (PathId %i, path stored by %s)' WHERE `word_id` = 4326; -- mangos_string - content : entry=234
UPDATE `trans_words` SET `content_loc9`='After your recent battle in %s our best attempts to award you a Mark of Honor failed. Enclosed you will find the Mark of Honor we were not able to deliver to you at the time. Thanks for fighting in %s!' WHERE `word_id` = 4683; -- mangos_string - content : entry=666
UPDATE `trans_words` SET `content_loc9`='AI-Information for Npc Entry %u' WHERE `word_id` = 4908; -- mangos_string - content : entry=1504
UPDATE `trans_words` SET `content_loc9`='AIName: %s (%s) ScriptName: %s' WHERE `word_id` = 4909; -- mangos_string - content : entry=1505
UPDATE `trans_words` SET `content_loc9`='AIScriptName: %s' WHERE `word_id` = 4934; -- mangos_string - content : entry=252
UPDATE `trans_words` SET `content_loc9`='All log filters set to: %s' WHERE `word_id` = 4781; -- mangos_string - content : entry=1028
UPDATE `trans_words` SET `content_loc9`='All players saved.' WHERE `word_id` = 4178; -- mangos_string - content : entry=15
UPDATE `trans_words` SET `content_loc9`='All spell cooldowns removed for %s.' WHERE `word_id` = 4552; -- mangos_string - content : entry=492
UPDATE `trans_words` SET `content_loc9`='All tickets deleted.' WHERE `word_id` = 4378; -- mangos_string - content : entry=294
UPDATE `trans_words` SET `content_loc9`='All visual waypoints removed' WHERE `word_id` = 4331; -- mangos_string - content : entry=229
UPDATE `trans_words` SET `content_loc9`='All your items repaired by %s.' WHERE `word_id` = 4420; -- mangos_string - content : entry=337
UPDATE `trans_words` SET `content_loc9`='Amount of %s items is set to %u.' WHERE `word_id` = 4856; -- mangos_string - content : entry=1190
UPDATE `trans_words` SET `content_loc9`='any' WHERE `word_id` = 4518; -- mangos_string - content : entry=456
UPDATE `trans_words` SET `content_loc9`='Appearing at %s\'s location.' WHERE `word_id` = 4242; -- mangos_string - content : entry=113
UPDATE `trans_words` SET `content_loc9`='Areatrigger %u not has target coordinates' WHERE `word_id` = 4430; -- mangos_string - content : entry=357
UPDATE `trans_words` SET `content_loc9`='Areatrigger ID %u not found!' WHERE `word_id` = 4350; -- mangos_string - content : entry=262
UPDATE `trans_words` SET `content_loc9`='Argument required for \'%s\'.' WHERE `word_id` = 4327; -- mangos_string - content : entry=233
UPDATE `trans_words` SET `content_loc9`='Away from Keyboard' WHERE `word_id` = 4689; -- mangos_string - content : entry=710
UPDATE `trans_words` SET `content_loc9`='Ban Date: %s Bantime: %s Still active: %s  Reason: %s Set by: %s' WHERE `word_id` = 4481; -- mangos_string - content : entry=418
UPDATE `trans_words` SET `content_loc9`='Ban history for account %s:' WHERE `word_id` = 4480; -- mangos_string - content : entry=417
UPDATE `trans_words` SET `content_loc9`='Battlegrounds are set to 1v0 for debugging.' WHERE `word_id` = 4705; -- mangos_string - content : entry=739
UPDATE `trans_words` SET `content_loc9`='Battlegrounds are set to normal playercount.' WHERE `word_id` = 4706; -- mangos_string - content : entry=740
UPDATE `trans_words` SET `content_loc9`='Cannot access %s on map, maybe you are too far away from its spawn location' WHERE `word_id` = 4336; -- mangos_string - content : entry=224
UPDATE `trans_words` SET `content_loc9`='Cannot add spawn because no free guids for static spawn in reserved guids range. Server restart is required before command can be used. Also look GuidReserveSize.* config options.' WHERE `word_id` = 4907; -- mangos_string - content : entry=1503
UPDATE `trans_words` SET `content_loc9`='Cannot create item \'%i\' (amount: %i)' WHERE `word_id` = 4557; -- mangos_string - content : entry=497
UPDATE `trans_words` SET `content_loc9`='Cannot do that while fighting.' WHERE `word_id` = 4186; -- mangos_string - content : entry=23
UPDATE `trans_words` SET `content_loc9`='Cannot do that while flying.' WHERE `word_id` = 4181; -- mangos_string - content : entry=18
UPDATE `trans_words` SET `content_loc9`='Cannot find waypoint id %u for %s (in path %i, loaded from %s)' WHERE `word_id` = 4340; -- mangos_string - content : entry=220
UPDATE `trans_words` SET `content_loc9`='Character %s ticket deleted.' WHERE `word_id` = 4379; -- mangos_string - content : entry=295
UPDATE `trans_words` SET `content_loc9`='Character \'%s\' (GUID: %u Account %u) can\'t be restored: account character list full!' WHERE `word_id` = 4777; -- mangos_string - content : entry=1024
UPDATE `trans_words` SET `content_loc9`='Character \'%s\' (GUID: %u Account %u) can\'t be restored: account doesn\'t exist!' WHERE `word_id` = 4776; -- mangos_string - content : entry=1023
UPDATE `trans_words` SET `content_loc9`='Character \'%s\' (GUID: %u Account %u) can\'t be restored: name already in use!' WHERE `word_id` = 4778; -- mangos_string - content : entry=1025
UPDATE `trans_words` SET `content_loc9`='Character dump failed!' WHERE `word_id` = 4542; -- mangos_string - content : entry=482
UPDATE `trans_words` SET `content_loc9`='Character dumped successfully!' WHERE `word_id` = 4541; -- mangos_string - content : entry=481
UPDATE `trans_words` SET `content_loc9`='Character guid %u in use!' WHERE `word_id` = 4793; -- mangos_string - content : entry=1117
UPDATE `trans_words` SET `content_loc9`='Character loaded successfully!' WHERE `word_id` = 4539; -- mangos_string - content : entry=479
UPDATE `trans_words` SET `content_loc9`='Characters at account %s (Id: %u)' WHERE `word_id` = 4411; -- mangos_string - content : entry=328
UPDATE `trans_words` SET `content_loc9`='Closed ticket for player %s' WHERE `word_id` = 4924; -- mangos_string - content : entry=1510
UPDATE `trans_words` SET `content_loc9`='Combat-Movement is %s' WHERE `word_id` = 4911; -- mangos_string - content : entry=1507
UPDATE `trans_words` SET `content_loc9`='Command %s have subcommands:' WHERE `word_id` = 4171; -- mangos_string - content : entry=8
UPDATE `trans_words` SET `content_loc9`='Command .pinfo doesn\'t support \'rep\' option for offline players.' WHERE `word_id` = 4609; -- mangos_string - content : entry=550
UPDATE `trans_words` SET `content_loc9`='Command : Additem, itemId = %i, amount = %i' WHERE `word_id` = 4554; -- mangos_string - content : entry=494
UPDATE `trans_words` SET `content_loc9`='Command : Additemset, itemsetId = %i' WHERE `word_id` = 4555; -- mangos_string - content : entry=495
UPDATE `trans_words` SET `content_loc9`='Command can only be called from a Remote Admin console.' WHERE `word_id` = 4782; -- mangos_string - content : entry=1029
UPDATE `trans_words` SET `content_loc9`='Commands available to you:' WHERE `word_id` = 4172; -- mangos_string - content : entry=9
UPDATE `trans_words` SET `content_loc9`='Condition %u' WHERE `word_id` = 4942; -- mangos_string - content : entry=367
UPDATE `trans_words` SET `content_loc9`='Could not add waypoint %u to %s (pathId %i stored by %s)' WHERE `word_id` = 4330; -- mangos_string - content : entry=230
UPDATE `trans_words` SET `content_loc9`='Could not create visual waypoint with creatureID: %d' WHERE `word_id` = 4332; -- mangos_string - content : entry=228
UPDATE `trans_words` SET `content_loc9`='Could not find \'%s\'' WHERE `word_id` = 4497; -- mangos_string - content : entry=434
UPDATE `trans_words` SET `content_loc9`='Could not find NPC...' WHERE `word_id` = 4344; -- mangos_string - content : entry=256
UPDATE `trans_words` SET `content_loc9`='Creature (Entry: %u) cannot be tamed.' WHERE `word_id` = 4426; -- mangos_string - content : entry=343
UPDATE `trans_words` SET `content_loc9`='Creature (GUID: %u) No waypoints found - This is a MaNGOS db problem (single float).' WHERE `word_id` = 4337; -- mangos_string - content : entry=223
UPDATE `trans_words` SET `content_loc9`='Creature (GUID: %u) not found' WHERE `word_id` = 4335; -- mangos_string - content : entry=225
UPDATE `trans_words` SET `content_loc9`='Creature (GUID:%u) must be on the same map as player!' WHERE `word_id` = 4359; -- mangos_string - content : entry=272
UPDATE `trans_words` SET `content_loc9`='Creature moved.' WHERE `word_id` = 4358; -- mangos_string - content : entry=271
UPDATE `trans_words` SET `content_loc9`='Creature movement disabled.' WHERE `word_id` = 4467; -- mangos_string - content : entry=404
UPDATE `trans_words` SET `content_loc9`='Creature movement enabled.' WHERE `word_id` = 4468; -- mangos_string - content : entry=405
UPDATE `trans_words` SET `content_loc9`='Creature movement type set to \'%s\', waypoints removed (if any).' WHERE `word_id` = 4345; -- mangos_string - content : entry=257
UPDATE `trans_words` SET `content_loc9`='Creature movement type set to \'%s\', waypoints were not removed.' WHERE `word_id` = 4346; -- mangos_string - content : entry=258
UPDATE `trans_words` SET `content_loc9`='Creature not found!' WHERE `word_id` = 4356; -- mangos_string - content : entry=268
UPDATE `trans_words` SET `content_loc9`='Creature Removed' WHERE `word_id` = 4357; -- mangos_string - content : entry=270
UPDATE `trans_words` SET `content_loc9`='Creatures with equal chance:' WHERE `word_id` = 4452; -- mangos_string - content : entry=389
UPDATE `trans_words` SET `content_loc9`='Creatures with explicitly chance:' WHERE `word_id` = 4451; -- mangos_string - content : entry=388
UPDATE `trans_words` SET `content_loc9`='Current energy: %u' WHERE `word_id` = 4253; -- mangos_string - content : entry=124
UPDATE `trans_words` SET `content_loc9`='Current gamemasters:' WHERE `word_id` = 4650; -- mangos_string - content : entry=597
UPDATE `trans_words` SET `content_loc9`='Current Message of the day: $B$B%s' WHERE `word_id` = 268204; -- mangos_string - content : entry=56
UPDATE `trans_words` SET `content_loc9`='Current phase = %u' WHERE `word_id` = 4910; -- mangos_string - content : entry=1506
UPDATE `trans_words` SET `content_loc9`='Current State Information: GOState %u, LootState %u. Collision %s' WHERE `word_id` = 4859; -- mangos_string - content : entry=1194
UPDATE `trans_words` SET `content_loc9`='Current State Information: GOState %u, LootState %u. Collision %s, (door %s by default)' WHERE `word_id` = 4860; -- mangos_string - content : entry=1195
UPDATE `trans_words` SET `content_loc9`='Currently Banned Accounts:' WHERE `word_id` = 4646; -- mangos_string - content : entry=593
UPDATE `trans_words` SET `content_loc9`='Currently Banned IPs:' WHERE `word_id` = 4648; -- mangos_string - content : entry=595
UPDATE `trans_words` SET `content_loc9`='Deleting the following characters:' WHERE `word_id` = 4774; -- mangos_string - content : entry=1021
UPDATE `trans_words` SET `content_loc9`='delta must be between 0 and %d (inclusive)' WHERE `word_id` = 4393; -- mangos_string - content : entry=310
UPDATE `trans_words` SET `content_loc9`='Despawned by event %u (%s)' WHERE `word_id` = 4815; -- mangos_string - content : entry=1144
UPDATE `trans_words` SET `content_loc9`='direct damage' WHERE `word_id` = 4864; -- mangos_string - content : entry=1204
UPDATE `trans_words` SET `content_loc9`='direct heal' WHERE `word_id` = 4863; -- mangos_string - content : entry=1203
UPDATE `trans_words` SET `content_loc9`='Dishonored' WHERE `word_id` = 4896; -- mangos_string - content : entry=1430
UPDATE `trans_words` SET `content_loc9`='Do not Disturb' WHERE `word_id` = 4688; -- mangos_string - content : entry=709
UPDATE `trans_words` SET `content_loc9`='Doesn\'t accept whispers' WHERE `word_id` = 4226; -- mangos_string - content : entry=64
UPDATE `trans_words` SET `content_loc9`='dot damage' WHERE `word_id` = 4866; -- mangos_string - content : entry=1206
UPDATE `trans_words` SET `content_loc9`='dot heal' WHERE `word_id` = 4865; -- mangos_string - content : entry=1205
UPDATE `trans_words` SET `content_loc9`='Dump file have broken data!' WHERE `word_id` = 4790; -- mangos_string - content : entry=1114
UPDATE `trans_words` SET `content_loc9`='Effect movement' WHERE `word_id` = 4858; -- mangos_string - content : entry=1192
UPDATE `trans_words` SET `content_loc9`='Error, name can only contain characters A-Z and a-z.' WHERE `word_id` = 4303; -- mangos_string - content : entry=203
UPDATE `trans_words` SET `content_loc9`='ERROR: You can only assign a new name for a single selected character!' WHERE `word_id` = 4775; -- mangos_string - content : entry=1022
UPDATE `trans_words` SET `content_loc9`='Event %u already active!' WHERE `word_id` = 4640; -- mangos_string - content : entry=587
UPDATE `trans_words` SET `content_loc9`='Event %u not active!' WHERE `word_id` = 4641; -- mangos_string - content : entry=588
UPDATE `trans_words` SET `content_loc9`='Event %u: %s%s$B$BStart: %s End: %s Occurence: %s Length: %s$B$BNext state change: %s' WHERE `word_id` = 4977; -- mangos_string - content : entry=586
UPDATE `trans_words` SET `content_loc9`='Event not exist!' WHERE `word_id` = 4638; -- mangos_string - content : entry=585
UPDATE `trans_words` SET `content_loc9`='event started %u "%s"' WHERE `word_id` = 4801; -- mangos_string - content : entry=1130
UPDATE `trans_words` SET `content_loc9`='event stopped %u "%s"' WHERE `word_id` = 4802; -- mangos_string - content : entry=1131
UPDATE `trans_words` SET `content_loc9`='Exiled' WHERE `word_id` = 4897; -- mangos_string - content : entry=1431
UPDATE `trans_words` SET `content_loc9`='Explore quest:' WHERE `word_id` = 4439; -- mangos_string - content : entry=366
UPDATE `trans_words` SET `content_loc9`='Extended item cost %u not exist' WHERE `word_id` = 4414; -- mangos_string - content : entry=331
UPDATE `trans_words` SET `content_loc9`='Faction %i unknown!' WHERE `word_id` = 4391; -- mangos_string - content : entry=308
UPDATE `trans_words` SET `content_loc9`='Faction %s (%u) can\'not have reputation.' WHERE `word_id` = 4409; -- mangos_string - content : entry=326
UPDATE `trans_words` SET `content_loc9`='Faction %s (%u) reputation of %s was set to %5d!' WHERE `word_id` = 4389; -- mangos_string - content : entry=305
UPDATE `trans_words` SET `content_loc9`='Failed to load the character!' WHERE `word_id` = 4540; -- mangos_string - content : entry=480
UPDATE `trans_words` SET `content_loc9`='Failed to open file: %s' WHERE `word_id` = 4788; -- mangos_string - content : entry=1112
UPDATE `trans_words` SET `content_loc9`='File imported.' WHERE `word_id` = 4320; -- mangos_string - content : entry=240
UPDATE `trans_words` SET `content_loc9`='Forced rename for player %s (GUID #%u) will be requested at next login.' WHERE `word_id` = 4342; -- mangos_string - content : entry=254
UPDATE `trans_words` SET `content_loc9`='Forced rename for player %s will be requested at next login.' WHERE `word_id` = 4341; -- mangos_string - content : entry=253
UPDATE `trans_words` SET `content_loc9`='Found creatures %u: %u' WHERE `word_id` = 4504; -- mangos_string - content : entry=441
UPDATE `trans_words` SET `content_loc9`='Found gameobjects %u: %u' WHERE `word_id` = 4502; -- mangos_string - content : entry=439
UPDATE `trans_words` SET `content_loc9`='Found items %u: %u ( inventory %u mail %u auction %u guild %u)' WHERE `word_id` = 4501; -- mangos_string - content : entry=438
UPDATE `trans_words` SET `content_loc9`='Found near gameobjects (distance %f): %u' WHERE `word_id` = 4634; -- mangos_string - content : entry=581
UPDATE `trans_words` SET `content_loc9`='Game Master' WHERE `word_id` = 4894; -- mangos_string - content : entry=1428
UPDATE `trans_words` SET `content_loc9`='Game Object (Entry: %u) have invalid data and can\'t be spawned' WHERE `word_id` = 4429; -- mangos_string - content : entry=348
UPDATE `trans_words` SET `content_loc9`='Game Object (Entry: %u) not found' WHERE `word_id` = 4581; -- mangos_string - content : entry=522
UPDATE `trans_words` SET `content_loc9`='Game Object (GUID: %u) has references in not found owner %s GO list, can\'t be deleted.' WHERE `word_id` = 4361; -- mangos_string - content : entry=274
UPDATE `trans_words` SET `content_loc9`='Game Object (GUID: %u) not found' WHERE `word_id` = 4360; -- mangos_string - content : entry=273
UPDATE `trans_words` SET `content_loc9`='Game Object (GUID: %u) removed' WHERE `word_id` = 4362; -- mangos_string - content : entry=275
UPDATE `trans_words` SET `content_loc9`='Game Object |cffffffff|Hgameobject:%d|h[%s]|h|r (GUID: %u) moved' WHERE `word_id` = 4364; -- mangos_string - content : entry=277
UPDATE `trans_words` SET `content_loc9`='Game Object |cffffffff|Hgameobject:%d|h[%s]|h|r (GUID: %u) turned' WHERE `word_id` = 4363; -- mangos_string - content : entry=276
UPDATE `trans_words` SET `content_loc9`='Gameobjects with equal chance:' WHERE `word_id` = 4454; -- mangos_string - content : entry=391
UPDATE `trans_words` SET `content_loc9`='Gameobjects with explicitly chance:' WHERE `word_id` = 4453; -- mangos_string - content : entry=390
UPDATE `trans_words` SET `content_loc9`='Get %s bitstr value:[FIELD]:%u [VALUE]:%s' WHERE `word_id` = 4824; -- mangos_string - content : entry=1153
UPDATE `trans_words` SET `content_loc9`='Get %s float value:[FIELD]:%u [VALUE]:%f' WHERE `word_id` = 4626; -- mangos_string - content : entry=571
UPDATE `trans_words` SET `content_loc9`='Get %s hex value:[FIELD]:%u [VALUE]:%x' WHERE `word_id` = 4826; -- mangos_string - content : entry=1155
UPDATE `trans_words` SET `content_loc9`='Get %s uint32 value:[FIELD]:%u [VALUE]:%u' WHERE `word_id` = 4624; -- mangos_string - content : entry=569
UPDATE `trans_words` SET `content_loc9`='Global notify:' WHERE `word_id` = 4229; -- mangos_string - content : entry=100
UPDATE `trans_words` SET `content_loc9`='GM Chat Badge is OFF' WHERE `word_id` = 4418; -- mangos_string - content : entry=335
UPDATE `trans_words` SET `content_loc9`='GM Chat Badge is ON' WHERE `word_id` = 4417; -- mangos_string - content : entry=334
UPDATE `trans_words` SET `content_loc9`='GM mode is OFF' WHERE `word_id` = 4416; -- mangos_string - content : entry=333
UPDATE `trans_words` SET `content_loc9`='GM mode is ON' WHERE `word_id` = 4415; -- mangos_string - content : entry=332
UPDATE `trans_words` SET `content_loc9`='Graveyard #%u (faction: %s) is nearest from linked to zone #%u.' WHERE `word_id` = 4521; -- mangos_string - content : entry=459
UPDATE `trans_words` SET `content_loc9`='Graveyard #%u already linked to zone #%u (current).' WHERE `word_id` = 4513; -- mangos_string - content : entry=450
UPDATE `trans_words` SET `content_loc9`='Graveyard #%u can\'t be linked to subzone or not existed zone #%u (internal error).' WHERE `word_id` = 4515; -- mangos_string - content : entry=452
UPDATE `trans_words` SET `content_loc9`='Graveyard #%u doesn\'t exist.' WHERE `word_id` = 4512; -- mangos_string - content : entry=449
UPDATE `trans_words` SET `content_loc9`='Graveyard #%u linked to zone #%u (current).' WHERE `word_id` = 4514; -- mangos_string - content : entry=451
UPDATE `trans_words` SET `content_loc9`='Grunt' WHERE `word_id` = 4882; -- mangos_string - content : entry=1415
UPDATE `trans_words` SET `content_loc9`='GUID %i, faction is %i, flags is %i, npcflag is %i, DY flag is %i' WHERE `word_id` = 4257; -- mangos_string - content : entry=128
UPDATE `trans_words` SET `content_loc9`='GUID: %u Name: %s Account: %s (%u) Date: %s' WHERE `word_id` = 4779; -- mangos_string - content : entry=1026
UPDATE `trans_words` SET `content_loc9`='Guild not created! (already exists?)' WHERE `word_id` = 4561; -- mangos_string - content : entry=501
UPDATE `trans_words` SET `content_loc9`='Health (base): %u. (max): %u. (current): %u.' WHERE `word_id` = 4600; -- mangos_string - content : entry=541
UPDATE `trans_words` SET `content_loc9`='Hello! Ready for some training?' WHERE `word_id` = 4214; -- mangos_string - content : entry=51
UPDATE `trans_words` SET `content_loc9`='Hostile' WHERE `word_id` = 4402; -- mangos_string - content : entry=319
UPDATE `trans_words` SET `content_loc9`='ID %u from %s (%s), changed %s' WHERE `word_id` = 4944; -- mangos_string - content : entry=1514
UPDATE `trans_words` SET `content_loc9`='ID %u from GUID %u (%s), changed %s' WHERE `word_id` = 4946; -- mangos_string - content : entry=1516
UPDATE `trans_words` SET `content_loc9`='id: %d eff: %d name: %s%s%s caster: %s' WHERE `word_id` = 4532; -- mangos_string - content : entry=470
UPDATE `trans_words` SET `content_loc9`='id: %d eff: %d type: %d duration: %d maxduration: %d name: %s%s%s caster: %s (stacks: %d)' WHERE `word_id` = 4530; -- mangos_string - content : entry=468
UPDATE `trans_words` SET `content_loc9`='Incorrect syntax.' WHERE `word_id` = 4173; -- mangos_string - content : entry=10
UPDATE `trans_words` SET `content_loc9`='Incorrect value, use on or off' WHERE `word_id` = 4347; -- mangos_string - content : entry=259
UPDATE `trans_words` SET `content_loc9`='Incorrect values.' WHERE `word_id` = 4244; -- mangos_string - content : entry=115
UPDATE `trans_words` SET `content_loc9`='Inf.' WHERE `word_id` = 4482; -- mangos_string - content : entry=419
UPDATE `trans_words` SET `content_loc9`='Informing you about arriving tickets is %s.' WHERE `word_id` = 4948; -- mangos_string - content : entry=1518
UPDATE `trans_words` SET `content_loc9`='InstanceID: %u' WHERE `word_id` = 4606; -- mangos_string - content : entry=547
UPDATE `trans_words` SET `content_loc9`='Invaid item count (%u) for item %u' WHERE `word_id` = 4215; -- mangos_string - content : entry=52
UPDATE `trans_words` SET `content_loc9`='Invalid character guid!' WHERE `word_id` = 4792; -- mangos_string - content : entry=1116
UPDATE `trans_words` SET `content_loc9`='Invalid character name!' WHERE `word_id` = 4791; -- mangos_string - content : entry=1115
UPDATE `trans_words` SET `content_loc9`='Invalid creature id: %u' WHERE `word_id` = 4503; -- mangos_string - content : entry=440
UPDATE `trans_words` SET `content_loc9`='Invalid gameobject id: %u' WHERE `word_id` = 4500; -- mangos_string - content : entry=437
UPDATE `trans_words` SET `content_loc9`='Invalid item id: %u' WHERE `word_id` = 4498; -- mangos_string - content : entry=435
UPDATE `trans_words` SET `content_loc9`='Invalid parameter %s' WHERE `word_id` = 4392; -- mangos_string - content : entry=309
UPDATE `trans_words` SET `content_loc9`='Invalid skill id (%u)' WHERE `word_id` = 4546; -- mangos_string - content : entry=486
UPDATE `trans_words` SET `content_loc9`='invalid team, please fix database' WHERE `word_id` = 4517; -- mangos_string - content : entry=455
UPDATE `trans_words` SET `content_loc9`='IP: %s$B$BBan Date: %s$B$BUnban Date: %s$B$BRemaining: %s$B$BReason: %s$B$BSet by: %s' WHERE `word_id` = 4972; -- mangos_string - content : entry=423
UPDATE `trans_words` SET `content_loc9`='Item \'%i\' \'%s\' added to list with maxcount \'%i\' and incrtime \'%i\'' WHERE `word_id` = 4306; -- mangos_string - content : entry=206
UPDATE `trans_words` SET `content_loc9`='Item \'%i\' \'%s\' Added to Slot %i' WHERE `word_id` = 4566; -- mangos_string - content : entry=506
UPDATE `trans_words` SET `content_loc9`='Item \'%i\' \'%s\' deleted from vendor list' WHERE `word_id` = 4308; -- mangos_string - content : entry=208
UPDATE `trans_words` SET `content_loc9`='Item \'%i\' \'%s\' Item Slot %i' WHERE `word_id` = 4564; -- mangos_string - content : entry=504
UPDATE `trans_words` SET `content_loc9`='Item \'%i\' already in vendor list.' WHERE `word_id` = 4310; -- mangos_string - content : entry=210
UPDATE `trans_words` SET `content_loc9`='Item \'%i\' doesn\'t exist.' WHERE `word_id` = 4565; -- mangos_string - content : entry=505
UPDATE `trans_words` SET `content_loc9`='Item \'%i\' not found in database.' WHERE `word_id` = 4307; -- mangos_string - content : entry=207
UPDATE `trans_words` SET `content_loc9`='Item \'%i\' not found in vendor list.' WHERE `word_id` = 4309; -- mangos_string - content : entry=209
UPDATE `trans_words` SET `content_loc9`='Item Ratio' WHERE `word_id` = 4846; -- mangos_string - content : entry=1180
UPDATE `trans_words` SET `content_loc9`='Item save failed!' WHERE `word_id` = 4567; -- mangos_string - content : entry=507
UPDATE `trans_words` SET `content_loc9`='Items ratio for %s is set to %u.' WHERE `word_id` = 4857; -- mangos_string - content : entry=1191
UPDATE `trans_words` SET `content_loc9`='Last Waypoint not found for %s' WHERE `word_id` = 4339; -- mangos_string - content : entry=221
UPDATE `trans_words` SET `content_loc9`='Last Week: [Kills: |c0000ff00%u|r] [Honor: %u] [Standing: %u]' WHERE `word_id` = 4904; -- mangos_string - content : entry=1438
UPDATE `trans_words` SET `content_loc9`='Let the battle for Warsong Gulch begin!' WHERE `word_id` = 4657; -- mangos_string - content : entry=604
UPDATE `trans_words` SET `content_loc9`='Level: %u.' WHERE `word_id` = 4599; -- mangos_string - content : entry=540
UPDATE `trans_words` SET `content_loc9`='Life Time: [Rank Points: |c0000ff00%f|r] [Honorable Kills: |c0000ff00%u|r] [Dishonorable Kills: |c00ff0000%u|r] [Highest Rank %u: %s]' WHERE `word_id` = 4905; -- mangos_string - content : entry=1439
UPDATE `trans_words` SET `content_loc9`='Liquid level: %f, ground: %f, type flags %u, status: %d.' WHERE `word_id` = 4299; -- mangos_string - content : entry=175
UPDATE `trans_words` SET `content_loc9`='List known talents:' WHERE `word_id` = 4806; -- mangos_string - content : entry=1135
UPDATE `trans_words` SET `content_loc9`='Locations found are:$B$B %s' WHERE `word_id` = 5085; -- mangos_string - content : entry=168
UPDATE `trans_words` SET `content_loc9`='Log filters state:' WHERE `word_id` = 4780; -- mangos_string - content : entry=1027
UPDATE `trans_words` SET `content_loc9`='Loot: %u Pickpocket: %u Skinning: %u' WHERE `word_id` = 4602; -- mangos_string - content : entry=543
UPDATE `trans_words` SET `content_loc9`='Mail can\'t have more %u item stacks' WHERE `word_id` = 4216; -- mangos_string - content : entry=53
UPDATE `trans_words` SET `content_loc9`='Mail sent to %s' WHERE `word_id` = 4295; -- mangos_string - content : entry=169
UPDATE `trans_words` SET `content_loc9`='Map: %u (%s) Zone: %u (%s) Area: %u (%s)$B$BX: %f Y: %f Z: %f Orientation: %f$B$Bgrid[%u,%u]cell[%u,%u] InstanceID: %u$B$B ZoneX: %f ZoneY: %f$B$BGroundZ: %f FloorZ: %f Have height data (Map: %u VMap: %u)' WHERE `word_id` = 4953; -- mangos_string - content : entry=101
UPDATE `trans_words` SET `content_loc9`='Melee attacking is %s' WHERE `word_id` = 4912; -- mangos_string - content : entry=1508
UPDATE `trans_words` SET `content_loc9`='Message of the day changed to:$B$B%s' WHERE `word_id` = 268205; -- mangos_string - content : entry=1101
UPDATE `trans_words` SET `content_loc9`='Message sent to %s: %s' WHERE `word_id` = 4785; -- mangos_string - content : entry=1102
UPDATE `trans_words` SET `content_loc9`='Modify %s float field:%u to sum with:%f = %f' WHERE `word_id` = 4830; -- mangos_string - content : entry=1159
UPDATE `trans_words` SET `content_loc9`='Modify %s hex field:%u %s %x = %x (hex)' WHERE `word_id` = 4828; -- mangos_string - content : entry=1157
UPDATE `trans_words` SET `content_loc9`='Modify %s uint32 field:%u to sum with:%i = %u (%i)' WHERE `word_id` = 4628; -- mangos_string - content : entry=575
UPDATE `trans_words` SET `content_loc9`='New ticket from %s' WHERE `word_id` = 4374; -- mangos_string - content : entry=289
UPDATE `trans_words` SET `content_loc9`='New ticket show: OFF' WHERE `word_id` = 4376; -- mangos_string - content : entry=292
UPDATE `trans_words` SET `content_loc9`='New ticket show: ON' WHERE `word_id` = 4375; -- mangos_string - content : entry=291
UPDATE `trans_words` SET `content_loc9`='No area found!' WHERE `word_id` = 4505; -- mangos_string - content : entry=442
UPDATE `trans_words` SET `content_loc9`='No areatriggers found!' WHERE `word_id` = 4431; -- mangos_string - content : entry=358
UPDATE `trans_words` SET `content_loc9`='No character selected.' WHERE `word_id` = 4245; -- mangos_string - content : entry=116
UPDATE `trans_words` SET `content_loc9`='No characters found.' WHERE `word_id` = 4772; -- mangos_string - content : entry=1019
UPDATE `trans_words` SET `content_loc9`='No creatures found!' WHERE `word_id` = 4510; -- mangos_string - content : entry=447
UPDATE `trans_words` SET `content_loc9`='No event found!' WHERE `word_id` = 4637; -- mangos_string - content : entry=584
UPDATE `trans_words` SET `content_loc9`='No faction found!' WHERE `word_id` = 4390; -- mangos_string - content : entry=307
UPDATE `trans_words` SET `content_loc9`='No faction in Graveyard with id= #%u , fix your DB' WHERE `word_id` = 4516; -- mangos_string - content : entry=454
UPDATE `trans_words` SET `content_loc9`='No gamemasters.' WHERE `word_id` = 4652; -- mangos_string - content : entry=599
UPDATE `trans_words` SET `content_loc9`='No gameobjects found!' WHERE `word_id` = 4511; -- mangos_string - content : entry=448
UPDATE `trans_words` SET `content_loc9`='No GUID provided.' WHERE `word_id` = 4329; -- mangos_string - content : entry=231
UPDATE `trans_words` SET `content_loc9`='No item sets found!' WHERE `word_id` = 4506; -- mangos_string - content : entry=443
UPDATE `trans_words` SET `content_loc9`='No items found!' WHERE `word_id` = 4499; -- mangos_string - content : entry=436
UPDATE `trans_words` SET `content_loc9`='No items from itemset \'%u\' found.' WHERE `word_id` = 4562; -- mangos_string - content : entry=502
UPDATE `trans_words` SET `content_loc9`='No online players.' WHERE `word_id` = 4767; -- mangos_string - content : entry=1014
UPDATE `trans_words` SET `content_loc9`='No players found!' WHERE `word_id` = 4413; -- mangos_string - content : entry=330
UPDATE `trans_words` SET `content_loc9`='No pools found for map \'%s\' (Id:%u)' WHERE `word_id` = 4445; -- mangos_string - content : entry=377
UPDATE `trans_words` SET `content_loc9`='No pools found' WHERE `word_id` = 4458; -- mangos_string - content : entry=395
UPDATE `trans_words` SET `content_loc9`='No quests found!' WHERE `word_id` = 4509; -- mangos_string - content : entry=446
UPDATE `trans_words` SET `content_loc9`='No Rank' WHERE `word_id` = 4895; -- mangos_string - content : entry=1429
UPDATE `trans_words` SET `content_loc9`='No selection.' WHERE `word_id` = 4300; -- mangos_string - content : entry=200
UPDATE `trans_words` SET `content_loc9`='No skills found!' WHERE `word_id` = 4507; -- mangos_string - content : entry=444
UPDATE `trans_words` SET `content_loc9`='No spells found!' WHERE `word_id` = 4508; -- mangos_string - content : entry=445
UPDATE `trans_words` SET `content_loc9`='No taxinodes found!' WHERE `word_id` = 4528; -- mangos_string - content : entry=466
UPDATE `trans_words` SET `content_loc9`='No visual waypoints found' WHERE `word_id` = 4333; -- mangos_string - content : entry=227
UPDATE `trans_words` SET `content_loc9`='No waypoint number provided.' WHERE `word_id` = 4328; -- mangos_string - content : entry=232
UPDATE `trans_words` SET `content_loc9`='No waypoints found inside the database.' WHERE `word_id` = 4321; -- mangos_string - content : entry=239
UPDATE `trans_words` SET `content_loc9`='No' WHERE `word_id` = 4485; -- mangos_string - content : entry=422
UPDATE `trans_words` SET `content_loc9`='Not enough players. This game will close in %u mins.' WHERE `word_id` = 4707; -- mangos_string - content : entry=750
UPDATE `trans_words` SET `content_loc9`='Not enough players. This game will close in %u seconds.' WHERE `word_id` = 4708; -- mangos_string - content : entry=751
UPDATE `trans_words` SET `content_loc9`='Not yet implemented' WHERE `word_id` = 4305; -- mangos_string - content : entry=205
UPDATE `trans_words` SET `content_loc9`='Nothing found!' WHERE `word_id` = 4354; -- mangos_string - content : entry=266
UPDATE `trans_words` SET `content_loc9`='Object GUID is: %s' WHERE `word_id` = 4301; -- mangos_string - content : entry=201
UPDATE `trans_words` SET `content_loc9`='Object not found!' WHERE `word_id` = 4355; -- mangos_string - content : entry=267
UPDATE `trans_words` SET `content_loc9`='off' WHERE `word_id` = 4202; -- mangos_string - content : entry=39
UPDATE `trans_words` SET `content_loc9`='Officer' WHERE `word_id` = 4750; -- mangos_string - content : entry=812
UPDATE `trans_words` SET `content_loc9`='on' WHERE `word_id` = 4201; -- mangos_string - content : entry=38
UPDATE `trans_words` SET `content_loc9`='Online players: %u (max: %u) Queued players: %u (max: %u)' WHERE `word_id` = 4175; -- mangos_string - content : entry=12
UPDATE `trans_words` SET `content_loc9`='Only the Alliance can use that portal' WHERE `word_id` = 4709; -- mangos_string - content : entry=752
UPDATE `trans_words` SET `content_loc9`='Only the Horde can use that portal' WHERE `word_id` = 4710; -- mangos_string - content : entry=753
UPDATE `trans_words` SET `content_loc9`='Opcode %u sent to %s' WHERE `word_id` = 4538; -- mangos_string - content : entry=478
UPDATE `trans_words` SET `content_loc9`='Opcode %u with target %s was received from you.' WHERE `word_id` = 268203; -- mangos_string - content : entry=555
UPDATE `trans_words` SET `content_loc9`='Outlaw' WHERE `word_id` = 4898; -- mangos_string - content : entry=1432
UPDATE `trans_words` SET `content_loc9`='Pariah' WHERE `word_id` = 4899; -- mangos_string - content : entry=1433
UPDATE `trans_words` SET `content_loc9`='Part of pool %u' WHERE `word_id` = 4816; -- mangos_string - content : entry=1145
UPDATE `trans_words` SET `content_loc9`='Part of pool %u, top pool %u' WHERE `word_id` = 4817; -- mangos_string - content : entry=1146
UPDATE `trans_words` SET `content_loc9`='Password not changed (unknown error)!' WHERE `word_id` = 4188; -- mangos_string - content : entry=25
UPDATE `trans_words` SET `content_loc9`='Password:' WHERE `word_id` = 4224; -- mangos_string - content : entry=62
UPDATE `trans_words` SET `content_loc9`='Played time: %s Level: %u Money: %ug%us%uc' WHERE `word_id` = 4608; -- mangos_string - content : entry=549
UPDATE `trans_words` SET `content_loc9`='Player %s (Guid: %u) Account %s (Id: %u) deleted.' WHERE `word_id` = 4763; -- mangos_string - content : entry=1009
UPDATE `trans_words` SET `content_loc9`='Player %s kicked.' WHERE `word_id` = 4369; -- mangos_string - content : entry=282
UPDATE `trans_words` SET `content_loc9`='Player %s must have skill %u (%s) before using this command.' WHERE `word_id` = 4545; -- mangos_string - content : entry=485
UPDATE `trans_words` SET `content_loc9`='Player %s not found or offline' WHERE `word_id` = 4747; -- mangos_string - content : entry=808
UPDATE `trans_words` SET `content_loc9`='Player %s not have tickets.' WHERE `word_id` = 4443; -- mangos_string - content : entry=375
UPDATE `trans_words` SET `content_loc9`='Player (%s) does not exist.' WHERE `word_id` = 4241; -- mangos_string - content : entry=112
UPDATE `trans_words` SET `content_loc9`='Player already has a guild!' WHERE `word_id` = 4560; -- mangos_string - content : entry=500
UPDATE `trans_words` SET `content_loc9`='Player not found!' WHERE `word_id` = 4559; -- mangos_string - content : entry=499
UPDATE `trans_words` SET `content_loc9`='Player saved.' WHERE `word_id` = 4177; -- mangos_string - content : entry=14
UPDATE `trans_words` SET `content_loc9`='Player selected: %s.$B$BFaction: %u.$B$BnpcFlags: %u.$B$BEntry: %u.$B$BDisplayID: %u (Native: %u).' WHERE `word_id` = 4598; -- mangos_string - content : entry=539
UPDATE `trans_words` SET `content_loc9`='Player%s %s (guid: %u) Account: %s (id: %u) GMLevel: %u E-mail: %s Last IP: %s Last login: %s Latency: %ums' WHERE `word_id` = 4607; -- mangos_string - content : entry=548
UPDATE `trans_words` SET `content_loc9`='Player: %s - %s (Rank %u)' WHERE `word_id` = 4900; -- mangos_string - content : entry=1434
UPDATE `trans_words` SET `content_loc9`='Player\'s chat is already enabled.' WHERE `word_id` = 4386; -- mangos_string - content : entry=302
UPDATE `trans_words` SET `content_loc9`='Please provide character name' WHERE `word_id` = 4746; -- mangos_string - content : entry=807
UPDATE `trans_words` SET `content_loc9`='Pool %u - Mother pool: %u [%s] AutoSpawn: %u MaxLimit: %u' WHERE `word_id` = 4456; -- mangos_string - content : entry=393
UPDATE `trans_words` SET `content_loc9`='Pool %u - Mother pool: %u |cffffffff|Hpool:%u|h[%s]|h|r AutoSpawn: %u MaxLimit: %u' WHERE `word_id` = 4455; -- mangos_string - content : entry=392
UPDATE `trans_words` SET `content_loc9`='Pool %u - Mother pool: none AutoSpawn: %u MaxLimit: %u' WHERE `word_id` = 4457; -- mangos_string - content : entry=394
UPDATE `trans_words` SET `content_loc9`='Pool %u not found (Maximal pool entry is %u)' WHERE `word_id` = 4913; -- mangos_string - content : entry=1509
UPDATE `trans_words` SET `content_loc9`='Pools with equal chance:' WHERE `word_id` = 4461; -- mangos_string - content : entry=398
UPDATE `trans_words` SET `content_loc9`='Pools with explicitly chance:' WHERE `word_id` = 4460; -- mangos_string - content : entry=397
UPDATE `trans_words` SET `content_loc9`='Position: %f %f %f.' WHERE `word_id` = 4603; -- mangos_string - content : entry=544
UPDATE `trans_words` SET `content_loc9`='Quest %u not found.' WHERE `word_id` = 4533; -- mangos_string - content : entry=471
UPDATE `trans_words` SET `content_loc9`='Quest %u started from item. For correct work, please, add item to inventory and start quest in normal way: .additem %u' WHERE `word_id` = 4534; -- mangos_string - content : entry=472
UPDATE `trans_words` SET `content_loc9`='Quest removed.' WHERE `word_id` = 4535; -- mangos_string - content : entry=473
UPDATE `trans_words` SET `content_loc9`='Queue status for %s (Lvl: %u to %u)$B$BQueued alliances: %u (Need at least %u more)$B$BQueued hordes: %u (Need at least %u more)' WHERE `word_id` = 5007; -- mangos_string - content : entry=711
UPDATE `trans_words` SET `content_loc9`='Removed bit %i in field %i.' WHERE `word_id` = 4288; -- mangos_string - content : entry=161
UPDATE `trans_words` SET `content_loc9`='Removed itemID = %i, amount = %i from %s' WHERE `word_id` = 4556; -- mangos_string - content : entry=496
UPDATE `trans_words` SET `content_loc9`='Requires search parameter.' WHERE `word_id` = 4292; -- mangos_string - content : entry=165
UPDATE `trans_words` SET `content_loc9`='Response:$B$B%s' WHERE `word_id` = 5067; -- mangos_string - content : entry=373
UPDATE `trans_words` SET `content_loc9`='Restoring the following characters:' WHERE `word_id` = 4773; -- mangos_string - content : entry=1020
UPDATE `trans_words` SET `content_loc9`='Revered' WHERE `word_id` = 4407; -- mangos_string - content : entry=324
UPDATE `trans_words` SET `content_loc9`='ScriptID set to non-existing id %u, add it to DBScriptsEngine and reload the table.' WHERE `word_id` = 4933; -- mangos_string - content : entry=250
UPDATE `trans_words` SET `content_loc9`='Scripting library not found or not accessible.' WHERE `word_id` = 4833; -- mangos_string - content : entry=1166
UPDATE `trans_words` SET `content_loc9`='Selected object:$B$B|cffffffff|Hgameobject:%d|h[%s]|h|r GUID: %u ID: %u$B$BX: %f Y: %f Z: %f MapId: %u$B$BOrientation: %f' WHERE `word_id` = 4974; -- mangos_string - content : entry=524
UPDATE `trans_words` SET `content_loc9`='Selected player or creature not have victim.' WHERE `word_id` = 4632; -- mangos_string - content : entry=579
UPDATE `trans_words` SET `content_loc9`='server console command' WHERE `word_id` = 4298; -- mangos_string - content : entry=172
UPDATE `trans_words` SET `content_loc9`='Server uptime: %s' WHERE `word_id` = 4176; -- mangos_string - content : entry=13
UPDATE `trans_words` SET `content_loc9`='Set bit %i in field %i.' WHERE `word_id` = 4289; -- mangos_string - content : entry=162
UPDATE `trans_words` SET `content_loc9`='Set for %s field:%u to to float value:%f' WHERE `word_id` = 4622; -- mangos_string - content : entry=567
UPDATE `trans_words` SET `content_loc9`='Set for %s field:%u to uint32 value:%u' WHERE `word_id` = 4620; -- mangos_string - content : entry=565
UPDATE `trans_words` SET `content_loc9`='Skill %u (%s) for player %s set to %u and current maximum set to %u (without permanent (talent) bonuses).' WHERE `word_id` = 4544; -- mangos_string - content : entry=484
UPDATE `trans_words` SET `content_loc9`='Someone in your party is already in this battleground queue. (S)he must leave it before joining as group.' WHERE `word_id` = 4698; -- mangos_string - content : entry=730
UPDATE `trans_words` SET `content_loc9`='Someone in your party is already in three battleground queues. You cannot join as group.' WHERE `word_id` = 4700; -- mangos_string - content : entry=732
UPDATE `trans_words` SET `content_loc9`='Someone in your party is Deserter. You can\'t join as group.' WHERE `word_id` = 4699; -- mangos_string - content : entry=731
UPDATE `trans_words` SET `content_loc9`='Spawn distance changed to: %f' WHERE `word_id` = 4381; -- mangos_string - content : entry=297
UPDATE `trans_words` SET `content_loc9`='Spawn time changed to: %i' WHERE `word_id` = 4382; -- mangos_string - content : entry=298
UPDATE `trans_words` SET `content_loc9`='Spawned by event %u (%s)' WHERE `word_id` = 4814; -- mangos_string - content : entry=1143
UPDATE `trans_words` SET `content_loc9`='SpawnTime: Full:%s Remain:%s' WHERE `word_id` = 4635; -- mangos_string - content : entry=582
UPDATE `trans_words` SET `content_loc9`='Spell %u %s = %f (*1.88 = %f) DB = %f AP = %f' WHERE `word_id` = 4862; -- mangos_string - content : entry=1202
UPDATE `trans_words` SET `content_loc9`='Spell %u broken and not allowed to cast or learn!' WHERE `word_id` = 4543; -- mangos_string - content : entry=483
UPDATE `trans_words` SET `content_loc9`='Spell %u cooldown removed for %s.' WHERE `word_id` = 4553; -- mangos_string - content : entry=493
UPDATE `trans_words` SET `content_loc9`='Spell %u not have auras.' WHERE `word_id` = 4832; -- mangos_string - content : entry=1165
UPDATE `trans_words` SET `content_loc9`='Spells of %s reset.' WHERE `word_id` = 4311; -- mangos_string - content : entry=211
UPDATE `trans_words` SET `content_loc9`='Spells of %s will reset at next login.' WHERE `word_id` = 4312; -- mangos_string - content : entry=212
UPDATE `trans_words` SET `content_loc9`='Spells will reset for all players at login. Strongly recommend re-login!' WHERE `word_id` = 4318; -- mangos_string - content : entry=218
UPDATE `trans_words` SET `content_loc9`='Talents of %s reset.' WHERE `word_id` = 4313; -- mangos_string - content : entry=213
UPDATE `trans_words` SET `content_loc9`='Talents of %s will reset at next login.' WHERE `word_id` = 4314; -- mangos_string - content : entry=214
UPDATE `trans_words` SET `content_loc9`='Talents will reset for all players at login. Strongly recommend re-login!' WHERE `word_id` = 4319; -- mangos_string - content : entry=219
UPDATE `trans_words` SET `content_loc9`='Target map or coordinates is invalid (X: %f Y: %f MapId: %u)' WHERE `word_id` = 4351; -- mangos_string - content : entry=263
UPDATE `trans_words` SET `content_loc9`='Target unit has %d auras of type %d:' WHERE `word_id` = 4531; -- mangos_string - content : entry=469
UPDATE `trans_words` SET `content_loc9`='Target unit has %d auras:' WHERE `word_id` = 4529; -- mangos_string - content : entry=467
UPDATE `trans_words` SET `content_loc9`='Target(%s) already know that spell.' WHERE `word_id` = 4549; -- mangos_string - content : entry=489
UPDATE `trans_words` SET `content_loc9`='TaxiNode ID %u not found!' WHERE `word_id` = 4428; -- mangos_string - content : entry=347
UPDATE `trans_words` SET `content_loc9`='Teleport location added.' WHERE `word_id` = 4525; -- mangos_string - content : entry=463
UPDATE `trans_words` SET `content_loc9`='Teleport location already exists!' WHERE `word_id` = 4524; -- mangos_string - content : entry=462
UPDATE `trans_words` SET `content_loc9`='Teleport location deleted.' WHERE `word_id` = 4527; -- mangos_string - content : entry=465
UPDATE `trans_words` SET `content_loc9`='Teleport location NOT added: database error.' WHERE `word_id` = 4526; -- mangos_string - content : entry=464
UPDATE `trans_words` SET `content_loc9`='Teleport location not found!' WHERE `word_id` = 4291; -- mangos_string - content : entry=164
UPDATE `trans_words` SET `content_loc9`='Teleport location table is empty!' WHERE `word_id` = 4290; -- mangos_string - content : entry=163
UPDATE `trans_words` SET `content_loc9`='The %s field of %s was set to %u' WHERE `word_id` = 4383; -- mangos_string - content : entry=299
UPDATE `trans_words` SET `content_loc9`='The %s has taken the %s' WHERE `word_id` = 4674; -- mangos_string - content : entry=657
UPDATE `trans_words` SET `content_loc9`='The %s has taken the %s! Its supplies will now be used for reinforcements!' WHERE `word_id` = 4715; -- mangos_string - content : entry=765
UPDATE `trans_words` SET `content_loc9`='The %s is under attack! If left unchecked, the %s will capture it!' WHERE `word_id` = 4714; -- mangos_string - content : entry=764
UPDATE `trans_words` SET `content_loc9`='The %s is under attack! If left unchecked, the %s will destroy it!' WHERE `word_id` = 4712; -- mangos_string - content : entry=760
UPDATE `trans_words` SET `content_loc9`='The %s was taken by the %s!' WHERE `word_id` = 4713; -- mangos_string - content : entry=761
UPDATE `trans_words` SET `content_loc9`='The (top)pool %u is despawned by event %u (%s)' WHERE `word_id` = 4819; -- mangos_string - content : entry=1148
UPDATE `trans_words` SET `content_loc9`='The (top)pool %u is spawned by event %u (%s)' WHERE `word_id` = 4818; -- mangos_string - content : entry=1147
UPDATE `trans_words` SET `content_loc9`='The Alliance flag is now placed at its base.' WHERE `word_id` = 4667; -- mangos_string - content : entry=614
UPDATE `trans_words` SET `content_loc9`='The Alliance Flag was dropped by $N!' WHERE `word_id` = 4661; -- mangos_string - content : entry=608
UPDATE `trans_words` SET `content_loc9`='The Alliance Flag was picked up by $N!' WHERE `word_id` = 4665; -- mangos_string - content : entry=612
UPDATE `trans_words` SET `content_loc9`='The Alliance Flag was returned to its base by $N!' WHERE `word_id` = 4662; -- mangos_string - content : entry=609
UPDATE `trans_words` SET `content_loc9`='The Alliance has gathered $1776W resources, and is near victory!' WHERE `word_id` = 4681; -- mangos_string - content : entry=664
UPDATE `trans_words` SET `content_loc9`='The Alliance Team is running out of reinforcements!' WHERE `word_id` = 4736; -- mangos_string - content : entry=787
UPDATE `trans_words` SET `content_loc9`='The Alliance wins!' WHERE `word_id` = 4653; -- mangos_string - content : entry=600
UPDATE `trans_words` SET `content_loc9`='The area has been set as explored.' WHERE `word_id` = 4617; -- mangos_string - content : entry=560
UPDATE `trans_words` SET `content_loc9`='The area has been set as not explored.' WHERE `word_id` = 4618; -- mangos_string - content : entry=561
UPDATE `trans_words` SET `content_loc9`='The Battle for Arathi Basin begins in 1 minute.' WHERE `word_id` = 4678; -- mangos_string - content : entry=661
UPDATE `trans_words` SET `content_loc9`='The Battle for Arathi Basin begins in 30 seconds. Prepare yourselves!' WHERE `word_id` = 4679; -- mangos_string - content : entry=662
UPDATE `trans_words` SET `content_loc9`='The Battle for Arathi Basin has begun!' WHERE `word_id` = 4680; -- mangos_string - content : entry=663
UPDATE `trans_words` SET `content_loc9`='The battle for Warsong Gulch begins in 1 minute.' WHERE `word_id` = 4655; -- mangos_string - content : entry=602
UPDATE `trans_words` SET `content_loc9`='The battle for Warsong Gulch begins in 30 seconds. Prepare yourselves!' WHERE `word_id` = 4656; -- mangos_string - content : entry=603
UPDATE `trans_words` SET `content_loc9`='The distance is: (3D) %f (2D) %f - (3D, point-to-point) %f yards.' WHERE `word_id` = 4563; -- mangos_string - content : entry=503
UPDATE `trans_words` SET `content_loc9`='The flags are now placed at their bases.' WHERE `word_id` = 4666; -- mangos_string - content : entry=613
UPDATE `trans_words` SET `content_loc9`='The following accounts match your query:' WHERE `word_id` = 4491; -- mangos_string - content : entry=428
UPDATE `trans_words` SET `content_loc9`='The following IPs match your pattern:' WHERE `word_id` = 4490; -- mangos_string - content : entry=427
UPDATE `trans_words` SET `content_loc9`='The Frostwolf General is Dead!' WHERE `word_id` = 4738; -- mangos_string - content : entry=789
UPDATE `trans_words` SET `content_loc9`='The GO state of GO lowGuid %u is %u.' WHERE `word_id` = 4936; -- mangos_string - content : entry=574
UPDATE `trans_words` SET `content_loc9`='The Horde flag is now placed at its base.' WHERE `word_id` = 4668; -- mangos_string - content : entry=615
UPDATE `trans_words` SET `content_loc9`='The Horde flag was dropped by $N!' WHERE `word_id` = 4660; -- mangos_string - content : entry=607
UPDATE `trans_words` SET `content_loc9`='The Horde flag was picked up by $N!' WHERE `word_id` = 4664; -- mangos_string - content : entry=611
UPDATE `trans_words` SET `content_loc9`='The Horde flag was returned to its base by $N!' WHERE `word_id` = 4663; -- mangos_string - content : entry=610
UPDATE `trans_words` SET `content_loc9`='The Horde has gathered $1777W resources, and is near victory!' WHERE `word_id` = 4682; -- mangos_string - content : entry=665
UPDATE `trans_words` SET `content_loc9`='The Horde Team is running out of reinforcements!' WHERE `word_id` = 4737; -- mangos_string - content : entry=788
UPDATE `trans_words` SET `content_loc9`='The Horde wins!' WHERE `word_id` = 4654; -- mangos_string - content : entry=601
UPDATE `trans_words` SET `content_loc9`='The lootstate of GO lowGuid %u is %u.' WHERE `word_id` = 4935; -- mangos_string - content : entry=573
UPDATE `trans_words` SET `content_loc9`='The name was too long by %i characters.' WHERE `word_id` = 4302; -- mangos_string - content : entry=202
UPDATE `trans_words` SET `content_loc9`='The new passwords do not match' WHERE `word_id` = 4217; -- mangos_string - content : entry=54
UPDATE `trans_words` SET `content_loc9`='The old password is wrong' WHERE `word_id` = 4190; -- mangos_string - content : entry=27
UPDATE `trans_words` SET `content_loc9`='The password was changed' WHERE `word_id` = 4189; -- mangos_string - content : entry=26
UPDATE `trans_words` SET `content_loc9`='The Stormpike General is Dead!' WHERE `word_id` = 4739; -- mangos_string - content : entry=790
UPDATE `trans_words` SET `content_loc9`='The subname was too long by %i characters.' WHERE `word_id` = 4304; -- mangos_string - content : entry=204
UPDATE `trans_words` SET `content_loc9`='The value index %u is too big to %s (count: %u).' WHERE `word_id` = 4619; -- mangos_string - content : entry=564
UPDATE `trans_words` SET `content_loc9`='There are no GMs currently logged in on this server.' WHERE `word_id` = 4180; -- mangos_string - content : entry=17
UPDATE `trans_words` SET `content_loc9`='There are no teleport locations matching your request.' WHERE `word_id` = 4293; -- mangos_string - content : entry=166
UPDATE `trans_words` SET `content_loc9`='There are the following active GMs on this server:' WHERE `word_id` = 4179; -- mangos_string - content : entry=16
UPDATE `trans_words` SET `content_loc9`='There is no banned account owning a character matching this part.' WHERE `word_id` = 4489; -- mangos_string - content : entry=426
UPDATE `trans_words` SET `content_loc9`='There is no help for that command' WHERE `word_id` = 4168; -- mangos_string - content : entry=5
UPDATE `trans_words` SET `content_loc9`='There is no matching account.' WHERE `word_id` = 4488; -- mangos_string - content : entry=425
UPDATE `trans_words` SET `content_loc9`='There is no matching IPban.' WHERE `word_id` = 4487; -- mangos_string - content : entry=424
UPDATE `trans_words` SET `content_loc9`='There is no such character.' WHERE `word_id` = 4477; -- mangos_string - content : entry=414
UPDATE `trans_words` SET `content_loc9`='There is no such command' WHERE `word_id` = 4169; -- mangos_string - content : entry=6
UPDATE `trans_words` SET `content_loc9`='There is no such IP in banlist.' WHERE `word_id` = 4478; -- mangos_string - content : entry=415
UPDATE `trans_words` SET `content_loc9`='There is no such mount.' WHERE `word_id` = 4276; -- mangos_string - content : entry=149
UPDATE `trans_words` SET `content_loc9`='There is no such subcommand' WHERE `word_id` = 4170; -- mangos_string - content : entry=7
UPDATE `trans_words` SET `content_loc9`='There was an error removing the ban on %s.' WHERE `word_id` = 4475; -- mangos_string - content : entry=412
UPDATE `trans_words` SET `content_loc9`='This Battleground is disabled by the server administration.' WHERE `word_id` = 4937; -- mangos_string - content : entry=714
UPDATE `trans_words` SET `content_loc9`='This Instance is disabled by the server administration.' WHERE `word_id` = 4938; -- mangos_string - content : entry=747
UPDATE `trans_words` SET `content_loc9`='This item(s) has problems with equipping/storing to inventory.' WHERE `word_id` = 4685; -- mangos_string - content : entry=706
UPDATE `trans_words` SET `content_loc9`='This Week: [Kills: |c0000ff00%u|r] [Honor: %u]' WHERE `word_id` = 4903; -- mangos_string - content : entry=1437
UPDATE `trans_words` SET `content_loc9`='Ticket %i doesn\'t exist' WHERE `word_id` = 4377; -- mangos_string - content : entry=293
UPDATE `trans_words` SET `content_loc9`='Ticket deleted.' WHERE `word_id` = 4380; -- mangos_string - content : entry=296
UPDATE `trans_words` SET `content_loc9`='Ticket of %s (Last updated: %s):$B$B%s' WHERE `word_id` = 5061; -- mangos_string - content : entry=290
UPDATE `trans_words` SET `content_loc9`='Ticket system is globally off, not accepting tickets at all' WHERE `word_id` = 4926; -- mangos_string - content : entry=1512
UPDATE `trans_words` SET `content_loc9`='Ticket system is globally on, accepting all tickets' WHERE `word_id` = 4925; -- mangos_string - content : entry=1511
UPDATE `trans_words` SET `content_loc9`='Tickets count: %i show new tickets: %s' WHERE `word_id` = 4373; -- mangos_string - content : entry=288
UPDATE `trans_words` SET `content_loc9`='Tickets count: %i' WHERE `word_id` = 4442; -- mangos_string - content : entry=374
UPDATE `trans_words` SET `content_loc9`='Today: [Honorable Kills: |c0000ff00%u|r] [Dishonorable Kills: |c00ff0000%u|r]' WHERE `word_id` = 4901; -- mangos_string - content : entry=1435
UPDATE `trans_words` SET `content_loc9`='Unfriendly' WHERE `word_id` = 4403; -- mangos_string - content : entry=320
UPDATE `trans_words` SET `content_loc9`='Unit Flags: %u.$B$BDynamic Flags: %u.$B$BFaction Template: %u.' WHERE `word_id` = 4601; -- mangos_string - content : entry=542
UPDATE `trans_words` SET `content_loc9`='Unknown case \'%s\' for .resetall command. Type full correct case name.' WHERE `word_id` = 4317; -- mangos_string - content : entry=217
UPDATE `trans_words` SET `content_loc9`='Unknown language' WHERE `word_id` = 4744; -- mangos_string - content : entry=805
UPDATE `trans_words` SET `content_loc9`='UNKNOWN' WHERE `word_id` = 4211; -- mangos_string - content : entry=48
UPDATE `trans_words` SET `content_loc9`='USER1: %i, ADD: %i, DIF: %i' WHERE `word_id` = 4279; -- mangos_string - content : entry=152
UPDATE `trans_words` SET `content_loc9`='USER2: %i, ADD: %i, RESULT: %i' WHERE `word_id` = 4287; -- mangos_string - content : entry=160
UPDATE `trans_words` SET `content_loc9`='Username:' WHERE `word_id` = 4223; -- mangos_string - content : entry=61
UPDATE `trans_words` SET `content_loc9`='Using creature EventAI: %s' WHERE `word_id` = 4222; -- mangos_string - content : entry=59
UPDATE `trans_words` SET `content_loc9`='Using script library' WHERE `word_id` = 4221; -- mangos_string - content : entry=58
UPDATE `trans_words` SET `content_loc9`='Using script library: <No Script Library Loaded>' WHERE `word_id` = 4228; -- mangos_string - content : entry=66
UPDATE `trans_words` SET `content_loc9`='Using script library: <Unknown Script Library>' WHERE `word_id` = 4227; -- mangos_string - content : entry=65
UPDATE `trans_words` SET `content_loc9`='Using World DB: %s' WHERE `word_id` = 4220; -- mangos_string - content : entry=57
UPDATE `trans_words` SET `content_loc9`='Value saved, you may need to rejoin or clean your client cache.' WHERE `word_id` = 4349; -- mangos_string - content : entry=261
UPDATE `trans_words` SET `content_loc9`='Value saved.' WHERE `word_id` = 4348; -- mangos_string - content : entry=260
UPDATE `trans_words` SET `content_loc9`='Vendor has too many items (max 128)' WHERE `word_id` = 4367; -- mangos_string - content : entry=280
UPDATE `trans_words` SET `content_loc9`='Veteran' WHERE `word_id` = 4751; -- mangos_string - content : entry=813
UPDATE `trans_words` SET `content_loc9`='visible' WHERE `word_id` = 4204; -- mangos_string - content : entry=41
UPDATE `trans_words` SET `content_loc9`='Waypoint %s modified.' WHERE `word_id` = 4322; -- mangos_string - content : entry=237
UPDATE `trans_words` SET `content_loc9`='Waypoint %u for %s (from pathId %i, stored by %s)' WHERE `word_id` = 4929; -- mangos_string - content : entry=246
UPDATE `trans_words` SET `content_loc9`='Waypoint changed.' WHERE `word_id` = 4325; -- mangos_string - content : entry=236
UPDATE `trans_words` SET `content_loc9`='Waypoint removed.' WHERE `word_id` = 4928; -- mangos_string - content : entry=241
UPDATE `trans_words` SET `content_loc9`='Waypoint-Creature (GUID: %u) Not found' WHERE `word_id` = 4343; -- mangos_string - content : entry=255
UPDATE `trans_words` SET `content_loc9`='Weather can\'t be changed for this zone.' WHERE `word_id` = 4469; -- mangos_string - content : entry=406
UPDATE `trans_words` SET `content_loc9`='Weather system disabled at server.' WHERE `word_id` = 4470; -- mangos_string - content : entry=407
UPDATE `trans_words` SET `content_loc9`='WP export successfull.' WHERE `word_id` = 4323; -- mangos_string - content : entry=238
UPDATE `trans_words` SET `content_loc9`='Wrong faction: %u (not found in factiontemplate.dbc).' WHERE `word_id` = 4258; -- mangos_string - content : entry=129
UPDATE `trans_words` SET `content_loc9`='Wrong link type!' WHERE `word_id` = 4570; -- mangos_string - content : entry=511
UPDATE `trans_words` SET `content_loc9`='Yesterday: [Kills: |c0000ff00%u|r] [Honor: %u]' WHERE `word_id` = 4902; -- mangos_string - content : entry=1436
UPDATE `trans_words` SET `content_loc9`='You already forgot that spell.' WHERE `word_id` = 4551; -- mangos_string - content : entry=491
UPDATE `trans_words` SET `content_loc9`='You already have pet.' WHERE `word_id` = 4427; -- mangos_string - content : entry=344
UPDATE `trans_words` SET `content_loc9`='You already know that spell.' WHERE `word_id` = 4548; -- mangos_string - content : entry=488
UPDATE `trans_words` SET `content_loc9`='You are being summoned by %s.' WHERE `word_id` = 4238; -- mangos_string - content : entry=109
UPDATE `trans_words` SET `content_loc9`='You are being teleported by %s.' WHERE `word_id` = 4240; -- mangos_string - content : entry=111
UPDATE `trans_words` SET `content_loc9`='You are not mounted so you can\'t dismount.' WHERE `word_id` = 4185; -- mangos_string - content : entry=22
UPDATE `trans_words` SET `content_loc9`='You are now invisible.' WHERE `word_id` = 4630; -- mangos_string - content : entry=577
UPDATE `trans_words` SET `content_loc9`='You are now visible.' WHERE `word_id` = 4631; -- mangos_string - content : entry=578
UPDATE `trans_words` SET `content_loc9`='You are summoning %s%s.' WHERE `word_id` = 4237; -- mangos_string - content : entry=108
UPDATE `trans_words` SET `content_loc9`='You are teleporting %s%s to %s.' WHERE `word_id` = 4239; -- mangos_string - content : entry=110
UPDATE `trans_words` SET `content_loc9`='You are: %s' WHERE `word_id` = 4203; -- mangos_string - content : entry=40
UPDATE `trans_words` SET `content_loc9`='You can go to the player\'s instance while not being in his party only if your GM mode is on.' WHERE `word_id` = 4234; -- mangos_string - content : entry=105
UPDATE `trans_words` SET `content_loc9`='You can not go to player %s from instance to instance.' WHERE `word_id` = 4235; -- mangos_string - content : entry=106
UPDATE `trans_words` SET `content_loc9`='You can not summon player %s from instance to instance.' WHERE `word_id` = 4236; -- mangos_string - content : entry=107
UPDATE `trans_words` SET `content_loc9`='You can summon a player to your instance only if he is in your party with you as leader.' WHERE `word_id` = 4232; -- mangos_string - content : entry=103
UPDATE `trans_words` SET `content_loc9`='You can\'t kick self, logout instead' WHERE `word_id` = 4368; -- mangos_string - content : entry=281
UPDATE `trans_words` SET `content_loc9`='You can\'t teleport self to self!' WHERE `word_id` = 4297; -- mangos_string - content : entry=171
UPDATE `trans_words` SET `content_loc9`='You can\'t use this command at non-instanceable map \'%s\' (Id:%u). Use .lookup pool command instead.' WHERE `word_id` = 4446; -- mangos_string - content : entry=378
UPDATE `trans_words` SET `content_loc9`='You can\'t use this command without args at non-instanceable map \'%s\' (Id:%u).' WHERE `word_id` = 4447; -- mangos_string - content : entry=379
UPDATE `trans_words` SET `content_loc9`='You cannot go to the player\'s instance because you are in a party now.' WHERE `word_id` = 4233; -- mangos_string - content : entry=104
UPDATE `trans_words` SET `content_loc9`='You cannot summon players to a battleground or arena map.' WHERE `word_id` = 4702; -- mangos_string - content : entry=734
UPDATE `trans_words` SET `content_loc9`='You cannot teleport to a battleground from another battleground. Please leave the current battleground first.' WHERE `word_id` = 4704; -- mangos_string - content : entry=736
UPDATE `trans_words` SET `content_loc9`='You cannot teleport to a battleground map.' WHERE `word_id` = 4701; -- mangos_string - content : entry=733
UPDATE `trans_words` SET `content_loc9`='You cant close a ticket for offline players' WHERE `word_id` = 4927; -- mangos_string - content : entry=1513
UPDATE `trans_words` SET `content_loc9`='You change gender of %s to %s.' WHERE `word_id` = 4796; -- mangos_string - content : entry=1120
UPDATE `trans_words` SET `content_loc9`='You change security level of account %s to %i.' WHERE `word_id` = 4464; -- mangos_string - content : entry=401
UPDATE `trans_words` SET `content_loc9`='You changed ENERGY of %s to %i/%i.' WHERE `word_id` = 4251; -- mangos_string - content : entry=122
UPDATE `trans_words` SET `content_loc9`='You changed GUID=%i \'s Faction to %i, flags to %i, npcflag to %i, dyflag to %i.' WHERE `word_id` = 4259; -- mangos_string - content : entry=130
UPDATE `trans_words` SET `content_loc9`='You changed HP of %s to %i/%i.' WHERE `word_id` = 4247; -- mangos_string - content : entry=118
UPDATE `trans_words` SET `content_loc9`='You changed level of %s to %i.' WHERE `word_id` = 4256; -- mangos_string - content : entry=127
UPDATE `trans_words` SET `content_loc9`='You changed MANA of %s to %i/%i.' WHERE `word_id` = 4249; -- mangos_string - content : entry=120
UPDATE `trans_words` SET `content_loc9`='You changed rage of %s to %i/%i.' WHERE `word_id` = 4254; -- mangos_string - content : entry=125
UPDATE `trans_words` SET `content_loc9`='You changed the %s spellmod %u to value %i for spell with family bit %u for %s.' WHERE `word_id` = 4260; -- mangos_string - content : entry=131
UPDATE `trans_words` SET `content_loc9`='You do not have enough free slots' WHERE `word_id` = 4741; -- mangos_string - content : entry=802
UPDATE `trans_words` SET `content_loc9`='You do not have enough gold' WHERE `word_id` = 4740; -- mangos_string - content : entry=801
UPDATE `trans_words` SET `content_loc9`='You do not have permission to perform that function' WHERE `word_id` = 4743; -- mangos_string - content : entry=804
UPDATE `trans_words` SET `content_loc9`='You don\'t know that language' WHERE `word_id` = 4745; -- mangos_string - content : entry=806
UPDATE `trans_words` SET `content_loc9`='You don\'t meet Battleground level requirements' WHERE `word_id` = 4692; -- mangos_string - content : entry=715
UPDATE `trans_words` SET `content_loc9`='You give %i copper to %s.' WHERE `word_id` = 4284; -- mangos_string - content : entry=157
UPDATE `trans_words` SET `content_loc9`='You give a mount to %s.' WHERE `word_id` = 4277; -- mangos_string - content : entry=150
UPDATE `trans_words` SET `content_loc9`='You have disabled %s\'s chat for %u minutes.' WHERE `word_id` = 4385; -- mangos_string - content : entry=301
UPDATE `trans_words` SET `content_loc9`='You have enabled %s\'s chat.' WHERE `word_id` = 4388; -- mangos_string - content : entry=304
UPDATE `trans_words` SET `content_loc9`='You have learned all spells in craft: %s' WHERE `word_id` = 4645; -- mangos_string - content : entry=592
UPDATE `trans_words` SET `content_loc9`='You have low security level for this.' WHERE `word_id` = 4466; -- mangos_string - content : entry=403
UPDATE `trans_words` SET `content_loc9`='You hear sound %u.' WHERE `word_id` = 4286; -- mangos_string - content : entry=159
UPDATE `trans_words` SET `content_loc9`='You learned all craft skills and recipes.' WHERE `word_id` = 4496; -- mangos_string - content : entry=433
UPDATE `trans_words` SET `content_loc9`='You learned all default spells for race/class and completed quests rewarded spells.' WHERE `word_id` = 4633; -- mangos_string - content : entry=580
UPDATE `trans_words` SET `content_loc9`='You learned all languages.' WHERE `word_id` = 4495; -- mangos_string - content : entry=432
UPDATE `trans_words` SET `content_loc9`='You learned all spells for class.' WHERE `word_id` = 4493; -- mangos_string - content : entry=430
UPDATE `trans_words` SET `content_loc9`='You learned all talents for class.' WHERE `word_id` = 4494; -- mangos_string - content : entry=431
UPDATE `trans_words` SET `content_loc9`='You learned default GM spells/skills.' WHERE `word_id` = 4547; -- mangos_string - content : entry=487
UPDATE `trans_words` SET `content_loc9`='You learned many spells/skills.' WHERE `word_id` = 4492; -- mangos_string - content : entry=429
UPDATE `trans_words` SET `content_loc9`='You modify for %s float field:%u to sum with:%f = %f' WHERE `word_id` = 4831; -- mangos_string - content : entry=1160
UPDATE `trans_words` SET `content_loc9`='You modify for %s hex field:%u %s %x = %x (hex)' WHERE `word_id` = 4829; -- mangos_string - content : entry=1158
UPDATE `trans_words` SET `content_loc9`='You modify for %s uint32 field:%u to sum with:%i = %u (%i)' WHERE `word_id` = 4629; -- mangos_string - content : entry=576
UPDATE `trans_words` SET `content_loc9`='You must be at least level %u to enter.' WHERE `word_id` = 4440; -- mangos_string - content : entry=49
UPDATE `trans_words` SET `content_loc9`='You must be at most level %u to enter.' WHERE `word_id` = 4940; -- mangos_string - content : entry=69
UPDATE `trans_words` SET `content_loc9`='You must be in GM mode to teleport to a player in a battleground.' WHERE `word_id` = 4703; -- mangos_string - content : entry=735
UPDATE `trans_words` SET `content_loc9`='You must be member of the Alliance to enter.' WHERE `word_id` = 4939; -- mangos_string - content : entry=68
UPDATE `trans_words` SET `content_loc9`='You must be member of the Horde to enter.' WHERE `word_id` = 4212; -- mangos_string - content : entry=67
UPDATE `trans_words` SET `content_loc9`='You must have item %s to enter.' WHERE `word_id` = 4213; -- mangos_string - content : entry=50
UPDATE `trans_words` SET `content_loc9`='You must have level %u to enter.' WHERE `word_id` = 4941; -- mangos_string - content : entry=70
UPDATE `trans_words` SET `content_loc9`='You must select a vendor' WHERE `word_id` = 4365; -- mangos_string - content : entry=278
UPDATE `trans_words` SET `content_loc9`='You must select a visual waypoint.' WHERE `word_id` = 4334; -- mangos_string - content : entry=226
UPDATE `trans_words` SET `content_loc9`='You must send id for item' WHERE `word_id` = 4366; -- mangos_string - content : entry=279
UPDATE `trans_words` SET `content_loc9`='You must use male or female as gender.' WHERE `word_id` = 4795; -- mangos_string - content : entry=1119
UPDATE `trans_words` SET `content_loc9`='You must wait %s before speaking again.' WHERE `word_id` = 4684; -- mangos_string - content : entry=705
UPDATE `trans_words` SET `content_loc9`='You need to provide a guild name!' WHERE `word_id` = 4558; -- mangos_string - content : entry=498
UPDATE `trans_words` SET `content_loc9`='You repair all %s\'s items.' WHERE `word_id` = 4419; -- mangos_string - content : entry=336
UPDATE `trans_words` SET `content_loc9`='You set all speeds to %2.2f from normal of %s.' WHERE `word_id` = 4266; -- mangos_string - content : entry=137
UPDATE `trans_words` SET `content_loc9`='You set for %s field:%u to float value: %f' WHERE `word_id` = 4623; -- mangos_string - content : entry=568
UPDATE `trans_words` SET `content_loc9`='You set for %s field:%u to uint32 value: %u' WHERE `word_id` = 4621; -- mangos_string - content : entry=566
UPDATE `trans_words` SET `content_loc9`='You set the backwards run speed to %2.2f from normal of %s.' WHERE `word_id` = 4272; -- mangos_string - content : entry=143
UPDATE `trans_words` SET `content_loc9`='You set the size %2.2f of %s.' WHERE `word_id` = 4274; -- mangos_string - content : entry=147
UPDATE `trans_words` SET `content_loc9`='You set the speed to %2.2f from normal of %s.' WHERE `word_id` = 4268; -- mangos_string - content : entry=139
UPDATE `trans_words` SET `content_loc9`='You set the swim speed to %2.2f from normal of %s.' WHERE `word_id` = 4270; -- mangos_string - content : entry=141
UPDATE `trans_words` SET `content_loc9`='You set waterwalk mode %s for %s.' WHERE `word_id` = 4421; -- mangos_string - content : entry=338
UPDATE `trans_words` SET `content_loc9`='You should select a character or a creature.' WHERE `word_id` = 4164; -- mangos_string - content : entry=1
UPDATE `trans_words` SET `content_loc9`='You should select a creature.' WHERE `word_id` = 4165; -- mangos_string - content : entry=2
UPDATE `trans_words` SET `content_loc9`='You take %i copper from %s.' WHERE `word_id` = 4282; -- mangos_string - content : entry=155
UPDATE `trans_words` SET `content_loc9`='You take all copper of %s.' WHERE `word_id` = 4280; -- mangos_string - content : entry=153
UPDATE `trans_words` SET `content_loc9`='You try to hear sound %u but it doesn\'t exist.' WHERE `word_id` = 4296; -- mangos_string - content : entry=170
UPDATE `trans_words` SET `content_loc9`='You try to view cinematic %u but it doesn\'t exist.' WHERE `word_id` = 4861; -- mangos_string - content : entry=1200
UPDATE `trans_words` SET `content_loc9`='You used it recently.' WHERE `word_id` = 4187; -- mangos_string - content : entry=24
UPDATE `trans_words` SET `content_loc9`='Your account level is: %i' WHERE `word_id` = 4174; -- mangos_string - content : entry=11
UPDATE `trans_words` SET `content_loc9`='Your chat has been disabled for %u minutes.' WHERE `word_id` = 4384; -- mangos_string - content : entry=300
UPDATE `trans_words` SET `content_loc9`='Your gender changed to %s by %s.' WHERE `word_id` = 4797; -- mangos_string - content : entry=1121
UPDATE `trans_words` SET `content_loc9`='Your group has an offline member. Please remove him before joining.' WHERE `word_id` = 4695; -- mangos_string - content : entry=727
UPDATE `trans_words` SET `content_loc9`='Your group has players from different battleground brakets. You can\'t join as group.' WHERE `word_id` = 4697; -- mangos_string - content : entry=729
UPDATE `trans_words` SET `content_loc9`='Your group has players from the opposing faction. You can\'t join the battleground as a group.' WHERE `word_id` = 4696; -- mangos_string - content : entry=728
UPDATE `trans_words` SET `content_loc9`='Your group is too large for this battleground. Please regroup to join.' WHERE `word_id` = 4694; -- mangos_string - content : entry=720
UPDATE `trans_words` SET `content_loc9`='Your partner does not have enough free bag slots' WHERE `word_id` = 4742; -- mangos_string - content : entry=803
UPDATE `trans_words` SET `content_loc9`='Your password can\'t be longer than 16 characters (client limit), password not changed!' WHERE `word_id` = 4218; -- mangos_string - content : entry=55
UPDATE `trans_words` SET `content_loc9`='Your spells have been reset.' WHERE `word_id` = 4315; -- mangos_string - content : entry=215
UPDATE `trans_words` SET `content_loc9`='Your talents have been reset.' WHERE `word_id` = 4316; -- mangos_string - content : entry=216
UPDATE `trans_words` SET `content_loc9`='Your waterwalk mode %s by %s.' WHERE `word_id` = 4422; -- mangos_string - content : entry=339
UPDATE `trans_words` SET `content_loc9`='Zone #%u doesn\'t have linked graveyards for faction: %s.' WHERE `word_id` = 4523; -- mangos_string - content : entry=461
UPDATE `trans_words` SET `content_loc9`='Zone #%u doesn\'t have linked graveyards.' WHERE `word_id` = 4522; -- mangos_string - content : entry=460
UPDATE `trans_words` SET `content_loc9`='Zone %u (%s) is part of instanceable map %u (%s)' WHERE `word_id` = 4353; -- mangos_string - content : entry=265
UPDATE `trans_words` SET `content_loc9`='Zone coordinates is invalid (X: %f Y: %f AreaId: %u)' WHERE `word_id` = 4352; -- mangos_string - content : entry=264

SET NAMES 'latin1';
