-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc9`='Alanna Raveneye' WHERE `word_id` = 75289; -- locales_points_of_interest - icon_name : entry=120
UPDATE `trans_words` SET `content_loc9`='Azar Stronghammer' WHERE `word_id` = 73183; -- locales_points_of_interest - icon_name : entry=80
UPDATE `trans_words` SET `content_loc9`='Cain Firesong' WHERE `word_id` = 73927; -- locales_points_of_interest - icon_name : entry=298
UPDATE `trans_words` SET `content_loc9`='Chaw Stronghide' WHERE `word_id` = 74762; -- locales_points_of_interest - icon_name : entry=327
UPDATE `trans_words` SET `content_loc9`='Cyndra Kindwhisper' WHERE `word_id` = 75286; -- locales_points_of_interest - icon_name : entry=118
UPDATE `trans_words` SET `content_loc9`='Dark Cleric Beryl' WHERE `word_id` = 73928; -- locales_points_of_interest - icon_name : entry=297
UPDATE `trans_words` SET `content_loc9`='Darnassus Alchemy Trainer' WHERE `word_id` = 127198; -- locales_points_of_interest - icon_name : entry=102
UPDATE `trans_words` SET `content_loc9`='Darnassus Bank' WHERE `word_id` = 127188; -- locales_points_of_interest - icon_name : entry=90
UPDATE `trans_words` SET `content_loc9`='Darnassus Cooking Trainer' WHERE `word_id` = 127199; -- locales_points_of_interest - icon_name : entry=103
UPDATE `trans_words` SET `content_loc9`='Darnassus Druid Trainer' WHERE `word_id` = 127194; -- locales_points_of_interest - icon_name : entry=98
UPDATE `trans_words` SET `content_loc9`='Darnassus Enchanting Trainer' WHERE `word_id` = 127200; -- locales_points_of_interest - icon_name : entry=104
UPDATE `trans_words` SET `content_loc9`='Darnassus First Aid Trainer' WHERE `word_id` = 127201; -- locales_points_of_interest - icon_name : entry=105
UPDATE `trans_words` SET `content_loc9`='Darnassus Fishing Trainer' WHERE `word_id` = 127202; -- locales_points_of_interest - icon_name : entry=106
UPDATE `trans_words` SET `content_loc9`='Darnassus Guild Master' WHERE `word_id` = 127190; -- locales_points_of_interest - icon_name : entry=92
UPDATE `trans_words` SET `content_loc9`='Darnassus Herbalism Trainer' WHERE `word_id` = 127249; -- locales_points_of_interest - icon_name : entry=440
UPDATE `trans_words` SET `content_loc9`='Darnassus Hippogryph Master' WHERE `word_id` = 127189; -- locales_points_of_interest - icon_name : entry=91
UPDATE `trans_words` SET `content_loc9`='Darnassus Hunter Trainer' WHERE `word_id` = 127195; -- locales_points_of_interest - icon_name : entry=99
UPDATE `trans_words` SET `content_loc9`='Darnassus Inn' WHERE `word_id` = 127191; -- locales_points_of_interest - icon_name : entry=93
UPDATE `trans_words` SET `content_loc9`='Darnassus Leatherworking Trainer' WHERE `word_id` = 127203; -- locales_points_of_interest - icon_name : entry=108
UPDATE `trans_words` SET `content_loc9`='Darnassus Mailbox' WHERE `word_id` = 127192; -- locales_points_of_interest - icon_name : entry=94
UPDATE `trans_words` SET `content_loc9`='Darnassus Rogue Trainer' WHERE `word_id` = 127196; -- locales_points_of_interest - icon_name : entry=100
UPDATE `trans_words` SET `content_loc9`='Darnassus Skinning Trainer' WHERE `word_id` = 127204; -- locales_points_of_interest - icon_name : entry=109
UPDATE `trans_words` SET `content_loc9`='Darnassus Tailor' WHERE `word_id` = 127205; -- locales_points_of_interest - icon_name : entry=110
UPDATE `trans_words` SET `content_loc9`='Dhugru Gorelust' WHERE `word_id` = 74861; -- locales_points_of_interest - icon_name : entry=246
UPDATE `trans_words` SET `content_loc9`='Dolanaar Inn' WHERE `word_id` = 127206; -- locales_points_of_interest - icon_name : entry=111
UPDATE `trans_words` SET `content_loc9`='Gelman Stonehand' WHERE `word_id` = 76709; -- locales_points_of_interest - icon_name : entry=48
UPDATE `trans_words` SET `content_loc9`='Gennia Runetotem' WHERE `word_id` = 74757; -- locales_points_of_interest - icon_name : entry=336
UPDATE `trans_words` SET `content_loc9`='Gimrizz Shadowcog' WHERE `word_id` = 76748; -- locales_points_of_interest - icon_name : entry=83
UPDATE `trans_words` SET `content_loc9`='Granis Swiftaxe' WHERE `word_id` = 73181; -- locales_points_of_interest - icon_name : entry=84
UPDATE `trans_words` SET `content_loc9`='Grif Wildheart' WHERE `word_id` = 73182; -- locales_points_of_interest - icon_name : entry=78
UPDATE `trans_words` SET `content_loc9`='Helene Peltskinner' WHERE `word_id` = 77268; -- locales_points_of_interest - icon_name : entry=15
UPDATE `trans_words` SET `content_loc9`='Herbalist Pomeroy' WHERE `word_id` = 73175; -- locales_points_of_interest - icon_name : entry=363
UPDATE `trans_words` SET `content_loc9`='Hunter Lodge' WHERE `word_id` = 127173; -- locales_points_of_interest - icon_name : entry=33
UPDATE `trans_words` SET `content_loc9`='Ilyenia Moonfire' WHERE `word_id` = 79676; -- locales_points_of_interest - icon_name : entry=96
UPDATE `trans_words` SET `content_loc9`='Ironforge Gryphon Master' WHERE `word_id` = 127179; -- locales_points_of_interest - icon_name : entry=53
UPDATE `trans_words` SET `content_loc9`='Ironforge Mailbox' WHERE `word_id` = 127181; -- locales_points_of_interest - icon_name : entry=56
UPDATE `trans_words` SET `content_loc9`='Ironforge Rogue Trainer' WHERE `word_id` = 127184; -- locales_points_of_interest - icon_name : entry=63
UPDATE `trans_words` SET `content_loc9`='Ironforge Warlock Trainer' WHERE `word_id` = 127185; -- locales_points_of_interest - icon_name : entry=64
UPDATE `trans_words` SET `content_loc9`='Jannok Breezesong' WHERE `word_id` = 75282; -- locales_points_of_interest - icon_name : entry=116
UPDATE `trans_words` SET `content_loc9`='Jenova Stoneshield' WHERE `word_id` = 79231; -- locales_points_of_interest - icon_name : entry=26
UPDATE `trans_words` SET `content_loc9`='Krang Stonehoof' WHERE `word_id` = 74756; -- locales_points_of_interest - icon_name : entry=332
UPDATE `trans_words` SET `content_loc9`='Kyra Windblade' WHERE `word_id` = 75281; -- locales_points_of_interest - icon_name : entry=117
UPDATE `trans_words` SET `content_loc9`='Laurna Morninglight' WHERE `word_id` = 75283; -- locales_points_of_interest - icon_name : entry=115
UPDATE `trans_words` SET `content_loc9`='Lilliam Sparkspindle' WHERE `word_id` = 76714; -- locales_points_of_interest - icon_name : entry=44
UPDATE `trans_words` SET `content_loc9`='Magis Sparkmantle' WHERE `word_id` = 73180; -- locales_points_of_interest - icon_name : entry=79
UPDATE `trans_words` SET `content_loc9`='Malorne Bladeleaf' WHERE `word_id` = 75287; -- locales_points_of_interest - icon_name : entry=122
UPDATE `trans_words` SET `content_loc9`='Nadyia Maneweaver' WHERE `word_id` = 75288; -- locales_points_of_interest - icon_name : entry=123
UPDATE `trans_words` SET `content_loc9`='Narm Skychaser' WHERE `word_id` = 74759; -- locales_points_of_interest - icon_name : entry=334
UPDATE `trans_words` SET `content_loc9`='Nurse Neela' WHERE `word_id` = 76878; -- locales_points_of_interest - icon_name : entry=290
UPDATE `trans_words` SET `content_loc9`='Orgrimmar Hunter\'s Hall' WHERE `word_id` = 127248; -- locales_points_of_interest - icon_name : entry=420
UPDATE `trans_words` SET `content_loc9`='Orgrimmar Inn' WHERE `word_id` = 127208; -- locales_points_of_interest - icon_name : entry=179
UPDATE `trans_words` SET `content_loc9`='Orgrimmar Mailbox' WHERE `word_id` = 127209; -- locales_points_of_interest - icon_name : entry=180
UPDATE `trans_words` SET `content_loc9`='Orgrimmar Zeppelin Tower' WHERE `word_id` = 127210; -- locales_points_of_interest - icon_name : entry=182
UPDATE `trans_words` SET `content_loc9`='Priestess Josetta' WHERE `word_id` = 72497; -- locales_points_of_interest - icon_name : entry=4
UPDATE `trans_words` SET `content_loc9`='Pyall Silentstride' WHERE `word_id` = 74760; -- locales_points_of_interest - icon_name : entry=331
UPDATE `trans_words` SET `content_loc9`='Radnaal Maneweaver' WHERE `word_id` = 77254; -- locales_points_of_interest - icon_name : entry=124
UPDATE `trans_words` SET `content_loc9`='Razor Hill Inn' WHERE `word_id` = 127213; -- locales_points_of_interest - icon_name : entry=253
UPDATE `trans_words` SET `content_loc9`='Saltheril\'s Haven, Tailor' WHERE `word_id` = 127247; -- locales_points_of_interest - icon_name : entry=418
UPDATE `trans_words` SET `content_loc9`='Sayoc & Hanashi' WHERE `word_id` = 127211; -- locales_points_of_interest - icon_name : entry=184
UPDATE `trans_words` SET `content_loc9`='Shelby Stoneflint' WHERE `word_id` = 78706; -- locales_points_of_interest - icon_name : entry=77
UPDATE `trans_words` SET `content_loc9`='Smith Argus' WHERE `word_id` = 72592; -- locales_points_of_interest - icon_name : entry=9
UPDATE `trans_words` SET `content_loc9`='Stonefire Tavern' WHERE `word_id` = 127180; -- locales_points_of_interest - icon_name : entry=55
UPDATE `trans_words` SET `content_loc9`='Stormwind - Rogue House' WHERE `word_id` = 127176; -- locales_points_of_interest - icon_name : entry=36
UPDATE `trans_words` SET `content_loc9`='Stormwind Bank' WHERE `word_id` = 127169; -- locales_points_of_interest - icon_name : entry=19
UPDATE `trans_words` SET `content_loc9`='Stormwind Barracks' WHERE `word_id` = 127177; -- locales_points_of_interest - icon_name : entry=39
UPDATE `trans_words` SET `content_loc9`='Stormwind Gryphon Master' WHERE `word_id` = 127171; -- locales_points_of_interest - icon_name : entry=23
UPDATE `trans_words` SET `content_loc9`='Tarshaw Jaggedscar' WHERE `word_id` = 74858; -- locales_points_of_interest - icon_name : entry=245
UPDATE `trans_words` SET `content_loc9`='The Deeprun Tram' WHERE `word_id` = 127170; -- locales_points_of_interest - icon_name : entry=21
UPDATE `trans_words` SET `content_loc9`='The Vault' WHERE `word_id` = 127178; -- locales_points_of_interest - icon_name : entry=51
UPDATE `trans_words` SET `content_loc9`='Therum Deepforge' WHERE `word_id` = 76707; -- locales_points_of_interest - icon_name : entry=41
UPDATE `trans_words` SET `content_loc9`='Thunder Bluff Auction house' WHERE `word_id` = 127241; -- locales_points_of_interest - icon_name : entry=320
UPDATE `trans_words` SET `content_loc9`='Thunder Bluff Inn' WHERE `word_id` = 127243; -- locales_points_of_interest - icon_name : entry=322
UPDATE `trans_words` SET `content_loc9`='Thunder Bluff Mailbox' WHERE `word_id` = 127242; -- locales_points_of_interest - icon_name : entry=321
UPDATE `trans_words` SET `content_loc9`='Tognus Flintfire' WHERE `word_id` = 73191; -- locales_points_of_interest - icon_name : entry=85
UPDATE `trans_words` SET `content_loc9`='Ulbrek Firehand' WHERE `word_id` = 78710; -- locales_points_of_interest - icon_name : entry=57
UPDATE `trans_words` SET `content_loc9`='Undercity Bank' WHERE `word_id` = 127236; -- locales_points_of_interest - icon_name : entry=283
UPDATE `trans_words` SET `content_loc9`='Undercity Bat Handler' WHERE `word_id` = 127235; -- locales_points_of_interest - icon_name : entry=281
UPDATE `trans_words` SET `content_loc9`='Undercity Blacksmithing Trainer' WHERE `word_id` = 127224; -- locales_points_of_interest - icon_name : entry=265
UPDATE `trans_words` SET `content_loc9`='Undercity Cooking Trainer' WHERE `word_id` = 127223; -- locales_points_of_interest - icon_name : entry=264
UPDATE `trans_words` SET `content_loc9`='Undercity Enchanting Trainer' WHERE `word_id` = 127222; -- locales_points_of_interest - icon_name : entry=263
UPDATE `trans_words` SET `content_loc9`='Undercity Engineering Trainer' WHERE `word_id` = 127221; -- locales_points_of_interest - icon_name : entry=262
UPDATE `trans_words` SET `content_loc9`='Undercity First Aid Trainer' WHERE `word_id` = 127220; -- locales_points_of_interest - icon_name : entry=261
UPDATE `trans_words` SET `content_loc9`='Undercity Fishing Trainer' WHERE `word_id` = 127219; -- locales_points_of_interest - icon_name : entry=260
UPDATE `trans_words` SET `content_loc9`='Undercity Guild Master' WHERE `word_id` = 127233; -- locales_points_of_interest - icon_name : entry=279
UPDATE `trans_words` SET `content_loc9`='Undercity Herbalism Trainer' WHERE `word_id` = 127218; -- locales_points_of_interest - icon_name : entry=259
UPDATE `trans_words` SET `content_loc9`='Undercity Inn' WHERE `word_id` = 127232; -- locales_points_of_interest - icon_name : entry=278
UPDATE `trans_words` SET `content_loc9`='Undercity Leatherworking Trainer' WHERE `word_id` = 127217; -- locales_points_of_interest - icon_name : entry=257
UPDATE `trans_words` SET `content_loc9`='Undercity Mage Trainers' WHERE `word_id` = 127229; -- locales_points_of_interest - icon_name : entry=272
UPDATE `trans_words` SET `content_loc9`='Undercity Mailbox' WHERE `word_id` = 127231; -- locales_points_of_interest - icon_name : entry=276
UPDATE `trans_words` SET `content_loc9`='Undercity Mining Trainer' WHERE `word_id` = 127216; -- locales_points_of_interest - icon_name : entry=256
UPDATE `trans_words` SET `content_loc9`='Undercity Priest Trainers' WHERE `word_id` = 127228; -- locales_points_of_interest - icon_name : entry=270
UPDATE `trans_words` SET `content_loc9`='Undercity Rogue Trainers' WHERE `word_id` = 127227; -- locales_points_of_interest - icon_name : entry=269
UPDATE `trans_words` SET `content_loc9`='Undercity Skinning Trainer' WHERE `word_id` = 127215; -- locales_points_of_interest - icon_name : entry=255
UPDATE `trans_words` SET `content_loc9`='Undercity Tailoring Trainer' WHERE `word_id` = 127214; -- locales_points_of_interest - icon_name : entry=254
UPDATE `trans_words` SET `content_loc9`='Undercity Warlock Trainers' WHERE `word_id` = 127226; -- locales_points_of_interest - icon_name : entry=268
UPDATE `trans_words` SET `content_loc9`='Undercity Warrior Trainers' WHERE `word_id` = 127225; -- locales_points_of_interest - icon_name : entry=267
UPDATE `trans_words` SET `content_loc9`='Undercity Zeppelin' WHERE `word_id` = 127230; -- locales_points_of_interest - icon_name : entry=273
UPDATE `trans_words` SET `content_loc9`='Uthan Stillwater' WHERE `word_id` = 77037; -- locales_points_of_interest - icon_name : entry=329
UPDATE `trans_words` SET `content_loc9`='Vance Undergloom' WHERE `word_id` = 76817; -- locales_points_of_interest - icon_name : entry=291
UPDATE `trans_words` SET `content_loc9`='Vira Younghoof' WHERE `word_id` = 77038; -- locales_points_of_interest - icon_name : entry=330
UPDATE `trans_words` SET `content_loc9`='Wind Rider Roost' WHERE `word_id` = 127244; -- locales_points_of_interest - icon_name : entry=324
UPDATE `trans_words` SET `content_loc9`='Yarr Hammerstone' WHERE `word_id` = 76615; -- locales_points_of_interest - icon_name : entry=339
UPDATE `trans_words` SET `content_loc9`='Yaw Sharpmane' WHERE `word_id` = 74758; -- locales_points_of_interest - icon_name : entry=335
UPDATE `trans_words` SET `content_loc9`='Yonn Deepcut' WHERE `word_id` = 77257; -- locales_points_of_interest - icon_name : entry=326

SET NAMES 'latin1';
