-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc9`='$N, I\'ll make sure all my friends in the Cartel know that you\'ve saved my life today. Here - I\'m going to need to be able to travel light, so please help yourself to my cache of tailoring and leatherworking supplies! Thanks again - see ya!' WHERE `word_id` = 7342; -- db_script_string - content : entry=2000005776
UPDATE `trans_words` SET `content_loc9`='$N, please take a look at the sample of the Vylestem vine that I took from the caverns, so that you know what to look for...' WHERE `word_id` = 7202; -- db_script_string - content : entry=2000005465
UPDATE `trans_words` SET `content_loc9`='$N, that\'s it! I have finally figured it out!' WHERE `word_id` = 7379; -- db_script_string - content : entry=2000000542
UPDATE `trans_words` SET `content_loc9`='%s begins to channel his energy, focusing on the stone.' WHERE `word_id` = 7335; -- db_script_string - content : entry=2000005650
UPDATE `trans_words` SET `content_loc9`='%s begins to flap his massive wings faster. He is preparing for flight.' WHERE `word_id` = 7374; -- db_script_string - content : entry=2000000534
UPDATE `trans_words` SET `content_loc9`='%s casually points at the orc target...' WHERE `word_id` = 7268; -- db_script_string - content : entry=2000005734
UPDATE `trans_words` SET `content_loc9`='%s dusts the base of the artifact.' WHERE `word_id` = 7061; -- db_script_string - content : entry=2000005348
UPDATE `trans_words` SET `content_loc9`='%s enters a trance...' WHERE `word_id` = 7343; -- db_script_string - content : entry=2000005800
UPDATE `trans_words` SET `content_loc9`='%s gestures to the pitcher of water sitting on the edge of the well.' WHERE `word_id` = 6952; -- db_script_string - content : entry=2000000027
UPDATE `trans_words` SET `content_loc9`='%s hits!' WHERE `word_id` = 7269; -- db_script_string - content : entry=2000005735
UPDATE `trans_words` SET `content_loc9`='%s I have created the totem. You, %n, must cleanse the well.' WHERE `word_id` = 7344; -- db_script_string - content : entry=2000005801
UPDATE `trans_words` SET `content_loc9`='%s lets loose a reptilian laugh... at least you think it\'s a laugh.' WHERE `word_id` = 7367; -- db_script_string - content : entry=2000000527
UPDATE `trans_words` SET `content_loc9`='%s listens to Sigilbringer\'s report...' WHERE `word_id` = 7252; -- db_script_string - content : entry=2000005777
UPDATE `trans_words` SET `content_loc9`='%s loosens her grasp on the journal she had been clutching.' WHERE `word_id` = 7387; -- db_script_string - content : entry=2000000612
UPDATE `trans_words` SET `content_loc9`='%s meticulously examines the large vase.' WHERE `word_id` = 7301; -- db_script_string - content : entry=2000005349
UPDATE `trans_words` SET `content_loc9`='%s misses again...' WHERE `word_id` = 7267; -- db_script_string - content : entry=2000005733
UPDATE `trans_words` SET `content_loc9`='%s misses...' WHERE `word_id` = 7265; -- db_script_string - content : entry=2000005731
UPDATE `trans_words` SET `content_loc9`='%s only hits the side of the box!' WHERE `word_id` = 7274; -- db_script_string - content : entry=2000005742
UPDATE `trans_words` SET `content_loc9`='%s picks the orc target...' WHERE `word_id` = 7264; -- db_script_string - content : entry=2000005730
UPDATE `trans_words` SET `content_loc9`='%s quickly shoots the middle target dead center...' WHERE `word_id` = 7272; -- db_script_string - content : entry=2000005740
UPDATE `trans_words` SET `content_loc9`='%s quickly shoots the orc dummy...' WHERE `word_id` = 7275; -- db_script_string - content : entry=2000005743
UPDATE `trans_words` SET `content_loc9`='%s shoots from the hip at the bottles...' WHERE `word_id` = 7277; -- db_script_string - content : entry=2000005745
UPDATE `trans_words` SET `content_loc9`='%s shuffles through the books.' WHERE `word_id` = 7391; -- db_script_string - content : entry=2000000789
UPDATE `trans_words` SET `content_loc9`='%s skims the pages of the book.' WHERE `word_id` = 7364; -- db_script_string - content : entry=2000000524
UPDATE `trans_words` SET `content_loc9`='%s smashes the dead, twisted claw.' WHERE `word_id` = 7254; -- db_script_string - content : entry=2000005779
UPDATE `trans_words` SET `content_loc9`='%s takes a more careful aim...' WHERE `word_id` = 7266; -- db_script_string - content : entry=2000005732
UPDATE `trans_words` SET `content_loc9`='%s takes aim at the bottles again...' WHERE `word_id` = 7271; -- db_script_string - content : entry=2000005738
UPDATE `trans_words` SET `content_loc9`='%s takes aim at the bottles...' WHERE `word_id` = 7270; -- db_script_string - content : entry=2000005736
UPDATE `trans_words` SET `content_loc9`='%s then takes aim at the bottles...' WHERE `word_id` = 7273; -- db_script_string - content : entry=2000005741
UPDATE `trans_words` SET `content_loc9`='%s tosses the sword into the shallow pool.' WHERE `word_id` = 7073; -- db_script_string - content : entry=2000005023
UPDATE `trans_words` SET `content_loc9`='%s turns to the paper target...' WHERE `word_id` = 7276; -- db_script_string - content : entry=2000005744
UPDATE `trans_words` SET `content_loc9`='%s waits for the guards to be out of sight.' WHERE `word_id` = 7238; -- db_script_string - content : entry=2000000180
UPDATE `trans_words` SET `content_loc9`='%s wildly flips through the pages of a large tome.' WHERE `word_id` = 7388; -- db_script_string - content : entry=2000000786
UPDATE `trans_words` SET `content_loc9`='*Sigh* You\'re probably right, Raven. I\'m going back on patrol....' WHERE `word_id` = 7398; -- db_script_string - content : entry=2000000796
UPDATE `trans_words` SET `content_loc9`='...And then the tauren said, "13 INCHES!"' WHERE `word_id` = 7080; -- db_script_string - content : entry=2000005032
UPDATE `trans_words` SET `content_loc9`='\'s soft voice trails away into the mists. "Know that I love you always..."' WHERE `word_id` = 7208; -- db_script_string - content : entry=2000005344
UPDATE `trans_words` SET `content_loc9`='AAAAAAAAAAAAAAAARGH!' WHERE `word_id` = 7220; -- db_script_string - content : entry=2000000123
UPDATE `trans_words` SET `content_loc9`='Aaahhh... Another glorious victory for The Horde!' WHERE `word_id` = 7261; -- db_script_string - content : entry=2000005773
UPDATE `trans_words` SET `content_loc9`='ACHOO!' WHERE `word_id` = 6999; -- db_script_string - content : entry=2000000128
UPDATE `trans_words` SET `content_loc9`='After all we\'ve been through? Well, I didn\'t like you anyway!!' WHERE `word_id` = 7204; -- db_script_string - content : entry=2000005550
UPDATE `trans_words` SET `content_loc9`='Ah, I see you toil with relics of the past.' WHERE `word_id` = 7167; -- db_script_string - content : entry=2000005306
UPDATE `trans_words` SET `content_loc9`='Ah, thank you kindly. I will leave you to the library while I tend to this small matter.' WHERE `word_id` = 7034; -- db_script_string - content : entry=2000000176
UPDATE `trans_words` SET `content_loc9`='Ah, this must be him now... no?' WHERE `word_id` = 7070; -- db_script_string - content : entry=2000005018
UPDATE `trans_words` SET `content_loc9`='All hands to battle stations! Naga incoming!' WHERE `word_id` = 7248; -- db_script_string - content : entry=2000005632
UPDATE `trans_words` SET `content_loc9`='All right, I shall find people to help him.' WHERE `word_id` = 6944; -- db_script_string - content : entry=2000000011
UPDATE `trans_words` SET `content_loc9`='Always so negative. The chances of that happening are between zero and none.' WHERE `word_id` = 7138; -- db_script_string - content : entry=2000005170
UPDATE `trans_words` SET `content_loc9`='Amazing! I think I have found it, $N.' WHERE `word_id` = 7365; -- db_script_string - content : entry=2000000525
UPDATE `trans_words` SET `content_loc9`='Anaya...? Do my eyes deceive me? Is it really you?' WHERE `word_id` = 7181; -- db_script_string - content : entry=2000005336
UPDATE `trans_words` SET `content_loc9`='And I am determined to find out more... So if you need my help again, you know where I\'ll be.' WHERE `word_id` = 7221; -- db_script_string - content : entry=2000005026
UPDATE `trans_words` SET `content_loc9`='And should one die, two shall rise!' WHERE `word_id` = 7390; -- db_script_string - content : entry=2000000788
UPDATE `trans_words` SET `content_loc9`='And that\'s how Lother killed thirty six orcs with his bare hands!' WHERE `word_id` = 7099; -- db_script_string - content : entry=2000005115
UPDATE `trans_words` SET `content_loc9`='And then the rabbit just bit his head off... I swear.' WHERE `word_id` = 7095; -- db_script_string - content : entry=2000005111
UPDATE `trans_words` SET `content_loc9`='As if I don\'t have better things to do in my old age than carry buckets of water.' WHERE `word_id` = 5745; -- db_script_string - content : entry=2000005106
UPDATE `trans_words` SET `content_loc9`='Ask Kibler about the treasure! SQUAWK!' WHERE `word_id` = 5674; -- db_script_string - content : entry=2000005007
UPDATE `trans_words` SET `content_loc9`='Ask me how you can get a free drink at the Blue Recluse!' WHERE `word_id` = 7149; -- db_script_string - content : entry=2000005191
UPDATE `trans_words` SET `content_loc9`='At least we wouldn\'t be around to have to clean it up.' WHERE `word_id` = 7297; -- db_script_string - content : entry=2000005164
UPDATE `trans_words` SET `content_loc9`='Aye Remulos, prepare the mortal races.' WHERE `word_id` = 7864; -- db_script_string - content : entry=2000000382
UPDATE `trans_words` SET `content_loc9`='Baby wants her dolly!' WHERE `word_id` = 7090; -- db_script_string - content : entry=2000005058
UPDATE `trans_words` SET `content_loc9`='Be bathed in my power! Drink in my might! Battle for the glory of the Horde!' WHERE `word_id` = 6936; -- db_script_string - content : entry=2000000003
UPDATE `trans_words` SET `content_loc9`='Be warned that even your creators are fallible.' WHERE `word_id` = 7168; -- db_script_string - content : entry=2000005307
UPDATE `trans_words` SET `content_loc9`='Bear witness to the undeniable power of your Warchief! Be lifted by the rallying cry of your dragon slayers!' WHERE `word_id` = 7160; -- db_script_string - content : entry=2000005237
UPDATE `trans_words` SET `content_loc9`='begins to manipulate the Stone of Relu over the two fossils.' WHERE `word_id` = 7164; -- db_script_string - content : entry=2000005303
UPDATE `trans_words` SET `content_loc9`='Behold the might of the Alliance! The dread lady, Onyxia, hangs from the arches! Let the rallying cry of the dragon slayer lift your spirits!' WHERE `word_id` = 7162; -- db_script_string - content : entry=2000005239
UPDATE `trans_words` SET `content_loc9`='Best drinks in Stormwind!' WHERE `word_id` = 7146; -- db_script_string - content : entry=2000005186
UPDATE `trans_words` SET `content_loc9`='Beware $N! Look to the west!' WHERE `word_id` = 724; -- db_script_string - content : entry=2000000031
UPDATE `trans_words` SET `content_loc9`='Bijou knows where treasures are hidden.' WHERE `word_id` = 5676; -- db_script_string - content : entry=2000005004
UPDATE `trans_words` SET `content_loc9`='Bijou lost! SQUAWK! *cough' WHERE `word_id` = 7062; -- db_script_string - content : entry=2000005002
UPDATE `trans_words` SET `content_loc9`='Blue plus red... I predict...' WHERE `word_id` = 7378; -- db_script_string - content : entry=2000000541
UPDATE `trans_words` SET `content_loc9`='Breathtaking. Children, when we return to the school, you will each give an oral report on one of these legendary people.' WHERE `word_id` = 7118; -- db_script_string - content : entry=2000005141
UPDATE `trans_words` SET `content_loc9`='But if we stabilize it with an anchor thread at the appropriate energy crux then it should work.' WHERE `word_id` = 7136; -- db_script_string - content : entry=2000005172
UPDATE `trans_words` SET `content_loc9`='But isn\'t that what caused the initial problems with Adept Syleria\'s magical formula?' WHERE `word_id` = 7121; -- db_script_string - content : entry=2000005160
UPDATE `trans_words` SET `content_loc9`='But what if the resulting frequency shift were to send magical feedback up the flows?' WHERE `word_id` = 7122; -- db_script_string - content : entry=2000005159
UPDATE `trans_words` SET `content_loc9`='But wouldn\'t that mean crossing the streams? Isn\'t that really bad?' WHERE `word_id` = 7123; -- db_script_string - content : entry=2000005158
UPDATE `trans_words` SET `content_loc9`='By your command!' WHERE `word_id` = 7038; -- db_script_string - content : entry=2000000170
UPDATE `trans_words` SET `content_loc9`='Can anyone give my adorable, extra little kitty a home?' WHERE `word_id` = 5524; -- db_script_string - content : entry=2000005317
UPDATE `trans_words` SET `content_loc9`='Can I go collect more rocks for my necklace, Papa?' WHERE `word_id` = 7287; -- db_script_string - content : entry=2000005320
UPDATE `trans_words` SET `content_loc9`='Can we take a break? My feet are killing me and those ... those things down there are creeping me out.' WHERE `word_id` = 7395; -- db_script_string - content : entry=2000000793
UPDATE `trans_words` SET `content_loc9`='Can you imagine?' WHERE `word_id` = 7105; -- db_script_string - content : entry=2000005123
UPDATE `trans_words` SET `content_loc9`='Caught one! I\'ll see if any of the guards are hungry. Come on Fang!' WHERE `word_id` = 7284; -- db_script_string - content : entry=2000000190
UPDATE `trans_words` SET `content_loc9`='Cenarius fights at my side. Illidan sits atop his throne in Outland - brooding. I\'m afraid that the loss to Arthas proved to be his breaking point. Madness has embraced him, Remulos. He replays the events in his mind a thousand times per day, but in his mind, he is the victor and Arthas is utterly defeated. He is too far gone, old friend. I fear that the time may soon come that our bond is tested and it will not be as it was at the Well in Zin-Azshari.' WHERE `word_id` = 7316; -- db_script_string - content : entry=2000000384
UPDATE `trans_words` SET `content_loc9`='Chase me if you dare! I run without a care!' WHERE `word_id` = 7198; -- db_script_string - content : entry=2000005461
UPDATE `trans_words` SET `content_loc9`='Children if you would please follow me, we will now be going to see the keep where King Anduin Wrynn himself sits on this throne.' WHERE `word_id` = 7113; -- db_script_string - content : entry=2000005136
UPDATE `trans_words` SET `content_loc9`='Children of the Night, heed your Queen\'s call!' WHERE `word_id` = 7411; -- db_script_string - content : entry=2000000500
UPDATE `trans_words` SET `content_loc9`='Citizens and allies of Stormwind, on this day, history has been made. $N has laid waste to that which had attempted to usurp the rule of the kingdom. Gather round and join me in honoring our heroes.' WHERE `word_id` = 7161; -- db_script_string - content : entry=2000005238
UPDATE `trans_words` SET `content_loc9`='Cliffspring Falls lies along the mountains to the east and north.' WHERE `word_id` = 7183; -- db_script_string - content : entry=2000005347
UPDATE `trans_words` SET `content_loc9`='Come, $N. The lake is around the bend.' WHERE `word_id` = 7858; -- db_script_string - content : entry=2000000375
UPDATE `trans_words` SET `content_loc9`='Coming right up!' WHERE `word_id` = 7385; -- db_script_string - content : entry=2000000266
UPDATE `trans_words` SET `content_loc9`='Crybaby! Crybaby!' WHERE `word_id` = 7091; -- db_script_string - content : entry=2000005057
UPDATE `trans_words` SET `content_loc9`='Dabu! I will be careful Papa!' WHERE `word_id` = 7289; -- db_script_string - content : entry=2000005322
UPDATE `trans_words` SET `content_loc9`='Defend yourself, fool!' WHERE `word_id` = 7282; -- db_script_string - content : entry=2000000186
UPDATE `trans_words` SET `content_loc9`='Defiler... you will be punished for this incursion. <A symbol of flame radiates from the relic before it crumbles to the earth.>' WHERE `word_id` = 7350; -- db_script_string - content : entry=2000000355
UPDATE `trans_words` SET `content_loc9`='Deja vu. For a moment I thought I was back home... before the plague...' WHERE `word_id` = 7093; -- db_script_string - content : entry=2000005108
UPDATE `trans_words` SET `content_loc9`='dissipates before your eyes.' WHERE `word_id` = 7170; -- db_script_string - content : entry=2000005309
UPDATE `trans_words` SET `content_loc9`='Do not taint these ruins, mortal. <You are engulfed in a blinding flash of light. A creature composed entirely of flame is the only thing you can remember seeing.>' WHERE `word_id` = 7355; -- db_script_string - content : entry=2000000360
UPDATE `trans_words` SET `content_loc9`='Do you hate me, my love? That I was forced to destroy your living form, that your spirit be released from unhappy bondage.' WHERE `word_id` = 7179; -- db_script_string - content : entry=2000005339
UPDATE `trans_words` SET `content_loc9`='Don\'t forget the orphans of Stormwind!' WHERE `word_id` = 7304; -- db_script_string - content : entry=2000000350
UPDATE `trans_words` SET `content_loc9`='Don\'t hurt Betsy, you meanie!' WHERE `word_id` = 7085; -- db_script_string - content : entry=2000005063
UPDATE `trans_words` SET `content_loc9`='Don\'t worry, I\'ll find a good home for ya.' WHERE `word_id` = 5527; -- db_script_string - content : entry=2000005316
UPDATE `trans_words` SET `content_loc9`='Dragons controlling orcs!? SQUAWK!' WHERE `word_id` = 7063; -- db_script_string - content : entry=2000005005
UPDATE `trans_words` SET `content_loc9`='Drink this, it will help.' WHERE `word_id` = 7279; -- db_script_string - content : entry=2000000035
UPDATE `trans_words` SET `content_loc9`='Eww... that\'s not a fish!' WHERE `word_id` = 7100; -- db_script_string - content : entry=2000005116
UPDATE `trans_words` SET `content_loc9`='Farewell, Cerellean, until we are joined once again...' WHERE `word_id` = 7175; -- db_script_string - content : entry=2000005343
UPDATE `trans_words` SET `content_loc9`='Farewell, old friend... Farewell...' WHERE `word_id` = 7868; -- db_script_string - content : entry=2000000386
UPDATE `trans_words` SET `content_loc9`='Feegly the Exiled begins to make strange grunting noises. The Tear of the Moons drops to the ground and shatters.' WHERE `word_id` = 7055; -- db_script_string - content : entry=2000000243
UPDATE `trans_words` SET `content_loc9`='Feegly the Exiled begins to rub the Tear of the Moons.' WHERE `word_id` = 7058; -- db_script_string - content : entry=2000000241
UPDATE `trans_words` SET `content_loc9`='Feeling blue? Come on down to the Blue Recluse for a good time!' WHERE `word_id` = 7148; -- db_script_string - content : entry=2000005188
UPDATE `trans_words` SET `content_loc9`='Find me something good, you dogs!' WHERE `word_id` = 6947; -- db_script_string - content : entry=2000005557
UPDATE `trans_words` SET `content_loc9`='Fizzles used to be a great wizard. But got turned into a rabbit when one of his spells went bad.' WHERE `word_id` = 7144; -- db_script_string - content : entry=2000005184
UPDATE `trans_words` SET `content_loc9`='For so long I have drifted in my cursed form. You have freed me... Your hard work shall be repaid.' WHERE `word_id` = 7332; -- db_script_string - content : entry=2000005647
UPDATE `trans_words` SET `content_loc9`='Free drinks at the Blue Recluse!' WHERE `word_id` = 7150; -- db_script_string - content : entry=2000005193
UPDATE `trans_words` SET `content_loc9`='Get him out of there!' WHERE `word_id` = 924; -- db_script_string - content : entry=2000005099
UPDATE `trans_words` SET `content_loc9`='Gimmie my dolly!!' WHERE `word_id` = 7086; -- db_script_string - content : entry=2000005062
UPDATE `trans_words` SET `content_loc9`='Give of your hearts and your purses! Give to the children of Stormwind who have lost their parents.' WHERE `word_id` = 7305; -- db_script_string - content : entry=2000000351
UPDATE `trans_words` SET `content_loc9`='Give to the charities who seek to help the victims of these hard times! Please.' WHERE `word_id` = 7303; -- db_script_string - content : entry=2000000349
UPDATE `trans_words` SET `content_loc9`='Glad to see you\'re doing so well, Harlan. And I hope to see you again soon?' WHERE `word_id` = 7020; -- db_script_string - content : entry=2000000149
UPDATE `trans_words` SET `content_loc9`='Glorious, indeed, Maltrake. It looks as if my plan worked perfectly. Wouldn\'t you say so, mortal?' WHERE `word_id` = 7366; -- db_script_string - content : entry=2000000526
UPDATE `trans_words` SET `content_loc9`='Go swiftly $N. My fate is in your hands.' WHERE `word_id` = 7069; -- db_script_string - content : entry=2000005017
UPDATE `trans_words` SET `content_loc9`='Goddess, grant me the power to overcome my enemies! Hear me, please, my need is desperate and my cause is just!' WHERE `word_id` = 6197; -- db_script_string - content : entry=2000005241
UPDATE `trans_words` SET `content_loc9`='Good day to you both. I would speak to Lord Lescovar.' WHERE `word_id` = 7036; -- db_script_string - content : entry=2000000172
UPDATE `trans_words` SET `content_loc9`='Greetings, mortals! I have been activated by the Discs of Norgannon to assist you!' WHERE `word_id` = 7409; -- db_script_string - content : entry=2000000817
UPDATE `trans_words` SET `content_loc9`='Grimclaw begins to moan and roar at Terenthis while stomping his paws on the ground.' WHERE `word_id` = 7191; -- db_script_string - content : entry=2000005387
UPDATE `trans_words` SET `content_loc9`='Grimclaw roars at Terenthis more, but this time the druid seems to understand the bear.' WHERE `word_id` = 7187; -- db_script_string - content : entry=2000005391
UPDATE `trans_words` SET `content_loc9`='Grimclaw roars at Terenthis to get his attention.' WHERE `word_id` = 7194; -- db_script_string - content : entry=2000005385
UPDATE `trans_words` SET `content_loc9`='Grimclaw roars in acknowledgement at Terenthis.' WHERE `word_id` = 7185; -- db_script_string - content : entry=2000005393
UPDATE `trans_words` SET `content_loc9`='Grimclaw?! Easy there, my friend... where is your master Volcor?' WHERE `word_id` = 7192; -- db_script_string - content : entry=2000005386
UPDATE `trans_words` SET `content_loc9`='Ha ha! I have Betsy!' WHERE `word_id` = 7088; -- db_script_string - content : entry=2000005060
UPDATE `trans_words` SET `content_loc9`='He cannot be defeated. <The relic burns to nothing. The memories it held are now your own. This city was destroyed by a being not of this world.>' WHERE `word_id` = 7354; -- db_script_string - content : entry=2000000359
UPDATE `trans_words` SET `content_loc9`='Head on over to the Blue Recluse. Where everybody knows your name!' WHERE `word_id` = 7147; -- db_script_string - content : entry=2000005187
UPDATE `trans_words` SET `content_loc9`='Hello Grimclaw' WHERE `word_id` = 6938; -- db_script_string - content : entry=2000000004
UPDATE `trans_words` SET `content_loc9`='Hello, Charys. I have my list, could you get me all of that, especially the last ingredient.' WHERE `word_id` = 7140; -- db_script_string - content : entry=2000005180
UPDATE `trans_words` SET `content_loc9`='Hello, Selarin. I\'m afraid I cannot help you at the moment, but perhaps some of the adventurers here in Auberdine can...' WHERE `word_id` = 7321; -- db_script_string - content : entry=2000000395
UPDATE `trans_words` SET `content_loc9`='Help the children of Stormwind... victims of the war and plague!' WHERE `word_id` = 7306; -- db_script_string - content : entry=2000000352
UPDATE `trans_words` SET `content_loc9`='Help us, outsider. <The relic crumbles to dust. A vision of eight Dark Iron dwarves performing some sort of ritual fills your head.>' WHERE `word_id` = 7351; -- db_script_string - content : entry=2000000356
UPDATE `trans_words` SET `content_loc9`='Here we have Stormwind Keep. Built upon the ruins of Stormwind Castle, which was destroyed by the Horde in the first Great War.' WHERE `word_id` = 7114; -- db_script_string - content : entry=2000005137
UPDATE `trans_words` SET `content_loc9`='Here we have the Cathedral of Light, the center of spiritual enlightenment here in Stormwind.' WHERE `word_id` = 7111; -- db_script_string - content : entry=2000005134
UPDATE `trans_words` SET `content_loc9`='Here\'s a beacon, $N. Keep it to yourself, if you\'re gonna find mutilated things that we need.' WHERE `word_id` = 7059; -- db_script_string - content : entry=2000000318
UPDATE `trans_words` SET `content_loc9`='Hey Nag, how about you slice me off a piece of that...' WHERE `word_id` = 7383; -- db_script_string - content : entry=2000000264
UPDATE `trans_words` SET `content_loc9`='Hey Nagmara! How about a mug of Dark Iron Ale?' WHERE `word_id` = 7380; -- db_script_string - content : entry=2000000261
UPDATE `trans_words` SET `content_loc9`='Hey! Do you like the sauce? The sauce is good, no?' WHERE `word_id` = 7151; -- db_script_string - content : entry=2000005214
UPDATE `trans_words` SET `content_loc9`='HEY! No fair!' WHERE `word_id` = 7400; -- db_script_string - content : entry=2000000614
UPDATE `trans_words` SET `content_loc9`='Hey, Raven...' WHERE `word_id` = 7393; -- db_script_string - content : entry=2000000791
UPDATE `trans_words` SET `content_loc9`='Hey, someone help me catch this thing!' WHERE `word_id` = 7153; -- db_script_string - content : entry=2000005218
UPDATE `trans_words` SET `content_loc9`='Hmm, it could be that meddler Shaw. I will see what I can discover. Be off with you. I\'ll contact you again soon.' WHERE `word_id` = 7241; -- db_script_string - content : entry=2000000183
UPDATE `trans_words` SET `content_loc9`='Hmm... That rock is nice, but too small.' WHERE `word_id` = 7291; -- db_script_string - content : entry=2000005324
UPDATE `trans_words` SET `content_loc9`='Honor your heroes! On this day, they have dealt a great blow against one of our most hated enemies! The false Warchief, Rend Blackhand, has fallen!' WHERE `word_id` = 6937; -- db_script_string - content : entry=2000000002
UPDATE `trans_words` SET `content_loc9`='Hopefully I can send a worthy few to help Ashenvale and the Sentinels.' WHERE `word_id` = 7323; -- db_script_string - content : entry=2000000397
UPDATE `trans_words` SET `content_loc9`='How, my love? How will I find the strength to face the ages of the world without you by my side...' WHERE `word_id` = 7209; -- db_script_string - content : entry=2000005345
UPDATE `trans_words` SET `content_loc9`='I am going to practice and become a warrior like my father!' WHERE `word_id` = 7255; -- db_script_string - content : entry=2000005767
UPDATE `trans_words` SET `content_loc9`='I am looking for some bodyguards that would like to protect the Gizelton Caravan. We are stopped on the road east of Kormek\'s Hut, north of Kolkar Centaur Village.' WHERE `word_id` = 7405; -- db_script_string - content : entry=2000000401
UPDATE `trans_words` SET `content_loc9`='I bet my friend Gruk would like this rock for the spear he is making! It\'s very sharp... I hope he likes it.' WHERE `word_id` = 7293; -- db_script_string - content : entry=2000005326
UPDATE `trans_words` SET `content_loc9`='I can get back to the Stronghold on my own, I think. Now that you bought me some time, I should be able to stealth out of here. Who ever you are... thank you. May Elune bless you always!' WHERE `word_id` = 7196; -- db_script_string - content : entry=2000005396
UPDATE `trans_words` SET `content_loc9`='I can\'t believe dad won\'t let me keep your sister.' WHERE `word_id` = 5523; -- db_script_string - content : entry=2000005315
UPDATE `trans_words` SET `content_loc9`='I can\'t take these taxes! F.I.C.A. me? F.I.C.A. YOU!' WHERE `word_id` = 7157; -- db_script_string - content : entry=2000005234
UPDATE `trans_words` SET `content_loc9`='I caught a fish if you are hungry...' WHERE `word_id` = 7285; -- db_script_string - content : entry=2000000191
UPDATE `trans_words` SET `content_loc9`='I come from the land down under... where women plague and men sunder.' WHERE `word_id` = 7079; -- db_script_string - content : entry=2000005031
UPDATE `trans_words` SET `content_loc9`='I don\'t get paid enough for this bull excrement!' WHERE `word_id` = 7155; -- db_script_string - content : entry=2000005229
UPDATE `trans_words` SET `content_loc9`='I dont think there\'s any fish in these canals.' WHERE `word_id` = 7098; -- db_script_string - content : entry=2000005114
UPDATE `trans_words` SET `content_loc9`='I dunno, Jill. If Klaven comes down while we\'re slacking, we may end up as one of those things!' WHERE `word_id` = 7396; -- db_script_string - content : entry=2000000794
UPDATE `trans_words` SET `content_loc9`='I fear for the worst, old friend. Within the Dream we fight a new foe, born of an ancient evil. Ysera\'s noble brood has fallen victim to the old whisperings. It seems as if the Nightmare has broken through the realm to find a new host on Azeroth.' WHERE `word_id` = 7862; -- db_script_string - content : entry=2000000380
UPDATE `trans_words` SET `content_loc9`='I feel... dizzy. It\'s so hot... in... here...' WHERE `word_id` = 7173; -- db_script_string - content : entry=2000005312
UPDATE `trans_words` SET `content_loc9`='I got worm guts on my shoes.' WHERE `word_id` = 7101; -- db_script_string - content : entry=2000005117
UPDATE `trans_words` SET `content_loc9`='I have failed... I have failed in my duty... failed my people... The worgen run rampant, and the Scythe of my goddess is lost.' WHERE `word_id` = 7232; -- db_script_string - content : entry=2000005243
UPDATE `trans_words` SET `content_loc9`='I have your dolly! Nyah nyah!' WHERE `word_id` = 7087; -- db_script_string - content : entry=2000005061
UPDATE `trans_words` SET `content_loc9`='I haven\'t really figured out what it is, but there\'s something strange about the hot springs...' WHERE `word_id` = 7075; -- db_script_string - content : entry=2000005024
UPDATE `trans_words` SET `content_loc9`='I hope that was a fish!' WHERE `word_id` = 7103; -- db_script_string - content : entry=2000005121
UPDATE `trans_words` SET `content_loc9`='I join you in celebration of this most revered of nights - the night we Forsaken broke the Scourge\'s yoke of oppression!' WHERE `word_id` = 7412; -- db_script_string - content : entry=2000000501
UPDATE `trans_words` SET `content_loc9`='I leave you now, mortals. Alive and with these trinkets. Maltrake! Present them with the trinkets!' WHERE `word_id` = 7372; -- db_script_string - content : entry=2000000532
UPDATE `trans_words` SET `content_loc9`='I personally didn\'t mind him. It was the Prince who took exception to a high elf in his domain. Alas, I am not one to question the Prince. In his defense, he did not incinerate Master Winthalus immediately.' WHERE `word_id` = 7325; -- db_script_string - content : entry=2000000197
UPDATE `trans_words` SET `content_loc9`='I said GOOD DAY!' WHERE `word_id` = 7228; -- db_script_string - content : entry=2000000163
UPDATE `trans_words` SET `content_loc9`='I sensed as much, Malfurion. Dark days loom ahead.' WHERE `word_id` = 7863; -- db_script_string - content : entry=2000000381
UPDATE `trans_words` SET `content_loc9`='I shall cling to the love of my daughter and hope that I will find forgiveness under the Light for my sins.' WHERE `word_id` = 7230; -- db_script_string - content : entry=2000000165
UPDATE `trans_words` SET `content_loc9`='I shall use this time wisely, milord. Thank you.' WHERE `word_id` = 7235; -- db_script_string - content : entry=2000000177
UPDATE `trans_words` SET `content_loc9`='I should have taken the translucent pill.' WHERE `word_id` = 7154; -- db_script_string - content : entry=2000005228
UPDATE `trans_words` SET `content_loc9`='I suppose that could work, if we had twenty people to cast it with.' WHERE `word_id` = 7124; -- db_script_string - content : entry=2000005157
UPDATE `trans_words` SET `content_loc9`='I swear, people have actualy seen them. Pandaren really do exist!!' WHERE `word_id` = 7096; -- db_script_string - content : entry=2000005112
UPDATE `trans_words` SET `content_loc9`='I thank you. $N. And my brother thanks you.' WHERE `word_id` = 7060; -- db_script_string - content : entry=2000000808
UPDATE `trans_words` SET `content_loc9`='I think i see something.' WHERE `word_id` = 7102; -- db_script_string - content : entry=2000005118
UPDATE `trans_words` SET `content_loc9`='I think not, I don\'t need to be blown up again.' WHERE `word_id` = 7125; -- db_script_string - content : entry=2000005156
UPDATE `trans_words` SET `content_loc9`='I understand, my friend. I shall find someone to help your master. Go back to him now, or at least stay close.' WHERE `word_id` = 7186; -- db_script_string - content : entry=2000005392
UPDATE `trans_words` SET `content_loc9`='I very much doubt that he will have anything to say, stranger...' WHERE `word_id` = 7324; -- db_script_string - content : entry=2000000196
UPDATE `trans_words` SET `content_loc9`='I will need to focus my energies onto this knife. By doing so, I should catch some of the stronger psychic impressions associated with it.' WHERE `word_id` = 7361; -- db_script_string - content : entry=2000000521
UPDATE `trans_words` SET `content_loc9`='I win!' WHERE `word_id` = 7401; -- db_script_string - content : entry=2000000615
UPDATE `trans_words` SET `content_loc9`='I wonder if your dolly can swim!' WHERE `word_id` = 7089; -- db_script_string - content : entry=2000005059
UPDATE `trans_words` SET `content_loc9`='I... I\'ve seen enough I think... so very draining...' WHERE `word_id` = 7362; -- db_script_string - content : entry=2000000522
UPDATE `trans_words` SET `content_loc9`='I\'ll bring it right over, baby...' WHERE `word_id` = 7386; -- db_script_string - content : entry=2000000267
UPDATE `trans_words` SET `content_loc9`='I\'m out of here!' WHERE `word_id` = 1304; -- db_script_string - content : entry=2000005551
UPDATE `trans_words` SET `content_loc9`='I\'ve found that when I throw something into this water, it has improved incredibly when I retrieve it.' WHERE `word_id` = 7072; -- db_script_string - content : entry=2000005022
UPDATE `trans_words` SET `content_loc9`='I\'ve run out of arrows! I\'m afraid if any more come you will need to take them on by yourself my friend.' WHERE `word_id` = 7244; -- db_script_string - content : entry=2000005628
UPDATE `trans_words` SET `content_loc9`='If we can just hold them now, I am sure we will be in the clear.' WHERE `word_id` = 7249; -- db_script_string - content : entry=2000005633
UPDATE `trans_words` SET `content_loc9`='If we reverse the Essence flows perhaps we can alter the polarity.' WHERE `word_id` = 7133; -- db_script_string - content : entry=2000005148
UPDATE `trans_words` SET `content_loc9`='If we use the appropriate sequence we should be ok. Will just take some serious studying before we start.' WHERE `word_id` = 7300; -- db_script_string - content : entry=2000005173
UPDATE `trans_words` SET `content_loc9`='If we use the Surian theory, then yes, but not if we go with the Y\'serian approach.' WHERE `word_id` = 7137; -- db_script_string - content : entry=2000005171
UPDATE `trans_words` SET `content_loc9`='If you have the time, Grimclaw and his master Volcor could use your help. If you\'re interested, speak with me further...' WHERE `word_id` = 7214; -- db_script_string - content : entry=2000005394
UPDATE `trans_words` SET `content_loc9`='If you want the key, you\'ll have to catch me!' WHERE `word_id` = 7197; -- db_script_string - content : entry=2000005460
UPDATE `trans_words` SET `content_loc9`='Incredible! Amazing! I don\'t even know what this means!' WHERE `word_id` = 282621; -- db_script_string - content : entry=2000005804
UPDATE `trans_words` SET `content_loc9`='Into the box me pretties! Thas it. One by one, ye go.' WHERE `word_id` = 7327; -- db_script_string - content : entry=2000000074
UPDATE `trans_words` SET `content_loc9`='Is it true that the paladins train here?' WHERE `word_id` = 7134; -- db_script_string - content : entry=2000005167
UPDATE `trans_words` SET `content_loc9`='Isn\'t it amazing, children? All who enter the city must walk beneath the watchful eyes of the greatest heroes of our lands.' WHERE `word_id` = 7117; -- db_script_string - content : entry=2000005140
UPDATE `trans_words` SET `content_loc9`='It is this night that our enemies fear us the most. It is THIS night that we show our enemies what it means to stand against the Forsaken!' WHERE `word_id` = 7413; -- db_script_string - content : entry=2000000502
UPDATE `trans_words` SET `content_loc9`='It was shrouded in nightmares, Malfurion. What is happening in the Dream? What could cause such atrocities?' WHERE `word_id` = 7861; -- db_script_string - content : entry=2000000379
UPDATE `trans_words` SET `content_loc9`='It\'s getting away!' WHERE `word_id` = 7081; -- db_script_string - content : entry=2000005035
UPDATE `trans_words` SET `content_loc9`='It\'s time for my meditation, leave me.' WHERE `word_id` = 7236; -- db_script_string - content : entry=2000000178
UPDATE `trans_words` SET `content_loc9`='Jack and Jill my wrinkled patoot! I do all the water luggin\' round here.' WHERE `word_id` = 7517; -- db_script_string - content : entry=2000005103
UPDATE `trans_words` SET `content_loc9`='Just sit right back and you\'ll hear a ta... *hic* a tai... *hic* a taiii *hic* Damnit!' WHERE `word_id` = 7156; -- db_script_string - content : entry=2000005233
UPDATE `trans_words` SET `content_loc9`='Kibler is being investigated by G.E.T.A.' WHERE `word_id` = 5671; -- db_script_string - content : entry=2000005003
UPDATE `trans_words` SET `content_loc9`='Kitten for sale, looking for a good home.' WHERE `word_id` = 6535; -- db_script_string - content : entry=2000005319
UPDATE `trans_words` SET `content_loc9`='Klaven doesn\'t pay me enough to deal with those zombies, drones or whatever he calls \'em. I don\'t know, Jill. If Klaven comes down while we\'re slacking, we might end up as those things!' WHERE `word_id` = 7397; -- db_script_string - content : entry=2000000795
UPDATE `trans_words` SET `content_loc9`='Leave this place. <The relic emits a white hot arc of flame. A memory has been gained: A lone Dark Iron dwarf is surrounded by seven corpses, kneeling before a monolith of flame.>' WHERE `word_id` = 7353; -- db_script_string - content : entry=2000000354
UPDATE `trans_words` SET `content_loc9`='Let it not trouble your heart, beloved. You have freed me from slavery, and for that I love you all the more.' WHERE `word_id` = 7178; -- db_script_string - content : entry=2000005340
UPDATE `trans_words` SET `content_loc9`='Let me help you with those.' WHERE `word_id` = 7278; -- db_script_string - content : entry=2000000034
UPDATE `trans_words` SET `content_loc9`='Let us return to the grove, mortal.' WHERE `word_id` = 7869; -- db_script_string - content : entry=2000000387
UPDATE `trans_words` SET `content_loc9`='Let\'s move forward!' WHERE `word_id` = 7222; -- db_script_string - content : entry=2000005553
UPDATE `trans_words` SET `content_loc9`='Look alive, dogs! We got an operation to run here!' WHERE `word_id` = 7110; -- db_script_string - content : entry=2000005132
UPDATE `trans_words` SET `content_loc9`='Ma reth bromo zoln kilagrin dra ma zoern tu ko fraht ka tadrom Ma krin drinor zaln dirnor Ma krin kan aasrugel korsul' WHERE `word_id` = 7031; -- db_script_string - content : entry=2000000160
UPDATE `trans_words` SET `content_loc9`='Magical studies stressing your brain? Relax at the Blue Recluse!' WHERE `word_id` = 7145; -- db_script_string - content : entry=2000005185
UPDATE `trans_words` SET `content_loc9`='Maginor says that twisting alternating flows of positive energy actually creates a much more stable flow.' WHERE `word_id` = 7129; -- db_script_string - content : entry=2000005152
UPDATE `trans_words` SET `content_loc9`='Malfurion!' WHERE `word_id` = 7309; -- db_script_string - content : entry=2000000377
UPDATE `trans_words` SET `content_loc9`='Milord, your guest has arrived. He awaits your presence.' WHERE `word_id` = 7212; -- db_script_string - content : entry=2000000175
UPDATE `trans_words` SET `content_loc9`='Mistress, you tell Plugger that I want more of his ale. I can\'t get enough!' WHERE `word_id` = 7382; -- db_script_string - content : entry=2000000263
UPDATE `trans_words` SET `content_loc9`='Mogg, get inside. It is not safe out there while your father is gone.' WHERE `word_id` = 7262; -- db_script_string - content : entry=2000005774
UPDATE `trans_words` SET `content_loc9`='Mommy? Can I pet Fizzles?' WHERE `word_id` = 7143; -- db_script_string - content : entry=2000005183
UPDATE `trans_words` SET `content_loc9`='My father says that\'s just a story.' WHERE `word_id` = 7108; -- db_script_string - content : entry=2000005126
UPDATE `trans_words` SET `content_loc9`='My legs feels much better now, the remedy must be working. If you will excuse me, I must go report to my superiors about what has transpired here.' WHERE `word_id` = 7246; -- db_script_string - content : entry=2000005630
UPDATE `trans_words` SET `content_loc9`='My scepter will once again become whole!' WHERE `word_id` = 7338; -- db_script_string - content : entry=2000005653
UPDATE `trans_words` SET `content_loc9`='My sword Archeus served me well in life, but as at last my spirit may pass from the unhappy existence, I need it no longer.' WHERE `word_id` = 7229; -- db_script_string - content : entry=2000000164
UPDATE `trans_words` SET `content_loc9`='My, that Black Claw stout packs quite a punch!' WHERE `word_id` = 7172; -- db_script_string - content : entry=2000005311
UPDATE `trans_words` SET `content_loc9`='Nagmara! Have any mutton left?' WHERE `word_id` = 7381; -- db_script_string - content : entry=2000000262
UPDATE `trans_words` SET `content_loc9`='No matter. You were a fool to help me, and now you will pay!' WHERE `word_id` = 7331; -- db_script_string - content : entry=2000000236
UPDATE `trans_words` SET `content_loc9`='No! Anaya... Anaya! Don\'t leave me! Please...' WHERE `word_id` = 7176; -- db_script_string - content : entry=2000005342
UPDATE `trans_words` SET `content_loc9`='No! Get away from me! Help!!' WHERE `word_id` = 7358; -- db_script_string - content : entry=2000005626
UPDATE `trans_words` SET `content_loc9`='None may steal the secrets of the Makers!' WHERE `word_id` = 5656; -- db_script_string - content : entry=2000005555
UPDATE `trans_words` SET `content_loc9`='Now go back home where you belong!' WHERE `word_id` = 7260; -- db_script_string - content : entry=2000005772
UPDATE `trans_words` SET `content_loc9`='NOW is the time of the Forsaken! Power to the Forsaken - NOW AND FOREVER!!!' WHERE `word_id` = 7416; -- db_script_string - content : entry=2000000505
UPDATE `trans_words` SET `content_loc9`='Now is the time to shake the world to its foundations! NOW is the time to remind those who would enslave us that we shall never yield!' WHERE `word_id` = 7415; -- db_script_string - content : entry=2000000504
UPDATE `trans_words` SET `content_loc9`='Now let\'s try it...' WHERE `word_id` = 7250; -- db_script_string - content : entry=2000005752
UPDATE `trans_words` SET `content_loc9`='Now to find an unsuspecting Harpy!' WHERE `word_id` = 7256; -- db_script_string - content : entry=2000005768
UPDATE `trans_words` SET `content_loc9`='Now where did I put the Venture Company formulations?' WHERE `word_id` = 7392; -- db_script_string - content : entry=2000000790
UPDATE `trans_words` SET `content_loc9`='Now, let\'s see... If I am correct, then... Hmmm...' WHERE `word_id` = 7377; -- db_script_string - content : entry=2000000540
UPDATE `trans_words` SET `content_loc9`='Now, take another long look before we make our way to the Holy District and the great Cathedral of Light.' WHERE `word_id` = 7119; -- db_script_string - content : entry=2000005142
UPDATE `trans_words` SET `content_loc9`='O\'ourse I\'m talking to myself. Only way to get a decent conversation in this city.' WHERE `word_id` = 5744; -- db_script_string - content : entry=2000005105
UPDATE `trans_words` SET `content_loc9`='Of course. He awaits you in the library.' WHERE `word_id` = 7037; -- db_script_string - content : entry=2000000173
UPDATE `trans_words` SET `content_loc9`='Ograbisi needs new hat.' WHERE `word_id` = 7360; -- db_script_string - content : entry=2000005102
UPDATE `trans_words` SET `content_loc9`='Oh man, I thought I was dead for sure. Ugh... still dizzy...' WHERE `word_id` = 7195; -- db_script_string - content : entry=2000005395
UPDATE `trans_words` SET `content_loc9`='Oh no! Here they come!' WHERE `word_id` = 7207; -- db_script_string - content : entry=2000005547
UPDATE `trans_words` SET `content_loc9`='OH NOES! Da king is dead! Uh... hail to da new king! Yeah!' WHERE `word_id` = 7340; -- db_script_string - content : entry=2000000166
UPDATE `trans_words` SET `content_loc9`='Oh yes, the molt - do not lose it. There are those of my kin in the Burning Steppes that would craft items that only the molt of the black dragonflight could fortify.' WHERE `word_id` = 7375; -- db_script_string - content : entry=2000000535
UPDATE `trans_words` SET `content_loc9`='Ok, here I go!' WHERE `word_id` = 7206; -- db_script_string - content : entry=2000005548
UPDATE `trans_words` SET `content_loc9`='Only if we didn\'t follow the proper initialization procedures.' WHERE `word_id` = 7299; -- db_script_string - content : entry=2000005166
UPDATE `trans_words` SET `content_loc9`='Ooohh... This rock is nice and colorful. Let\'s see if I can find more like it...' WHERE `word_id` = 7290; -- db_script_string - content : entry=2000005323
UPDATE `trans_words` SET `content_loc9`='Opus wants some Cuergo\'s Gold... with worm.' WHERE `word_id` = 5672; -- db_script_string - content : entry=2000005001
UPDATE `trans_words` SET `content_loc9`='Our oldest clutch of dragons are still far from maturity, but with patience and study, we are confident the dragons will soon be ready.' WHERE `word_id` = 7078; -- db_script_string - content : entry=2000005029
UPDATE `trans_words` SET `content_loc9`='People of the Horde, citizens of Orgrimmar, come, gather round and celebrate heroes of the Horde. On this day, $N, under the auspices of our glorious Warchief, laid a mortal blow against the Black Dragonflight. The brood mother, Onyxia, has been slain!' WHERE `word_id` = 7159; -- db_script_string - content : entry=2000005236
UPDATE `trans_words` SET `content_loc9`='Perhaps Ograbisi will use your head as a tiny little hat when I\'m through with you.' WHERE `word_id` = 7356; -- db_script_string - content : entry=2000005100
UPDATE `trans_words` SET `content_loc9`='Please do as I instruct you, $N.' WHERE `word_id` = 7333; -- db_script_string - content : entry=2000005648
UPDATE `trans_words` SET `content_loc9`='Please speak with Sentinel Onaeya at Maestra\'s Post in Ashenvale, she will see to it that you are properly rewarded for your bravery this day.' WHERE `word_id` = 7247; -- db_script_string - content : entry=2000005631
UPDATE `trans_words` SET `content_loc9`='Please, follow me.' WHERE `word_id` = 7074; -- db_script_string - content : entry=2000005025
UPDATE `trans_words` SET `content_loc9`='Poor Dorius. If I ever get my hands on those Dark Irons, so help me...' WHERE `word_id` = 7302; -- db_script_string - content : entry=2000005350
UPDATE `trans_words` SET `content_loc9`='Power! Glorious power!' WHERE `word_id` = 7056; -- db_script_string - content : entry=2000000242
UPDATE `trans_words` SET `content_loc9`='Praise Elune! I don\'t know if I could have survived the day without you, friend.' WHERE `word_id` = 7245; -- db_script_string - content : entry=2000005629
UPDATE `trans_words` SET `content_loc9`='Putting in twelve centers of focus might allow the magical energies to form more solidly, adding the necessary stability.' WHERE `word_id` = 7126; -- db_script_string - content : entry=2000005155
UPDATE `trans_words` SET `content_loc9`='Quillboar scraps! These should do the trick. Fish love Quillboar.' WHERE `word_id` = 7283; -- db_script_string - content : entry=2000000189
UPDATE `trans_words` SET `content_loc9`='Read this tome I have placed before you, and speak the words aloud.' WHERE `word_id` = 7334; -- db_script_string - content : entry=2000005649
UPDATE `trans_words` SET `content_loc9`='Ready. Set. GO!' WHERE `word_id` = 7399; -- db_script_string - content : entry=2000000613
UPDATE `trans_words` SET `content_loc9`='Remulos, I am being drawn back... Tyrande... send her my love... Tell her I am safe... Tell her... Tell her I will return... Farewell...' WHERE `word_id` = 7317; -- db_script_string - content : entry=2000000385
UPDATE `trans_words` SET `content_loc9`='Remulos, old friend. It is good to see you once more. I knew the message would find its way to you - one way or another.' WHERE `word_id` = 7310; -- db_script_string - content : entry=2000000378
UPDATE `trans_words` SET `content_loc9`='Right away, master!' WHERE `word_id` = 7373; -- db_script_string - content : entry=2000000533
UPDATE `trans_words` SET `content_loc9`='Sadly, even this must be cut short... The ties that bind me to this world weaken, and pull me away...' WHERE `word_id` = 7177; -- db_script_string - content : entry=2000005341
UPDATE `trans_words` SET `content_loc9`='Sargath fades into the mist...' WHERE `word_id` = 6969; -- db_script_string - content : entry=2000000053
UPDATE `trans_words` SET `content_loc9`='Say hello to my little friends!' WHERE `word_id` = 7201; -- db_script_string - content : entry=2000005464
UPDATE `trans_words` SET `content_loc9`='Search this rubble.' WHERE `word_id` = 6946; -- db_script_string - content : entry=2000005556
UPDATE `trans_words` SET `content_loc9`='Seems like a hundred times a day I walk all the way to get more water. No respect for their elders I tell ya.' WHERE `word_id` = 5747; -- db_script_string - content : entry=2000005107
UPDATE `trans_words` SET `content_loc9`='SILENCE FOOL!' WHERE `word_id` = 7370; -- db_script_string - content : entry=2000000530
UPDATE `trans_words` SET `content_loc9`='So sorry to leave a customer but we have places to go and people to swindle. We will be back sometime later today. Good-bye!' WHERE `word_id` = 7404; -- db_script_string - content : entry=2000000400
UPDATE `trans_words` SET `content_loc9`='So then the array of magics would cascade into a chain reaction of positively charged energies.' WHERE `word_id` = 7131; -- db_script_string - content : entry=2000005150
UPDATE `trans_words` SET `content_loc9`='Speak with me to hear my tale.' WHERE `word_id` = 7408; -- db_script_string - content : entry=2000000813
UPDATE `trans_words` SET `content_loc9`='Spirits of the forest come forth and heed nature\'s call!' WHERE `word_id` = 7348; -- db_script_string - content : entry=2000005781
UPDATE `trans_words` SET `content_loc9`='Spirits of the forest, you are needed! Make haste to the Charred Vale!' WHERE `word_id` = 7349; -- db_script_string - content : entry=2000005782
UPDATE `trans_words` SET `content_loc9`='Spirits of Water, I give you praise, and I beg of you a favour. You have heard $N\'s please, and I trust his inent is noble. Please, will you aid us?' WHERE `word_id` = 6972; -- db_script_string - content : entry=2000000057
UPDATE `trans_words` SET `content_loc9`='SQUAWK!! *cough* *cough* I need to quit smoking!' WHERE `word_id` = 5675; -- db_script_string - content : entry=2000005008
UPDATE `trans_words` SET `content_loc9`='Stand near me, $N. I will protect you should anything go wrong.' WHERE `word_id` = 7859; -- db_script_string - content : entry=2000000376
UPDATE `trans_words` SET `content_loc9`='Stand Prepared! The naga won\'t wait long to press their advantage once they know we\'re alive.' WHERE `word_id` = 7339; -- db_script_string - content : entry=2000000466
UPDATE `trans_words` SET `content_loc9`='Stonemasons. . .errr. . Defias be warned:  The rusty anchor sinks tonight.' WHERE `word_id` = 7226; -- db_script_string - content : entry=2000005302
UPDATE `trans_words` SET `content_loc9`='Sure Paige. Just be gentle.' WHERE `word_id` = 7141; -- db_script_string - content : entry=2000005181
UPDATE `trans_words` SET `content_loc9`='Take that you mangy Harpy! Hyaa!' WHERE `word_id` = 7258; -- db_script_string - content : entry=2000005770
UPDATE `trans_words` SET `content_loc9`='Terenthis begins to cast a spell on Grimclaw.' WHERE `word_id` = 7189; -- db_script_string - content : entry=2000005389
UPDATE `trans_words` SET `content_loc9`='Terenthis, Raene sent me to find you. The Sentinels are in need of help in Ashenvale.' WHERE `word_id` = 7320; -- db_script_string - content : entry=2000000260
UPDATE `trans_words` SET `content_loc9`='Thank you, $N. And luck to you.' WHERE `word_id` = 7184; -- db_script_string - content : entry=2000005346
UPDATE `trans_words` SET `content_loc9`='Thank you, Terenthis. I shall remain here for as long as I can.' WHERE `word_id` = 7322; -- db_script_string - content : entry=2000000396
UPDATE `trans_words` SET `content_loc9`='Thank you. The Light be with you both.' WHERE `word_id` = 7035; -- db_script_string - content : entry=2000000174
UPDATE `trans_words` SET `content_loc9`='Thanks, Charys. C\'mon Paige, sweetie.' WHERE `word_id` = 7142; -- db_script_string - content : entry=2000005182
UPDATE `trans_words` SET `content_loc9`='That the fates should be so cruel as to permit us only this after a thousand years apart...' WHERE `word_id` = 7180; -- db_script_string - content : entry=2000005338
UPDATE `trans_words` SET `content_loc9`='That will unbalance the magical focus, though, and cause a reverse vibration in the ether.' WHERE `word_id` = 7120; -- db_script_string - content : entry=2000005161
UPDATE `trans_words` SET `content_loc9`='That\'s it! That\'s what you were waiting for! KILL THEM!' WHERE `word_id` = 7243; -- db_script_string - content : entry=2000000185
UPDATE `trans_words` SET `content_loc9`='That\'s neat.' WHERE `word_id` = 7109; -- db_script_string - content : entry=2000005129
UPDATE `trans_words` SET `content_loc9`='The abomination has overrun the Night Watch camp! Quickly, we must intercept it before it reaches town!' WHERE `word_id` = 7281; -- db_script_string - content : entry=2000000187
UPDATE `trans_words` SET `content_loc9`='The ages have been cruel to you and I, my love, but be assured, it is, and at long last we are reunited.' WHERE `word_id` = 7182; -- db_script_string - content : entry=2000005337
UPDATE `trans_words` SET `content_loc9`='The beast is slain! All is well in Darkshire.' WHERE `word_id` = 7328; -- db_script_string - content : entry=2000000188
UPDATE `trans_words` SET `content_loc9`='The boss wants all hands on high alert. The rusty anchor sinks tonight.' WHERE `word_id` = 7225; -- db_script_string - content : entry=2000005301
UPDATE `trans_words` SET `content_loc9`='The burning of the Wickerman will begin in fifteen minutes! Come to the festival - located just west of the Undercity - and celebrate Hallow\'s End and our liberation from the Scourge!' WHERE `word_id` = 7418; -- db_script_string - content : entry=2000000509
UPDATE `trans_words` SET `content_loc9`='The burning of the Wickerman will begin in five minutes! Come to the festival - located just west of the Undercity - and celebrate Hallow\'s End and our liberation from the Scourge!' WHERE `word_id` = 7419; -- db_script_string - content : entry=2000000510
UPDATE `trans_words` SET `content_loc9`='The burning of the Wickerman will begin in thirty minutes! Come to the festival - located just west of the Undercity - and celebrate Hallow\'s End and our liberation from the Scourge!' WHERE `word_id` = 7417; -- db_script_string - content : entry=2000000508
UPDATE `trans_words` SET `content_loc9`='The deeds are mine, brother! Soon you shall be out of my way for good!' WHERE `word_id` = 6935; -- db_script_string - content : entry=2000000001
UPDATE `trans_words` SET `content_loc9`='The discs are now ready! Engage the Discs of Norgannon once again to retrieve them!' WHERE `word_id` = 7410; -- db_script_string - content : entry=2000000818
UPDATE `trans_words` SET `content_loc9`='The invisibility liquor is ready for you, $N.' WHERE `word_id` = 7005; -- db_script_string - content : entry=2000000134
UPDATE `trans_words` SET `content_loc9`='The legion of Blackrock comes, dwarflings! We shall scorch the earth and set fire to the heavens. None shall survive...' WHERE `word_id` = 7376; -- db_script_string - content : entry=2000000536
UPDATE `trans_words` SET `content_loc9`='The Lich King\'s forces are building. It is imperative that our timetable supports his plans.' WHERE `word_id` = 7076; -- db_script_string - content : entry=2000005027
UPDATE `trans_words` SET `content_loc9`='The magical wards at that sholud be supported enough by the energy flux to certain the entity.' WHERE `word_id` = 7130; -- db_script_string - content : entry=2000005151
UPDATE `trans_words` SET `content_loc9`='The numbers of my companions dwindles, goddess, and my own power shall soon be insufficient to hold back the demons of Felwood.' WHERE `word_id` = 6198; -- db_script_string - content : entry=2000005240
UPDATE `trans_words` SET `content_loc9`='The portal will shift slightly, at this point if you cast a binding cantrip you will solidify it in place.' WHERE `word_id` = 7128; -- db_script_string - content : entry=2000005153
UPDATE `trans_words` SET `content_loc9`='The power of the Tear of the Moons is mine! Mine I say!' WHERE `word_id` = 7057; -- db_script_string - content : entry=2000000240
UPDATE `trans_words` SET `content_loc9`='The resultant energies could collapse though, and that could cause an energy flux that would give you a migraine for weeks.' WHERE `word_id` = 7296; -- db_script_string - content : entry=2000005163
UPDATE `trans_words` SET `content_loc9`='The Stonewrought Dam has been saved! Three cheers for $N!' WHERE `word_id` = 7163; -- db_script_string - content : entry=2000005300
UPDATE `trans_words` SET `content_loc9`='The sweet irony -- Stormwind forces cut down in defense of their city, only to rise and fight alongside the Brotherhood as instruments of destruction.' WHERE `word_id` = 7389; -- db_script_string - content : entry=2000000787
UPDATE `trans_words` SET `content_loc9`='The what-bringer? Oh, ASHbringer? Never heard of it... What? Stop bothering me!' WHERE `word_id` = 7152; -- db_script_string - content : entry=2000005215
UPDATE `trans_words` SET `content_loc9`='The Wickerman Festival now begins! Power to the Forsaken!' WHERE `word_id` = 7420; -- db_script_string - content : entry=2000000511
UPDATE `trans_words` SET `content_loc9`='There you are. What news from Westfall?' WHERE `word_id` = 7239; -- db_script_string - content : entry=2000000181
UPDATE `trans_words` SET `content_loc9`='There... That should be enough rocks to make a necklace. I should probably get home now anyway.' WHERE `word_id` = 7294; -- db_script_string - content : entry=2000005327
UPDATE `trans_words` SET `content_loc9`='There... that should help. Now, tell me what\'s happened, Grimclaw.' WHERE `word_id` = 7188; -- db_script_string - content : entry=2000005390
UPDATE `trans_words` SET `content_loc9`='There\'s one! For the Horde!' WHERE `word_id` = 7257; -- db_script_string - content : entry=2000005769
UPDATE `trans_words` SET `content_loc9`='They all go to the Spire but none never come back... just like Bijou.' WHERE `word_id` = 5673; -- db_script_string - content : entry=2000005006
UPDATE `trans_words` SET `content_loc9`='They say he can turn into a raven sometimes.' WHERE `word_id` = 7094; -- db_script_string - content : entry=2000005109
UPDATE `trans_words` SET `content_loc9`='They will live of only to see the fruits of their labor: the destruction and chaos that will surely ensue as the legion of Blackrock invade the gorge.' WHERE `word_id` = 7371; -- db_script_string - content : entry=2000000531
UPDATE `trans_words` SET `content_loc9`='This evil I have unleashed... In whose hand does the power my goddess granted to me now lie... By whose hand is it directed?' WHERE `word_id` = 7233; -- db_script_string - content : entry=2000005244
UPDATE `trans_words` SET `content_loc9`='This is a shiney rock. I\'ll put it in my bucket. Ok, I just need a few more...' WHERE `word_id` = 7292; -- db_script_string - content : entry=2000005325
UPDATE `trans_words` SET `content_loc9`='This is Rigger Gizelton asking for assistance escorting my caravan past Mannoroc Coven. I\'m on the road east of Shadowprey village.' WHERE `word_id` = 7407; -- db_script_string - content : entry=2000000403
UPDATE `trans_words` SET `content_loc9`='Time for my patrol. I\'ll be back shortly.' WHERE `word_id` = 7158; -- db_script_string - content : entry=2000005235
UPDATE `trans_words` SET `content_loc9`='Time for the Gizelton Caravan to head on out! We\'ll be back soon but if you cannot wait, head north to Kormek\'s Hut. We open shop in about an hour.' WHERE `word_id` = 7406; -- db_script_string - content : entry=2000000402
UPDATE `trans_words` SET `content_loc9`='Together, the two parts shall become one, once again.' WHERE `word_id` = 7336; -- db_script_string - content : entry=2000005651
UPDATE `trans_words` SET `content_loc9`='Tomorrow we will begin training of our promising dragons, so don\'t forget your chew toys.' WHERE `word_id` = 7077; -- db_script_string - content : entry=2000005028
UPDATE `trans_words` SET `content_loc9`='Ugh! That\'s terrible!' WHERE `word_id` = 7251; -- db_script_string - content : entry=2000005753
UPDATE `trans_words` SET `content_loc9`='VanCleef sends word that the plans are underway. But he\'s heard rumors about someone snooping about.' WHERE `word_id` = 7240; -- db_script_string - content : entry=2000000182
UPDATE `trans_words` SET `content_loc9`='Very well. I will return then.' WHERE `word_id` = 7242; -- db_script_string - content : entry=2000000184
UPDATE `trans_words` SET `content_loc9`='Volcor need help ?' WHERE `word_id` = 6943; -- db_script_string - content : entry=2000000010
UPDATE `trans_words` SET `content_loc9`='Volcor was gone?' WHERE `word_id` = 6940; -- db_script_string - content : entry=2000000006
UPDATE `trans_words` SET `content_loc9`='Wait here, $N. Spybot will make Lescovar come out as soon as possible. Be ready! Attack only after you\'ve overheard their conversation.' WHERE `word_id` = 7039; -- db_script_string - content : entry=2000000171
UPDATE `trans_words` SET `content_loc9`='Wait, $N!!! It looks like we\'re going to need some help here...' WHERE `word_id` = 6957; -- db_script_string - content : entry=2000000041
UPDATE `trans_words` SET `content_loc9`='Wait... did you hear that? Something approaches from the west!' WHERE `word_id` = 6945; -- db_script_string - content : entry=2000005627
UPDATE `trans_words` SET `content_loc9`='Wanna race again? Best two out of three!' WHERE `word_id` = 7403; -- db_script_string - content : entry=2000000617
UPDATE `trans_words` SET `content_loc9`='We burn the effigy of the Wickerman as a symbol of our struggle against those who would oppose us. We wear the ashes of the burnt Wickerman as a symbol of our neverending fight against those who would enslave us.' WHERE `word_id` = 7414; -- db_script_string - content : entry=2000000503
UPDATE `trans_words` SET `content_loc9`='We most definitely do not need any more attention drawn to us, stranger. Return to those that sent you in search of the lost master and tell them that nothing could be found. When this is done - and I will know when it is so - return and I shall reveal the secrets of the deceased.' WHERE `word_id` = 7326; -- db_script_string - content : entry=2000000198
UPDATE `trans_words` SET `content_loc9`='We must hurry.' WHERE `word_id` = 7347; -- db_script_string - content : entry=2000005780
UPDATE `trans_words` SET `content_loc9`='Well done, soldiers! At ease!' WHERE `word_id` = 7064; -- db_script_string - content : entry=2000005009
UPDATE `trans_words` SET `content_loc9`='Well, ok. I am now sending people . We need find and help him.' WHERE `word_id` = 6942; -- db_script_string - content : entry=2000000008
UPDATE `trans_words` SET `content_loc9`='Well, whatever it is, it works quite well!' WHERE `word_id` = 7071; -- db_script_string - content : entry=2000005021
UPDATE `trans_words` SET `content_loc9`='What does allergic mean anyway? And what does it have to do with either of my kitties?' WHERE `word_id` = 5525; -- db_script_string - content : entry=2000005314
UPDATE `trans_words` SET `content_loc9`='What happens?' WHERE `word_id` = 6939; -- db_script_string - content : entry=2000000005
UPDATE `trans_words` SET `content_loc9`='What if we used three focuses in Tyrean pattern? That should solve it.' WHERE `word_id` = 7139; -- db_script_string - content : entry=2000005169
UPDATE `trans_words` SET `content_loc9`='What was that noise? It sounded like a roar.' WHERE `word_id` = 7193; -- db_script_string - content : entry=2000005384
UPDATE `trans_words` SET `content_loc9`='What will we do with them, master? They are of no use to us anymore.' WHERE `word_id` = 7369; -- db_script_string - content : entry=2000000529
UPDATE `trans_words` SET `content_loc9`='What... what is this? Could this by the answer to my prayers? Elune has granted me a weapon -- this scythe -- to defeat the demons.' WHERE `word_id` = 7231; -- db_script_string - content : entry=2000005242
UPDATE `trans_words` SET `content_loc9`='What? $N, you served me well, but...' WHERE `word_id` = 7329; -- db_script_string - content : entry=2000000234
UPDATE `trans_words` SET `content_loc9`='What? How dare you say that to me?!?' WHERE `word_id` = 7205; -- db_script_string - content : entry=2000005549
UPDATE `trans_words` SET `content_loc9`='What?? The Burning Blade is spreading! We must investigate!' WHERE `word_id` = 7253; -- db_script_string - content : entry=2000005778
UPDATE `trans_words` SET `content_loc9`='When is pappa comming back from the fights in Warsong? It has been so long...' WHERE `word_id` = 7263; -- db_script_string - content : entry=2000005775
UPDATE `trans_words` SET `content_loc9`='When the Horde was shattered, men returned here and began to rebuild the once great city as a testament to our own survival.' WHERE `word_id` = 7115; -- db_script_string - content : entry=2000005138
UPDATE `trans_words` SET `content_loc9`='When the positively aligned energies collide with the negatively charged energies, they don\'t negate one another.' WHERE `word_id` = 7127; -- db_script_string - content : entry=2000005154
UPDATE `trans_words` SET `content_loc9`='Where I come from, you get shanked for opening another inmate\'s cell door!' WHERE `word_id` = 7357; -- db_script_string - content : entry=2000005101
UPDATE `trans_words` SET `content_loc9`='Where\'s the water Emma? Get the water Emma? If\'n it weren\'t fer me that lot wouldn\'t know what water looks like.' WHERE `word_id` = 5746; -- db_script_string - content : entry=2000005104
UPDATE `trans_words` SET `content_loc9`='Who dares step into my domain! Come! Come, and be consumed!' WHERE `word_id` = 7203; -- db_script_string - content : entry=2000005552
UPDATE `trans_words` SET `content_loc9`='Who hath summoned forth Aman?' WHERE `word_id` = 7166; -- db_script_string - content : entry=2000005305
UPDATE `trans_words` SET `content_loc9`='Whoa! This is way more than what I bargained for, you\'re on your own, Slim!' WHERE `word_id` = 747; -- db_script_string - content : entry=2000000602
UPDATE `trans_words` SET `content_loc9`='Whoa, whoa there, my friend. One moment...' WHERE `word_id` = 7190; -- db_script_string - content : entry=2000005388
UPDATE `trans_words` SET `content_loc9`='Why can\'t we just shift the array to compensate for the variance in the flux?' WHERE `word_id` = 7132; -- db_script_string - content : entry=2000005149
UPDATE `trans_words` SET `content_loc9`='Why do we have to learn this stuff anyway?' WHERE `word_id` = 7135; -- db_script_string - content : entry=2000005168
UPDATE `trans_words` SET `content_loc9`='Why have you summoned me so soon? I haven\'t yet reached my full power!' WHERE `word_id` = 7330; -- db_script_string - content : entry=2000000235
UPDATE `trans_words` SET `content_loc9`='Why would you ever want to harm me!? Come. Friends we can be!' WHERE `word_id` = 7199; -- db_script_string - content : entry=2000005462
UPDATE `trans_words` SET `content_loc9`='Will someone please give my little kitten a good home?' WHERE `word_id` = 5526; -- db_script_string - content : entry=2000005318
UPDATE `trans_words` SET `content_loc9`='Worm goes on the hook, hook goes in the water, Fish is in the water, our fish.' WHERE `word_id` = 7104; -- db_script_string - content : entry=2000005122
UPDATE `trans_words` SET `content_loc9`='Wouldn\'t that cause the weave to unravel if not properly anchored before starting the casting?' WHERE `word_id` = 7295; -- db_script_string - content : entry=2000005162
UPDATE `trans_words` SET `content_loc9`='Wow, all of this for a love potion. Hope he\'s worth it.' WHERE `word_id` = 7298; -- db_script_string - content : entry=2000005165
UPDATE `trans_words` SET `content_loc9`='Wow.' WHERE `word_id` = 7107; -- db_script_string - content : entry=2000005125
UPDATE `trans_words` SET `content_loc9`='Yar, he\'s dead all right. That makes you da new king... well, all of you! Gordok is yours now, boss! You should talk to me so you can learn everything there is about being da king! I was... is his assistant! Yeah, that\'s why I\'m called da crafty one!' WHERE `word_id` = 7341; -- db_script_string - content : entry=2000000167
UPDATE `trans_words` SET `content_loc9`='Yes right away momma!' WHERE `word_id` = 7066; -- db_script_string - content : entry=2000005011
UPDATE `trans_words` SET `content_loc9`='Yes you may, Okla. But do not stray too far from home.' WHERE `word_id` = 7288; -- db_script_string - content : entry=2000005321
UPDATE `trans_words` SET `content_loc9`='Yes, sir!' WHERE `word_id` = 7237; -- db_script_string - content : entry=2000000179
UPDATE `trans_words` SET `content_loc9`='Yes, that is true. Paladins and Priests alike train their skills and research great truths behind the walls of the Cathedral.' WHERE `word_id` = 7112; -- db_script_string - content : entry=2000005135
UPDATE `trans_words` SET `content_loc9`='Yes, well...let\'s head on to the monument dedicated to the heroes of the two Great Wars, the Valley of Heroes. Follow Me.' WHERE `word_id` = 7116; -- db_script_string - content : entry=2000005139
UPDATE `trans_words` SET `content_loc9`='You can\'t get away from a warrior of the Horde! Take that! And that!' WHERE `word_id` = 7259; -- db_script_string - content : entry=2000005771
UPDATE `trans_words` SET `content_loc9`='You cheated!' WHERE `word_id` = 7402; -- db_script_string - content : entry=2000000616
UPDATE `trans_words` SET `content_loc9`='You got it!' WHERE `word_id` = 7384; -- db_script_string - content : entry=2000000265
UPDATE `trans_words` SET `content_loc9`='You have been gone too long, Malfurion. Peace between the Children of Azeroth has become tenuous at best. What of my father? Of your brother? Have you any news?' WHERE `word_id` = 7315; -- db_script_string - content : entry=2000000383
UPDATE `trans_words` SET `content_loc9`='You know where he is?' WHERE `word_id` = 6941; -- db_script_string - content : entry=2000000007
UPDATE `trans_words` SET `content_loc9`='You know why Orcs eyes glow red? It\'s because they drink blood!' WHERE `word_id` = 7097; -- db_script_string - content : entry=2000005113
UPDATE `trans_words` SET `content_loc9`='You wish to learn of the stone? Follow me.' WHERE `word_id` = 7174; -- db_script_string - content : entry=2000005646
UPDATE `trans_words` SET `content_loc9`='You would not have helped the legion of Blackrock had we just asked for your assistance, now would you?' WHERE `word_id` = 7368; -- db_script_string - content : entry=2000000528
UPDATE `trans_words` SET `content_loc9`='You\'re going to be just fine.' WHERE `word_id` = 7280; -- db_script_string - content : entry=2000000036
UPDATE `trans_words` SET `content_loc9`='Your existence is acknowledged. <The relic turns to dust. Your head throbs with newfound wisdom. Something evil lurks in the heart of the mountain.>' WHERE `word_id` = 7352; -- db_script_string - content : entry=2000000357
UPDATE `trans_words` SET `content_loc9`='Zug zug! Happy to help!' WHERE `word_id` = 7065; -- db_script_string - content : entry=2000005010

SET NAMES 'latin1';
