-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc3`='[PH] Get E.C.A.C.' WHERE `word_id`=128451; -- locales_gossip_menu_option - option_text : menu_id=524-id=0
UPDATE `trans_words` SET `content_loc3`='[PH] Get Thieves\' Tools' WHERE `word_id`=128154; -- locales_gossip_menu_option - option_text : menu_id=161-id=1
UPDATE `trans_words` SET `content_loc3`='[PH] I desire an aqual quintessence, Duke Hydraxis.' WHERE `word_id`=128495; -- locales_gossip_menu_option - option_text : menu_id=5065-id=0
UPDATE `trans_words` SET `content_loc3`='[ph]Learn recipe...' WHERE `word_id`=128221; -- locales_gossip_menu_option - option_text : menu_id=6443-id=0
UPDATE `trans_words` SET `content_loc3`='<Nod>' WHERE `word_id`=128168; -- locales_gossip_menu_option - option_text : menu_id=5702-id=0
UPDATE `trans_words` SET `content_loc3`='Bank' WHERE `word_id`=114494; -- locales_gossip_menu_option - option_text : menu_id=3506-id=0
UPDATE `trans_words` SET `content_loc3`='Do you know where I can find Half Pendant of Aquatic Agility?' WHERE `word_id`=127921; -- locales_gossip_menu_option - option_text : menu_id=4041-id=1
UPDATE `trans_words` SET `content_loc3`='Gor\'shak is my friend, you can trust me.' WHERE `word_id`=128512; -- locales_gossip_menu_option - option_text : menu_id=1830-id=0
UPDATE `trans_words` SET `content_loc3`='Gul\'dan' WHERE `word_id`=84267; -- locales_gossip_menu_option - option_text : menu_id=4764-id=0
UPDATE `trans_words` SET `content_loc3`='I can not Vaelastrasz ! Surely there must be some way to heal you!' WHERE `word_id`=128456; -- locales_gossip_menu_option - option_text : menu_id=6021-id=0
UPDATE `trans_words` SET `content_loc3`='I know this is rather silly but a young ward who is a bit shy would like your hoofprint.' WHERE `word_id`=127943; -- locales_gossip_menu_option - option_text : menu_id=5851-id=0
UPDATE `trans_words` SET `content_loc3`='Lady Jaina, this may sound like an odd request... but I have a young ward who is quite shy. You are a hero to him, and he asked me to get your autograph.' WHERE `word_id`=127878; -- locales_gossip_menu_option - option_text : menu_id=2465-id=0
UPDATE `trans_words` SET `content_loc3`='My answer - Alexstrasza.' WHERE `word_id`=127930; -- locales_gossip_menu_option - option_text : menu_id=4763-id=3
UPDATE `trans_words` SET `content_loc3`='My answer - Malygos.' WHERE `word_id`=127929; -- locales_gossip_menu_option - option_text : menu_id=4763-id=4
UPDATE `trans_words` SET `content_loc3`='My answer - Neltharion.' WHERE `word_id`=127932; -- locales_gossip_menu_option - option_text : menu_id=4763-id=1
UPDATE `trans_words` SET `content_loc3`='My answer - Nozdormu.' WHERE `word_id`=127931; -- locales_gossip_menu_option - option_text : menu_id=4763-id=2
UPDATE `trans_words` SET `content_loc3`='My answer - Ysera.' WHERE `word_id`=127933; -- locales_gossip_menu_option - option_text : menu_id=4763-id=0
UPDATE `trans_words` SET `content_loc3`='Natalia?' WHERE `word_id`=128020; -- locales_gossip_menu_option - option_text : menu_id=6549-id=0
UPDATE `trans_words` SET `content_loc3`='Ner\'zhul' WHERE `word_id`=128151; -- locales_gossip_menu_option - option_text : menu_id=4764-id=2
UPDATE `trans_words` SET `content_loc3`='Not enough, you need to tell me more.' WHERE `word_id`=128513; -- locales_gossip_menu_option - option_text : menu_id=1829-id=0
UPDATE `trans_words` SET `content_loc3`='Ok, let me get this straight. You put the scepter entrusted to your Flight by Anachronos  on a minnow of your own making and now you expect me to build an... an arcanite buoy or something... to force your minnow out of hiding? AND potentially incur the wrath of an Elemental Lord? Did I miss anything? Perhaps I am to do this without any clothes on, during a solar eclipse, on a leap year?' WHERE `word_id`=130110; -- locales_gossip_menu_option - option_text : menu_id=15010-id=0
UPDATE `trans_words` SET `content_loc3`='Paladin' WHERE `word_id`=99882; -- locales_gossip_menu_option - option_text : menu_id=2144-id=2
UPDATE `trans_words` SET `content_loc3`='Paval Reethe.' WHERE `word_id`=128449; -- locales_gossip_menu_option - option_text : menu_id=1186-id=1
UPDATE `trans_words` SET `content_loc3`='Transcript the Tablet' WHERE `word_id`=128093; -- locales_gossip_menu_option - option_text : menu_id=2187-id=0

SET NAMES 'latin1';
