-- File generated by Mangos Online Translation Editor (MOTE) v3.03
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc3`='%s looks weak enough to capture.' WHERE `word_id` = 5797; -- creature_ai_texts - content : entry=-274
UPDATE `trans_words` SET `content_loc3`='%s\'s laughter trails off..' WHERE `word_id` = 5903; -- creature_ai_texts - content : entry=-663
UPDATE `trans_words` SET `content_loc3`='Aaaahhhhhh!' WHERE `word_id` = 5806; -- creature_ai_texts - content : entry=-212
UPDATE `trans_words` SET `content_loc3`='ARRRRRRR!' WHERE `word_id` = 5775; -- creature_ai_texts - content : entry=-366
UPDATE `trans_words` SET `content_loc3`='At last, it ends...' WHERE `word_id` = 5542; -- creature_ai_texts - content : entry=-1298
UPDATE `trans_words` SET `content_loc3`='At last: one among you is worthy of my knowledge. Worry not: I have probed your thoughts, no harm will come to you.' WHERE `word_id` = 5906; -- creature_ai_texts - content : entry=-666
UPDATE `trans_words` SET `content_loc3`='By the Light, you will leave this tomb!' WHERE `word_id` = 5677; -- creature_ai_texts - content : entry=-581
UPDATE `trans_words` SET `content_loc3`='Come, spirits, attend your master!' WHERE `word_id` = 5550; -- creature_ai_texts - content : entry=-1223
UPDATE `trans_words` SET `content_loc3`='DON\'T LET THIS STATUE BE MY ONLY COMPANY, COME OUT AND PLAY!' WHERE `word_id` = 5911; -- creature_ai_texts - content : entry=-1208
UPDATE `trans_words` SET `content_loc3`='Foolish mortal, you serve me now!' WHERE `word_id` = 5545; -- creature_ai_texts - content : entry=-1295
UPDATE `trans_words` SET `content_loc3`='Get it while it\'s hot!' WHERE `word_id` = 5895; -- creature_ai_texts - content : entry=-142
UPDATE `trans_words` SET `content_loc3`='HAVE YOU RUN OUT OF SHIPS TO SEND? WHERE IS YOUR COURAGE?' WHERE `word_id` = 5914; -- creature_ai_texts - content : entry=-1211
UPDATE `trans_words` SET `content_loc3`='I HAVE YOUR LITTLE BELT TIED AROUND MY FINGER, SMOTTS. DON\'T YOU WANT IT BACK?' WHERE `word_id` = 5916; -- creature_ai_texts - content : entry=-1213
UPDATE `trans_words` SET `content_loc3`='More... More souls.' WHERE `word_id` = 5554; -- creature_ai_texts - content : entry=-1204
UPDATE `trans_words` SET `content_loc3`='No rest, for the angry dead.' WHERE `word_id` = 5555; -- creature_ai_texts - content : entry=-1203
UPDATE `trans_words` SET `content_loc3`='Now that you have had a chance to study imp, let us move on the next minion you will be able to summon, the voidwalker.' WHERE `word_id` = 5927; -- creature_ai_texts - content : entry=-1414
UPDATE `trans_words` SET `content_loc3`='Obsidion, Rise and Serve your Master!' WHERE `word_id` = 5905; -- creature_ai_texts - content : entry=-665
UPDATE `trans_words` SET `content_loc3`='Silithid Creeper Egg begins to crack and open...' WHERE `word_id` = 5528; -- creature_ai_texts - content : entry=-1318
UPDATE `trans_words` SET `content_loc3`='Silithid Creeper Egg splits open!' WHERE `word_id` = 5530; -- creature_ai_texts - content : entry=-1319
UPDATE `trans_words` SET `content_loc3`='Silithid Creeper lays an egg!' WHERE `word_id` = 5529; -- creature_ai_texts - content : entry=-1317
UPDATE `trans_words` SET `content_loc3`='SMOTTS! HEY, SMOTTS! COME OUT AND PLAY!' WHERE `word_id` = 5910; -- creature_ai_texts - content : entry=-1207
UPDATE `trans_words` SET `content_loc3`='SMOTTS, I HAVE YOUR LITTLE BELT....COME GET IT!' WHERE `word_id` = 5909; -- creature_ai_texts - content : entry=-1206
UPDATE `trans_words` SET `content_loc3`='This will teach you to lay off the herb, $R.' WHERE `word_id` = 5600; -- creature_ai_texts - content : entry=-1019
UPDATE `trans_words` SET `content_loc3`='TIMMY!' WHERE `word_id` = 5561; -- creature_ai_texts - content : entry=-1197
UPDATE `trans_words` SET `content_loc3`='What? How dare you!' WHERE `word_id` = 5897; -- creature_ai_texts - content : entry=-144
UPDATE `trans_words` SET `content_loc3`='You are in the presence of a god!' WHERE `word_id` = 5575; -- creature_ai_texts - content : entry=-1048
UPDATE `trans_words` SET `content_loc3`='You just got MALOWNED!' WHERE `word_id` = 5562; -- creature_ai_texts - content : entry=-1196
UPDATE `trans_words` SET `content_loc3`='You land lovers are tougher then I thought! I will need to improvise' WHERE `word_id` = 5836; -- creature_ai_texts - content : entry=-175
UPDATE `trans_words` SET `content_loc3`='You\'ll never leave this place... alive.' WHERE `word_id` = 5552; -- creature_ai_texts - content : entry=-1221

SET NAMES 'latin1';
