-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc3`='(Night Elf Female)' WHERE `word_id` = 79079; -- locales_creature - subname : entry=10798
UPDATE `trans_words` SET `content_loc3`='Adjutant Tesoran' WHERE `word_id` = 76344; -- locales_creature - name : entry=4948
UPDATE `trans_words` SET `content_loc3`='Agam\'ar' WHERE `word_id` = 268289; -- locales_creature - name : entry=4511
UPDATE `trans_words` SET `content_loc3`='Ahn\'Qiraj Trigger' WHERE `word_id` = 81096; -- locales_creature - name : entry=15426
UPDATE `trans_words` SET `content_loc3`='Alchemist Arbington' WHERE `word_id` = 79222; -- locales_creature - name : entry=11056
UPDATE `trans_words` SET `content_loc3`='Alchemist Narett' WHERE `word_id` = 76329; -- locales_creature - name : entry=4900
UPDATE `trans_words` SET `content_loc3`='Alexandre Lefevre' WHERE `word_id` = 75243; -- locales_creature - name : entry=3552
UPDATE `trans_words` SET `content_loc3`='Aman' WHERE `word_id` = 75265; -- locales_creature - name : entry=3582
UPDATE `trans_words` SET `content_loc3`='A-Me 01' WHERE `word_id` = 78637; -- locales_creature - name : entry=9623
UPDATE `trans_words` SET `content_loc3`='Ammunition Vendor' WHERE `word_id` = 81854; -- locales_creature - subname : entry=17598
UPDATE `trans_words` SET `content_loc3`='Anathemus' WHERE `word_id` = 74476; -- locales_creature - name : entry=2754
UPDATE `trans_words` SET `content_loc3`='Andi' WHERE `word_id` = 75190; -- locales_creature - name : entry=3507
UPDATE `trans_words` SET `content_loc3`='Arikara' WHERE `word_id` = 79119; -- locales_creature - name : entry=10882
UPDATE `trans_words` SET `content_loc3`='Balai Lok\'Wein' WHERE `word_id` = 80251; -- locales_creature - name : entry=13476
UPDATE `trans_words` SET `content_loc3`='Bale' WHERE `word_id` = 74527; -- locales_creature - name : entry=2806
UPDATE `trans_words` SET `content_loc3`='Balir Frosthammer' WHERE `word_id` = 72719; -- locales_creature - name : entry=713
UPDATE `trans_words` SET `content_loc3`='Baron Aquanis' WHERE `word_id` = 80052; -- locales_creature - name : entry=12876
UPDATE `trans_words` SET `content_loc3`='Baron Geddon' WHERE `word_id` = 79773; -- locales_creature - name : entry=12056
UPDATE `trans_words` SET `content_loc3`='Baron Kazum' WHERE `word_id` = 80967; -- locales_creature - name : entry=15205
UPDATE `trans_words` SET `content_loc3`='Baron Revilgaz' WHERE `word_id` = 74238; -- locales_creature - name : entry=2496
UPDATE `trans_words` SET `content_loc3`='Baron Vardus' WHERE `word_id` = 74060; -- locales_creature - name : entry=2306
UPDATE `trans_words` SET `content_loc3`='Baroness Anastari' WHERE `word_id` = 78906; -- locales_creature - name : entry=10436
UPDATE `trans_words` SET `content_loc3`='Bethaine Flinthammer' WHERE `word_id` = 78732; -- locales_creature - name : entry=10046
UPDATE `trans_words` SET `content_loc3`='Big Will' WHERE `word_id` = 77231; -- locales_creature - name : entry=6238
UPDATE `trans_words` SET `content_loc3`='Billy' WHERE `word_id` = 73344; -- locales_creature - name : entry=1367
UPDATE `trans_words` SET `content_loc3`='Bingles Blastenheimer' WHERE `word_id` = 77378; -- locales_creature - name : entry=6577
UPDATE `trans_words` SET `content_loc3`='Black Battlestrider' WHERE `word_id` = 20557; -- locales_creature - name : entry=14334
UPDATE `trans_words` SET `content_loc3`='Black War Kodo' WHERE `word_id` = 20561; -- locales_creature - name : entry=14333
UPDATE `trans_words` SET `content_loc3`='Bor\'zehn' WHERE `word_id` = 76059; -- locales_creature - name : entry=4546
UPDATE `trans_words` SET `content_loc3`='Brawn' WHERE `word_id` = 73362; -- locales_creature - name : entry=1385
UPDATE `trans_words` SET `content_loc3`='Brine' WHERE `word_id` = 77002; -- locales_creature - name : entry=5899
UPDATE `trans_words` SET `content_loc3`='Bro\'kin' WHERE `word_id` = 74220; -- locales_creature - name : entry=2480
UPDATE `trans_words` SET `content_loc3`='Burth' WHERE `word_id` = 80747; -- locales_creature - name : entry=14827
UPDATE `trans_words` SET `content_loc3`='Camerick Jongleur' WHERE `word_id` = 73425; -- locales_creature - name : entry=1451
UPDATE `trans_words` SET `content_loc3`='Charity Mipsy' WHERE `word_id` = 76324; -- locales_creature - name : entry=4896
UPDATE `trans_words` SET `content_loc3`='Chatter' WHERE `word_id` = 72645; -- locales_creature - name : entry=616
UPDATE `trans_words` SET `content_loc3`='Clunk' WHERE `word_id` = 78182; -- locales_creature - name : entry=8447
UPDATE `trans_words` SET `content_loc3`='Cog Glitzspinner' WHERE `word_id` = 72493; -- locales_creature - name : entry=374
UPDATE `trans_words` SET `content_loc3`='Colonel Kurzen' WHERE `word_id` = 72808; -- locales_creature - name : entry=813
UPDATE `trans_words` SET `content_loc3`='Cranky Benj' WHERE `word_id` = 80381; -- locales_creature - name : entry=14223
UPDATE `trans_words` SET `content_loc3`='Craven Drok' WHERE `word_id` = 76766; -- locales_creature - name : entry=5639
UPDATE `trans_words` SET `content_loc3`='Crocilisk Trainer' WHERE `word_id` = 74578; -- locales_creature - subname : entry=2876
UPDATE `trans_words` SET `content_loc3`='Cyclonian' WHERE `word_id` = 77232; -- locales_creature - name : entry=6239
UPDATE `trans_words` SET `content_loc3`='Cyrus Therepentous' WHERE `word_id` = 78556; -- locales_creature - name : entry=9459
UPDATE `trans_words` SET `content_loc3`='Daisy' WHERE `word_id` = 76027; -- locales_creature - name : entry=4507
UPDATE `trans_words` SET `content_loc3`='Darcy' WHERE `word_id` = 72498; -- locales_creature - name : entry=379
UPDATE `trans_words` SET `content_loc3`='Debug Point' WHERE `word_id` = 81095; -- locales_creature - name : entry=15425
UPDATE `trans_words` SET `content_loc3`='Duggan Wildhammer' WHERE `word_id` = 79097; -- locales_creature - name : entry=10817
UPDATE `trans_words` SET `content_loc3`='Durdek Karrin' WHERE `word_id` = 74583; -- locales_creature - name : entry=2881
UPDATE `trans_words` SET `content_loc3`='Dwarf Female' WHERE `word_id` = 79073; -- locales_creature - subname : entry=10792
UPDATE `trans_words` SET `content_loc3`='Dwarf Male' WHERE `word_id` = 79072; -- locales_creature - subname : entry=10791
UPDATE `trans_words` SET `content_loc3`='Elu' WHERE `word_id` = 78857; -- locales_creature - name : entry=10377
UPDATE `trans_words` SET `content_loc3`='Enraged Form' WHERE `word_id` = 74198; -- locales_creature - subname : entry=2454
UPDATE `trans_words` SET `content_loc3`='Falstad Wildhammer' WHERE `word_id` = 76760; -- locales_creature - name : entry=5635
UPDATE `trans_words` SET `content_loc3`='Fedfennel' WHERE `word_id` = 72557; -- locales_creature - name : entry=472
UPDATE `trans_words` SET `content_loc3`='Felcular' WHERE `word_id` = 77837; -- locales_creature - name : entry=7735
UPDATE `trans_words` SET `content_loc3`='Fenthwick' WHERE `word_id` = 76486; -- locales_creature - name : entry=5167
UPDATE `trans_words` SET `content_loc3`='Florist' WHERE `word_id` = 73258; -- locales_creature - subname : entry=1302
UPDATE `trans_words` SET `content_loc3`='Fobeed' WHERE `word_id` = 76135; -- locales_creature - name : entry=4620
UPDATE `trans_words` SET `content_loc3`='Frostwolf' WHERE `word_id` = 79169; -- locales_creature - name : entry=10981
UPDATE `trans_words` SET `content_loc3`='Gadgetzan Water Co.' WHERE `word_id` = 77704; -- locales_creature - subname : entry=7407
UPDATE `trans_words` SET `content_loc3`='Gazelle' WHERE `word_id` = 75742; -- locales_creature - name : entry=4166
UPDATE `trans_words` SET `content_loc3`='Gazlowe' WHERE `word_id` = 75077; -- locales_creature - name : entry=3391
UPDATE `trans_words` SET `content_loc3`='General Colbatann' WHERE `word_id` = 78787; -- locales_creature - name : entry=10196
UPDATE `trans_words` SET `content_loc3`='General Drakkisath' WHERE `word_id` = 78846; -- locales_creature - name : entry=10363
UPDATE `trans_words` SET `content_loc3`='General Fangferror' WHERE `word_id` = 77393; -- locales_creature - name : entry=6650
UPDATE `trans_words` SET `content_loc3`='General Kirika' WHERE `word_id` = 81841; -- locales_creature - name : entry=17079
UPDATE `trans_words` SET `content_loc3`='General Marcus Jonathan' WHERE `word_id` = 72551; -- locales_creature - name : entry=466
UPDATE `trans_words` SET `content_loc3`='General Rajaxx' WHERE `word_id` = 81046; -- locales_creature - name : entry=15341
UPDATE `trans_words` SET `content_loc3`='General Zog' WHERE `word_id` = 81199; -- locales_creature - name : entry=15539
UPDATE `trans_words` SET `content_loc3`='Gest' WHERE `word_id` = 75008; -- locales_creature - name : entry=3327
UPDATE `trans_words` SET `content_loc3`='Ghost Visual' WHERE `word_id` = 80045; -- locales_creature - subname : entry=12861
UPDATE `trans_words` SET `content_loc3`='Ghost/Ghoul spawner' WHERE `word_id` = 81712; -- locales_creature - subname : entry=16306
UPDATE `trans_words` SET `content_loc3`='Ghost/Skeleton spawner' WHERE `word_id` = 81713; -- locales_creature - subname : entry=16336
UPDATE `trans_words` SET `content_loc3`='Ghoul/Skeleton spawner' WHERE `word_id` = 81714; -- locales_creature - subname : entry=16338
UPDATE `trans_words` SET `content_loc3`='Gibblesnik' WHERE `word_id` = 80513; -- locales_creature - name : entry=14427
UPDATE `trans_words` SET `content_loc3`='Gizlock' WHERE `word_id` = 80307; -- locales_creature - name : entry=13620
UPDATE `trans_words` SET `content_loc3`='Gnome Female' WHERE `word_id` = 79075; -- locales_creature - subname : entry=10794
UPDATE `trans_words` SET `content_loc3`='Gobbler' WHERE `word_id` = 73211; -- locales_creature - name : entry=1259
UPDATE `trans_words` SET `content_loc3`='Gol\'dir' WHERE `word_id` = 74068; -- locales_creature - name : entry=2316
UPDATE `trans_words` SET `content_loc3`='Gor\'tesh' WHERE `word_id` = 78481; -- locales_creature - name : entry=9176
UPDATE `trans_words` SET `content_loc3`='Grazle' WHERE `word_id` = 79462; -- locales_creature - name : entry=11554
UPDATE `trans_words` SET `content_loc3`='Grellkin' WHERE `word_id` = 73813; -- locales_creature - name : entry=1989
UPDATE `trans_words` SET `content_loc3`='Grimlok' WHERE `word_id` = 76293; -- locales_creature - name : entry=4854
UPDATE `trans_words` SET `content_loc3`='Grizlak' WHERE `word_id` = 73397; -- locales_creature - name : entry=1425
UPDATE `trans_words` SET `content_loc3`='Grizzle' WHERE `word_id` = 78425; -- locales_creature - name : entry=9028
UPDATE `trans_words` SET `content_loc3`='Grub' WHERE `word_id` = 75123; -- locales_creature - name : entry=3443
UPDATE `trans_words` SET `content_loc3`='Gurky' WHERE `word_id` = 81604; -- locales_creature - name : entry=16069
UPDATE `trans_words` SET `content_loc3`='Haggle' WHERE `word_id` = 80366; -- locales_creature - name : entry=14041
UPDATE `trans_words` SET `content_loc3`='Harken Windtotem' WHERE `word_id` = 74624; -- locales_creature - name : entry=2947
UPDATE `trans_words` SET `content_loc3`='Henria Derth' WHERE `word_id` = 74575; -- locales_creature - name : entry=2870
UPDATE `trans_words` SET `content_loc3`='Herod' WHERE `word_id` = 75578; -- locales_creature - name : entry=3975
UPDATE `trans_words` SET `content_loc3`='Hilary' WHERE `word_id` = 78397; -- locales_creature - name : entry=8962
UPDATE `trans_words` SET `content_loc3`='Hogger' WHERE `word_id` = 72536; -- locales_creature - name : entry=448
UPDATE `trans_words` SET `content_loc3`='Human Female' WHERE `word_id` = 79077; -- locales_creature - subname : entry=10796
UPDATE `trans_words` SET `content_loc3`='Human Male' WHERE `word_id` = 79076; -- locales_creature - subname : entry=10795
UPDATE `trans_words` SET `content_loc3`='Hurom Juggendolf' WHERE `word_id` = 74581; -- locales_creature - name : entry=2880
UPDATE `trans_words` SET `content_loc3`='Hydroling' WHERE `word_id` = 80457; -- locales_creature - name : entry=14350
UPDATE `trans_words` SET `content_loc3`='Impsy' WHERE `word_id` = 80553; -- locales_creature - name : entry=14470
UPDATE `trans_words` SET `content_loc3`='Isalien Trigger' WHERE `word_id` = 81579; -- locales_creature - name : entry=16045
UPDATE `trans_words` SET `content_loc3`='Jalinda Sprig' WHERE `word_id` = 78612; -- locales_creature - name : entry=9561
UPDATE `trans_words` SET `content_loc3`='Jekyll Flandring' WHERE `word_id` = 80164; -- locales_creature - name : entry=13219
UPDATE `trans_words` SET `content_loc3`='Jern Hornhelm' WHERE `word_id` = 73067; -- locales_creature - name : entry=1105
UPDATE `trans_words` SET `content_loc3`='Jhordy Lapforge' WHERE `word_id` = 80713; -- locales_creature - name : entry=14743
UPDATE `trans_words` SET `content_loc3`='Jubling' WHERE `word_id` = 80789; -- locales_creature - name : entry=14878
UPDATE `trans_words` SET `content_loc3`='Kayneth Stillwind' WHERE `word_id` = 75471; -- locales_creature - name : entry=3848
UPDATE `trans_words` SET `content_loc3`='Kelv Sternhammer' WHERE `word_id` = 76430; -- locales_creature - name : entry=5113
UPDATE `trans_words` SET `content_loc3`='Kiknikle' WHERE `word_id` = 75358; -- locales_creature - name : entry=3683
UPDATE `trans_words` SET `content_loc3`='Kirge Sternhorn' WHERE `word_id` = 75104; -- locales_creature - name : entry=3418
UPDATE `trans_words` SET `content_loc3`='Kormok Trigger' WHERE `word_id` = 81581; -- locales_creature - name : entry=16047
UPDATE `trans_words` SET `content_loc3`='Lady Anacondra' WHERE `word_id` = 75347; -- locales_creature - name : entry=3671
UPDATE `trans_words` SET `content_loc3`='Lady Blaumeux' WHERE `word_id` = 81600; -- locales_creature - name : entry=16065
UPDATE `trans_words` SET `content_loc3`='Lady Falther\'ess' WHERE `word_id` = 80679; -- locales_creature - name : entry=14686
UPDATE `trans_words` SET `content_loc3`='Lady Hederine' WHERE `word_id` = 78792; -- locales_creature - name : entry=10201
UPDATE `trans_words` SET `content_loc3`='Lady Hoteshem' WHERE `word_id` = 80845; -- locales_creature - name : entry=15008
UPDATE `trans_words` SET `content_loc3`='Lady Illucia Barov' WHERE `word_id` = 78948; -- locales_creature - name : entry=10502
UPDATE `trans_words` SET `content_loc3`='Lady Katrana Prestor' WHERE `word_id` = 73642; -- locales_creature - name : entry=1749
UPDATE `trans_words` SET `content_loc3`='Lady Onyxia' WHERE `word_id` = 79995; -- locales_creature - name : entry=12756
UPDATE `trans_words` SET `content_loc3`='Lady Sarevess' WHERE `word_id` = 76278; -- locales_creature - name : entry=4831
UPDATE `trans_words` SET `content_loc3`='Lady Sathrah' WHERE `word_id` = 77631; -- locales_creature - name : entry=7319
UPDATE `trans_words` SET `content_loc3`='Lady Sesspira' WHERE `word_id` = 77392; -- locales_creature - name : entry=6649
UPDATE `trans_words` SET `content_loc3`='Lady Sevine' WHERE `word_id` = 77802; -- locales_creature - name : entry=7667
UPDATE `trans_words` SET `content_loc3`='Lady Szallah' WHERE `word_id` = 76588; -- locales_creature - name : entry=5343
UPDATE `trans_words` SET `content_loc3`='Lady Vespia' WHERE `word_id` = 78965; -- locales_creature - name : entry=10559
UPDATE `trans_words` SET `content_loc3`='Lady Vespira' WHERE `word_id` = 77487; -- locales_creature - name : entry=7016
UPDATE `trans_words` SET `content_loc3`='Lady' WHERE `word_id` = 80862; -- locales_creature - name : entry=15065
UPDATE `trans_words` SET `content_loc3`='Lady Zephris' WHERE `word_id` = 80414; -- locales_creature - name : entry=14277
UPDATE `trans_words` SET `content_loc3`='Lefty' WHERE `word_id` = 81583; -- locales_creature - name : entry=16049
UPDATE `trans_words` SET `content_loc3`='Ley Sprite' WHERE `word_id` = 79914; -- locales_creature - name : entry=12381
UPDATE `trans_words` SET `content_loc3`='Lil\' Smoky' WHERE `word_id` = 16240; -- locales_creature - name : entry=9657
UPDATE `trans_words` SET `content_loc3`='Loatheb' WHERE `word_id` = 81553; -- locales_creature - name : entry=16011
UPDATE `trans_words` SET `content_loc3`='Lord Alexei Barov' WHERE `word_id` = 78950; -- locales_creature - name : entry=10504
UPDATE `trans_words` SET `content_loc3`='Lord Aliden Perenolde' WHERE `word_id` = 74174; -- locales_creature - name : entry=2423
UPDATE `trans_words` SET `content_loc3`='Lord Angler' WHERE `word_id` = 80395; -- locales_creature - name : entry=14236
UPDATE `trans_words` SET `content_loc3`='Lord Arkkoroc' WHERE `word_id` = 77153; -- locales_creature - name : entry=6134
UPDATE `trans_words` SET `content_loc3`='Lord Azrethoc' WHERE `word_id` = 76879; -- locales_creature - name : entry=5760
UPDATE `trans_words` SET `content_loc3`='Lord Condar' WHERE `word_id` = 80405; -- locales_creature - name : entry=14268
UPDATE `trans_words` SET `content_loc3`='Lord Gregor Lescovar' WHERE `word_id` = 73647; -- locales_creature - name : entry=1754
UPDATE `trans_words` SET `content_loc3`='Lord Hel\'nurath' WHERE `word_id` = 80594; -- locales_creature - name : entry=14506
UPDATE `trans_words` SET `content_loc3`='Lord Incendius' WHERE `word_id` = 78412; -- locales_creature - name : entry=9017
UPDATE `trans_words` SET `content_loc3`='Lord Kazzak' WHERE `word_id` = 79921; -- locales_creature - name : entry=12397
UPDATE `trans_words` SET `content_loc3`='Lord Kragaru' WHERE `word_id` = 79908; -- locales_creature - name : entry=12369
UPDATE `trans_words` SET `content_loc3`='Lord Kri' WHERE `word_id` = 81172; -- locales_creature - name : entry=15511
UPDATE `trans_words` SET `content_loc3`='Lord Lakmaeran' WHERE `word_id` = 80033; -- locales_creature - name : entry=12803
UPDATE `trans_words` SET `content_loc3`='Lord Malathrom' WHERE `word_id` = 72584; -- locales_creature - name : entry=503
UPDATE `trans_words` SET `content_loc3`='Lord Maldazzar' WHERE `word_id` = 73717; -- locales_creature - name : entry=1848
UPDATE `trans_words` SET `content_loc3`='Lord Maxwell Tyrosus' WHERE `word_id` = 79201; -- locales_creature - name : entry=11034
UPDATE `trans_words` SET `content_loc3`='Lord Melenas' WHERE `word_id` = 73852; -- locales_creature - name : entry=2038
UPDATE `trans_words` SET `content_loc3`='Lord Pythas' WHERE `word_id` = 75346; -- locales_creature - name : entry=3670
UPDATE `trans_words` SET `content_loc3`='Lord Roccor' WHERE `word_id` = 78422; -- locales_creature - name : entry=9025
UPDATE `trans_words` SET `content_loc3`='Lord Sakrasis' WHERE `word_id` = 74282; -- locales_creature - name : entry=2541
UPDATE `trans_words` SET `content_loc3`='Lord Serpentis' WHERE `word_id` = 75350; -- locales_creature - name : entry=3673
UPDATE `trans_words` SET `content_loc3`='Lord Shalzaru' WHERE `word_id` = 78031; -- locales_creature - name : entry=8136
UPDATE `trans_words` SET `content_loc3`='Lord Skwol' WHERE `word_id` = 81020; -- locales_creature - name : entry=15305
UPDATE `trans_words` SET `content_loc3`='Lord Tirion Fordring' WHERE `word_id` = 79791; -- locales_creature - name : entry=12126
UPDATE `trans_words` SET `content_loc3`='Lord Tony Romano' WHERE `word_id` = 80176; -- locales_creature - name : entry=13283
UPDATE `trans_words` SET `content_loc3`='Lord Valthalak Trigger' WHERE `word_id` = 81582; -- locales_creature - name : entry=16048
UPDATE `trans_words` SET `content_loc3`='Lord Valthalak' WHERE `word_id` = 81576; -- locales_creature - name : entry=16042
UPDATE `trans_words` SET `content_loc3`='Lord Victor Nefarius' WHERE `word_id` = 78775; -- locales_creature - name : entry=10162
UPDATE `trans_words` SET `content_loc3`='Magister Kalendris' WHERE `word_id` = 79436; -- locales_creature - name : entry=11487
UPDATE `trans_words` SET `content_loc3`='Magus Tirth' WHERE `word_id` = 77355; -- locales_creature - name : entry=6548
UPDATE `trans_words` SET `content_loc3`='Major Pakkon' WHERE `word_id` = 81077; -- locales_creature - name : entry=15388
UPDATE `trans_words` SET `content_loc3`='Mana Sprite' WHERE `word_id` = 79915; -- locales_creature - name : entry=12382
UPDATE `trans_words` SET `content_loc3`='Mangorn Flinthammer' WHERE `word_id` = 76424; -- locales_creature - name : entry=5107
UPDATE `trans_words` SET `content_loc3`='Marin Noggenfogger' WHERE `word_id` = 77783; -- locales_creature - name : entry=7564
UPDATE `trans_words` SET `content_loc3`='Maxima Blastenheimer' WHERE `word_id` = 81017; -- locales_creature - name : entry=15303
UPDATE `trans_words` SET `content_loc3`='Mekgineer Trigger' WHERE `word_id` = 80343; -- locales_creature - name : entry=13876
UPDATE `trans_words` SET `content_loc3`='Milla Fairancora' WHERE `word_id` = 79208; -- locales_creature - name : entry=11041
UPDATE `trans_words` SET `content_loc3`='Mok\'rash' WHERE `word_id` = 73466; -- locales_creature - name : entry=1493
UPDATE `trans_words` SET `content_loc3`='Moktar Krin' WHERE `word_id` = 76007; -- locales_creature - name : entry=4483
UPDATE `trans_words` SET `content_loc3`='Montarr' WHERE `word_id` = 76305; -- locales_creature - name : entry=4878
UPDATE `trans_words` SET `content_loc3`='Morgan Pestle' WHERE `word_id` = 72437; -- locales_creature - name : entry=279
UPDATE `trans_words` SET `content_loc3`='Morgan Stern' WHERE `word_id` = 76252; -- locales_creature - name : entry=4794
UPDATE `trans_words` SET `content_loc3`='Morganth' WHERE `word_id` = 72511; -- locales_creature - name : entry=397
UPDATE `trans_words` SET `content_loc3`='Motley Garmason' WHERE `word_id` = 73038; -- locales_creature - name : entry=1074
UPDATE `trans_words` SET `content_loc3`='Mr. Bigglesworth' WHERE `word_id` = 81826; -- locales_creature - name : entry=16998
UPDATE `trans_words` SET `content_loc3`='Muckrake' WHERE `word_id` = 74172; -- locales_creature - name : entry=2421
UPDATE `trans_words` SET `content_loc3`='Murky' WHERE `word_id` = 80948; -- locales_creature - name : entry=15186
UPDATE `trans_words` SET `content_loc3`='Murloc' WHERE `word_id` = 72439; -- locales_creature - name : entry=285
UPDATE `trans_words` SET `content_loc3`='Mythidan' WHERE `word_id` = 75806; -- locales_creature - name : entry=4233
UPDATE `trans_words` SET `content_loc3`='Nag\'zehn' WHERE `word_id` = 76058; -- locales_creature - name : entry=4545
UPDATE `trans_words` SET `content_loc3`='Najak Hexxen' WHERE `word_id` = 80374; -- locales_creature - name : entry=14185
UPDATE `trans_words` SET `content_loc3`='Nalesette Wildbringer' WHERE `word_id` = 72610; -- locales_creature - name : entry=543
UPDATE `trans_words` SET `content_loc3`='Nancy Vishas' WHERE `word_id` = 75588; -- locales_creature - name : entry=3984
UPDATE `trans_words` SET `content_loc3`='Naxxramas Template' WHERE `word_id` = 81532; -- locales_creature - name : entry=15973
UPDATE `trans_words` SET `content_loc3`='Nibbles' WHERE `word_id` = 79916; -- locales_creature - name : entry=12383
UPDATE `trans_words` SET `content_loc3`='Night Elf Male' WHERE `word_id` = 79078; -- locales_creature - subname : entry=10797
UPDATE `trans_words` SET `content_loc3`='Noxxion' WHERE `word_id` = 80175; -- locales_creature - name : entry=13282
UPDATE `trans_words` SET `content_loc3`='Nyse' WHERE `word_id` = 75888; -- locales_creature - name : entry=4317
UPDATE `trans_words` SET `content_loc3`='Omen' WHERE `word_id` = 81146; -- locales_creature - name : entry=15467
UPDATE `trans_words` SET `content_loc3`='Orc Female' WHERE `word_id` = 79065; -- locales_creature - subname : entry=10784
UPDATE `trans_words` SET `content_loc3`='Orwin Gizzmick' WHERE `word_id` = 78000; -- locales_creature - name : entry=8021
UPDATE `trans_words` SET `content_loc3`='Ouro Spawner' WHERE `word_id` = 81527; -- locales_creature - name : entry=15957
UPDATE `trans_words` SET `content_loc3`='Panther' WHERE `word_id` = 72738; -- locales_creature - name : entry=736
UPDATE `trans_words` SET `content_loc3`='Phalanx' WHERE `word_id` = 78571; -- locales_creature - name : entry=9502
UPDATE `trans_words` SET `content_loc3`='Pikkle' WHERE `word_id` = 78027; -- locales_creature - name : entry=8128
UPDATE `trans_words` SET `content_loc3`='Pozzik' WHERE `word_id` = 76142; -- locales_creature - name : entry=4630
UPDATE `trans_words` SET `content_loc3`='Priest Epic Event Caller' WHERE `word_id` = 80580; -- locales_creature - name : entry=14493
UPDATE `trans_words` SET `content_loc3`='Primalist Thurloga' WHERE `word_id` = 80167; -- locales_creature - name : entry=13236
UPDATE `trans_words` SET `content_loc3`='Professor Thaddeus Paleo' WHERE `word_id` = 80766; -- locales_creature - name : entry=14847
UPDATE `trans_words` SET `content_loc3`='Pterrordax' WHERE `word_id` = 78479; -- locales_creature - name : entry=9166
UPDATE `trans_words` SET `content_loc3`='PvP ALT-N Credit Marker' WHERE `word_id` = 80842; -- locales_creature - name : entry=15005
UPDATE `trans_words` SET `content_loc3`='PvP ALT-S Credit Marker' WHERE `word_id` = 80841; -- locales_creature - name : entry=15004
UPDATE `trans_words` SET `content_loc3`='PvP A-Mid Credit Marker' WHERE `word_id` = 80838; -- locales_creature - name : entry=15001
UPDATE `trans_words` SET `content_loc3`='PvP H-Mid Credit Marker' WHERE `word_id` = 80840; -- locales_creature - name : entry=15003
UPDATE `trans_words` SET `content_loc3`='PvP Mid Credit Marker' WHERE `word_id` = 80839; -- locales_creature - name : entry=15002
UPDATE `trans_words` SET `content_loc3`='Quentin' WHERE `word_id` = 78497; -- locales_creature - name : entry=9238
UPDATE `trans_words` SET `content_loc3`='Raena Flinthammer' WHERE `word_id` = 76425; -- locales_creature - name : entry=5108
UPDATE `trans_words` SET `content_loc3`='Razzeric' WHERE `word_id` = 76211; -- locales_creature - name : entry=4706
UPDATE `trans_words` SET `content_loc3`='Rendow' WHERE `word_id` = 73595; -- locales_creature - name : entry=1695
UPDATE `trans_words` SET `content_loc3`='Rhag Garmason' WHERE `word_id` = 73039; -- locales_creature - name : entry=1075
UPDATE `trans_words` SET `content_loc3`='Rigger Gizelton' WHERE `word_id` = 79501; -- locales_creature - name : entry=11626
UPDATE `trans_words` SET `content_loc3`='Rivern Frostwind' WHERE `word_id` = 78994; -- locales_creature - name : entry=10618
UPDATE `trans_words` SET `content_loc3`='Riznek' WHERE `word_id` = 77323; -- locales_creature - name : entry=6495
UPDATE `trans_words` SET `content_loc3`='Scald' WHERE `word_id` = 78090; -- locales_creature - name : entry=8281
UPDATE `trans_words` SET `content_loc3`='Shyn' WHERE `word_id` = 77999; -- locales_creature - name : entry=8020
UPDATE `trans_words` SET `content_loc3`='Sida' WHERE `word_id` = 73910; -- locales_creature - name : entry=2111
UPDATE `trans_words` SET `content_loc3`='Singe' WHERE `word_id` = 72472; -- locales_creature - name : entry=335
UPDATE `trans_words` SET `content_loc3`='Sir Zeliek' WHERE `word_id` = 81598; -- locales_creature - name : entry=16063
UPDATE `trans_words` SET `content_loc3`='Skhowl' WHERE `word_id` = 74196; -- locales_creature - name : entry=2452
UPDATE `trans_words` SET `content_loc3`='Skul' WHERE `word_id` = 78872; -- locales_creature - name : entry=10393
UPDATE `trans_words` SET `content_loc3`='Sly Garrett' WHERE `word_id` = 74361; -- locales_creature - name : entry=2622
UPDATE `trans_words` SET `content_loc3`='Smoldar' WHERE `word_id` = 78087; -- locales_creature - name : entry=8278
UPDATE `trans_words` SET `content_loc3`='Solomon' WHERE `word_id` = 72794; -- locales_creature - name : entry=798
UPDATE `trans_words` SET `content_loc3`='Spike' WHERE `word_id` = 80869; -- locales_creature - name : entry=15072
UPDATE `trans_words` SET `content_loc3`='Spotlight' WHERE `word_id` = 81282; -- locales_creature - name : entry=15631
UPDATE `trans_words` SET `content_loc3`='Sprok' WHERE `word_id` = 78115; -- locales_creature - name : entry=8320
UPDATE `trans_words` SET `content_loc3`='Starn' WHERE `word_id` = 78602; -- locales_creature - name : entry=9551
UPDATE `trans_words` SET `content_loc3`='Stratholme Trigger' WHERE `word_id` = 80668; -- locales_creature - name : entry=14646
UPDATE `trans_words` SET `content_loc3`='Survival Trainer' WHERE `word_id` = 74521; -- locales_creature - subname : entry=2801
UPDATE `trans_words` SET `content_loc3`='Swift Dawnsaber' WHERE `word_id` = 80633; -- locales_creature - name : entry=14557
UPDATE `trans_words` SET `content_loc3`='Tallow' WHERE `word_id` = 74490; -- locales_creature - name : entry=2770
UPDATE `trans_words` SET `content_loc3`='Tannok Frosthammer' WHERE `word_id` = 77451; -- locales_creature - name : entry=6806
UPDATE `trans_words` SET `content_loc3`='Tapoke "Slim" Jahn' WHERE `word_id` = 76356; -- locales_creature - name : entry=4962
UPDATE `trans_words` SET `content_loc3`='Tauren Female' WHERE `word_id` = 79067; -- locales_creature - subname : entry=10786
UPDATE `trans_words` SET `content_loc3`='Tauren Male' WHERE `word_id` = 79066; -- locales_creature - subname : entry=10785
UPDATE `trans_words` SET `content_loc3`='Tawny Grisette' WHERE `word_id` = 76067; -- locales_creature - name : entry=4554
UPDATE `trans_words` SET `content_loc3`='The Head of The Black Flight' WHERE `word_id` = 79478; -- locales_creature - subname : entry=11583
UPDATE `trans_words` SET `content_loc3`='Thyssiana' WHERE `word_id` = 75889; -- locales_creature - name : entry=4319
UPDATE `trans_words` SET `content_loc3`='Tick' WHERE `word_id` = 78062; -- locales_creature - name : entry=8198
UPDATE `trans_words` SET `content_loc3`='Tideress' WHERE `word_id` = 79998; -- locales_creature - name : entry=12759
UPDATE `trans_words` SET `content_loc3`='Treant' WHERE `word_id` = 73797; -- locales_creature - name : entry=1964
UPDATE `trans_words` SET `content_loc3`='Troll Female' WHERE `word_id` = 79069; -- locales_creature - subname : entry=10788
UPDATE `trans_words` SET `content_loc3`='Troll Male' WHERE `word_id` = 79068; -- locales_creature - subname : entry=10787
UPDATE `trans_words` SET `content_loc3`='Undead Female' WHERE `word_id` = 79071; -- locales_creature - subname : entry=10790
UPDATE `trans_words` SET `content_loc3`='Undead Male' WHERE `word_id` = 79070; -- locales_creature - subname : entry=10789
UPDATE `trans_words` SET `content_loc3`='Vaelan' WHERE `word_id` = 78817; -- locales_creature - name : entry=10296
UPDATE `trans_words` SET `content_loc3`='Vek Twins Trigger' WHERE `word_id` = 81305; -- locales_creature - name : entry=15695
UPDATE `trans_words` SET `content_loc3`='Vel\'rin Fang' WHERE `word_id` = 74884; -- locales_creature - name : entry=3194
UPDATE `trans_words` SET `content_loc3`='Venture Co.' WHERE `word_id` = 75849; -- locales_creature - subname : entry=4276
UPDATE `trans_words` SET `content_loc3`='Verifonix' WHERE `word_id` = 80578; -- locales_creature - name : entry=14492
UPDATE `trans_words` SET `content_loc3`='Vi\'el' WHERE `word_id` = 268292; -- locales_creature - name : entry=16015
UPDATE `trans_words` SET `content_loc3`='William Pestle' WHERE `word_id` = 72408; -- locales_creature - name : entry=253
UPDATE `trans_words` SET `content_loc3`='Winkey' WHERE `word_id` = 77852; -- locales_creature - name : entry=7770
UPDATE `trans_words` SET `content_loc3`='Wolf Trainer' WHERE `word_id` = 74576; -- locales_creature - subname : entry=2870
UPDATE `trans_words` SET `content_loc3`='XT:4' WHERE `word_id` = 75667; -- locales_creature - name : entry=4073
UPDATE `trans_words` SET `content_loc3`='XT:9' WHERE `word_id` = 75668; -- locales_creature - name : entry=4074
UPDATE `trans_words` SET `content_loc3`='Ysida\'s Trigger' WHERE `word_id` = 81625; -- locales_creature - name : entry=16100
UPDATE `trans_words` SET `content_loc3`='Zamek' WHERE `word_id` = 76214; -- locales_creature - name : entry=4709
UPDATE `trans_words` SET `content_loc3`='Ziz Fizziks' WHERE `word_id` = 75777; -- locales_creature - name : entry=4201
UPDATE `trans_words` SET `content_loc3`='Zuzubee' WHERE `word_id` = 76212; -- locales_creature - name : entry=4707

SET NAMES 'latin1';
